### ISSUE TITLE
Mappa Instagram

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#10]
Serve avere una mappa Instagram dei tag terremoto da embeddare nel sito. Un tool potrebbe essere questo https://github.com/iltempe/InstaMap (cartoDB come backend) ma siamo aperti a tutte le soluzioni

**Comment by iltempe** [comment]
assegnato

**Comment by olistik** [comment]
@iltempe per poter uscire dalla modalità Sandbox di Instagram servirebbe una Privacy Policy URL:

> 1. Provide a publicly accessible privacy policy that tells people what you collect and how you will use this information.

[fonte](https://www.instagram.com/about/legal/terms/api/)

@iltempe Qualche idea veloce su come averne una precompilata?

**Comment by olistik** [comment]
@iltempe @mfortini come mi ha giustamente indicato @aborruso, con un auth token di Instagram, ottenuto seguendo un flusso da terminale con _curl_, sono infine riuscito a ricevere alcuni dati tramite l'API.
A causa del sandbox mode non riesco a recuperare dati "interessanti" come i post corrispondenti ad un hashtag e per ora ho ottenuto e iniettato nello sheet solo le informazioni relative al mio account:

<img width="1061" alt="screen shot 2016-08-26 at 19 03 34" src="https://cloud.githubusercontent.com/assets/21038/18013760/e1d64742-6bbf-11e6-8aca-68270811b40b.png">

Appena mettiamo una Privacy Policy sul server possiamo effettuare la submission ad Instagram.

**Comment by iltempe** [comment]
questo probabilmente significa che i TOS di instagram non consentono più di prelevare immagini per TAG ma solo di un utente.

**Comment by iltempe** [comment]
Ho verificato. le API non lo consentono più. Se trovate altri strumenti per farlo. procediamo se no chiudo issue.

**Comment by olistik** [comment]
@iltempe sicuro? mi sembra che [GET /tags/#{tag-name}/media/recent](https://www.instagram.com/developer/endpoints/tags/#get_tags_media_recent) faccia al caso nostro, no?
L'unico problema è che richiede lo scope _public_, che non è accessibile in sandbox mode.

**Comment by iltempe** [comment]
@olistik a questo punto proverei con questa soluzione se va. https://github.com/iltempe/InstaMap si basava su quell API e cartodb. mi pareva non ci fosse più la richiesta GET. forse mi sbagliavo.

**Comment by olistik** [comment]
@iltempe anche [InstaMap](/iltempe/InstaMap) usa lo stesso endpoint che ho menzionato sopra ([link](https://github.com/iltempe/InstaMap/blob/master/script/config_temp.php#L12)).

Quindi il problema mi sembra simile a quello dell'API JS: o ci facciamo promuovere l'app Instagram per usare quell'endpoint oppure troviamo un'altra soluzione.

**Comment by iltempe** [comment]
un'altra soluzione potrebbe essere installare questo e deviare su twitter, feed e segnalazioni georiferite. https://github.com/ushahidi/platform

**Comment by aborruso** [comment]
Non risolvibile via Instagram in tempi rapidi. La chiudo
