### ISSUE TITLE
BUG: condivisione link su Twitter

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#103]
Pare che la condivisione su twitter possa dare questo problema
![image001](https://cloud.githubusercontent.com/assets/6368214/18057540/c390a78e-6e10-11e6-9d3a-7c4381754b6f.png)

**Comment by Pinzauti** [comment]
@iltempe Dovrebbe essere risolto.
![twitter](https://cloud.githubusercontent.com/assets/16691846/18064770/23a11044-6e31-11e6-8ec1-18eec648959f.PNG)
