### ISSUE TITLE
LOGO su Facebook

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#104]
Creare un banner Facebook da mettere sull'intestazione con la stessa immagine ad oggi presente ed il logo ufficiale.

**Comment by Manfro** [comment]
Potrebbe andare o troppo banale? e quale se mai?
![copertinagruppo](https://cloud.githubusercontent.com/assets/18487107/18092036/0912aacc-6ecb-11e6-9c7e-ee168fc1e107.png)

![copertina](https://cloud.githubusercontent.com/assets/18487107/18091427/e28d73c0-6ec8-11e6-8353-caa9cb6b2d02.png)

**Comment by iltempe** [comment]
fatto!
