### ISSUE TITLE
Pagina about: precisare natura del progetto

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#106]
Modificare parte iniziale

cambia da

``` javascript
Questo progetto è nato per condividere 
info utili e possibilmente verificate 
sul Terremoto del 24 Agosto 2016.
```

a 

``` javascript
Questo progetto è non profit e organizzato
interamente da volontari ed è nato per 
condividere info utili e possibilmente 
verificate sul Terremoto del 24 Agosto 2016.
```

**Comment by favoeva** [comment]
aggiungerei tra gli obiettivi anche verifica informazioni e debunking delle notizie
lavoriamo anche sull'ecologia dell'informazione di fatto

**Comment by dontyna** [comment]
Questo è un progetto non profit, organizzato
interamente da volontari. È nato per 
condividere informazioni utili e 
verificate sul Terremoto del 24 Agosto 2016.

**Comment by iltempe** [comment]
fatto.
