### ISSUE TITLE
Gestione account Twitter @terremotocentroitalia

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#109]
Coordinamento sull'account.

**Comment by rosy2015** [comment]
Presente.

**Comment by favoeva** [comment]
TO DO LIST (una prima proposta)
Rivedere short bio 
Tweet fissato in alto (Ontologia #hashtag +
Invito a mandare info e richieste anche tramite tw?)
Rivedere contenuti automatismi

**Comment by rosy2015** [comment]
Concordo ;-)

**Comment by rosy2015** [comment]
Sono entrata nel l'account. Vedo RT solo su articoli ma  misogna assolutamente aumentare i contenuti di servizio da propagare (oltre i RT), i tweet vanno riscritto con hashtag.

**Comment by mfortini** [comment]
Mi permetto: quando trovate cose nuove da fare, aprite issue nuove, non
scrivetele nei commenti.

Il mar 30 ago 2016, 07:29 rosy2015 notifications@github.com ha scritto:

**Comment by favoeva** [comment]
(scrivo qui perchè non c'è issue MEDIA TEAM (la facciamo?) 

"il media team Modera+Monitora FB e TW + Registra sugli sheet." 
Sono d'accordo che il lavoro debba essere fatto in modo integrato (hangout di ieri @rosy2015), per questioni di sostenibilità complessiva dell'attività proporrei
Su moderazione: io @dontyna @rosy2015 Cristina Galasso Dario Manfrin (Matteo T..... Chi altri? dite dite) 
- Controlliamo post per evitare spam e polemiche politiche in base alla linea che abbiamo già condiviso
- scriviamo post di coordinamento (per questo diamo i contenuti a Matteo T. e posta lui ?), promozione dei contenuti più preziosi, novità sul sito, uscite sulla stampa (ringraziamenti)
  Direi che moderando così vediamo anche le chiusure di chi ha registrato in gsheet: se queste avranno il link dove quel contenuto è stato pubblicato non avremo grosse difficoltà a fare il lavoro integrato di cui parlavamo ieri perché possano essere oggetto di FB post o tweet

Su monitoraggio FB +registrazione in gsheet dobbiamo sicuramente cercare di integrare il gruppo: lanciamo una chiamata specifica sul gruppone Telegram? 

Nella issue specifica su questo secondo punto Matteo T ha messo istruzioni operative : ci  diamo un'occhiata per vedere se integrarle per coordinamento attività  media team ?

**Comment by rosy2015** [comment]
Sì Matteo grazie ma questo riguarda esclusivamente la gestione dell'account Twitter con il Media team abbiamo detto di usare questa issue e non la chat per tenere traccia. Ma non posso aprire una issue per ogni cosa, a mio avviso

**Comment by rosy2015** [comment]
Facciamo una issue Media Team. In ogni caso io ho mandato primo tweet e rilancio prima news da Twitter di Agorà Vox.

**Comment by rosy2015** [comment]
Allora ho lavorato una mezz'ora circa per farvi capire come a mio avviso sarebbe fa gestire. Oggi non riesco a tenere questi ritmi. In ogni caso tweet con contenuti che rimandano al sito (screenshot+Tag su follower fedeli a rotazione Rt+link), Rt le mention e rilancio articoli che parlano di noi. A mio avviso almeno un tweet all'ora andrebbe fatto. Ho creato le liste che poi ci possono aiutare nella gestione da desk (community,  istituzioni, media e giornalisti, volontari). Passo e chiudo per ora

**Comment by dontyna** [comment]
**Proposta**: Se usiamo Tweetdeck per la gestione da desktop/web i tweet programmati vengono condivisi con tutti.

**Comment by dontyna** [comment]
**Proposta** Bio per twitter:

`Servizio di monitoraggio e diffusione di informazioni verificate sul terremoto del 24 agosto 2016 in centro Italia.`

**Comment by favoeva** [comment]
ok per tweetdeck 
per short bio non aggiungiamo un hashtag? #129

**Comment by dontyna** [comment]
@favoeva come avrete capito ho un problema personale con gli hashtag :) quale aggiungiamo? decidiamo qual è quello per info verified.

**Comment by Manfro** [comment]
Ciao a tutte, anche secondo me la short bio può andare, basta aggiungere gli hashtag, #terremotoinfo secondo me potrebbe andare come proposto da @dontyna sulla #129
