### ISSUE TITLE
Layout della home per tirare fuori i contenuti

### ISSUE THREAD

**Issue by rosy2015** [emergenzeHack/terremotocentro#110]
Carissimi tutti,
come divevamo in hangout, sarebbe utile rendere più accessibili i contenuti che ora sono nella sezione "pagine" creando magari in home delle sezioni per i contenuti che possono diventare dei post ed essere divulgati nei social. Io di fatto me li sono costruiti facendo screenshot e mettendo link. 

Non sono una sviluppatrice ma come @nelsonmau ho esperienza nella progettazione di contenuti editoriali e nella user experience
La sezione http://terremotocentroitalia.info/donazioni/ è quella che ha maggior contenuti che possono essere divulgati dal media team.
Penso ad una semplice struttura "grid" magari in cui far apparire gli ultimi aggiornamenti presenti ad esempio nella categoria "donazioni: ecco il nuovo numero di ...." con post relativo"; "Fabbisogni" ultima tenda disponibile...ecc.ecc. 
Non so se sono stata chiara. Chiedo al Media Team @dontyna @favoeva e @cristigalas e al team sviluppatori @iltempe  di dire la loro. 
Grazie, resto a disposizione (per favore ditemi come aggiungere le etichette, che non me lo fa fare...:-/)

**Comment by cristigalas** [comment]
Sono d'accordo con Rosy, anch'io finora twittavo link e screenshot delle varie richieste ma non è certo la soluzione migliore. Più o meno credo di aver capito quanto suggerisce Rosy e penso che un intervento in questo senso vada senz'altro previsto (come fare vedete voi sviluppatori ;)

**Comment by Pinzauti** [comment]
@rosy2015 @cristigalas 
Adesso le sezioni "Bollettino" e "Alloggi" dovrebbero essere condivisibili senza bisogno di screenshot. 
Se va bene modifico così anche la sezione "Donazioni".
Per la Home invece non ho ben chiaro come la vorresti strutturare.
Intendi dividerla in sezioni che rimandano agli ultimi 2-3 link della sezione "Donazioni" e magari di altre?

**Comment by favoeva** [comment]
nella home manca Notizie Utili che vada a pescare contenuti da qui https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=8819636 @Pinzauti

**Comment by Pinzauti** [comment]
Okay @favoeva, sono fuori casa in questi giorni, appena posso ci butto un occhio

**Comment by favoeva** [comment]
Grazie mille!

**Comment by iltempe** [comment]
posso chiudere?

**Comment by favoeva** [comment]
io direi che la chiudiamo, gestiamo insieme usabilità e layout hp sito 

resta aperta per la parte relativa al fatto che nella home manca Notizie Utili che vada a pescare contenuti da qui https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=8819636 ma la inserisco nella #261
