### ISSUE TITLE
Feeds

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#12]
Serve avere un maxi feed che tramite i link in https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=1149746747 foglio Feeds costruisca dinamicamente il merge di tutti i feed e sia unico da diffondere. Tra questi feed va anche messo il feed generato dal foglio Bollettino.

**Comment by aborruso** [comment]
E' già presente ed  è questo http://feeds.feedburner.com/TerremotoCentroItalia-RaccoltaFeedRss

Contiene tutti i feed marcati con una "x" nella colonna "Inserito" del foglio "Feeds" dello spreadsheet di lavoro condiviso.
