### ISSUE TITLE
Gruppo Flickr per foto e video

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#120]
Attualmente le foto e i video (brevi) possono essere archiviati su questo gruppo Flickr 
https://www.flickr.com/groups/3003557@N20/

La cartella google precedentemente creata la eliminiamo.

**Comment by nelsonmau** [comment]
tnx
possiamo chiudere questa issue?
terrei aperta solo l'altra di lorenzo

**Comment by lorenzoperone** [comment]
converge su #117
