### ISSUE TITLE
Creare url univoci per i singoli pannelli "annunci" e renderli condivisibli

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#122]
Ieri in hangout è emerso che questa cosa non è possibile e qualcuna (mi pare mariaeva) diceva: «Io devo fare lo screenshot per condividere il singolo annuncio. 

Si potrebbe sistemare così:
- ad ogni panel viene associato un `id` e con questo id generiamo un ancora, di conseguenza un url univoco (esempio: `http://terremotocentroitalia.info/donazioni/#27-7-2016-18.22` )
- l'id può essere generato dalla colonna orario (che sia stampiano nel panel, sia usiamo per popolare l'id
- in basso aggiungere pulsanti di condivisione che come url utilizzano l'id,  ad esempio: `http://terremotocentroitalia.info/donazioni/#27-7-2016-18.22` 

questo permette di avere un url univo per ogni panel 

allego screenshot esemplificativo

![tci_panel](https://cloud.githubusercontent.com/assets/1769578/18077777/0c9f7e74-6e88-11e6-9625-3eaa652f3015.png)

**Comment by nelsonmau** [comment]
@mfortini non sono in grado di farlo al momento... è una idea che ti convince? puoi farlo tu?
 / cc @iltempe @aborruso

**Comment by mfortini** [comment]
Sì mi convince, se nessuno ci lavora entro pranzo poi mi ci metto.

Il mar 30 ago 2016, 08:07 Andrea Nelson Mauro notifications@github.com ha
scritto:

**Comment by mfortini** [comment]
Prima prova nella pagina alloggi, mi date feedback? Ci sono alcune cose non proprio bellissime da correggere, volevo sapere se vi piace la forma

**Comment by Pinzauti** [comment]
@mfortini 
Faccio alcune segnalazioni:
- Il caricamento è molto lento.
-  Il javascript di Facebook e Twitter è incluso in tutte le pagine, anche dove i link di condivisione non sono presenti.
- Il testo dell'ancora è un po' "sporco".  Sarebbe meglio tolgliere puntini e il resto.

![ancora](https://cloud.githubusercontent.com/assets/16691846/18103149/b1053bee-6ef5-11e6-8445-5820cdfe3be3.png)
- Ai più non è chiaro il significato di permalink.
- Pulsanti di condivisione non allineati. 

![pulsanti](https://cloud.githubusercontent.com/assets/16691846/18103247/0a3b7502-6ef6-11e6-829d-314b5e5a43a4.png)
- Il link con l'ancora non fa atterrare nella sezione interessata, che anzi è tagliata e si vede poco bene, creando confusione. Paradossalmente risultano invece in risalto le sezioni successive, che si presentano al centro della pagina.

![errore](https://cloud.githubusercontent.com/assets/16691846/18103314/4dd9f9dc-6ef6-11e6-8fb9-086a449f3244.PNG)

Queste sono un po' di cose che mi vengono in mente, se posso aiuto volentieri.

**Comment by mfortini** [comment]
Grazie decidiamo se fare revert o lavorare da qui.
- caricamento: ho visto la lentezza estrema, è colpa del fatto che viene
  contattato da ogni link Facebook, forse si può trovare una versione più
  "statica"
- allineamento: ho guardato su stackoverflow e pare un problema di come fb
  fa i js, ci sono varie proposte di soluzione, vediamo se ce n'è una che
  funziona
- js caricato: forse finisce in cache, ma guardiamo se fa male.
- permalink: bisogna mettere copy link, non lo so fare al volo
- copertura navbar: bisogna adattare il css che c'è in fondo a main per
  gestire anche panel

Grazie mille

Il mar 30 ago 2016, 21:12 Francesco Pinzauti notifications@github.com ha
scritto:

**Comment by mfortini** [comment]
Per i puntini, truncate li mette, magari mettiamo un replace anche se
sarebbe più utile se truncate troncasse e basta

Il mar 30 ago 2016, 21:21 Matteo Fortini matteo.fortini@gmail.com ha
scritto:

**Comment by Pinzauti** [comment]
@mfortini 
- Mi viene in mente, perché invece di utilizzare il Javascript Twitter e Facebook non utilizziamo dei pulsanti di condivisione custom che puntano ai vari sharer. [Vedi qui](http://stackoverflow.com/questions/12448134/social-share-links-with-custom-icons)
  Risolveremmo:
  - Il problema dell'allineamento.
  - I problemi di caricamento.
  - E inoltre possiamo anche customizzare il titolo che apparirà sui social in maniera tale da non far apparire sempre "Alloggi | Terremoto Centro Italia" per ogni link diverso ma le effettive informazioni degli alloggi.
- Potremmo inoltre cambiare colore (o evidenziare in altro modo) la sezione che è selezionata dall'ancora per evidenziarla meglio.
- Per quanto riguarda truncate non ci sono altre informazioni da poter utilizzare come ID? Una data, un ID o altro...
- Il JS comunque viene caricato ovunque non per la cache ma perché è stato inserito nell'head.html che viene inserito in ogni pagina.
- Per il permalink non ho capito bene, io intendevo di cambiare la scritta "Permalink" in semplicemente "Link", dato che molti credo non sappiano cosa è un permalink.

**Comment by Pinzauti** [comment]
@mfortini C'è qualcosa che non va nel css in fondo pagina e anche nell'url condiviso. Comunque anche io sto aggiungendo i pulsanti tra un po' faccio una pull.

**Comment by mfortini** [comment]
- ho eliminato i puntini in fondo alla stringa troncata. Usiamo i primi 20 caratteri della descrizione, spero bastino (sha256 non c'è in liquid per jekyll)
- ho usato i tasti fb e twitter che ci sono nel template, così è anche più uniforme
- la scritta Link andrebbe allineata al centro verticalmente
- il link facebook non va perché pare che il sito non sia fra quelli autorizzati. Dovrebbe essere un problema di settare alcune variabili della pagina

**Comment by mfortini** [comment]
@Pinzauti ok mi dispiace se ti ho pestato i piedi, dimmi quando hai fatto grazie

**Comment by Pinzauti** [comment]
@mfortini figurati l'importante è che funzioni :)
Comunque adesso vedo che la pull va in conflitto a causa dei cambiamenti, quindi è inutile che continui.
Provo a fare un altro fork

**Comment by Pinzauti** [comment]
@mfortini Unica cosa non riesco a capire da dove arrivi questo effetto, si verifica dall'aggiunta dei pulsanti.
![capture](https://cloud.githubusercontent.com/assets/16691846/18108555/0ab21df8-6f0d-11e6-82c2-f38a365821b7.PNG)

**Comment by Pinzauti** [comment]
@mfortini 
Segnalo questi errori dopo il e5e6e90:
- CSS che si comporta in maniera strana in fondo pagina. Ecco un immagine.

![css](https://cloud.githubusercontent.com/assets/16691846/18109687/330453ba-6f13-11e6-8bd7-d84de4620958.PNG)
- Problemi nella visualizzazione da mobile. 

![mobile](https://cloud.githubusercontent.com/assets/16691846/18109720/7d217d6a-6f13-11e6-8c2d-1efab8c0a714.png)
- Problemi nella condivisione su Facebook (non per problemi di autorizzazione ma per un errore nell'URL).

![url1](https://cloud.githubusercontent.com/assets/16691846/18109750/b8fdae6c-6f13-11e6-96ff-6c7cdac4b92a.png)

![url](https://cloud.githubusercontent.com/assets/16691846/18109756/bd3d278c-6f13-11e6-9402-032113454b1b.png)

Se riesci a fare un revert provo a fare una pull della modifica a cui stavo lavorando, altrimenti continuamo da qua. :)

**Comment by mfortini** [comment]
Vorrei preservare le variabili che ho generato all'inizio della lista
provo a farti revert

**Comment by mfortini** [comment]
Fatto, cerchiamo di ripristinare in fretta una pagina funzionante. Grazie mille

**Comment by Pinzauti** [comment]
@mfortini Certo di fare il prima possibile :)

**Comment by Pinzauti** [comment]
@mfortini 
Fatto. E' tardi quindi non garantisco sul risultato, ma dovrebbe andare. :+1:

**Comment by nelsonmau** [comment]
ciao gente, scusate il blackout ma non riesco a fare copia locale perché nokogiri won't work :(
`An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.` e non riesco a trovare il fix. 

In generale, mi sembra che abbiate fatto un ottimo lavoro oltre che rapidissimo.
Vi chiedo: visto che popoliamo tutto via API di fb, secondo voi non sarebbe il caso anche di importare e stampare il Timestamp? 
Così come sono gli annunci appaiono "senza tempo" e può essere misleading. Con il timestamp invece l'utente si può rendere conto di quanto è vecchio o nuovo un annuncio.

Una volta importato poi anche l'ordinamento in pagina può essere discendente in ordine temporale

spero di averla detta bene e vi chiedo se vi sembra utile

grazie!

**Comment by mfortini** [comment]
Great!

Rimane un problema con il link facebook, almeno per me.

**Comment by mfortini** [comment]
Ho aggiunto la stessa cosa nel Bollettino. Teniamo tutto in standby perché stiamo discutendo di qualcosa di simile in #148

**Comment by Pinzauti** [comment]
@mfortini Perfetto, unica cosa mi sembra non funzionino le ancore in Bollettino.
Per FB strano a me funziona...mi mandi uno screen dell'errore?

**Comment by Pinzauti** [comment]
@mfortini che ne dici di aggiungere la stessa funzione anche alle sezioni:
- Donazioni
- Raccolte fondi
- Fabbisogni

Potremmo aggiungere anche qualche altro social poi.
Qua è possibile [scaricare](https://github.com/emergenzeHack/terremotocentro/files/447385/icone.zip) le altre icone dello stesso set.
