### ISSUE TITLE
problema TAG Facebook

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#123]
Condividendo http://terremotocentroitalia.info/2016-08-30-Condividere-immagini-e-video-dell-evento/ su Facebook attualmente non compare il corretto titolo del post. Verificare i tag grazie

**Comment by mfortini** [comment]
Segnalo
https://developers.facebook.com/tools/debug/

per debuggare queste cose

**Comment by mfortini** [comment]
- ok capito il problema homepage
- penso che se esiste la variabile title, eviterei il più possibile duplicarla con titolo: fa confusione a chi fa post, se viene dimenticato è un problema

piuttosto, variabile per identificare la homepage e gestire quella nel titolo. Tocchiamo le cose una volta sola.
O addirittura, template diverso per la homepage.

**Comment by iltempe** [comment]
ora funziona. volevi fare altro?

**Comment by iltempe** [comment]
il problema pare fixato. se ci sono altre cose aprite altro issue.
