### ISSUE TITLE
Tag Description

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#126]
Meta tag description mancante in tutte le pagine. Almeno in quelle principali andrebbe scritta una breve descrizione.

**Comment by nelsonmau** [comment]
@Pinzauti ti riferisci a questo a uno di questi? 
- https://github.com/emergenzeHack/terremotocentro/blob/master/_includes/head.html
- https://github.com/emergenzeHack/terremotocentro/blob/master/_includes/meta.html
- https://github.com/emergenzeHack/terremotocentro/blob/master/_includes/header.html

vedo che funzionano tutti con il templating, ma non c'è un placeholder
come si sistema?

**Comment by Pinzauti** [comment]
@nelsonmau

**Comment by Pinzauti** [comment]
@nelsonmau Basta aggiungere `page.subtitle` nei vari md.
Il problema però è scriverle.

Scusate per la chiusura e riapertura ma ero da cellulare e ho fatto confusione.

**Comment by riccardonuzz** [comment]
basta aggiungere "description: testo_della_descrizione" sotto title io ogni pagina md

**Comment by Pinzauti** [comment]
@riccardonuzz L'aggiunta non è un problema, bisogna però che qualcuno le scriva

**Comment by p-marco** [comment]
Gentili contributori di questa bellissima iniziativa: mi faccio avanti se posso essere utile nella redazione dei vari tag description dei file md - e potrei farlo da questa sera stessa. 
Non vorrei però passare davanti a nessuno, perciò mi rimetto al vostro giudizio. 
Ancora complimenti per l'iniziativa,
Marco.

**Comment by Pinzauti** [comment]
Ciao @p-marco,
Puoi scrivere tu i description, ancora nessuno si è fatto avanti.
Grazie mille!

**Comment by p-marco** [comment]
Ciao @Pinzauti, 
grazie della gentilezza. 
Puoi trovare le modifiche sul repository nel mio git (al momento mi sono limitato alle pagine di primo livello). 
Spero di non aver sbagliato perché non sono molto ferrato con github - in caso sono pronto a modificare senza problemi. 
Scrivimi pure qui o via mail per qualsiasi necessità. 
Ciao a tutti.
