### ISSUE TITLE
Pagina "Come fare segnalazioni" (strumenti e canali)

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#127]
Visto il moltiplicarsi di canali di segnalazione suggerisco di preparare una pagina da aggiungere al sito che si chiama "segnala" dove elenchiamo tutti i canali usabili per fare segnalazioni con ICONA e link al CANALE con la descrizione di "a cosa serve quel canale"

Inserirei tra questi
- FACEBOOK per segnalazioni generiche
- WAZE per segnalazioni traffico
- FLICKR per foto
- BOT Telegram per segnalare da campo

La metterei nel sito perchè è più immediata.

Che dite?

**Comment by iltempe** [comment]
Può essere fatto revisionando questa pagina.

http://terremotocentroitalia.info/aiuto/ e nominandola SEGNALA

**Comment by gufogio** [comment]
Me ne sto occupando.
