### ISSUE TITLE
Hashtag per la comunicazione esterna

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#129]
Ho un dubbio sul continuare a usare #terremoto per veicolare all'esterno informazioni già processate e verificate: in quel flusso su Twitter viene fuori di tutto e di più, una persona che lo clicca per cercare info utili difficilmente trova le nostre. 

Propongo di continuare a usare [le regole](http://terremotocentroitalia.info/2016-08-25-come-postare-sui-social/) de @iltempe per chiedere alle persone di condividere le richieste dal campo, le raccolte fondi, ecc, mentre comunicare all'esterno, con il nostro account, diffondiamo i contenuti con #terremotoinfo in modo tale che ci distinguiamo dal resto e comunichiamo che questa etichetta vale per post verificati. Che ne dite?
#109

Sono aperta al dibattito.

**Comment by favoeva** [comment]
ok @dontyna sono daccordo ma per i primi giorni usiamoli insieme ( anche se l'hashtag terremoto non è TT oggi, non sottovalutiamo che alcuni potrebbero continuare a usarlo per ricerche tw ...) inserirei comunque da subito questa indicazione anche in gsheet per redazione contenuti BOLLETTINO che è automatizzato con account twitter (utilizzare hashtag #terremotoinfo) #109  

qui il link a gsheet BOLLETTINO dove ho già inserito alcune indicazioni per ottimizzare automatismi tw e telegram https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=220064593 

ditemi ...

**Comment by cristigalas** [comment]
Sì, concordo... credo che almeno per ora sia meglio usare entrambi gli hashtag. Alle 15 posso allora seguire Twitter....

**Comment by dontyna** [comment]
Ok. Tra l'altro _#terremotoinfo_ è solo una proposta, vorrei capire cosa ne pensa anche @iltempe .

**Comment by iltempe** [comment]
io penso che a emergenza24 era stato dato #terremotocentroitalia come ht ufficiale. immagino lo usino per tuittare il nostro sito. per me potete cabiarlo come volete purchè si sappia qual'è quello monitorato. @aborruso inoltre aveva messo in piedi un meccanismo per archiviare i tweet con un certo ht quindi va aggiornato se lo cambiate. grazie a tutti/e

**Comment by favoeva** [comment]
Allora direi #terremotocentroitalia (l'abbiamo già messo anche nella short bio ) così chiudiamo la issue e alziamo la percentuale delle issue chiuse facile-facile 😜

**Comment by Pinzauti** [comment]
Nella #186 ho aggiunto (nella condivisione tramite Twitter) gli hashtag #terremoto e #terremotoinfo come detto da @dontyna 
Modifico in #terremotocentroitalia o lascio?

**Comment by dontyna** [comment]
@Pinzauti lasciamo #terremotocentroitalia

**Comment by favoeva** [comment]
@iltempe ok la chiudiamo.

**Comment by Pinzauti** [comment]
@dontyna @favoeva
Forse non mi sono spiegato bene:
Attualmente (dopo la #186) sul sito gli hashtag nella condivisione via Twitter sono #terremoto e #terremotoinfo.
Se volete cambairli in #terremotocentroitalia chiedete a uno sviluppatore di farlo. Lo farei io ma sono fuori casa in questi giorni.

**Comment by iltempe** [comment]
riaperto. per favore fa impostato l'HT #terremotocentroitalia e basta sulla condivisione.

**Comment by iltempe** [comment]
fatto.
