### ISSUE TITLE
Gestione Periodica CSV ->Github per sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#13]
E' da creare un cron che ogni "tot tempo" (da definire quanto) prelevi il contenuto in CSV di https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=0 e lo archivi nella cartella DATA di questo repo https://github.com/emergenzeHack/terremotocentro/tree/master/_data secondo la classificazione fatta dei contenuti.

**Comment by mfortini** [comment]
Fatto, lo script gira ogni 5 minuti su un server, _per favore controllate prima di push di nuove versioni!_
