### ISSUE TITLE
Testo in tabella troppo piccolo

### ISSUE THREAD

**Issue by gufogio** [emergenzeHack/terremotocentro#137]
Vedere ad esempio http://terremotocentroitalia.info/about/. Pure da mobile non si legge molto.

**Comment by mfortini** [comment]
Il testo l'ho messo piccolo perché altrimenti era molto fuori centro la tabella. Penso si debba pensare di usare bootstrap e una grid in modo da tenere le cose ordinate.

**Comment by iltempe** [comment]
anche la pagina http://terremotocentroitalia.info/press/ mi è venuta cosi. immagino stesso motivo.

**Comment by ghost** [comment]
Ciao, il problema delle tabelle è il container. Il layout è stato concepito per essere liquido per cui la tabella contenuta si adatta alla regola "col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1". Una soluzione immediata potrebbe essere. Togliere l'attuale regola sul font-size applicata per le tabelle, quì la [preview about](https://cloud.githubusercontent.com/assets/330838/18120859/1ba27d1a-6f62-11e6-8c10-1e74f21ffa6b.png) e [preview press](https://cloud.githubusercontent.com/assets/330838/18121186/ab446874-6f63-11e6-9513-39d5705b9c48.png). È un po brutto vedere le date così giganti ma chi ha problemi di vista probabilmente ci ringrazierà. Che dite ?
