### ISSUE TITLE
Mappatura iniziative operatori telecomunicazioni

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#139]
Da segnalazione FB, ci sono due pdf con iniziative dei provider da estrapolare e mettere in "donazioni"? http://www.ilsole24ore.com/pdf2010/Editrice/ILSOLE24ORE/ILSOLE24ORE/Online/_Oggetti_Embedded/Documenti/2016/08/31/agcom-mappa-solidarieta.pdf + http://www.ilsole24ore.com/pdf2010/Editrice/ILSOLE24ORE/ILSOLE24ORE/Online/_Oggetti_Embedded/Documenti/2016/08/31/agcom-tab-iniziative-urgenti-1.pdf

**Comment by iltempe** [comment]
io i pdf li archivierei in archive.org almeno non si perdono.
