### ISSUE TITLE
Note legali al sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#14]
Vanno inserite le note legali del sito.

**Comment by olistik** [comment]
È un requisito anche per #10 .
Sto creando una Privacy Policy con [Iubenda](https://www.iubenda.com).

Per ora ho inserito i servizi:
1. Instagram Authentication
2. Google Analytics with anonymised IP (vedi #17)

Ne servono altri?

Per i campi Name e E-mail, cosa possiamo mettere?

<img width="401" alt="screen shot 2016-08-26 at 19 19 13" src="https://cloud.githubusercontent.com/assets/21038/18014174/ff914320-6bc1-11e6-9bbf-dd254bc43a8d.png">

**Comment by iltempe** [comment]
domani arriva un testo di un legale.

**Comment by aborruso** [comment]
@iltempe se non arriva quello di iubenda è perfetto e a nomra

**Comment by Pinzauti** [comment]
@iltempe Ci sono novità? Con la #114 avevo inserito un piccolo banner per i cookie in attesa della privacy e cookie policy però vedo che non è stata presa in considerazione.

**Comment by iltempe** [comment]
Per favore per i coockie mettete questo banner @Pinzauti o comunque se hai già fatto pulla. Il resto è a posto su /legal

INFORMATIVA BREVE PER COOKIE (BANNER)

Questo sito utilizza cookies analitici e di terze parti per funzionalità quali la condivisione sui social network e/o la visualizzazione di media. Chiudendo questo banner, cliccando in un'area sottostante o accedendo ad un'altra pagina del sito, acconsenti all’uso dei cookie. Se non acconsenti all'utilizzo dei cookie di terze parti, alcune di queste funzionalità potrebbero essere non disponibili. Per maggiori informazioni consulta la pagina Privacy policy [inserire link]
