### ISSUE TITLE
bot telegram miglioramenti

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#147]
Con il campo si discuteva di:
- usare il bot per segnalazioni
- inviare i dati a foglio Google sheet o altro sistema di centralizzazione informazioni (vedi qui https://github.com/emergenzeHack/terremotocentro/issues/148)
- avere un campo nel sistema centrale che permetta in centrale di validare la richiesta
- quando la richiesta è validata aggiornare un feed rss unico da distribuire su Twitter telegram e sito 
- rispondere a chi fa la segnalazione con dati utili se ci sono
- pensare a gestire la chiusura di una richiesta (da definire ancora il metodo vedere qui https://github.com/emergenzeHack/terremotocentro/issues/148).

Questo issue si aggancia a come si decide di implementare 
questo meccanismo https://github.com/emergenzeHack/terremotocentro/issues/148

**Comment by aborruso** [comment]
@iltempe foglio elettronico fatto https://docs.google.com/spreadsheets/d/1NOThalsYqG9YeH_vvH3ol5VxTa5oMUdkH-nZ7isqkFs/edit?usp=sharing

**Comment by iltempe** [comment]
Chiudo, sono state prese altre stade che vanno documentate quanto prima.
