### ISSUE TITLE
meccanismo apertura/chiusura segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#148]
Dal campo ci chiedono di valutare un formato dati e un metodo opportuno per potere rendere dinamiche tutte le informazioni ed in particolare 
- offerte alloggi 
- segnalazioni
- richieste di aiuto

Il senso è fare in modo di gestire quando una di queste informazioni "scade" perché la segnalazione venga automaticamente chiusa.

**Comment by iltempe** [comment]
Con @mfortini stamo valutando la possibilità di fare questa azione con gli ISSUE di Github. Fare in modo cioè che in un repository github arrivino le segnalazioni (dai vari canali che abbiamo) come ISSUE e come tali siano gestiti. Sul tema mi piacerebbe il parere di un po' di voi tipo @aborruso ma anche tutti gli altri. Che ne dite? Proviamo?

**Comment by lorenzoperone** [comment]
Ciao,
lo trovo attimo, permette di registrare l'assegnazione della issue la data
di apertura/chiusura e il commento di chiusura della stessa.
My two cents.
l.

Lorenzo Perone
twitter: @lorenzo_perone https://twitter.com/lorenzo_perone
photoblog: http://immagini.me

Il giorno 31 agosto 2016 09:17, Iltempe notifications@github.com ha
scritto:

**Comment by mfortini** [comment]
Pro:
- consolidato
- markdown nei commenti ma anche plain text
- email e possibilità di reply via email
- tag delle issue
- il bot potrebbe inserire issue via API taggandole bot
- embeddiamo la lista nel sito
- commenti, chiusura, riapertura, storico

Contro:
- necessità di account github per alcune cose
- c'è un minimo da imparare ad usarlo

Secondo il mio punto di vista uno strumento così potente non lo mettiamo 
in piedi in un giorno

Il 31/08/2016 09:17, Iltempe ha scritto:

**Comment by aborruso** [comment]
Le caratteristiche di un issue tracker sono quanto di più vicino mi viene in mente per una cosa di questo tipo. E' un'ottima idea e difatti github è usato per mille altre cose.

Secondo me:
- scriviamo un documento di una pagina con il caso d'uso insieme a che è sul campo (in cui parliamo non della tecnologia, ma di cosa è necessario);
- poi si apre un nuovo repo solo per questo;
- si scelgono le label per i repo;
- si scrive una guida di una pagina per tutti;
- si crea una redazione da assegnare solo a questo a repo.

My 2 cents

**Comment by lorenzoperone** [comment]
Tra l'altro l'applicazione github da mobile sarebbe comoda per chi è in campo, manca solo la possibilità di inserire coordinate.

**Comment by mfortini** [comment]
@lorenzoperone da mobile vorrebbero continuare a usare Telegram per segnalare, probabilmente il nostro valore aggiunto sarebbe proprio quello di fare il collegamento

**Comment by nelsonmau** [comment]
ottimissimo, bisogna capire chi sta sul campo cosa riesce a fare (dovrebbe spiegare come si fa).
è christian quintili? ma non è iscritto a github?

**Comment by nelsonmau** [comment]
d'accordo con @mfortini

**Comment by ghost** [comment]
E' necessario passare per Github?  Non riusciamo a fare tutto tramite Telegram? 

Creazione Offerta: 
-L'utente apre una richiesta e invia descrizione e dati vari
-Il Bot restituisce un Id dell'operazione numerico e aggiorna GSheet

Disattivazione Offerta:
-Il Bot richiede l'Id 
-L'utente copia l'Id che aveva ricevuto e chiede di disattivare l'offerta. 
-Il Bot aggiorna GSheet

L'offerta può essere attivata/disattivata infinite volte, cambiamo solo un campo Bool nel GSheet

**Comment by iltempe** [comment]
Tiro le fila se per voi è ok,
- In questa fase usiamo Gsheet come meglio si ritiene opportuno per gestire dal BOT le segnalazioni.
- Si cerca di integrare da subito nel BOT Telegram (senza cambiare l'interfaccia utente) un modo per segnalare su GITHUB gli issue. Questo perchè si migliora in gestione e abbiamo dati in automatico in più. Per gestire issue Github mi offro io di fare WIKI e supporter per insegnare ad un team di persone.

**Comment by gufogio** [comment]
Se quello che ci serve è attivare/disattivare/modificare un'offerta, non so quanto valga la pena star lì a collegare Github con il bot. Non basta avere un database SQL sullo stesso server del bot, più un API per esportare il CSV? Mi sembra più semplice e efficace

**Comment by iltempe** [comment]
Chiudo. Sono state prese altre strade che vanno documentate e coordinate qui quanto prima.
