### ISSUE TITLE
Feed Rss da Waze

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#150]
Sono riuscito ad avere da Waze Italia il feed rss della viabilità. Direi, per chi può farlo, di usarlo per 
- archivio dati e pagina relativa
-  canale telegram 
- Twitter 
- Altro? 

http://www.wazeitalia.it/home/events/?cat=3&feed=rss2 

Provatelo prima.

**Comment by aborruso** [comment]
@iltempe è un feed per tutto il territorio nazionale o è ristretto alle "nostre" aree?

**Comment by iltempe** [comment]
È un feed creato per "evento terremoto". Il che vuol dire che ci finisce tutto ciò che Waze categorizza come terremoto 24 agosto.

**Comment by aborruso** [comment]
On 31 August 2016 at 10:12, Iltempe notifications@github.com wrote:

> È un feed creato per "evento terremoto". Il che vuol dire che ci finisce
> tutto ciò che Waze categorizza come terremoto 24 agosto.

Lo inserisco nel megafeed e faccio confluire avvisi sia in channel che in
gruppo (con tag #waze)?

---

Andrea Borruso
website: http://blog.spaziogis.it
38° 7' 48" N, 13° 21' 9" E, EPSG:4326

---

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by iltempe** [comment]
Ottimo. Forse anche Twitter?

**Comment by drizzt** [comment]
Se preferite atom il feed si trova qui http://www.wazeitalia.it/home/events/?cat=3&feed=atom

**Comment by aborruso** [comment]
Ok, attivate tutte le automazioni (canale e gruppo Telegram, mega feed e account twitter)
