### ISSUE TITLE
elenco eventi facebook su amatrice

### ISSUE THREAD

**Issue by ipersoft** [emergenzeHack/terremotocentro#151]
elenco in aggiornamento in formato json http://www.ipersoft.it/amatrice/
possibilità di aggiungere come query di ricerca le altre città

**Comment by ipersoft** [comment]
esempio di mappa 
https://www.infocitta.info/terremotocentroitalia/

https://github.com/infocitta/terremotocentroitalia

**Comment by iltempe** [comment]
@ipersoft fai scrape di fb?

**Comment by ipersoft** [comment]
uso le api di facebook per recuperare gli eventi.
il problema riguarda il fatto che facebook ti permette di ricercare gli eventi per contenuto, restituendo una ventina di eventi.
ho fatto un sistema che interroga facebook per un tot di città ogni ora. Il giro totale dura un paio di giorni.

http://www.ipersoft.it/eventsmap/

**Comment by iltempe** [comment]
chiudo.
