### ISSUE TITLE
 Sottomenu per "Vuoi donare?"

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#153]
La voce di menu del sito "Vuoi donare?" dovrebbe poter avere sottovoce di menu come accade per "Il progetto, "Hai bisogno?" e "Aggioramenti". È divisa infatti in tre sottosezioni: per arrivare all'ultima bisogna scorrere tutta la pagina e soprattutto a prima vista non si percepisce che oltre alle raccolte fondi ci sono anche altre voci ("Donazioni" e "Fabbisogni"). Se il menu con le sotto voci non è praticabile, almeno una lista delle sezioni con le ancore a inizio documento sarebbe opportuna.

**Comment by epoeta** [comment]
Ok Vincenzo. A inizio sezione e fine sezione link che riportino all'indice delle ancore?

**Comment by ghost** [comment]
@epoeta ho inserito l'implementazione dello scroll on top.

**Comment by epoeta** [comment]
OK. Adesso mi pare stiano lavorando a pagine autonome. Ma non posso verificare (connessione ballerina)
