### ISSUE TITLE
Fabbisogni nella sezione donazioni

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#161]
Ci sono annunci di fabbisogni nella sezione "Donazioni" invece che nella sezione "Fabbisogni".
In più non è ben chiara la differenza tra le due sezioni, forse andrebbe rinominata la sezione "Donazioni" in maniera più specifica.

**Comment by favoeva** [comment]
La stiamo specificando qui https://github.com/emergenzeHack/terremotocentro/wiki/Linea-guida-per-compilare-il-google-sheet-%28bozza%29/_edit

**Comment by Pinzauti** [comment]
Perfetto @favoeva 
Sposterei anche i fabbisogni giá presenti in "Donazioni" nella sezione "Fabbisogni".

**Comment by favoeva** [comment]
ok @Pinzauti se hai altre richieste vai in questa issue dedicata #28
