### ISSUE TITLE
Dati strutturati

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#163]
Sarebbe utile aggiungere del markup al sito.

**Comment by ghost** [comment]
Per eventuali test: https://search.google.com/structured-data/testing-tool/u/0/
Vedo se riesco a trovare un mapping degli elementi che ci sono sul sito in schema.org

**Comment by Pinzauti** [comment]
Segnalo anche[ l'helper di Google](https://www.google.com/webmasters/markup-helper/) e la [documentazione](https://developers.google.com/search/docs/guides/intro-structured-data) che possono aiutare.

**Comment by ghost** [comment]
Individuati a livello strutturale:
- http://schema.org/Organization 
- https://schema.org/WPFooter
- https://schema.org/SiteNavigationElement

Altri futuri:
- http://schema.org/Article da applicare negli articoli tuttavia ci manca author publisher e l'immagine
- http://schema.org/Persona da applicare nell'elenco delle vittime, sfortunatamente non sono riuscito ad inniettare span dentro l'md per cui se vogliamo farlo dobbiamo trasformare queste in html.

Direi che quelle più salienti per i motore di ricerca ci sono.

**Comment by Pinzauti** [comment]
@tailot Perfetto solo una cosa, nel footer c'è un errore.
![screenshot_20160901-021846](https://cloud.githubusercontent.com/assets/16691846/18150873/875cb858-6fea-11e6-8923-3f113a48d471.png)

**Comment by ghost** [comment]
Dimmi così lo cambio

**Comment by Pinzauti** [comment]
@tailot quel "sameAs"

**Comment by ghost** [comment]
@Pinzauti ok visto
