### ISSUE TITLE
Link Copernicus

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#166]
Al link sottostante trovate mappe e relativi dati sia rester che vettoriali prodotti dal servizio emergency di COPERNICUS 

http://emergency.copernicus.eu/mapping/#zoom=2&lat=35.93975&lon=-34.99735&layers=00B0T

Qui invece webgis con i dati COPERNICUS pubblicati online 

http://www.arcgis.com/home/item.html?id=06e62f6134f24d2fafdfe1f9bfa7e127

**Comment by alesarrett** [comment]
Il servizio copernicus e il link al progetti relativo al terremotoin Italia sono già presenti nel blog post su Openstreetmap: http://terremotocentroitalia.info/2016-08-29-Risorse-e-attivit%C3%A0-di-mappatura-su-Openstreetmap/
C'è da fare un altro blog post specifico?
Oppure non si potrebbe mettere nella sezione "Mappe" del testo statico (invece che i blog posts) che riassuma le varie informazioni in un testo e delle liste abbastanza semplici che fanno poi riferimenti ai vari blog posts?

Per quanto riguarda il secondo link, non si capisce assolutamente da dove vengono i dati, chi li ha metti su ecc... Da dove è stato comunicato il link?

**Comment by iltempe** [comment]
@alesarrett è arrivata una mail al nostro sistema

**Comment by alesarrett** [comment]
Ho spedito un'email di richiesta di approfondimenti prima di aggiungere le informazionial sito

**Comment by iltempe** [comment]
@alesarrett hai update?
