### ISSUE TITLE
Inserire nel footer logo ActionAid

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#168]
Inserire nel footer in piccolo il logo di actionaid al posto del link al loro sito se tecnicamente possibile

![logo aa_nuovo_rgb](https://cloud.githubusercontent.com/assets/6368214/18132078/8719de02-6f95-11e6-956b-b9dfad2b87f8.png)

**Comment by iltempe** [comment]
Va inserito scrivendo "con il sostegno di " + logo piccolo

**Comment by massimog** [comment]
Prendo in carico

**Comment by massimog** [comment]
Questo è il logo ridimensionato e reso trasparente, va messo sotto /images/actionaid-logo.png (io non posso caricarlo)

![actionaid-logo](https://cloud.githubusercontent.com/assets/6948602/18206138/a332994e-7125-11e6-8a5d-eb5023d543b5.png)

**Comment by massimog** [comment]
Perdonate, maestri, non conosco ancora bene Git. Ci riprovo e questa volta faccio il fork come consigliato
