### ISSUE TITLE
Problema visualizzazione mobile

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#172]
Da mobile alcune pagine (tra cui l'home) non si visualizzano correttamente in quanto parte del contenuto della pagina straborda.
Questo rende necessario un resize da parte dell'utente.
Allego screenshot.
![screenshot_20160831-181227](https://cloud.githubusercontent.com/assets/16691846/18137216/c18bb36e-6fa7-11e6-9a40-9d3be096b801.png)

![screenshot_20160831-181211](https://cloud.githubusercontent.com/assets/16691846/18137223/cadd0b7a-6fa7-11e6-92d4-3ae0b8360bfe.png)

**Comment by gufogio** [comment]
Nella home il difetto è dovuto a un titolo troppo lungo (_Waze supporta TerremotoCentroItalia_), dovremmo aggiungere al CSS qualcosa come `hypens: auto; word-break: break-word;` in modo che la parolona _TerremotoCentroItalia_ venga spezzata.

![schermata 2016-09-01 alle 09 56 20](https://cloud.githubusercontent.com/assets/8479376/18159734/5ddd4552-702a-11e6-9fa8-ae5e8828e3b5.png)

Nel secondo caso con `display: block; overflow: auto;` potremmo far rientrare la barra orizzontale nella tabella, non so però se vale la pena e le cose migliorano visivamente. Si potrebbe pensare di fare un layout tipo "lista" per il mobile.

![schermata 2016-09-01 alle 09 54 37](https://cloud.githubusercontent.com/assets/8479376/18159740/659f4ce0-702a-11e6-81f0-6ed0bc24c22a.png)

**Comment by Pinzauti** [comment]
@gufogio Mi sembrano tutte e due valide soluzioni, secondo me un overflow non da fastidio. Al limite potremmo fare anche una media query e ridurre di un po' il carattere da mobile.

**Comment by Pinzauti** [comment]
Dopo la pull di @gufogio l'home page ed altre pagine si visualizzano correttamente.
Rimane però il problema nelle sezioni "Canali di comunicazione ufficiali" e "Mappe".

**Comment by Ibernato93** [comment]
Una soluzione migliore sarebbe quella di creare una applicazione mobile così si gestisce meglio, altrimenti ci tocca adattare il sito.

**Comment by iltempe** [comment]
chiudo?

**Comment by Pinzauti** [comment]
No @iltempe ci sono ancora due pagine che danno problemi: 
- "Canali di comunicazione ufficiali"  (per via del titolo lungo).
- "Mappe" (per via delle mappe appunto).

**Comment by riccardonuzz** [comment]
si può chiudere, fixato

**Comment by Pinzauti** [comment]
Perfetto, chiudo.
