### ISSUE TITLE
Raccolta fondi non mostra il campo causale

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#174]
Il Gsheet di Raccolta fondi è strutturato con alcuni campi come "Causale" che sono utili a rendere più ordinato il data entry. Ma il template non mostra la voce "Causale". Sarebbe opportuno renderla visibile.

**Comment by drizzt** [comment]
io la vedo la casuale (quando c'è), per esempio la provincia di reggio emilia http://terremotocentroitalia.info/fondi/

**Comment by Pinzauti** [comment]
@drizzt Non vorrei sbagliarmi ma credo si riferisca alle linee guida per compilare il Google Sheet.

**Comment by drizzt** [comment]
@Pinzauti anche le linee guide comprendono la Casuale https://github.com/emergenzeHack/terremotocentro/wiki/Linea-guida-per-compilare-il-google-sheet-(bozza)

**Comment by Pinzauti** [comment]
@drizzt Hai ragione, prima avevo guardato e mi sembrava di no. Allora non lo so sinceramente

**Comment by epoeta** [comment]
Che dire ragazzi? Prima inseriti item nel Gsheet con tanto di causale e non li mostrava. Ora li mostra.
