### ISSUE TITLE
Fabbisogni in ordine cronologico

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#176]
Suggerimento che arriva da FB: nella sezione "fabbisogni" invertirei l'ordine cronologico perché credo che l'urgenza sia l'elemento principale quindi partirei dagli ultimi (e man mano che passano i giorni toglierei quelli che non servono più, altrimenti si rischia di dare informazioni sbagliate).

**Comment by aborruso** [comment]
@dontyna mi sembra già così http://terremotocentroitalia.info/fabbisogni/

Buttaci un occhio anche tu e eventualmente chiudila (ormai posso parlare in gergo)
