### ISSUE TITLE
Caricamento home page lento

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#178]
Come è possibile vedere [qui](https://gtmetrix.com/reports/terremotocentroitalia.info/lg01mEjH) e [qui](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fterremotocentroitalia.info%2F&tab=mobile) il caricamento dell'home page risulta davvero molto lento.

**Comment by drizzt** [comment]
visto che la stragrande maggioranza dei problemi sono dovuti ad umap credo si possa fare poco. si può giusto spostare qualche include javascript o css, ma poca roba.
forse cloudflare potrebbe aiutare ulteriormente visto che ha server ovunque

**Comment by iltempe** [comment]
@mfortini altre piattaforme per mapping?

**Comment by ghost** [comment]
Se si considera la quantità di dati che contiene la mappa, si carica anche velocemente.

**Comment by drizzt** [comment]
rimanendo su umap sembrerebbe che altre istanze supportino gzip, per esempio http://umap.osm.ch/

**Comment by Pinzauti** [comment]
@tailot 
Si però per un'home page (secondo me) i tempi non sono accettabili, soprattutto sotto 3G.

Si rischia:
- Alta frequenza di rimbalzo, la gente scappa.
- Penalizzazione in SERP da parte di Google.
- Problemi di fruizione generali, soprattutto su vecchi device non troppo performanti.

Fino a che era solo nella sezione "Mappe" ci poteva stare ma adesso secondo me va trovata una soluzione.

**Comment by ghost** [comment]
@Pinzauti si concorto, la cosa che può dare fastidio è 1,2 MB di dati scambiati specialmente in 3g. In paesini credo che vadano direttamente in roaming.

**Comment by mfortini** [comment]
OK ci guardiamo, grazie dei commenti molto dettagliati

Il mer 31 ago 2016, 21:50 Vincenzo Tilotta notifications@github.com ha
scritto:

**Comment by Pinzauti** [comment]
La mappa è stata tolta dall'home page quindi direi che possiamo chiudere.

**Comment by mfortini** [comment]
Ni, nel senso che ci piacerebbe avere una mappa in homepage... :)

Il 31/08/2016 22:48, Francesco Pinzauti ha scritto:
