### ISSUE TITLE
Utilizzare il campo "approvato" per i CSV

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#18]
Attualmente i CSV ignorano il campo approvato. Inserire un if nel template per ignorare le voci non approvate.

**Comment by aborruso** [comment]
@mfortini ma nel foglio elettronico c'è una colonna "approvato"? Parli del foglio generale o ce ne è un altro?

**Comment by mfortini** [comment]
Nella cartella DB c'è un foglio che pesca da quello originale per poterlo
pulire  https://drive.google.com/folderview?id=0B6F5bbIgNBMFU0wyQUJvYV9SMGM

I fogli publish non sono ancora usati

Il sab 27 ago 2016, 09:57 Andrea Borruso notifications@github.com ha
scritto:

**Comment by aborruso** [comment]
@mfortini nel tuo [script](https://github.com/emergenzeHack/terremotocentro/blob/master/scripts/csvupdate.sh) di chiamata ai CSV potrestri mettere la query con verifica di approvazione direttamente nell'URL di chiamata.

Ad esempio per "contatti":

```
http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CF%2CG%2CH%2CI%2CJ%2CK%20where%20A%20%3D%27x%27&key=1WL5BuoKQRM560VNctYOeDeineLeBwP7vtFlwltasASM&gid=0
```

In cui dentro c'è

``` SQL
select A,B,C,D,E,F,G,H,I,J,K where A ='x'
```

**Comment by gufogio** [comment]
Oppure fare direttamente un {% if %} nel template?

**Comment by iltempe** [comment]
direi superato con #242
