### ISSUE TITLE
Modifica FEED Bollettino per facilitare monitoraggio social

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#183]
Parlando con  @dontyna abbiamo valutato che il Bollettino potrebbe contenere informazioni doppie 
e ridondanti rispetto ad altri fogli. In ogni caso questo aumenta il lavoro di chi riempie il foglio perchè deve riempire Bollettino+Altrofoglio (quello relativo al contenuto da registrare)

Un modo che mi è venuto in mente per facilitare il lavoro è rimuovere il foglio Bollettino ed inserire una colonna Bollettino (da marcare con una X) nei fogli:
- Raccolte Fondi
- Donazioni
- Alloggi
- Notizie Utili
- Fabbisogni

e creare Feed RSS Bollettino dalle righe nei vari fogli. 

In questo modo le informazioni vengono messe solo nei "normali fogli di lavoro" e con una X si indica se si vuole inviarle come Bollettino.
Che ne pensate?

**Comment by dontyna** [comment]
Sarebbe meraviglioso.

**Comment by aborruso** [comment]
@iltempe dove posso leggere come funziona adesso? Così posso capire cosa fare a livello di RSS e segnalazioni automatiche. 

Grazie

**Comment by iltempe** [comment]
@aborruso stiamo

**Comment by iltempe** [comment]
@aborruso attualmente funziona con il foglio
https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=1997631888
e la gestione spiegata nei WIKI
Avevo chiuso l'issue perchè vorremmo muoverci su questa proposta e gestire tutto in un nuovo modo
https://docs.google.com/document/d/1--3bSH7R9uGaaLlbjfi9uflgjv2wf1fcrGz_ImrBUvk/edit#heading=h.kl2ttjat7j6m

Che dici?

**Comment by aborruso** [comment]
@iltempe nel primo messaggio leggo "creare Feed RSS Bollettino dalle righe nei vari fogli". Volevo solo capire se già c'è un feed RSS che crea dai vari fogli?

Credo di no, e che il feed ci sia solo per il Bollettino. Volevo capire se fosse utile una fase di transizione e gestire per un po' come descrivevi nel primo post di questo thread

**Comment by iltempe** [comment]
@aborruso si può fare certamente. Il feed c'è solo per il bollettino ora. Io intanto inizio ad aprire issue per gestire tutto il resto. Grazie
