### ISSUE TITLE
Feed Rss per un wall di notizie

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#187]
un certo @aborruso ha messo in piedi un feed aggregando varie fondi

http://feeds.feedburner.com/TerremotoCentroItalia-RaccoltaFeedRss

andrebbe creata una pagina "ultime notizie" per spararlo dentro.

se possibile, con live search.
- per creare la pagina se non c'è di meglio si può usare questo https://github.com/imonroe/simplenewsrss
- questo invece per impostare un filtro: si popola un campo di ricerca con una key, il sistema nasconde tutti gli item che non la contengono (quindi è alla fine l'effetto è tipo live search). Di default funziona sulle <table> ma si può fare anche sui <p> o altri, basta dirglielo

https://github.com/rmm5t/jquery-sieve

Se piace e qualche anima più ci si mette, si fa tutto in un paio d'ore max

**Comment by nelsonmau** [comment]
(simple rss ha bisogno anche di moment.js - che va aggiunto - sennò ha problemi sul parsing della data e la scrive all'americana).

**Comment by iltempe** [comment]
Potrebbe essere ottima cosa da mettere in HOME page assieme alla mappa delle segnalazioni (accanto o sotto). Vedo che ne tiro fuori

**Comment by epoeta** [comment]
Potrebbe teoricamente funzionare un sistema automatizzato con chiavi del genere elenco dei nomi delle località (vedi elenco [qui](http://www.mef.gov.it/ufficio-stampa/comunicati/2016/comunicato_0153.html)) e operatori booleani che combinino la query con altre query come sisma, terremoto, zone terremotate, cratere eccetera. Due attenzioni: la query andrebbe costruita in collaborazione con e monitorata dal media team per selezionare o togliere item irrilevanti, fuori policy - esiste? - eccetera ([Facebook docet](http://www.ilpost.it/2016/08/31/trending-topics-megyn-kelly/)). Seconda attenzione: le fonti. Anche in questo caso le sorgenti del feed devono essere valide e "validate" (rischio bufale eccetera).

**Comment by iltempe** [comment]
Aggiornamenti rss maxi feed in home. Non funzionano ancora.

**Comment by nelsonmau** [comment]
@iltempe in che senso non funzionano? qualcuno sta lavorando alla implementazione?

**Comment by iltempe** [comment]
ho fatto delle prove in locale. provato a committare ma serve lavorare di CSS per avere una tabella fatta a "modino". quindi ti direi attualmente non ci sta lavorando nessuno.

**Comment by nelsonmau** [comment]
ok provo a finalizzare qlc io entro stasera.
Intanto lo metto in funzione con il feed di @aborruso, poi vedremo meglio come gestire le fonti.
Entro sera committo una roba che funziona

**Comment by epoeta** [comment]
@nelsonmau la gestione fonti potrebbe essere inserita in #242, no?

**Comment by nelsonmau** [comment]
@epoeta certamente sì, definite insieme al team comunicazione con @dontyna e @favoeva e gli altri/le altre :)

**Comment by nelsonmau** [comment]
**Under Embargo**

@iltempe Per il momento ho fatto tutto in html e funziona (anche il parsing data)
http://terremotocentroitalia.info/news.html

non è linkata nel menu, magari @Pinzauti o @mfortini mi riescono a dare una dritta o a fare loro:

il mio problema è che sono praticamente a digiuno di jekyll e in mezz'ora mi viene difficile impararlo :D  E allora: per creare una pagina che importa un feed rss dall'esterno ho bisogno di includere alcune librerie javascript

**Comment by epoeta** [comment]
@iltempe @nelsonmau sul feed si vede in tutta la sua evidenza il problema del template dei tweet automatici di cui a #233

**Comment by nelsonmau** [comment]
ho implementato anche una livesearch, @dontyna sarà orgogliosa di me

![livesearch](https://cloud.githubusercontent.com/assets/1769578/18282522/c3847d22-7461-11e6-9357-9e4803672459.png)

**Comment by iltempe** [comment]
@nelsonmau quando si muove fa cose bellissime.

**Comment by nelsonmau** [comment]
:) metterei questa pagina come voce del menu "aggiornamenti" se non l'avete già messa altrove
http://terremotocentroitalia.info/news/

**Comment by iltempe** [comment]
@Pinzauti si può aggiungere a #275 ?

**Comment by nelsonmau** [comment]
l'ho messa ma non funziona... ho editato config.yml
se mi dite dove ho sbagliato mi fare contento così capisco :)

``` navbar-links:
  Aggiornamenti:
    - News: "news/"
    - Bollettino: "bollettino/"
    - Blog: "post/"
    - Storie: "storie/"
  Hai bisogno?:
    - Segnala: "aiuto/"
...

```

**Comment by nelsonmau** [comment]
ohibò, ora funziona :O
@iltempe per me possiamo chiudere la issue
sorry per il procurato allarme :)
