### ISSUE TITLE
Aggiungere canale e bot Telegram in About

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#188]
Oppure, aggiungere una sezione apposita "canali di comunicazione" in cui linkiamo tutti i nostri account ufficiali (quelli del footer, + bot + Flickr).

**Comment by drizzt** [comment]
Facciamo una pagina apposita sul google spreadsheet con la lista così è mantenibile anche dai non sviluppatori o è facciamo la pagina html (MD) secca con i link?

**Comment by Pinzauti** [comment]
@dontyna Va bene così?

**Comment by dontyna** [comment]
@Pinzauti benissimo. Linkerei quella sottosezione anche a 'contatti' in about.
