### ISSUE TITLE
Medium

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#191]
Nasce l'esigenza di iniziare a narrare alcune piccole storie di successo di questo progetto. Non tanto per pubblicità quanto per dimostrare che è utile in piccolo a qualcosa.

Il sottoscritto aveva aperto rivista medium con un po' di diario personale. Da arricchire con altro.
https://medium.com/terremotocentroitalia

Il dubbio che ci assale è: è lo strumento giusto?
E anche: si può esportare i contenuti da Medium Publication...magari con delle API?

Se ne parla qui grazie a tutti

**Comment by ghost** [comment]
Nella documentazione delle API non si parla di come ottenere la lista dei post e il contenuto, ma è molto semplice: 
Aggiungendo **?format=json** a qualsiasi URL di post, si ottiene il json del post. 
Oppure, si può creare un feed in json dell'utente, in questo modo: 
_https://medium.com/@manueloccorso/latest?format=json_

Qui c'è un **SDK per php** se vogliamo fare il contrario: postare in automatico il bollettino, la lista degli alloggi ecc..  : https://github.com/jonathantorres/medium-sdk-php

Per quanto riguarda la domanda fondamentale: Secondo me è un buonissimo strumento. Sarebbe utile contattare quelli della **redazione di MediumItalia**, per far includere i post nella pubblicazione (che è la più seguita in italia). 
Vanno contattati via email, di solito rispondono in uno/due giorni, accettano articoli ben scritti ma sicuramente non penso che si facciano problemi ad accettare di pubblicare i bollettini o qualsiasi altro contenuto.

**Comment by ghost** [comment]
Ovviamente, dal Feed si ricava solo l'Id dei post, poi si costruisce l'url del tipo
https://medium.com/@manueloccorso/ff51f8412741?format=json

**Comment by iltempe** [comment]
Ok. Vorremmo usarlo per raccontare storie non come bollettino. Ma ci farebbe comodo uno script per archiviarle come md file nel formato dei nostri post. Che dici?

**Comment by iltempe** [comment]
con roba del genere ad esempio https://github.com/xdamman/mediumexporter

**Comment by drizzt** [comment]
jekyll supporta json direttamente.
visto che il json non è parsabile direttamente bisogna prima strippare l'anti JSON hijacking, per cui
qualcosa tipo
`curl -s https://medium.com/@manueloccorso/latest?format=json | sed 's:^])}while(1);</x>::' > _data/medium.json`
funziona

**Comment by iltempe** [comment]
con il buon @mfortini infatti si pensava a questo punto di scrivere post qui e quelli con una certa categoria inviarli su MEDIUM in rivista.

**Comment by iltempe** [comment]
Segnalo che stiamo provando con una volontaria a fare un MD con categoria STORIE per provare.

**Comment by favoeva** [comment]
ecco la issue #195 c'è già un bel pezzo di Gloria Schiavi ;)

**Comment by iltempe** [comment]
Pubblicata la pagina storie
