### ISSUE TITLE
Critico: Documentare Cosa Fa il Bot Telegram

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#193]
Chiedo cortesemente che venga aggiunta alla sezione wiki di questo repo (o di un altro purche si abbia visibilità) cosa fa il BOT telegram e qual è il processo attualmente implementato. Questo punto è necessario per l'usabilità dello strumento da parte di chi non lo conosce. Grazie mille.

**Comment by milesimarco** [comment]
Aggiornamento 1 settembre 2016

# Nuova segnalazione
1. Invio propria posizione GPS
2. Inserimento di una descrizione
3. Invio di una foto tramite "Invia Foto"
4. Attendere la conferma (in caso contrario provare a rimandare la foto)

Il processo inizia sempre con l'invio della posizione GPS.

# Pulsanti tastiera
- segnala -> spiega come inoltrare una segnalazone (il processo parte inviando la posizione GPS)
- mappa -> mostra un'altra tastiera dalla quale si può visualizzare mappa odierna e totale
- stato -> mostra il numero delle segnalazioni inoltrate dall'utente
- info -> mostra credits

# Funzioni amministratori

Gli amministratori riceveranno, sempre all'interno del bot, la notifica di ogni foto (segnalazione).
- ok -> approva tutte le foto ricevute nel bot (stato da 0 a 1)
- d:ID -> elimina una foto (stato da 0 o 1 a 2)
- as:ID -> crea issue su GitHub - https://github.com/emergenzeHack/terremotocentro_segnalazioni/

## Note

Ogni segnalazione ha stato iniziale = 0
Il CSV estrapola solamente le segnalazioni con stato = 1
Il comando d:ID è attivo sia per segnalazioni con stato = 0, sia per stato = 1
Il comando ok agisce solo su foto con stato = 0
In caso di digitazione as:ID ma issue già creata viene ritornato errore

**Comment by iltempe** [comment]
Grazie Marco. 
Alcuni chiarimenti per me
- dove è in esecuzione adesso il BOT?
- a che serve il CSV?
- come aggiungiamo amministratori?

Grazie

**Comment by milesimarco** [comment]
> dove è in esecuzione adesso il BOT?

Mio server, hosting condiviso su HTTPS e CDN. Settimana prossima valutiamo se tiene o tentiamo con server virtuale del CNR

> a che serve il CSV?

Il csv è il ponte tra il db mysql del sito e umap. Umap prende tutti i dati del csv, che contiene le segnalazioni con stato = 1 presenti nel db

> come aggiungiamo amministratori?

Per il momento devo farlo io, aggiungendo gli ID di Telegram nel file php di customizzazione su WordPress.

**Comment by iltempe** [comment]
Sulle tue risposte sopra:
- ok, valutiamo bene quando lo sposti dove viene spostato. Personalmente preferirei fosse su una macchina con più amministratori perchè se tu non ci sei potrebbe essere un problema.
- per il csv ok ho capito. Anche questo è su un tuo server? Puoi linkarlo pubblicamente?
- Per aggiongere ammistratori potrebbe essere utile far leggere ad un tuo script un file di testo da editare in cui mettiamo i nomi di chi deve essere moderatore. Su questo una domanda: se ci sono più amministratori ed entrambi approvano una segnalazione in tempi diversi cosa accade?

Grazie marco!

**Comment by milesimarco** [comment]
> ok, valutiamo bene quando lo sposti dove viene spostato. Personalmente preferirei fosse su una macchina con più amministratori perchè se tu non ci sei potrebbe essere un problema.

Per questo l'ideale era un sottodominio all'interno del progetto. Qualsiasi altra soluzione è e rimarrà "esterna". Valuteremo...

> per il csv ok ho capito. Anche questo è su un tuo server? Puoi linkarlo pubblicamente?

In realtà è un link che genera un csv all'istante:
https://terremotocentroitalia.mmilesi.ml/?get-csv=true (scarica csv)
https://terremotocentroitalia.mmilesi.ml/?get-csv=false (visualizza csv)

Con parametri opzionali:
https://terremotocentroitalia.mmilesi.ml/?get-csv=false&giorno=30&mese=8
https://terremotocentroitalia.mmilesi.ml/?get-csv=false&giorno=oggi

> Per aggiongere ammistratori potrebbe essere utile far leggere ad un tuo script un file di testo da editare in cui mettiamo i nomi di chi deve essere moderatore. Su questo una domanda: se ci sono più amministratori ed entrambi approvano una segnalazione in tempi diversi cosa accade?

Al momento è fatto modificando un file php. Vedremo di raffinarlo ma questa modalità può continuare a mio avviso.
Riguardo ai comandi:
- ok -> ogni ok cambia lo stato da 0 a 1 di tutto il db
- d:ID -> viene settato stato=2 per una segnalazione (non è poi possibile recuperarla). Funziona per il primo che usa il comando
- as:ID -> viene creata issue. Se qualcun'altro digita successivamente il comando viene avvisato che la issue è già creata

**Comment by milesimarco** [comment]
GUIDA AGGIORNATA E INSERITA IN
https://github.com/emergenzeHack/terremotocentroitalia-bot-telegram

(segnalo in particolare la possibilità di inviare segnalazioni di solo testo)

**Comment by iltempe** [comment]
ok. grazie

**Comment by favoeva** [comment]
Ciao tutti  
(da mobile) il clic su mappa --> foto geolocalizzate --> vai a segnalazione non mi apre nulla
I dati riversati nel csv (lì li vedo )sono da monitorare e gestire come segnalazioni per il gsheet come quello che arriva da tutti gli altri canali corretto? @iltempe

**Comment by piersoft** [comment]
ciao a tutti. Attenzione! lo sviluppo e implementazione della mappa su UMAP è stato abbandonato, proprio per quello che scriveva @favoeva ed inoltre la cache di UMAP era fuorviante.
Ho implementato una nuova mappa direttamente sul mio server, a regime dei vari cambiamenti che Izzi e Quintilii mi stanno facendo fare, pubblico i sorgenti e poi decidiamo se spostarla. la mappa è disponibile su [http://www.piersoft.it/terremotocentro/](http://www.piersoft.it/terremotocentro/) e gestisce la ricerca tramite Nominatim, il cambio layer su Humanitarian OSM o RealVista via Satellite, gestisce il filtro su progressive e odierne e nel pop up ha (se presente) il link al github e allo username del segnalatore. Ha nel link le coordinate e lo zoom. Prende in automatico dal DB del WP senza cache. ho fatto anche un'immagine sintetica:
![schermatamappa](https://cloud.githubusercontent.com/assets/6083002/18223078/cd6e74ea-71ab-11e6-85d3-da71ac3a6297.png)
