### ISSUE TITLE
pubblicare storia

### ISSUE THREAD

**Issue by gloriaschiavi** [emergenzeHack/terremotocentro#195]
intro per la pagina storie + successo del caso "cavo di rete"
[2016-9-01-I-successi-reali-della-condivisione-social.txt](https://github.com/emergenzeHack/terremotocentro/files/449889/2016-9-01-I-successi-reali-della-condivisione-social.txt)

**Comment by favoeva** [comment]
ottimo pezzo @gloriaschiavi è per quello che si diceva nel media team su https://medium.com/terremotocentroitalia ?
come funziona?
proponiamo dei pezzi qui e poi @mfortini vaglia?

**Comment by iltempe** [comment]
fatto. per mandarl su medium studiamo un modo automatico. Grande @gloriaschiavi !!!!
http://terremotocentroitalia.info/storie/
