### ISSUE TITLE
Fare un post nel blog

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#20]
fare un post che riporti richiesta per sviluppo web (ogni linguaggio di programmazione è accetto) e competenze github.

e divulgarlo sui social. categoria BLOG

Istruzioni nella pagina wiki.

**Comment by Manfro** [comment]
Può andare? 
[2016-8-26-Sei-uno-sviluppatore-se-vuoi-aiutaci.zip](https://github.com/emergenzeHack/terremotocentro/files/439963/2016-8-26-Sei-uno-sviluppatore-se-vuoi-aiutaci.zip)

**Comment by iltempe** [comment]
ottimo. ho fatto un paio di correzioni su un link. lo metto online.

**Comment by iltempe** [comment]
online. grazie
