### ISSUE TITLE
Dati 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#200]
Qui inseriamo i link ai dati su sfollati, censimento danni e quanto possa rientrare sotto la voce "dati". Specificare fonte e quando possibile allegare documenti originali. 

Ok @iltempe?

**Comment by cristigalas** [comment]
**Dati aree accoglienza Norcia, 31 agosto**
[Dati_aree_di_accoglienza_NORCIA.pdf](https://github.com/emergenzeHack/terremotocentro/files/450402/Dati_aree_di_accoglienza_NORCIA.pdf)
fonte: [Umbria Notizie](http://umbrianotizieweb.it/cronaca/8478-sisma-umbria-dati-centro-protezione-civile-su-assistenza-persone-e-attivita-censimento-danni)

**Comment by favoeva** [comment]
Lista comuni che beneficiano della sospensione versamenti e adempimenti tributari per  residenti o operatori nei comuni colpiti dal terremoto (decreto MEF 1 settembre 2016) http://www.mef.gov.it/ufficio-stampa/comunicati/2016/comunicato_0153.html
Fonte: Ministero Economia e Finanze

**Comment by cristigalas** [comment]
![image](https://cloud.githubusercontent.com/assets/21283775/18187052/b99031c6-70a6-11e6-9f29-eeb8cf9bb444.jpeg)
Dati interventi Vigili del fuoco su luoghi terremoto al 1/09/2016.
Fonte: Vigili del fuoco [Twitter](https://twitter.com/emergenzavvf/status/771435250534739968)

**Comment by cristigalas** [comment]
![image](https://cloud.githubusercontent.com/assets/21283775/18187074/f9ec96ba-70a6-11e6-93c1-f897b06a11a0.jpeg)
Mappa interventi mancati ad Amatrice e Accumoli.
Fonte: [Twitter](https://twitter.com/anto_tlc/status/771289934690979840)

**Comment by iltempe** [comment]
chiudo. @cristigalas contattami in pvt ti dico dove archiviare quest documentazione
