### ISSUE TITLE
RSS delle fonti giornalistiche locali

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#201]
Costruire un RSS, a uso interno del media team, che aggreghi i feed di testate locali delle zone terremotate (elenco iniziale: posso avviarlo a richiesta). Il feed generato dovrebbe pescare dagli RSS esposti in rete dai siti o ricavati con tool per estrazione da HTML, ove non presenti RSS, filtrando gli item con nomi località coinvolte da sisma. Uso: alimentare Gsheet dopo presa in carico delle informazioni da parte del media team.

**Comment by drizzt** [comment]
che altri feed hai a parte quelli presenti qui? https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=1149746747

**Comment by dontyna** [comment]
Hai visto questa #187  @epoeta ?

**Comment by epoeta** [comment]
Ho aggiunto commento a #187 @dontyna con un paio di osservazioni. Ma quello è il front end, questa mia è una proposta da back office. Le due issue potrebbero combinarsi: un wall alimentato automaticamente e un back office di controllo.

**Comment by epoeta** [comment]
@drizzt 
- Corriere dell'Umbria e Corriere di Rieti http://corrieredellumbria.corr.it/feed.jsp
- Il Messaggero rss (ha edizioni locali, che però sembra esporre solo Roma) http://www.ilmessaggero.it/rss.php
- Il Messaggero Rieti (no rss) http://www.ilmessaggero.it/?p=leggitutte&sezione=RIETI
- Il Messaggero Umbria (no rss) http://www.ilmessaggero.it/?p=leggitutte&sezione=UMBRIA
- Il Messaggero Abruzzo (no rss)  http://www.ilmessaggero.it/?p=leggitutte&sezione=ABRUZZO
- Corriere Adriatico Marche (no rss) http://www.corriereadriatico.it/MARCHE/
- Corriere Adriatico Ascoli Piceno (no rss) http://www.corriereadriatico.it/ASCOLIPICENO/
- Corriere Adriatico (rss sembra non aggiornato integralmente) http://www.corriereadriatico.it/rss/home.xml
- Resto del Carlino Ascoli Piceno (no rss) http://www.ilrestodelcarlino.it/ascoli
-  Il Centro L'Aquila http://ilcentro.gelocal.it/laquila/rss/cronaca/
- Il Giornale di Rieti (rss) http://www.ilgiornaledirieti.it/gdr_allnews.asp
- La Nazione Umbria (no rss) http://www.lanazione.it/umbria/cronaca

**Comment by iltempe** [comment]
A me tutto questo piace. Ma vorrei anche che tutte queste testate divulgassero il nostro di FEED, che dite?

**Comment by epoeta** [comment]
@dontyna ;-)

**Comment by marco-acorte** [comment]
aggiungo anche un feed google alert che ho impostato un po' di tempo fa... e che pesca principalmente da fonti news online estere...
https://www.google.com/alerts/feeds/00304239730252557547/10338645909018565840

ooopsss... fonti locali... quindi questa c'ntra una fava... ahahhaa vabbe'

**Comment by iltempe** [comment]
scusate cosa possiamo farne di tutti questi feed ? attualmente sono usati?

**Comment by epoeta** [comment]
@iltempe potrebbe essere una fonte da consultare da parte del Media Team per colmare buchi informativi (segnalazioni non arrivate nel gruppo o via webform)
