### ISSUE TITLE
Cambiare stile pagina segnala

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#202]
Cambierei questa pagina
http://terremotocentroitalia.info/aiuto/

facendo un elenco esattamente come quello fatto in questa
http://terremotocentroitalia.info/canali/

ovviamente inserendo SOLO i social che ci sono nella 
http://terremotocentroitalia.info/aiuto/
che sono quelli usati per segnalare

**Comment by Pinzauti** [comment]
@iltempe Me ne occupo io

**Comment by Pinzauti** [comment]
@iltempe Va bene?
