### ISSUE TITLE
Sistemare o eliminare automatismo bollettino gsheet verso Twitter 

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/terremotocentro#204]
Quando in bollettino la notizia non si riferisce a un 
Comune
indirizzo
Nel gsheet le relative Colonne vengono lasciate vuote e Il tweet automatico non ha senso . Esempio qui https://twitter.com/terremotocentro/status/771418649110413312

**Comment by cristigalas** [comment]
Io toglierei questo automatismo del tutto da Twitter...

**Comment by iltempe** [comment]
Lo chiudo perchè duplicato con #233
