### ISSUE TITLE
Gestione (anche) manuale canale Telegram

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#205]
Per migliorare la comunicazione via Telegram, sarebbe meglio prevedere anche una gestione manuale del canale con post ad hoc che rilancino richieste o info particolarmente utili... Io mi rendo disponibile a gestirlo.

**Comment by Manfro** [comment]
Se servisse una mano sono disponibile, inoltre la trovo un'ottima idea!

**Comment by mfortini** [comment]
Ok ne parliamo, poi mi serviranno in pvt i contatti per aggiungervi

Il ven 2 set 2016, 09:27 Manfro notifications@github.com ha scritto:

**Comment by iltempe** [comment]
Per me si può fare ma in modo moderato senza abusarne.

**Comment by iltempe** [comment]
chiudo.
