### ISSUE TITLE
Crosspost to Medium

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#209]
Provare ed installare https://github.com/aarongustafson/jekyll-crosspost-to-medium
ed impostarlo in modo che i post della cartella _storie vadino sulla rivista Medium di terremotocentroitalia

**Comment by ghost** [comment]
Ciao, il plugin in questione permette di pubblicare su Medium i soli 'posts' senza possibilità di configurarlo. Ho già pensato a come cambiarlo per farlo funzionare con le 'storie (sparando lo script come piace anoi direttamente in plugin).
Soluzioni che vedo sono:
1) Installarlo tramite la gemma funzionante solo per posts (anche se ci serve è poco è più pulito)
2) Installarlo con il "metodo capuozzo" e farlo funzionare per le storie (modifica ce l'ho pronta per essere pushiata).

@iltempe che ne pensi ?

**Comment by iltempe** [comment]
@tailot  io direi 2. verifica che si possa pubblicare su rivista casomai.

**Comment by ghost** [comment]
# A seguire le istruzioni per configurare la piattaforma.

Nel file di configurazione è stata settata la modalità per pubblicare i post in maniera draft (ovviamente si può cambiare).
Le variabili d'ambiente da configurare vanno configurate nell'attuale vps che lancia lo script scripts/csvupdate.sh (questo va modificato in maniera tale da settarle non pubbliche e lanciare la build)
MEDIUM_USER_ID preso da https://api.medium.com/v1/me?accessToken= (aggiungere id ricavato sopra nell'url)
MEDIUM_INTEGRATION_TOKEN preso da quì https://medium.com/me/settings 
MEDIUM_ENTITY con storie (nel caso in cui si voglia pubblicare in automatico le storie)

Storie ovviamente vanno popolate con l'attributo,  crosspost_to_medium: true

Altre cose che si possono configurare sempre in: https://github.com/aarongustafson/jekyll-crosspost-to-medium

**ATTENZIONE:**
Prima di mergiare bisogna configurare travis e settare le variabili d'ambiente dentro travis (fasulle giusto per non fare fallire i test):
MEDIUM_USER_ID test
MEDIUM_INTEGRATION_TOKEN test
MEDIUM_ENTITY test

**Comment by ghost** [comment]
@mfortini serve un tuo intervento se possibile per modificare lo script (/scripts/csvupdate.sh) così da caricare le ENV specificate quì sopra e successivamente lanciare bundle exec jekyll build (in questo modo viene aggiornato medium). Che ne pensi ?. Grazie

**Comment by ghost** [comment]
Il plugin adesso è abilitato. Abbiamo fatto la prova con @iltempe le storie vengono pubblicate in draft. Sfortunatamente lo storico delle storie pubblicate viene salvato su filesystem, questo è un problema se il filesystem è volatile.

**Comment by iltempe** [comment]
quindi è disabilitato ora. no?

**Comment by ghost** [comment]
Si è installato ma disabilitato. Piuttosto che persistere l'informazione sul filesystem il buon @drizzt consigliava di controllare semplicemente i titoli dal json in questione https://medium.com/@terremotocentroitalia/latest l'idea è ottima. Bisogna cambiare la logica del plugin (https://github.com/tailot/jekyll-crosseverything-to-medium)

**Comment by iltempe** [comment]
mmm ok. teniamolo disabilitato per ora. se avete update lo riabilitiamo.

**Comment by ghost** [comment]
@iltempe  curl -sH "Accept: application/json" https://medium.com/@terremotocentroitalia/latest

**Comment by ghost** [comment]
@iltempe sono riuscito a snellire la versione del plugin ([quì](https://gist.github.com/tailot/bea7dcfe406662d173098cf0e6a19b21)) in maniera tale da non persistere sul filesystem. In più ho poi capito come pubblicare le storie direttamente su https://medium.com/terremotocentroitalia. Per fare ciò mi serve l'auto di @drizzt per settare la env MEDIUM_USER_ID=c08337fdd701

Le storie già pubblicate non sono pubblicabili in quanto adesso ci basiamo sui titoli.
