### ISSUE TITLE
Monitoraggio: salvare PDF e pagine segnalati da Antonella Milanini

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#210]
La signora in oggetto sta facendo un lavoro ottimo di monitoraggio degli atti precedenti al sisma. Salvarli possibilmente aggiungendo al nome file yyyy-mm-dd_HH:MM con data e ora scaricamento. Si può caricare qui https://drive.google.com/folderview?id=0B6F5bbIgNBMFRk90M0hGMXZpVm8

**Comment by Manfro** [comment]
Okay, inizio!

**Comment by Manfro** [comment]
Le informazioni segnalateci dalla Signora fino ad ora sono state inserite

**Comment by iltempe** [comment]
Esiste questo account che ho appena creato https://archive.org/details/@emergenzehack

**Comment by Manfro** [comment]
Per caricare su archive.org @iltempe si sviluppa la issue #211 o si fa manualmente?

**Comment by iltempe** [comment]
Si fa con uno script. da decidere come nella #211

**Comment by iltempe** [comment]
contattato personalmente la signora. ci da una mano e per ora lo fa lei a mano.
