### ISSUE TITLE
Sostituire "Donazioni" con "Risorse disponibili"

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#216]
Dopo brainstorming del gruppo media abbiamo pensato che il termine "Donazioni" fosse fuorviante. In quella sezione ci sono sia beni che servizi a disposizione di associazioni e persone, non possibilità di fare donazioni.

**Comment by lucaferri** [comment]
Ho modificato il titolo in "Risorse disponibili" ma, essendo più lungo di "Donazioni", va a capo sia sulla pagina che sul link nel menu. Può andare o è preferibile cambiare qualcosa?
