### ISSUE TITLE
Segnalare sul sito i fabbisogni risolti

### ISSUE THREAD

**Issue by Manfro** [emergenzeHack/terremotocentro#219]
Segnalare nella pagina Fabbisogni quali richieste sono state risolte, come è stato fatto per la pagina "Bollettino". Si potrebbe procedere eliminando la visibilità (senza eliminare dallo sheet la riga corrispondente) oppure barrandola (come per bollettino)

**Comment by iltempe** [comment]
verrà fatto con nuovo metodo segnalazioni.
