### ISSUE TITLE
Aggiungere data pubblicazione a "risorse disponibili"

### ISSUE THREAD

**Issue by gloriaschiavi** [emergenzeHack/terremotocentro#221]
Come per i fabbisogni, potrebbe essere utile aggiungere nella sezione del sito "risorse disponibili" anche la data di pubblicazione, così si sa quando quella risorsa è stata messa a disposizione. Questo vale anche in considerazione del fatto che è difficile avere riscontro del fatto che la risorsa sia stata donata e quindi non sia più disponibile. Che dite?

**Comment by ghost** [comment]
Decisamente utile, ho aperto il gsheet per vedere se fossero già disponibili le date e fossero solo da implementare ne sito, ma ho notato che in "donazioni" (è la pagina risorse disponibili, no?) ci sono anche dei fabbisogni.
Sbaglio?

**Comment by gloriaschiavi** [comment]
Si, "donazioni" è diventato "risorse disponibili" ed è possibilissimo che ci siano dei record al posto sbagliato. 
io ne ho visto uno - una donazione che era un fabbisogno - e l'ho messo nell'issue #222 
Grazie!
