### ISSUE TITLE
Creare sistema in gsheet che aggreghi per tipologia di richieste 

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/terremotocentro#225]
Ha senso aggregare le richieste che ci arrivano per tipologia es 
Acqua
Wi fi
Batterie 
Medicinali
Ecc ...
Per poi mandarle a contatto pro civ che si occupa di smistamento

**Comment by favoeva** [comment]
Ne abbiamo parlato con Rosy Gloria e Christian nel media team 

Bisognerebbe creare la possibilità nello sheet fabbisogni di inserire una parola chiave che rappresenta la richiesta che Permetta di aggregare in automatico

**Comment by iltempe** [comment]
@favoeva stiamo cercando di mettere a punto nuovo sistema di gestione richieste. prendo li in carico questo tuo commento.

**Comment by aborruso** [comment]
se serve ancora una mano sul foglio elettronico, ci sono

**Comment by iltempe** [comment]
@aborruso vorremmo migrare su questa nuova gestione. https://docs.google.com/document/d/1--3bSH7R9uGaaLlbjfi9uflgjv2wf1fcrGz_ImrBUvk/edit
