### ISSUE TITLE
Bollettino - suggerimenti dal campo

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#228]
- invertire colori (la fonte coi link etc colorata di blu, di bianco il testo della segnalazione)
- aggiungere la possibilità di commentare (per chi ha bisogno di ricevere info lo scrive nel commento, ad esempio)
- aggiungere tasto per segnalare chiusa la segnalazione (magari inserendo un modello pro forma da compilare con i dati che confermano l'adempimento)

**Comment by iltempe** [comment]
direi ci siamo con #242
