### ISSUE TITLE
Formato tweet automatici

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#233]
I tweet generati in automatico dal Gsheet, cartella Bollettino, hanno una struttura che li rende poco comprensibili. Esempio https://twitter.com/terremotocentro/status/772396517500002304 che poi è stato ritwittato in formato 'potabile'. Andrebbero tolti i richiami automatizzati ai campi indirizzo e forse anche agli hashtag, inserendo nelle linee guida del Gsheet l'obbligo a formulare la prima frase delle entry del Bollettino in un centinaio di caratteri (spazi inclusi) che comprenda, se opportuno, l'indirizzo e l'impegno ad allegare un hashtag della località nel campo di Gsheet.

**Comment by aborruso** [comment]
Me ne occupo io, grazie

**Comment by epoeta** [comment]
Segnalo per completezza che stessa esigenza rilevata in #204.

**Comment by aborruso** [comment]
@epoeta ho fatto una prima pulizia http://feeds.feedburner.com/Terremotocentroitalia-Bollettino

Che ne pensi adesso?

Grazie

**Comment by epoeta** [comment]
Great! È ok!

**Comment by epoeta** [comment]
Quasi quasi, chiudiamo?
