### ISSUE TITLE
Sito mobile friendly

### ISSUE THREAD

**Issue by avivace** [emergenzeHack/terremotocentro#234]
In relazione a [questo](https://github.com/emergenzeHack/terremotocentro/issues/232) issue, siamo giunti alla conclusione che **offrire un punto di accesso consultabile facilmente da smartphone è essenziale**.
La quasi totalità di strumenti, risorse, feed, e contenuti messi a disposizione si possono raggiungere dal sito web, non avrebbe dunque senso, almeno non ora, ricostruire l'intera infrastruttura come app nativa.
L'idea è dunque un'app che, semplicemente, visualizzi la versione mobile del sito a cui poi successivamente, potremmo aggiungere delle feature marginali native (notifiche, form per l'invio di dati/segnalazioni).
Il sito è già mobile-responsive e il layout si mantiene _perfettamente_ sui dispositivi su cui ho fatto delle prove.
C'è però da lavorare ad una serie di accorgimenti per renderlo appetibile (situazione già emersa [qui](https://github.com/emergenzeHack/terremotocentro/issues/40)):
- Stili css che evitino quegli orribili titoloni enormi e spacing laterale eccessivo (sono le prime cose che mi vengono in mente, aprendo il sito da cellulare o usando servizi come MobileTest.me potete vedere voi stessi)
- Una sorta di front page specifica per la versione mobili che orienti i primi utilizzatori e fornisca comunque un buon punto di partenza per i più esperti. Una sorta di lista organizzata della lista di strumenti messi a disposizione.

**Comment by iltempe** [comment]
io non ho niente in contrario a fare evolvere il sito in questo senso (senza app nativa, concordo). Tenete conto che avremo un form per inserimento segnalazioni da integrare nella parte di frontend.

**Comment by avivace** [comment]
Esattamente in questo sta la scalabilità della questione, qualsiasi nuova funzione o strumento, se è raggiungibile da un frontend web, sarebbe automaticamente disponibile nella versione mobile.

**Comment by mgranatelli** [comment]
Se l'idea è un'App che rappresenti in maniera semplice una specie di indice verso tutte le risorse a disposizione sul web, potrei farvene vedere una, è in fase di rilascio, già pubblicata negli store, che potrei mettere a disposizione dell'iiniziativa gratuitamente.
L'App di fatto è una bacheca digitale multiuso, con possibilità di inviare un alert in push notification.
Logica di comunicazione uno a molti, per distribuire disposizioni, informative, etc.
Possibilità di bacheche pubbliche, private, segrete.
Non ho parlato prima di questa mia possibilità perché non volevo generare equivoci, ma se posso permettermi adesso provo a realizzare una prova di rilascio su questa iniziativa e ve la sottopongo.
Se vi può andare bene come utilizzo al volo senza dover sviluppare nulla, per me va benissimo.
Considerate che questa idea è nata nel 2014, ed è stata progettata, in maniera prevalente, proprio per esigenze emergenziali, tipo quella di cui stiamo parlando.
Questo è il link su Android, se volete dare un'occhiata: https://play.google.com/apps/testing/com.topnotice.topnotice

L'App per gli utenti è gratuita, quindi non si paga nulla.

Nelle prossime ore provo a realizzare un account intestato a questo progetto e vi faccio vedere cosa si potrebbe fare.
Poi mi dite voi se l'idea vi piace oppure no, nessun problema, e se vi piace concordiamo come e chi mettere nelle condizioni di pubblicare le info in maniera diretta.

mg

**Comment by Ibernato93** [comment]
@avivace  non so con quali cell hai provato ma vedi che alcune sezioni non si visualizzano correttamente sul mobile.  Scarica questo plug-in per chrome https://chrome.google.com/webstore/detail/responsive-web-design-tes/objclahbaimlfnbjdeobicmmlnbhamkg così puoi vedere come viene visualizzato il sito su un determinato mobile.

**Comment by iltempe** [comment]
ragazzi qui posso chiudere?
