### ISSUE TITLE
Mappa Centri smistamenti

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#235]
Mappa usata attuamente al Centro smistamenti a Cittareale. 

I comuni in emergenza primaria sono essenzialmente due, quello di amatrice e quello di accumoli. Cittareale è il comune prima di amatrice in cui il sisma non ha creato una situazione di emergenza primaria come gli altri due comuni.

Il solo comune di amatrice ha ben 69 frazioni. Nella mappa ci sono i punti di interesse in cui ci sono persone che hanno bisogno di aiuto perché costrette a vivere in tende, container o campi organizzati dalla protezione civile. Nella maggior parte dei casi questi punti di interesse si trovano nelle frazioni, ma non è obbligatorio.

https://www.google.com/maps/d/u/0/edit?mid=1n0N18czyGIfREDVQgAgMwZOi42Y

**Comment by c83n** [comment]
Inauguro mia presenza su questo augusto mezzo segnalando che due super pro bergamini e piersoft avevano già spaciugato sulle coordinate delle varie frazioni che magari tornano utili, mi pare però che ne manchino alcune da georef a mano e mi faccio aiutare da chiara appena diffondo l'augusto mezzo ai colleghi :)

https://docs.google.com/spreadsheets/d/1ERSFsWsqV_X_qPLekXo6NakcWjz3DWpTZEwTgAq1EKM/edit?usp=sharing
