### ISSUE TITLE
Aggiungere logo Archive nel footer

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#237]
aggiungere logo archive.org nel footer accanto ai social media. dovrà puntare a questo link https://archive.org/details/@terremotocentroita

**Comment by marco-acorte** [comment]
allora dovrei avere fatto io... nel fork... https://github.com/marco-acorte/terremotocentro

**Comment by iltempe** [comment]
io andrei con una PULL request allora no? @marco-acorte

**Comment by marco-acorte** [comment]
fatta pull...

**Comment by iltempe** [comment]
chiudo!
