### ISSUE TITLE
Sezione dedicata alla connettività area terremotata

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#238]
Creare una sezione - magari accompagnata anche da mappa con un layer sulla connettività - relativa alle notizie sullo stato delle reti in territori colpito da sisma. Le notizie potrebbero essere accompagnate anche dal permalink ai due pdf che Agcom aggiorna sulle iniziative degli operatori delle telecomunicazioni in occasione del sisma reperibili qui: https://www.agcom.it/emergenza-sisma-nel-centro-italia-del-24-agosto-2016. Esiste su questo già una precedente issue: #139 .

**Comment by iltempe** [comment]
@mfortini aveva proposto questo #73
