### ISSUE TITLE
URGENTE: gsheet non alimenta più il sito

### ISSUE THREAD

**Issue by Manfro** [emergenzeHack/terremotocentro#239]
Il gsheet non comunica più con il sito, le informazioni inserite nei vari fogli non vengono inserite anche nel sito. Ad esempio Bollettino, Raccolte fondi e press.
Link gsheet:
https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=1997631888

**Comment by drizzt** [comment]
sembra un problema di github inquanto i file csv vengono correttamente pushati ed aggiornati e localmente vedo le modifiche. ho già aperto un ticket a github

**Comment by iltempe** [comment]
dipende da github. ci stanno lavorando.

**Comment by iltempe** [comment]
il sito è nuovamente UP.
