### ISSUE TITLE
Gestire la mappa sito per indicizzazione google

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#24]
Da far gestire sitemap del sito in modo da indicizzare tutto con google.

**Comment by ghost** [comment]
Ciao, la sitemap sembra gia attiva quì: http://terremotocentroitalia.info/sitemap.xml
Viene gestita tramite il plugin ufficiale https://github.com/jekyll/jekyll-sitemap
Al fine di agevolare le operazioni di indicizzazione conviene segnalarla nel pannellino google webmaster tools https://www.google.com/webmasters/tools/home?hl=it  previa verifica del dominio.

**Comment by iltempe** [comment]
done.
