### ISSUE TITLE
Creazione WebForm per aprire issue github

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#240]
Secondo quanto indicato qui https://docs.google.com/document/d/1--3bSH7R9uGaaLlbjfi9uflgjv2wf1fcrGz_ImrBUvk/edit#
 creare un webform che consenta di aprire un issue su github indicando una segnalazione specifica. il form dovrà contenere la possibilità di georiferire l'informazione.

**Comment by Pinzauti** [comment]
Se ce la faccio lo finisco entro stasera.

**Comment by Pinzauti** [comment]
Questo potrebbe andare come inizio?
Link al webform: https://terremoto.francescopinzauti.com/
Link ai CSV da usare per le mappe: https://terremoto.francescopinzauti.com/csv
Repository di prova: https://github.com/Pinzauti/Prova/issues

**Comment by iltempe** [comment]
Mi pare sia un buon inizio! attendiamo anche il commento di altri, ma io intanto togliere tutti i campi obbligatori cioè lascerei libertà all'utente di inserire ciò che c'è.
@mfortini che dici?

**Comment by iltempe** [comment]
@Pinzauti aggiungo: ho visto la parte github. ottimo va bene un formato strutturato in quel modo.  una domanda. Se non c'è georeferenziazione (e quindi la segnalazione è di tipo generico) gestisci in un file diverso?

**Comment by Pinzauti** [comment]
@iltempe 
Ogni sezione (Donazioni, Alloggi, Notizie utili) viene gestita da un file PHP diverso.
Le sezioni con georeferenziazione vengono inviate a GitHub e salvate nel relativo CSV, mentre le sezioni di tipo generico vanno solamente su GitHub senza essere salvate in un CSV.

**Comment by iltempe** [comment]
@Pinzauti ok. chiaro. un appunto su questo: tecnicamente bisognerebbe che tutto confluisse in github ma il csv lo si ricostruisse in un secondo step tramite le API di github stesso. questo perchè in questo modo io ottengo in qualunque momento lo stato attuale di ogni issue e genero tutti i csv che voglio. Magari puoi prevedere (non so se già lo fai) di apporre di default un'etichetta che dica il tipo di segnalazione aperta (fabbisogni, alloggi....). che ne pensi?

**Comment by Pinzauti** [comment]
@iltempe 
Se ho capito bene quello che intendi l'etichetta c'è già.

La segnalazione fatta da te per esempio ha l'etichetta fabbisogni (che è la sezione da cui l'hai inviata).
![capture](https://cloud.githubusercontent.com/assets/16691846/18255248/09a5f228-73a8-11e6-867f-0700a978256b.PNG)

Mentre quella fatta da me ha l'etichetta "Notizie Utili".
![2](https://cloud.githubusercontent.com/assets/16691846/18255255/173d86a8-73a8-11e6-9610-2ae50702b8bd.PNG)

Nei CSV non ho aggiunto etichette perché ho direttamente separato i 3 Databse con geolocalizzazione.
Chiaro comunque il discorso sul creare il CSV dopo l'inserimento su GitHub. 
Guardo la Documentazione delle API GitHub e vedo se riesco a farlo.

**Comment by iltempe** [comment]
ok. perfetto! si se non riesci e condividi il repo ti diamo una mano. facci sapere.

**Comment by iltempe** [comment]
@Pinzauti aggiungerei un form CONTATTI per mappare un CONTATTO utile sul territorio in cui si inseriscono i dati del contatto e chi è e in cosa può essere utile.

**Comment by mfortini** [comment]
@Pinzauti un'idea che abbiamo visto è https://github.com/boblauer/GitHubPlus 
la segnalo non perché si voglia mettere in piedi una cosa così complicata, ma per segnalare che loro mettono nel body della issue un tag html che si può beccare al volo con un xpath e poi lo riempiono con un JSON. Potrebbe essere un modo vincente. In alternativa, si potrebbe inserire uno YAML che è più leggibile a occhio umano, formattato come codice.

Il discorso CSV a posteriori potrebbe essere comunque in un file cache che viene aggiornato soltanto quando updated-at di una issue viene modificato o viene inserito nuova issue

**Comment by Pinzauti** [comment]
@iltempe 
Ho tolto alcuni campi obbligatori e aggiunto il form Contatti:
https://terremoto.francescopinzauti.com/

@mfortini 
Leggo ora il commento, darò un occhiata ai link, per adesso avevo pensato di creare le issue nel modo in cui puoi vedere nella repository di prova, dici che crea problemi in quel formato?
Qui il link alla repository di prova: https://github.com/Pinzauti/Prova/issues

Per i CSV poi ho usato cron (1 volta ogni ora penso basti) che prende direttamente le issue dalla repository di prova e li trasforma in un CSV (Solo quelle con etichetta "Non accettato" per provare, poi prenderà solo quelle con etichetta "Accettato").
Qui i CSV: https://terremoto.francescopinzauti.com/csv/

Fate un po' di test e ditemi se può andare.

**Comment by iltempe** [comment]
@Pinzauti ho fatto alcuni test. mi pare ci siamo come funzionalità di base. 
Due cose formali:
- metti il titolo del tipo di segnalazione nel pulsante e basta. cioè invece di mettere tante volte "segnala" nel pulsanti scriverei in alto SEGNALA e sui pulsanti la dicitura di cosa si vuole segnalare.
- nel campo link metti in trasparenza "http://" se non hanno questo i link ho visto non vengono presi.

Per i csv io fornirei dei link ai tuoi script PHP che producono il CSV nel momento in cui servono oppure lo ricreano ad ogni modifica dell' ISSUE.

**Comment by Pinzauti** [comment]
@iltempe
- Modifico i pulsanti.
- Aggiungo http.
- Per i CSV in [questa](https://terremoto.francescopinzauti.com/csv/) pagina puoi aggiornarli al bisogno (se non vedi il pulsante cancella la cache). Ogni ora comunque vengono aggiornati in automatico

**Comment by fizzi** [comment]
Ho testato l'invio di una segnalazione inserendo l'indirizzo attraverso il field "indirizzo" 
qui la issue create [link](https://github.com/Pinzauti/Prova/issues/39) 

sembra che lat e lon in questo caso non vengono memorizzate

**Comment by Pinzauti** [comment]
@fizzi Non hai selezionato la località dal dropdown

**Comment by fizzi** [comment]
Si l'ho fatto @Pinzauti

**Comment by Pinzauti** [comment]
@fizzi 
Mmm strano allora, puoi mandarmi uno screen del form un attimo prima di inviarlo?

**Comment by fizzi** [comment]
mmm, strano adesso ha inserito correttamete le cordinate forse prima non ho selezionato bene dalla dropdown ... ma con tasto INVIO

**Comment by fizzi** [comment]
si ... se fai invio quando cerchi una località si verifica

https://github.com/Pinzauti/Prova/issues/41

**Comment by fizzi** [comment]
e credo che vengano anche inviati i dati al server direttamente

**Comment by Pinzauti** [comment]
Ok @fizzi disabilito l'invio dei dati nel momento in cui viene premuto il tasto invio, dalla lista però si dovrà comunque selezionare a mano

**Comment by fizzi** [comment]
@Pinzauti ok direi cosi evitiamo anche invii involontari

**Comment by iltempe** [comment]
@Pinzauti farei puntare il tuo webform qui https://github.com/emergenzeHack/terremotocentro_segnalazioni
che è dove si fa adesso il testing delle segnalazioni. In più se non è complicato permetterei di allegare da webform un'immagine che poi risulti tra gli allegati in issue github. grazie molte.

**Comment by Pinzauti** [comment]
Okay @iltempe provo ad aggiungere le immagini e faccio puntare su quella repository. Mi puoi autorizzare l'account per le label?

**Comment by iltempe** [comment]
@Pinzauti le mie note per migliorare il form:
- Rimuoverei completamente le frasi sopra i pulsanti "Vuoi donare un bene o un servizio?", dato che i pulsanti sono più "parlanti" adesso
- aggiungerei la possibilità di embeddare il form ovunque si voglia (mantenendo il nostro repo centrale come archivio segnalazioni), 
- predisporrei (ma ancora non attiverei) nella pagina "Segnala" del sito questo form.

Poi per me ci siamo.

**Comment by Pinzauti** [comment]
@iltempe Ok per le scritte sopra i pulsanti.
Per quanto riguarda la possibilità di embeddare basta fare un iframe giusto?

**Comment by iltempe** [comment]
si ok per IFRAME: un pulsante che mi da il codice per mettere il webform con tutte le finestre in una pagina web.

@mfortini @aborruso non riusciamo ad inserire un immagine come allegato github. pare che le api degli issue non lo consentono. Che dite?

**Comment by iltempe** [comment]
chiudo.
