### ISSUE TITLE
Export Issue github

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#241]
Individuare metodo per fare exporting degli issue github in 
- FEED RSS
- Una Pagina del sito

L'export dovrà contenere anche eventuali campi custom, label, milestone e assegnazioni associate.

**Comment by aborruso** [comment]
Per le issue di questo repo, ma senza gli attributi di cui parli, c'è già
questo http://feeds.feedburner.com/IssueDelProgettoTerremotocentroitalia

Il lun 5 set 2016 14:14 Iltempe notifications@github.com ha scritto:

**Comment by iltempe** [comment]
@mfortini ha fatto export in CSV come scritto qui: https://github.com/emergenzeHack/terremotocentro/wiki/Issue-tracking-Github

**Comment by Pinzauti** [comment]
Lascio il link ai csv del webform https://terremoto.francescopinzauti.com/csv

**Comment by mfortini** [comment]
@Pinzauti @drizzt @milesimarco ho aggiornato lo script:
- in una colonna mette le label in JSON
- il body della issue viene copiato in una colonna
- URL della issue nella prima colonna

TODO
- filtrare solo per label/milestone approvato
- non ho ancora messo in una colonna il link all'immagine
- aggiungere una colonna milestone

se vi va di provare a vedere come va e vedere se si possa esportare un CSV, con un cron o con un webhook, vediamo se siamo allineati come webform e bot.

Complimenti sta venendo una cosa molto bella

**Comment by Pinzauti** [comment]
@mfortini Io ho impostato cron ogni 30 minuti, le issue del webform si esportano già con immagini e tutto solo da labels approvato, mi manca che il bot si uniformi come da #255 
O in alternativa faccio solo export in CSV del webform e qualcun altro si occupa del bot

Qui lo script: https://terremoto.francescopinzauti.com/csv

**Comment by iltempe** [comment]
@Pinzauti quindi usiamo lo script @mfortini o il tuo? non ho capito. @drizzt teniamo conto di questo per il #260

**Comment by Pinzauti** [comment]
Neanche io, per me è uguale comunque. Quello script lo avevo fatto insieme al form. Fate un po' di prove e vedete voi quale può tornare comodo

**Comment by drizzt** [comment]
se vogliamo tenere i csv delle issue in _data, come viene fatto ora per lo spreadsheet google, conviene farlo girare insieme ad `csvupdate.sh` o comunque dove può committare le modifiche

**Comment by iltempe** [comment]
@drizzt per me può girare dove si vuole basta che i file CSV siano sempre accessibili e completi di tutti i dati contenuti negli issue perchè su quelli poi si possa fare elaborazione, query etc...

**Comment by mfortini** [comment]
@drizzt ho soltanto paura che si crei un loop: avevamo intenzione di far girare gli script su webhook di push e di issue, bisogna controllare che uno non faccia girare l'altro :)

**Comment by iltempe** [comment]
@mfortini ci dici come usare lo script? lo installiamo su heroku ok?. @drizzt che dici?
https://github.com/emergenzeHack/terremotocentro/wiki/Issue-tracking-Github

**Comment by drizzt** [comment]
Consiglio di usare i webhooks di GitHub, per cui praticamente ad ogni modifica di una issue viene scatenato un evento (JSON o POST) https://developer.github.com/v3/activity/events/types/#issuesevent che potrebbe essere intercettato da uno script PHP su heroku (come lo script d'esempio che devo fixxare https://github.com/emergenzeHack/terremotocentroitalia-heroku-php/blob/master/webhooks.php) e poi basta parsare il JSON / POST che arriva per aggiornare le informazioni sul csv **solo** relativamente a quella issue modificata.
Questo ci evita di tenerci cache ridondanti o di rigenerare ogni volta tutto il file.

L'alternativa (più facile da implementare ed abbastanza efficente) è di rigenerare tutto il file ogni volta che viene scatenato l'hook (senza tenere cache), visto che occorre fare una sola query verso GitHub (https://api.github.com/repos/emergenzeHack/terremotocentro_segnalazioni/issues).

che ne pensate?

**Comment by mfortini** [comment]
Penso che la soluzione webhook sia la più efficiente, ma sia comunque indispensabile avere qualcosa che possa generare la lista a partire da zero, siccome non possiamo sapere se il CSV sia stra definitivo o possa cambiare. Siccome come giustamente fai notare la query è una soltanto, io voterei per l'approccio più bovino, ma sicuro, di rigenerare tutto ogni volta.

**Comment by drizzt** [comment]
sono d'accordo e tenere la cache è abbastanza inutile visto che comunque a ciclare il json ci sprechi veramente pochissimo tempo

**Comment by iltempe** [comment]
Quindi si può fare con questo?
https://github.com/emergenzeHack/terremotocentro/blob/master/scripts/github2CSV.py

@mfortini mancano ancora queste cose vero?
- filtrare solo per label/milestone approvato
- non ho ancora messo in una colonna il link all'immagine
- aggiungere una colonna milestone

**Comment by drizzt** [comment]
si può far committare il csv generato dallo script python direttamente? sennò lo faccio in webhooks.php che richiama lo script python

**Comment by iltempe** [comment]
@drizzt per me è indifferente, ma il CSV dove lo mettiamo? in _data?

**Comment by mfortini** [comment]
ok per ora mi fermo, ho implementato:
- uso delle environment variable
- colonna milestone
- filtro per label "Accettato"

**Comment by drizzt** [comment]
dipende per cosa vengono usati quei csv, se servono per generare pagine nel sito allora meglio metterlo in _data altrimenti si può anche usare un altro repo (tipo quello specifico per le issue)

**Comment by iltempe** [comment]
grazie @mfortini. a questo punto farei in modo di chiamare questo script.
@drizzt servirà per vari scopi, sito, mappe ma anche analisi dati. Mettiamolo in _data qui e chiamiamo lo script di @mfortini da dove pensi sia meglio.  quando possiamo ci inseriamo anche il link all'immagine.

**Comment by iltempe** [comment]
@drizzt chiudo?
