### ISSUE TITLE
Nuova politica di gestione segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#242]
Abbiamo definito qui una nuova politica di gestione segnalazioni da sperimentare ed implementare.
https://docs.google.com/document/d/1--3bSH7R9uGaaLlbjfi9uflgjv2wf1fcrGz_ImrBUvk/edit#

Gli issue qui dentro definiranno anche cosa serve per implementarla.

Questo issue verrà chiuso quando si passerà ufficialmente ad usarla (dopo che sarà stata implementata).

**Comment by epoeta** [comment]
Farei confluire lato amministrazione quanto già segnalato in #201 e #244.

**Comment by annaluciont** [comment]
PROPOSTA x REDAZIONE

Cosa fa la redazione ?
SEGNALA (info, richieste, donazioni)
PROCESSA (accedendo alle funz Labels)
SMISTA (elenco per categorie by Labels)
LINK’n’CALL (tramite rubrica condivisa)

Cosa serve?
creare Labels ad hoc (link voci)
moderatori/nerd facilitano inserimento Labels
rubrica corrispondente (inserire rif. mancanti - Field)
telefono

Come funziona?
Segnalazioni vengono etichettate (labels)
Smistate su apposita scheda Excel drive in continuo aggiornamento (oppure??)
Si processano tramite chiamata ai rispettivi ns contatti sensori
Si contrassegnano come CHIUSE se a buon fine
Siamo in fase sperimentale io e @chiccap

**Comment by iltempe** [comment]
@annaluciont si poni un tema importante. quello di documentare COME gestire le segnalazioni. mi prometto di creare una semplice procedura da condividere con tutti per discuterla.

**Comment by iltempe** [comment]
Abbiamo terminato la transizione su github.
