### ISSUE TITLE
Feed aggregato da Fb di pagine e gruppi sull'area colpita

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#244]
Generare un feed rss da tutte le pagine e gruppi Fb dedicati all'area colpita per un monitoraggio delle iniziative da condividere nel gruppo o inserire negli altri canali.

**Comment by iltempe** [comment]
@epoeta se tu riuscissi a fare una lista di gruppi e pagine si potrebbe iniziare da li. che dici? puoi elencarle anche in questo issue

**Comment by epoeta** [comment]
@iltempe domani ci provo

**Comment by epoeta** [comment]
@iltempe questo è quanto ho raccolto ma se apri una issue e chiediamo a tutti di contribuire: su Marche e Umbria ho trovato poco, molti i gruppi chiusi e quelli troppo piccoli li ho un po' tralasciati

Aiutiamo Amatrice
https://www.facebook.com/Aiutiamo-Amatrice-1574932246143457/

Aiutiamo Amatrice e Accumoli
https://www.facebook.com/terremotoamatrice/

Aiutiamo Retrosi
https://www.facebook.com/aiutiamoretrosi/

AiutiAMO Amatrice
https://www.facebook.com/groups/1163779023644513/

Aiutiamo Amatrice
https://www.facebook.com/groups/311795955834025/

Amatricenews
https://www.facebook.com/amatricenews/

Amatrice
https://www.facebook.com/amatrice/

Amatrice Forever
https://www.facebook.com/groups/111949405810441/

Amatrice e d'intorni
https://www.facebook.com/groups/781993155163453/

Comune di Amatrice
https://www.facebook.com/ComunediAmatrice/

Sei di Amatrice se
https://www.facebook.com/groups/632441540212297/

Terremoto Amatrice Accumoli
https://www.facebook.com/terremotoamatriceaiutiaiterremotati/

Terremoto Amatrice, Accumoli, Arquata del Tronto
https://www.facebook.com/groups/326987210974587/

SOS AMATRICE TERREMOTO
https://www.facebook.com/groups/1781276868754867/

Emergenza Terremoto
https://www.facebook.com/centrosmistamentocittareale/

Supporto FB Terremoto Amatrice
https://www.facebook.com/groups/1828041794081943/

Gruppo di aiuto terremoto Amatrice Accumoli
https://www.facebook.com/groups/1652394191737659/

Terremoto Amatrice Aiutiamoli!
https://www.facebook.com/groups/328935627447457/

GRUPPO EMERGENZA TERREMOTO
https://www.facebook.com/groups/1766050840303534/

Compriamo i prodotti dell'area del terremoto
https://www.facebook.com/groups/1446533295373900/

Accumoli e dintorni
https://www.facebook.com/groups/33167172372/

Accumoli, le frazioni, gli abitanti
https://www.facebook.com/groups/170473436306742/

Illica di Accumoli
https://www.facebook.com/groups/28317258986/

Pro Loco Arquata del Tronto
https://www.facebook.com/Pro-Loco-Arquata-del-Tronto-1569815429963187/

Rieti Life
https://www.facebook.com/rietilife/

Il Giornale di Rieti
https://www.facebook.com/Il-Giornale-di-Rieti-177088159057388/

Amatrice Sempreverde
https://www.facebook.com/groups/619473104813842/

**Comment by c83n** [comment]
taggo anche @annaluciont per aiutarvi

**Comment by iltempe** [comment]
chiudo.
