### ISSUE TITLE
Twitter, Waze e il Bollettino non vanno d'accordo

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#253]
Il feed di Waze viene twittato immediatamente. Ed è cosa buona e giusta. Parimenti dovrebbe essere inserito in automatico sul gruppo Facebook e sul Bollettino. Fatto ciò andrebbe "comunicato" al Gsheet di coordinamento del media team dell'avvenuto inserimento (per evitare cosìche i curatori poi facciano twittare di nuovo un contenuto già twittato grazie al rss di Waze... né possono fare a meno di inserire queste info altrimenti non uscirebbero né su Bollettino né su canale Telegram --- a meno che, immagino, anche questo sia alimentato da rss Waze).

**Comment by aborruso** [comment]
Non potrebbero bastare queste  cose:
- [x] fare in modo che gli avvisi wave vengano comunicati anche nel gruppo Telegram;
- [ ] fare in modo che gli avvisi wave vengano comunicati anche nel gruppo Telegram del media team;
- [ ] fare in modo che venga pubblicato sul gruppo facebook.

Che ne pensate @epoeta e @dontyna ?

**Comment by aborruso** [comment]
@epoeta ti ho letto male. Tu proponi anche di pubblicare su gruppo facebook. E' giusto.

Modifico sopra

**Comment by epoeta** [comment]
L'idea è prendere gli item di Waze e farli affluire direttamente in bollettino e gruppo Fb (Media Team aggiorna policy interna stabilendo di ignorare ogni segnalazione Waze perché automatizzata su tutti i canali). Non sarebbe male aggiornare pure Gsheet interno di coordinamento del Media Team con un bel "Inserito" in corrispondenza del post generato in automatico.

**Comment by aborruso** [comment]
@iltempe per pubblicare in automatico sul gruppo Facebook, avrei bisogno di un account "virtuale" che pubblichi i dati dal waze feed (un po' come l'utente bot di Telegram).
C'è già un utente fb terremotocentroitalia? Se c'è lo posso usare per pubblicare sul gruppo fb via API?

Grazie

**Comment by marco-acorte** [comment]
scusate ma terremotocentroitalia ha un account IFTTT ?

**Comment by iltempe** [comment]
@aborruso non abbiamo un account fb. anche perchè non saprei come aprire un account fb di un progetto. Al massimo potremmo aprire una pagina. fa lo stesso secondo te?
