### ISSUE TITLE
Uniformare Tag BOT Telegram con WebForm

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#255]
I tag del bot telegram vanno uniformati con quelli del web form come mostrato in questo issue di esempio
https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/101

**Comment by Pinzauti** [comment]
Il formato lo lasciamo così `nome:cosa`?
Se non ci sono problemi per me l'ideale sarebbe modificare i due punti in un simbolo meno in uso nel linguaggio comune.

**Comment by iltempe** [comment]
Io vorrei fare in modo che di gestire i tag con i : esattamente come è adesso, per un semplice motivo: lo si trasforma in modo facile in un YAML. che è macinabile dal sito o da altre applicazioni web.

**Comment by Pinzauti** [comment]
Okay allora vada per i due punti

**Comment by iltempe** [comment]
@Pinzauti file https://github.com/emergenzeHack/terremotocentroitalia-heroku-php/blob/master/wordpress/wp-content/plugins/terremotocentroitalia-bot-telegram/telegram-bot-custom.php riga 188 circa...
