### ISSUE TITLE
Gestione Foto nelle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#256]
Dal momento che le API Github non consentono di fare upload di foto (almeno che non abbia preso un abbaglio io) per gestire le foto propongo di fare upload della foto su FLICKR secondo il #120 #117  e poi nel tag "immagine" inserire il link diretto alla foto.  Questo sia per il BOT Telegram che per il WebForm. Che ne pensate?

**Comment by Pinzauti** [comment]
@iltempe Upload di foto eventualmente lo puoi fare però va nella parte "code"  della repository e poi va linkato nell'issue.

**Comment by iltempe** [comment]
Secondo me andrebbe fatto l'upload dagli script PHP su FLICKR. e poi referenziato il link alla foto sul TAG Immagine dell'issue.

**Comment by Pinzauti** [comment]
Ok mi passi in privato i dati d'accesso a flickr?

**Comment by iltempe** [comment]
@lorenzoperone come facciamo a postare nel gruppo che hai fatto su flickr?

**Comment by lorenzoperone** [comment]
Possiamo fare l'upload direttamente nel profilo Flickr "[Emergenze Hack](https://www.flickr.com/photos/144881851@N07/)" utilizzando le credenzialidi accesso che ho creato (chi fa questo task mi contatti in privato).
Consiglio di creare uno specifico "album" per le foto da abbinare alle issue, il caricamento può avvenire utilizzando le API di Flickr che sono descritte [qui](https://www.flickr.com/services/api/), in particolare il caricamento può essere [sincrono ](https://www.flickr.com/services/api/upload.api.html) o [asincrono](https://www.flickr.com/services/api/upload.async.html) e le foto possono essere rese pubbliche o private. In fase di inserimento è opportuno taggarle, se le foto vengono inserite anche nel [gruppo](https://www.flickr.com/groups/3003557@N20/) e sono provviste dei geotag, queste saranno visualizzabili anche nella [mappa](https://www.flickr.com/photos_user_map.gne?path=&nsid=3003557%40N20&mode=group). Per richiamare una foto è sufficente utilizzare il photo_id che viene restituito in fase di upload. Il formato della foto da richiamare può essere quello descritto [qui](https://www.flickr.com/services/api/flickr.photos.getSizes.html).
Le altre persone che vogliono pubblicare foto sul gruppo condiviso (possibilmente geotaggate e complete di specifici tag di cui @iltempe dovremo definire un dizionario) possono farlo attraverso un qualsiasi altro account Flickr da desktop o da mobile utilizzando le app di Flickr o altre app compatibili (Lightroom, FlickFolio, ecc).

**Comment by Pinzauti** [comment]
@lorenzoperone quando puoi passami i dati d'accesso, info@francescopinzauti.com

**Comment by iltempe** [comment]
@Pinzauti @milesimarco direi di procedere ad archiviare le foto come dice @lorenzoperone e poi embeddarle nello stesso modo negli issue. grazie.
@lorenzoperone sul dizionario ci sentiamo a parte. grazie!
