### ISSUE TITLE
Pagina Fabbisogni non correttamente compilata

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#257]
La pagina fabbisogni va riordinata per campo data dalla data più recente a quella più vecchia. I dati sono quelli prelevati dal file
https://github.com/emergenzeHack/terremotocentro/blob/master/_data/fabbisogni.csv

**Comment by aborruso** [comment]
@iltempe ho modificato la source e con il prossimo update si dovrebbe ordinare correttamente.
I compilatori possono anche non ordinare per data, sarà la query successiva a fare l'ordinamento.

C'è da aspettare il prossimo update

**Comment by iltempe** [comment]
ok visto update @aborruso.  chiudo.

**Comment by aborruso** [comment]
@iltempe sembra ok. Fai un check e chiudi?
