### ISSUE TITLE
integrazione webform nel sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#258]
Nella pagina Segnala inserire il webform per segnalazioni #240 possibilmente con lo stesso css del sito.

Da fare solo dopo aver chiuso #256 e #255 .

**Comment by Pinzauti** [comment]
@iltempe ma intendi con un iframe o inserito direttamente?

**Comment by iltempe** [comment]
@Pinzauti intendo integrato direttamente in modo che sta principalmente dove sta il sito. Poi se uno vuole se lo embedda e lo mette dove gli pare.

che dici?

**Comment by Pinzauti** [comment]
Ok @iltempe mi pare una buona idea, rimane però il problema del back-end che ti accennavo su Telegram

**Comment by iltempe** [comment]
@Pinzauti per il backend scripts e tutto ci organizziamo con la #260

**Comment by iltempe** [comment]
il form da integrare è questo. https://terremotocentroitalia.herokuapp.com/segnalazioni" va integrato in modo responsive

**Comment by Pinzauti** [comment]
Può andare @iltempe ?
http://terremotocentroitalia.info/segnala/

**Comment by iltempe** [comment]
Ottimo chiudo e la discutiamo
