### ISSUE TITLE
Completamento dei crediti

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#259]
Chiedo a chi sta contribuendo a questo progetto implementando o supportando in altro modo di segnalarsi qui sotto assieme al tipo di contributo che state dando per darci modo di verificare e completare i crediti. Da citare ancora di sicuro io so di @Pinzauti @drizzt Donato @marco-acorte Vincenzo. Grazie.

**Comment by favoeva** [comment]
@Manfro Fabio Manfrin
