### ISSUE TITLE
bot telegram

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#26]
creare un bot telegram per ricerca automatica di coordinate e foto

**Comment by olistik** [comment]
@iltempe dove memorizziamo foto e coordinate?

**Comment by iltempe** [comment]
partirei da qui

http://pratosmart.teo-soft.com/come-fare-una-mappa-di-segnalazioni-usando-telegram/ http://pratosmart.teo-soft.com/come-fare-una-mappa-di-segnalazioni-usando-telegram/

**Comment by milesimarco** [comment]
Mi permetto di segnalare questo sistema in WordPress:
[wordpress.org/plugins/telegram-bot](https://wordpress.org/plugins/telegram-bot/)

Sfrutta gli webhook quindi tutte le risposte sono istantanee. Richiede come base un sito WordPress ma, a parte questo, consente praticamente qualsiasi cosa

Ci sono possibilità di espansione per parsing di testo e di coordinate:

```
add_action('telegram_parse','telegramcustom_parse', 10, 2);

function telegramcustom_parse( $telegram_user_id, $text ) {
    $plugin_post_id = telegram_getid( $telegram_user_id );

    if ( !$plugin_post_id ) {
        return;
    }

    /*
    Here is the dynamic processing and how to reply.
    You can:
    - use if, switch and everything that works in php
    - check if $text is made of multiple words (create an array from $text)
    - customize and code other actions (ex. create WordPress post is $telegram_user_id is your id)
    */

    if ( $text == '/command') {
        telegram_sendmessage( $telegram_user_id, 'Oh, yes you typed /command');
    }

    return;
}

add_action('telegram_parse_location','telegramcustom_c_parse_location', 10, 3);

function telegramcustom_c_parse_location ( $telegram_user_id, $lat, $long  ) {
//Location received from users. Let's save it somewhere
}
```

**Comment by mfortini** [comment]
Se avete le risorse WordPress, php, qualsiasi cosa fate pure, importante è cominciare a registrare perché in emergenza è utile. Grazie

**Comment by milesimarco** [comment]
Ok, se intendiamo seguire la strada WordPress occorre un sito. Non ho problemi a metterlo online, ma se si riuscisse a installare sul sito terremotocentroitalia.info (magari in sottocartella o sottodominio "telegram") sarebbe più azzeccato.

**Comment by mfortini** [comment]
Il sito è su github e tutte le altre elaborazioni si fanno su server
esterni. Se si vuole usare un server utente DB su gruppo Telegram ha detto
di poterne fornire

Il sab 27 ago 2016, 10:46 Marco Milesi notifications@github.com ha
scritto:

**Comment by milesimarco** [comment]
Ok, prendo in carico la questione. Riporto qui i risultati

**Comment by iltempe** [comment]
@milesimarco @mfortini il @aborruso propone un metodo con un FORM per questo tema.

**Comment by aborruso** [comment]
Qui c'è il form [https://enketo.ona.io/x/#Y9N1](https://enketo.ona.io/x/#Y9N1)

E' costruito on XLSForm e OpenDataKit e non richiede l'installazione di nulla. Funziona benino anche da mobile.

Non lo vedo necessariamente in concorrenza con un bot, ma mi sembra di grande facilità e immadiatezza d'utilizzo.

Aldilà della tecnologia che sceglieremo, vale la pena ragionare su questo workflow e sulla sua utilità. Sarebbe fantastico coinvolgere qualcuno che è sui luoghi

**Comment by milesimarco** [comment]
Bot: @TerremotoCentroItalia_bot
~~Csv: https://terremotocentroitalia.mmilesi.ml/segnalazioni.csv~~
Nuovo link csv: https://terremotocentroitalia.mmilesi.ml/?get-csv=true

L'utilità del bot può andare oltre alla geolocalizzazione integrando broadcast o risponditori automatici.

Segnalo anche che il bot creato è compatibile con Zapier (può mandare in push del testo in base a azioni avvenute in Zapier) e possiamo collegarlo ad altri servizi.

EDIT:
Codice BOT caricato su
https://gist.github.com/milesimarco/2f2ff70a18c06d25b162cb474c87b0c5

**Comment by milesimarco** [comment]
Codice bot disponibile su

**Comment by iltempe** [comment]
Per il coinvolgimento sui luoghi sono in contatto con qualcuno che sul campo potrebbe stare connesso con noi. Vi aggiorno.

**Comment by milesimarco** [comment]
Perfect, thanks

Il 28/ago/2016 12:43 AM, "Iltempe" notifications@github.com ha scritto:

**Comment by mfortini** [comment]
@piersoft ci ha condiviso il suo italiapulitabot che fa molte delle cose che cerchiamo, può essere utile? https://github.com/piersoft/italiapulita

**Comment by davidegalletti** [comment]
Durante SOD16 a Trento e nei giorni seguenti ho creato un bot @segnalazionibot per raccogliere foto geolocalizzate nell'ambito del gruppo di lavoro sull'amianto. 
[Codice del bot](https://github.com/spaghetti-open-data/code4health-amianto/tree/master/segnalazionibot)
[La descrizione del funzionamento sul wiki](https://github.com/spaghetti-open-data/code4health-amianto/wiki/Il-bot-per-Telegram-segnalazionibot)
[La mappa delle segnalazioni](http://108.161.134.31:8800/static/map.html)
[I dati in JSON](http://108.161.134.31:8800/static/maps/markers.json) (i dati al momento sono solo test quasi esclusivamente fatti da me)

Sono a disposizione per dare una mano su @TerremotoCentroItalia_bot (anche se non ho esperienza su wordpress, @milesimarco fammi sapere se c'è un ambito in cui posso essere utile) e/o a creare/estendere funzionalmente un'istanza di @segnalazionibot

**Comment by iltempe** [comment]
Dico la mia sul tema degli strumenti: possiamo avere anche vari canali di informazione diversi (anzi meglio) per segnalazione da campo ma direi di elencarli in modo da poter fornire una lista chiara a chi li cerca.
Direi di fare una pagina wiki dove si scrive esattamente il nome dello strumento e il link al database che riporta le segnalazioni. 

Se riuscite qui sotto a dirmi quelli attualmente usabili sia come strumenti che come link al DB procedo ad elencarli io nel wiki grazie.

**Comment by milesimarco** [comment]
Con @mfortini si pensava di geolocalizzare le foto in automatico dai dati exif. Cosa ne pensi @davidegalletti ?

PS. Il codice è qui:
https://github.com/milesimarco/terremotocentroitalia-bot-telegram
(lo strato inferiore di interfacciamento è gestito da https://wordpress.org/plugins/telegram-bot/ a cui però manca la ricezione di file - che implementerò appena possibile)

**Comment by iltempe** [comment]
Per favore usiamo questo bot per fare questa cosa qui e archiviare dati su CVS.
E’ ottima idea.
Grazie

**Comment by davidegalletti** [comment]
Purtroppo Telegram non ti manda i dati exif; ho contattato il supporto e adducono motivi di privacy (che non condivido).

**Comment by davidegalletti** [comment]
Bot

> No, we don't save the metadata of the images. But if you bot needs them, you can query the user for the location easily using the new "request_location" buttons.

Davide

> Thanks, that is what I am doing now but I wanted to make it easier for the user. Hope that this will change in the future, all the best, Davide

Bot

> Well, keeping all that information is not something reallly privacy-oriented.  I'm not sure if it will be changed anytime.

**Comment by milesimarco** [comment]
Ok, in tal caso direi:
- soluzione web di @aborruso con estrazione automatica di dati exif: si può fare?
- alternativa Telegram con @TerremotoCentroItalia_bot (un po' più macchinosa perché bisogna mandare **anche** la propria posizione ad ogni foto, ma sicuramente di maggior fruibilità

Questa è un'altra cosa che non condivido:

Marco:

> What about sending bulk messages?

Bot Support:

> I'm afraid that bots api doesn't support this feature at the moment, but you may can simulate it if you create a channel and add your bot as admin there (asking your bot's users to join that channel).

**Comment by davidegalletti** [comment]
La soluzione di @aborruso mi sembra abbastanza comoda da usare anche senza l'estrazione dei dati exif perché è sufficiente dare conferma alla richiesta di comunicare la posizione.

**Comment by mfortini** [comment]
Use case è questo: Christian Quintili fa 200 foto con geotag abilitato oggi e stasera è in copertura WiFi. A questo punto usa qualsiasi cosa che sia il più vicino possibile a selezionare le 200 foto e premere l'icona condividi con...
E le sue foto vanno archiviate su un server, con permalink scritti su un archivio online (CSV, gsheet, ...), che estrae in alcune colonne dati exif come data, ora, latitudine, longitudine.
Poi qualcuno aggiunge in questo stesso foglio dei metadati estratti guardando le foto.
Il tutto va a finire in una mappa zoomabile e filtrabile per hashtag e periodo temporale

**Comment by davidegalletti** [comment]
Per questo use case la soluzione bot mi sembra poco adatta.
Immagino che ci sia più di una persona che debba fare l'upload. Proporrei l'uso di dropbox o simili per l'upload. Uno script in cron scarica le foto ogni ora, estrae le info EXIF e le rende disponibili per aggiunta metadati, etc..

**Comment by mfortini** [comment]
Ok speravo in telegram perché più dinamico, ma se strippa i dati exif non è
utile. Per Dropbox riesci a proporre una soluzione? Altre alternative?

Il dom 28 ago 2016, 14:37 Davide Galletti notifications@github.com ha
scritto:

**Comment by davidegalletti** [comment]
Telegram lo escluderei per questa parte dello use case: "...stasera è in copertura WiFi"
oltre che per il problema con EXIF...

La soluzione che sto esplorando è questa:
1. Christian e altri hanno accesso in scrittura su un folder Dropbox
2. Periodicamente scarico le immagini 
3. Estraggo le info EXIF e memorizzo il tutto su un DB
4. Periodicamente genero file CSV, geoJSON, ... necessari
5. Un'applicazione web (io la farei con django) consente di aggiungere/modificare tag e altre info (che finiscono nei file generati al punto 4)

**Comment by mfortini** [comment]
Sulla tecnologia app va bene qualsiasi cosa, l'importante è che sia
sufficientemente stabile per poter essere usata da oggi a qualche anno
(anche spostandola altrove ovviamente), anche da persone non
particolarmente informatiche.

Dropbox lo possiamo condividere sul web? È possibile che sia configurato
solo in append?

Il dom 28 ago 2016, 14:50 Davide Galletti notifications@github.com ha
scritto:

**Comment by milesimarco** [comment]
Dunque, il bot @TerremotoCentroItalia_bot con localizzazione manuale è pronto e salva in CSV su
https://terremotocentroitalia.mmilesi.ml/?get-csv=true

Volendo, possiamo tentare la strada di Telegram anche per questo caso d'uso: infatti se l'immagine viene mandata come file gli exif vengono conservati:

![schermata del 2016-08-28 14-55-59](https://cloud.githubusercontent.com/assets/3340185/18033918/cb4642d6-6d2f-11e6-9c78-eb2dc96cdd14.png)

**Comment by mfortini** [comment]
Quindi Marco dici che è soltanto questione del modo in cui viene fatta
condivisione? A quello ci possiamo arrivare, si fa da iOS?

Il dom 28 ago 2016, 14:58 Marco Milesi notifications@github.com ha
scritto:

**Comment by milesimarco** [comment]
Io ho fatto da Android ma suppongo sia analogo:
inviando "Foto" gli exif vengono rimossi
inviando come "File" rimangono (effettivamente la procedura è un attimo più complessa e va specificata la differenza nel bot)

**Comment by milesimarco** [comment]
Da app pc la questione è semplificata:

![senzanome](https://cloud.githubusercontent.com/assets/3340185/18033965/f54880b6-6d30-11e6-901e-5af6c7ac1ad3.png)

**Comment by davidegalletti** [comment]
Il 28/08/2016 14:57, Matteo Fortini ha scritto:

> Sulla tecnologia app va bene qualsiasi cosa, l'importante è che sia
> sufficientemente stabile per poter essere usata da oggi a qualche anno
> (anche spostandola altrove ovviamente), anche da persone non
> particolarmente informatiche.
> Non ho grossi dubbi sulla stabilità di Python, Django e di 
> un'applicazione relativamente semplice.
> Comunque è necessaria una certa gestione dovendo manipolare quantità di 
> file potenzialmente grossi.
> Ad esempio adesso la caricherei su una VM che ho sul cloud con spazio 
> disco non infinito. Periodicamente
> dovrei verificarlo. Lo stesso vale per l'account Dropbox.
> 
> Dropbox lo possiamo condividere sul web? È possibile che sia configurato
> solo in append?
> Si può fare in append con questo meccanismo di upload che comunque ti 
> consente di selezionare molti file contemporaneamente. Questa è una 
> prova che le carica sul mio dropbox:
> https://www.dropbox.com/request/wZIdUb2ERznjYIbsWhG1

**Comment by ebergam** [comment]
Ciao, sto facendo un po' da ponte tra voi, Matteo e Christian. Un'idea comoda in upload per fare presto (seguendo lo use case) sarebbe condividerle come file. Anche da iOS rimangono salvati gli exif. C'è questa libreria in python: https://pypi.python.org/pypi/ExifRead. Se ho capito bene da Matteo bisognerebbe farla utilizzare dal bot per estrarre exif e poi archiviare. (premetto: non ho idea di come fare un bot) però se riuscissimo a tenere su telegram ed evitare sbattimenti con le permission in dropbox sarebbe oro :)

**Comment by milesimarco** [comment]
@ebergam et voilà

Telegram bot @TerremotoCentroItalia_bot integrato con invio di "File"

# Iter "Foto"
- richiesta geolocalizzazione (tramite pulsante "segnala" o invio diretto della localizzazione)
- richiesta descrizione (facoltativa)
- richiesta foto
  Il documento salvato avrà timestamp coincidente con l'invio

# iter "File"
- invio diretto di un file. Se il sistema riesce a tracciare gli exif, allora salva nel db direttamente
  Il documento salvato avrà timestamp coincidente con l'ora di scatto della foto

Codice su https://github.com/milesimarco/terremotocentroitalia-bot-telegram

PS. Se qualcuno avesse un server (possibilmente SSL) possiamo fare qualche ragionamento per evitare il "mio" condiviso..
Teniamo presente che il metodo tramite "file" non comprime le foto...

**Comment by mfortini** [comment]
Perfetto ora valutiamo la sostenibilità nel tempo della cosa, server e quant'altro

**Comment by milesimarco** [comment]
Servirebbe un server veloce anche in termini di connessione (Telegram non ha api bulk quindi ogni chiamata "costa" tempo).

Certificato SSL obbligatorio (anche con ribaltamento gratuito dei DNS su CloudFlare).

PHP, WordPress, MySql...

L'ideale, a mio avviso, sarebbe metterlo in una sottocartella "telegram" del sito principale

**Comment by ebergam** [comment]
@milesimarco #mito

**Comment by ebergam** [comment]
@milesimarco, seguendo l'iter "file" è possibile fare in modo che venga aggiunta anche una descrizione? O è un casino da fare ed è meglio seguire l'iter foto?

**Comment by milesimarco** [comment]
La modalità "file" è talmente semplice che puoi mandare anche 10 foto alla volta. In tal caso come gestisci la descrizione?

**Comment by piersoft** [comment]
se vuoi posso mettere a disposizione piersoft.it dove ho i miei 80 bots

Inviato da iPhone
