### ISSUE TITLE
Usabilità sito web Terremotocentroitalia.info

### ISSUE THREAD

**Issue by Gheivs** [emergenzeHack/terremotocentro#261]
# WORK IN PROGRESS - aggiornato al 09/09/2016

_Queste sono le mie considerazioni personali, potrei includere, se necessario, dei wireframe per darvi spunti progettuali. Diciamo che è impossibile che un sito sia perfetto da un punto di vista dell’usabilità, per cui “accontentiamoci” di portare miglioramenti là dove riusciamo, in un costante work-in-progress. Commentate pure se qualcosa non è chiaro / ho sbagliato a scrivere / avete suggerimenti, anche perchè non so effettivamente se alcune cose sono già state fatte o se già le volete fare. Questo 'documento' serve a voi, per cui se possiamo indirizzarci a vicenda facciamo metà del lavoro
Cercherò di tradurre pian piano i vari paragrafi in operazioni concrete da svolgere._
## A chi è diretto?

Ai cittadini delle zone colpite (in primis), a sostenitori/volontari, ai giornalisti, ai tecnici.
## Chi sono i cittadini?

Sono principalmente anziani; c’è la possibilità che quelli che hanno più bisogno effettivo del sito abbiano anche minore dimestichezza con il mezzo.
## Obiettivo?

Essere il collegamento tra domanda ed offerta, il ponte tra il bisogno dell’utente e chi può in qualche modo risolverlo. 
- E’ importante che **le persone trovino subito quello che cerchino**. La priorità andrà alla chiarezza, piuttosto che alla coerenza (grafica soprattutto). Il fatto che sia un sito “operativo” vi da il grande vantaggio di non dovervi fissare troppo sulla questione estetica (palette colori, minimalismo, fighettate varie…) e potete anzi concentrarvi sul rendere il tutto autoevidente e autoesplicativo per chi ha poca dimestichezza con il mezzo digitale.
- Molte più persone oggi utilizzano lo smartphone; non credo che creare un’app sia la direzione più giusta, bensì tentare di accorpare tutto in un unico portale. Terremotocentroitalia.info è già responsive, per cui siamo sulla strada giusta.
- Prevedere che **i più anziani utilizzeranno con più facilità l’sms**. Oltretutto mi pare di aver capito che la rete cellulare è un po’ ballerina e probabilmente la gente troverà difficile accedere al portale. (So che ci stiamo muovendo con Actionaid per utilizzare il portale ContactLab, per cui attendo notizie a riguardo)
- Una persona dovrebbe essere in grado, al bisogno, di entrare su terremotocentroitalia.info e risolvere lì il suo problema, che si tratti di richieste di assistenza, segnalazioni, ricerca di info. Il fatto è che per ora dal punto di vista delle segnalazioni il sito riesce solo a linkare i vari canali accessori (Telegram, Fb, mail, twitter…) - che comunque rimarranno attivi - ma sarebbe l’ideale che il sito stesso le possa raccogliere con facilità.
## COSE SEMPLICI DA POTER FARE SUBITO
- **Volantini tipo vademecum** per spiegare ai cittadini delle zone colpite come è possibile fare segnalazioni. Può essere banalmente questa pagina http://terremotocentroitalia.info/aiuto/ con una spiegazione in dettaglio di come funzionano i vari canali (escluderei Flickr tra le priorità)
- Riorganizzare le sezioni del sito in base alla priorità dei cittadini: appena entrati, a mio avviso, ci dovrebbe essere la sezione “Hai bisogno?” con le relative sottocategorie.
## COSE DA FARE SUL LUNGO PERIODO
- Fare in modo che la piattaforma terremotocentroitalia.info permetta direttamente di segnalare/richiedere aiuto. L'idea è di incorporarvi le funzionalità che ora vengono testate su https://terremoto.francescopinzauti.com/ 
  Per quanto riguarda il layout e struttura del sito mi sto muovendo per disegnarne una prima bozza.

**Comment by iltempe** [comment]
ciao!
per quanto riguarda le "cose da fare" io farei degli issue singoli per ogni tua proposta.
Tieni conto che 
- la sezione hai bisogno c'è già.
- per le segnalazioni stiamo implementando più o meno quanto definito in #242 

Per il resto (sugli obiettivi) siamo mi pare allineatissimi ;-) 
grazie!

**Comment by favoeva** [comment]
nella home manca Notizie Utili che vada a pescare contenuti da qui https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=8819636
