### ISSUE TITLE
Infopack TCI 

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#265]
Ciao
a questo link trovate la draft di infopack preparata da Veronica Boggini 
https://goo.gl/BTQmYd

E' aperta alla revisione
# daje

**Comment by luciaroma** [comment]
tks!!!

**Comment by favoeva** [comment]
Ottimo lavoro davvero! Solo ci sono anche comuni in provincia di fermo , va aggiunta provincia ;)

**Comment by luciaroma** [comment]
grazie della segnalazione! ;) fatto

**Comment by Pinzauti** [comment]
Andrebbe aggiunta anche la possibilità di fare segnalazioni dal webform

**Comment by iltempe** [comment]
se può servire in  modo molto semplice avevo compilato questo wiki https://github.com/emergenzeHack/terremotocentro/wiki/Come-creare-segnalazioni
