### ISSUE TITLE
Serializzare YAML usando una libreria terze parti

### ISSUE THREAD

**Issue by drizzt** [emergenzeHack/terremotocentro#269]
Attualmente lo yaml è generato a mano sia nella webform che nel bot Telegram e questo può generare uno yaml con sintassi errata (se per esempio nella descrizione sono presenti caratteri speciali come " o ').

Ho fatto una prova usando la libreria symfony/yaml che genera sempre YAML valido a prescindere dall'input dato dall'utente.

Segue "snippet" di prova che può essere usato nel webform per generare sempre YAML valido:

``` php
use Symfony\Component\Yaml\Yaml;

$arr = array(
  'tel' => $tel,
  'email' => $email,
  'descrizione' => $descrizione,
  'indirizzo' => $indirizzo,
  'lat' => $lat,
  'lon' => $lon,
  'link' => $link,
  'immagine' => $immagine,
  'data' => $date
);
$yaml = Yaml::dump($arr);
$data = array(
  "title" => substr($descrizione, 0, 30),
  "body" => "<pre><yamldata>$yaml</yamldata></pre>",
  "labels" => [
    "Alloggi",
    "Form"
  ]
);

var_dump($data);
```

Che ne pensate?

**Comment by mfortini** [comment]
Mi sembra un'ottima idea

Il mar 13 set 2016, 12:30 Timothy Redaelli notifications@github.com ha
scritto:

**Comment by drizzt** [comment]
Potete vedere un esempio qui:
https://terremotocentroitalia.herokuapp.com/segnalazioni/yaml_serialize.php?tel=123123456&email=prova@prova.it&descrizione=Prova%2520%2527descrizione%2527%250Amultilinea%25OAcon%2520%2522caratteri%2522%2520speciali&indirizzo=Via%2520Prova,%252012%2520-%252020811%2520Lissone&lat=45,123&lon=19,123&link=http://www.prova.it&immagine=http://imgur.com/prova.php&date=2016-09-13T12:38:45+02:00

**Comment by drizzt** [comment]
Prova "live": https://terremotocentroitalia.herokuapp.com/segnalazioni/yaml_serialize.php?tel=123123456&email=prova@prova.it&descrizione=Prova%20%27descrizione%27%0Amultilinea%0Acon%20%22caratteri%22%20speciali&indirizzo=Via%20Prova,%2012%20-%2020811%20Lissone&lat=45,123&lon=19,123&link=http://www.prova.it&immagine=http://imgur.com/prova.php&date=2016-09-13T12:38:45+02:00

**Comment by iltempe** [comment]
Facciamolo.
