### ISSUE TITLE
Condivisione Errata link su Telegram

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#27]
Condividendo un link su telegram come http://terremotocentroitalia.info/alloggi/ si ha una lista di codice Ruby come in figura
<img width="613" alt="schermata 2016-08-26 alle 21 57 01" src="https://cloud.githubusercontent.com/assets/6368214/18018840/66019026-6bd9-11e6-9adf-a9046e0b0b88.png">

**Comment by stavrogin** [comment]
Ciao, 
analizzando il codice html ho notato questa riga nella sezione  :
  <meta name="twitter:description" content="{% for member in site.data.alloggi %} {{member.Descrizione}} {% if member.Dove %} Indirizzo: {{member.Dove}} {% endif %} {% if member.Numero %} Numero: {{member.Numero}} {% endif %} {% if member.Email and member.Email contains '@' %} Email: {{member.Email}} {% endif %} {% if member.Link %} Link:{{member.Link}} {% endif %} {% endfor %} {%..." />
Che è quello che effettivamente viene visualizzato su telegram... come fix veloce quantomeno metterei del testo statico

**Comment by olistik** [comment]
Sembra [una issue](https://github.com/jekyll/jekyll-archives/issues/28) ancora aperta.
