### ISSUE TITLE
Trasferire tutti i dati da Gdrive nelle segnalazioni Github

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#270]
Seguendo questa procedura https://github.com/emergenzeHack/terremotocentro/wiki/Creare-e-Gestire-segnalazioni
trasferire i dati del google sheet che sappiamo essere "buoni" come segnalazioni tramite webform in modo che saranno gestibili come issue github.

Vanno colorate nel Google Sheet le righe che sono state trasferite come segnalazioni in modo che sia identificabile cosa è stato trasferito e cosa no.

Per un periodo di transizione va mantenuta la doppia gestione delle segnalazioni in webform+google sheet.

A regime ogni segnalazione sarà gestita come issue github secondo quando scritto in #242 e il google sheet resterà solo per informazioni funzionali al sito ovvero
- feed
- press
- vittime

**Comment by dontyna** [comment]
In fabbisogni non si può inserire manualmente il campo indirizzo ed è un problema.

**Comment by favoeva** [comment]
E io questa se siete d'accordo la chiuderei (in Gdrive restano solo fogli 'press' e 'vittime')

**Comment by iltempe** [comment]
chiudo.
