### ISSUE TITLE
Gestione repository Terremotocentro_segnalazioni

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#272]
ciao gente, 
sappiamo che esiste un repository di sole segnalazioni
https://github.com/emergenzeHack/terremotocentro_segnalazioni

Che questo repository si popola non lato codice, ma solo con le issue. Ad ogni issue corrisponde una segnalazione.
@c83n giustamente sottolinea che a ciascuna segnalazione deve poter essere associata una `label` specifica e si candida ad occuparsene insieme ad alcune persone.

Per farlo, è sufficienete che @c83n diventi collaborator del repository? 

mi appello ad @aborruso @iltempe

**Comment by c83n** [comment]
l'ammiraglio sa quanta stima io riponga in lui quindi parto subito con un grazie :)
il problema è che sono impedito e non mi arriva la notifica che sono collaborator e quindi posso assegnare label, la qual cosa @iltempe pare abbia fatto da tempo #maiosoddecoccio 
guidatemi e ce la posso fare
tx

**Comment by iltempe** [comment]
@c83n a me risulti già abilitato a mettere le label, no?

**Comment by c83n** [comment]
ehm no :)

![image](https://cloud.githubusercontent.com/assets/1081488/18503962/0ea99086-7a60-11e6-9f03-433052ee99a7.png)

**Comment by aborruso** [comment]
@c83n hai ricevuto un invito, che non hai ancora accettato (non quello di oggi, quello di oggi buttalo)

Sinché non lo accetterai, non potrai assegnare label

![image](https://cloud.githubusercontent.com/assets/30607/18504149/1c6a39e0-7a61-11e6-885e-c8f6e66b8386.png)

**Comment by c83n** [comment]
grazie infatti email non funzionava
ma l'invito mi dovrebbere essere sempre arrivato via email?
perché in tal caso dovrei cercarmelo fra le 2.000 notifiche github che ho ricevuto
avete delle dritte? 
se cerco "invited" trovo solo 2 email di andy che non funziano
@iltempe me ne avevi mandato tu uno?
grazie

**Comment by nelsonmau** [comment]
@c83n questo è il bulk che github manda con questo genere di notifiche

```
Hi nelsonmau,

giuragu has invited you to join the giuragu/fire repository.

Visit https://github.com/giuragu/fire/invitations to accept or decline this invitation.

You can also head over to https://github.com/giuragu/fire to check out the repository.

Some helpful tips:

- If you get a 404 page, make sure you're signed in as nelsonmau.
- Too many emails from giuragu? Block them by visiting
  https://github.com/giuragu/fire/invitations and clicking the 'Block user' button.

---
View it on GitHub:
https://github.com/giuragu/fire
```

**Comment by iltempe** [comment]
Io ho reinvitato @c83n tre volte e abbiamo provato anche con mail diversa. Non vede gli inviti.

**Comment by aborruso** [comment]
Ho invitato @c83n  "di persona, personalmente". Tutto OK
