### ISSUE TITLE
Gestione segnalazioni in nuovo FORM

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#273]
In "Donazioni" per alcune segnalazioni non ci sono email o telefono, ma solo link. Manca un campo in cui inserirlo.

**Comment by Pinzauti** [comment]
@dontyna solo in "Donazioni" vorresti aggiungere mail e telefono? O anche in altre sezioni?

**Comment by Pinzauti** [comment]
@dontyna 
Sul webform nella sezione "Donazioni" c'è la possibilità di inserire sia la mail che telefono, a discrezione dell'utente come in accordo con il @iltempe

**Comment by chiccap** [comment]
Non riesco a riempire il campo "Indirizzo".

**Comment by Pinzauti** [comment]
@ChiaraParapini
Il campo indirizzo non è compilabile, bisogna spostare il pallino nella mappa in accordo con quanto detto da @iltempe e @piersoft
