### ISSUE TITLE
Campo indirizzo non compilabile

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#274]
Date le problematiche nell'usare Google Maps spiegate da @piersoft abbiamo cambiato tipo di mappa e tolta la possibilità all'utente di inserire l'indirizzo manualmente nel campo "Indirizzo" selezionandolo dall'autocompletamento Google (che avrebbe generato uno spostamento del marker nella mappa e relativa latitudine e longitudine).

Attualmente è possibile inviare la propria posizione <b>solo</b> muovendo il marker sulla mappa il quale compila automaticamente il campo indirizzo (di tipo readonly) e i campi latitudine e longitudine (di tipo hidden).

Questo crea due problemi principali:
- Le persone tendono a compilare l'indirizzo ma, vedendono che non possonno farlo, pensano ad un errore.
- Muovere il marker sulla mappa non è immediato ed è spesso scomodo soprattutto se da mobile e per grandi distanze.

[Cliccando qui](https://terremotocentroitalia.herokuapp.com/segnalazioni/) è possibile accedere al form.

Come potremmo risolvere?

**Comment by iltempe** [comment]
in diversi richiedono questa funzionalità. cioè la possibilità anche di compilare l'indirizzo a mano. @piersoft secondo te quali problemi ci sono a dare la possibilità di editare a mano quel campo? Che non si georiferisce bene?

**Comment by drizzt** [comment]
non si riesce a mettere la ricerca della posizione per indirizzo usando qualsiasi api?
per cui se uno cambia l'indirizzo il marker si cambia "da solo" e se uno cambia il marker l'indirizzo si cambia "da solo"

**Comment by drizzt** [comment]
ho appena visto che si può fare usando le api [Nominatim](http://wiki.openstreetmap.org/wiki/Nominatim)

**Comment by iltempe** [comment]
@drizzt si certo che si può fare. qui penso che il problema fosse che Nominatim a volte scazza a ricavare coordinate da indirizzo ed io non saprei dire con quale probabilità. Era un problema giustamente sollevato da @piersoft per cui avevamo deciso di dare solo la possibilità di spostare marker a mano. capisco che però cosi non è il massimo.

**Comment by fizzi** [comment]
json
http://nominatim.openstreetmap.org/search/?q=amatrice+italia&format=json&accept-language=it

html
http://nominatim.openstreetmap.org/search/?q=amatrice+italia&format=html&accept-language=it

**Comment by piersoft** [comment]
Piersoft Paolicelli, [14 set 2016, 13:14]: 
...vedete se il concetto vi garba. [http://www.piersoft.it/terremotocentro/webform/alloggi.php](http://www.piersoft.it/terremotocentro/webform/alloggi.php)

il marker non esiste più. basta spostare o zoomare la mappa e viene scritto l'indirizzo nel campo della webform
ora per cercare invece un indirizzo, e non tramite lo spostamento della mappa, basta cliccare sulla lente presente dentro la mappa. quando viene trovato l'indirizzo la mappa si zooma in automatico nel punto - via trovata e quindi viene compilato il campo indirizzo della webform

**Comment by iltempe** [comment]
@piersoft a me cosi piace. però va comunque impedito l'editing della TEXT BOX indirizzo ti torna?

**Comment by Pinzauti** [comment]
- E' possibile mantenere sia il marker (che forse è più chiaro) che il campo di ricerca?
- Per non avere duplicati e per evitare confusione, sarebbe possibile fare in modo che la ricerca (e l'autocompletamento) avvengano direttamente dal campo indirizzo (che è più chiaro e visibile) e non dalla lente di ingrandimento?

**Comment by piersoft** [comment]
dovrei cambiare la libreria del search. penso che non sia cosa semplice...

**Comment by piersoft** [comment]
@iltempe si rimane sempre inibito. il cambierei al posto di "cancella indirizzo" in "istruzioni per l'indirizzo" in modo da aprire una guida semplice che spiega come spostare la mappa piuttosto che usare la lente

**Comment by Pinzauti** [comment]
Secondo me diventa troppo macchinoso lato usabilitá

**Comment by iltempe** [comment]
@piersoft nel tuo esempio ho visto si poteva editare. proposta:
- il campo indirizzo lo facciamo grigio in modo che si capisca che non è usabile e lo mettiamo sotto la mappa
- sulla mappa ingrandiamo la lente (o scriviamo cerca indirizzo) in modo da capire che quella è il search.
  che dite?

**Comment by piersoft** [comment]
che ve ne pare cosi? http://www.piersoft.it/terremotocentro/webform/alloggi.php

**Comment by iltempe** [comment]
mi pare buono. metterei la box dell'indirizzo sotto la mappa in GRIGIO in modo da far vedere che è non editabile. che dite?

**Comment by iltempe** [comment]
@Pinzauti io a questo punto visto quest'ultima prova di @piersoft nasconderei il TEXTBOX indirizzo che è solo fuorviante. che dite?

**Comment by iltempe** [comment]
ho verificato. La soluzione di @piersoft non può essere deployata sul nostro host heroku. Non mi pare ci sia NPM installato al momento e come si vede qui è richiesto: https://github.com/stefanocudini/leaflet-search#examples. Occorre pensare ad altro.

**Comment by piersoft** [comment]
potremmo incorporare la mappa in un iframe e puntarla su un altro server (sul mio?) e lasciare il motore delle segnalazioni via webform su heroku oppure togliere la possibilità di ricerca indirizzo come era prima

Inviato da iPhone
