### ISSUE TITLE
Notizie utili - Nuova sezione

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#275]
Come fatto presente da @favoeva è necessario creare una sezione "Notizie Utili" che per adesso peschi contenuti da [qui](https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=8819636) (in futuro i contenuti saranno estrapolati da [questo CSV](https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issues.csv) come spiegato nella #242 e nella #276).

Pensavamo di aggiungere una nuova pagina nel sottomenù "Aggiornamenti" o eventualmente di aggiungere le notizie direttamente in home.

Ci sono proposte? Qualcuno può occuparsene?

**Comment by nelsonmau** [comment]
@Pinzauti e @iltempe scusate non avevo visto questa issue.
Dunque io ho fatto news https://github.com/emergenzeHack/terremotocentro/blob/master/news.md
- aggrega i contenuti da questo feed fatto da @aborruso http://feeds.feedburner.com/TerremotoCentroItalia-RaccoltaFeedRss
- include il plugin simpleRSS per acchiappare e stampare gli item del feed
- usa una microplugin jquery per fare ricerca

l'output è qui terremotocentroitalia.info/news
(e sembra funzionare per bene).

ha un nesso con quello che volete fare?

**Comment by nelsonmau** [comment]
@Pinzauti io ti ho previsto un pulsante per "Notizie utili" nella nuova HP
lo lascio o va tolto? @iltempe

**Comment by iltempe** [comment]
@nelsonmau l'ho rimosso perchè era TO DO. 

Ma non possiamo puntare a http://terremotocentroitalia.info/news/ ?

**Comment by iltempe** [comment]
Sulla pagina http://terremotocentroitalia.info/news/ ora ci sono due sezioni. la prima è generata sicuramente dagli issue. La seconda mi pare sia quella vecchia del google sheet.

Proporrei di rimuovere la seconda sezione e di formattare l'elenco delle news come già fatto in

http://terremotocentroitalia.info/risorse-disponibili/
