### ISSUE TITLE
Creare Pagine del sito tramite le segnalazioni github

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#276]
Va predisposto il sito in modo che dal [CSV delle segnalazioni](https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issues.csv), che a regime conterrà tutte le segnalazioni, si generino le pagine del sito divise per argomenti.

Una soluzione può essere embeddare gli ISSUE direttamente nel sito come in questo modo:
https://github.com/amandavisconti/embed-github-issues/blob/master/EmbedIssues.js

Le uniche pagine che possono restare a gestione tramite google sheet dovrebbero essere 
- press
- vittime
  o anche no (da decidere). che dite?

**Comment by mfortini** [comment]
Ho tentato così
http://terremotocentroitalia.info/issues/
utilizzando il plugin jekyll 
https://github.com/avillafiorita/jekyll-datapage_gen

Per ora
- i link alle pagine non vengono creati bene
- le pagine non hanno un gran senso come sono create, sono solo delle copie dei valori
- sarebbe utile poter fare parse del JSON contenuto nel campo data per poi riempire la pagina. Esiste o è possibile creare un filtro jekyll?

**Comment by mfortini** [comment]
github2csv può generare un file json
la pagina issues.md va  prendere un file in _data/issuesjson.json
in questo modo è possibile utilizzare member.data.chi, member.labels etc...

**Comment by iltempe** [comment]
ok. @mfortini come li dividiamo? per label? solo segnalazioni aperte?

**Comment by mfortini** [comment]
http://terremotocentroitalia.info/issues/scuola-danneggiata/index.html

ecco un esempio, se qualcuno ha idee su come mettere a posto _layouts/index.html abbiamo un buon risultato
