### ISSUE TITLE
Georeferenziazione obbligatoria

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#277]
Attualmente nel [webform](https://terremotocentroitalia.herokuapp.com/segnalazioni/) l'utente è libero, in tutte le sezioni, di inserire o meno la posizione.

Forse dovremmo rendere la georeferenziazione obbligatoria? Se si, dovremmo farlo per tutte le sezioni o solo per alcune?

Elenco alcuni pro e contro dell'obbligare l'utente a dare la propria posizione (secondo me ovviamente, liberi di aggiungere/modificare).

Pro:
- Avremmo un database più completo e meno frammentato.
- Sarebbe possibile inserire TUTTE le issue (almeno per determinate sezioni) nella mappa, mantenendo un solo strumento di visualizzazione per l'utente.

Contro:
- Rischio di scoraggiare la creazione di segnalazioni, o perché l'utente non può o non vuole dare la propria posizione, o per il problema descritto nella #274.
- Rischio di inserimento di indirizzi non utili, solo per compilare un campo obbligatorio.

**Comment by fizzi** [comment]
Credo sia importante geolocalizzare le segnalazioni, anche quelle non direttamente geolocalizzabili. Dovremmo pensare ad un modo per realizzarlo.

Se l'utente non vuole mandare la sua posizione (parlo del bot ... ma anche del form) ... pazienza la segnalazione non potrà essere accettata. E' un po come chiamare ai VVF per segnalare un incendio ... ma non voler dare l'indirizzo.

Anche per le segnalazioni per esempio di Raccolte Fondi, credo possa essere utile "come informazione" sapere che ad esempio Regione Toscana e Anci Toscana ha un puntino in via Novoli a Firenze.

**Comment by Pinzauti** [comment]
Per il bot questo giá avviene, dato che si occupa principalmente delle segnalazioni dal campo.

Per quanti riguarda il form invece, e nello specifico per la sezione raccolte fondi, ci sono casi in cui è impossibile geolocalizzare, come faceva giustamente presente @iltempe non esistono solo segnalazioni dal campo.
Ad esempio la raccolta fondi via SMS, dove potrebbe essere geolocalizzata?
Un conto è dare la possibilità, un conto è obbligare.
Se obbligo l'utente a inserire una posizione, finirá che non inserirá la raccolta fondi con gli SMS o inserirá una località a caso.
Se invece lo lascio scegliere, non geolocalizzerá la raccolta fondi degli SMS ma magari geolocalizzerá la raccolta fondi a Novoli.

Diversa è la questione, almeno secondo me, per alcune sezioni, come la sezione alloggi e fabbisogni, dove secondo me ci sta obbligare a dare un punto di riferimento geografico.

**Comment by iltempe** [comment]
Allora esistono informazioni che non necessariamente sono da georiferire: es appunto una raccolta fondi che non è detto abbia un luogo, ma anche le notizie utili. Le altre informazioni possono avere un georiferimento che per me può essere anche obbligatorio ma va data la possibilità di citare anche solo il nome di una città o di un paese perchè non è detto che si abbia sempre l'indirizzo. che dite?

**Comment by Pinzauti** [comment]
Sono d'accordo @iltempe, e qua allora torna il problema della #274

**Comment by iltempe** [comment]
Ho attualmente scritto nei WIKI come editare ogni issue per aggiungere la georeferenziazione anche dopo aver inserito i dati da webform. https://github.com/emergenzeHack/terremotocentro/wiki/Creare-e-Gestire-segnalazioni

**Comment by mfortini** [comment]
Ho installato per prova un geocoder con nominatim fatto da un CSS+JS su leaflet. In questa pagina nella mappa in alto a dx potete vedere l'esempio del riquadro "cerca"
http://terremotocentroitalia.info/issues/

I sorgenti del geocoder sono https://github.com/perliedman/leaflet-control-geocoder

si possono inserire nel webform?

**Comment by mfortini** [comment]
Ho inserito sempre nella stessa pagina esempio di geocoding che ricava anche le coordinate.
