### ISSUE TITLE
Nuova politica gestione segnalazioni - Beta Testing

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#278]
Stiamo procedendo come richiesto da #270 a trasferire i dati in issue github per gestire tutte le segnalazioni da un repository github. 
Attualmente restano attivi entrambi i modi di gestire dati: segnalazioni github e google sheet.
La guida wiki è qui https://github.com/emergenzeHack/terremotocentro/wiki/Creare-e-Gestire-segnalazioni. per miglioramenti o note scrivete pure issue. grazie

**Comment by nelsonmau** [comment]
#242 si può chiudere?

**Comment by iltempe** [comment]
chiudo.
