### ISSUE TITLE
Tenere aggiornato il Foglio Google

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#28]
Abbiamo creato questo foglio google per inserire dati (non post) che sono stati verificati e si possono riversare nel sito. Informazioni da social, contatti, chat e telefonate.

https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit

Va continuamente aggiornato verificando di non ridondare informazioni già esistenti e seguendo le istruzioni del primo foglio!

**Comment by favoeva** [comment]
in DONAZIONI  https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=1205831052
se siete daccordo, aggiungerei due campi: 
- DATA inserimento 
- ORA inserimento
- CHIUSA/APERTA (es. il post su richiesta carburante che si è chiusa)

**Comment by favoeva** [comment]
in RACCOLTE FONDI c'è un problema: i link inseriti, nonostante venga applicato il formato link nel gsheet, non vengono presi come link dal CSV github @olistik puoi dare un'occhiata tu?

**Comment by mfortini** [comment]
Per come è fatto il template, l'unica colonna che viene messa come link è
quella "Link", tutti gli altri formati noi non li vediamo perché dal csv
arriva solo il testo.

Il sab 27 ago 2016, 22:26 Marieva Favoino notifications@github.com ha
scritto:

**Comment by epoeta** [comment]
IN RACCOLTE FONDI È possibile fare in modo che il db venga ordinato alfabeticamente sulla base della colonna A (sarebbe molto più leggibile)? Sarebbe utile un campo condizionale sull'ultima colonna (COMPLETATO ad esempio) che quando valorizzato con SI/1 o non so quale altro valore dia il via libera alla pubblicazione.

**Comment by epoeta** [comment]
IN RACCOLTE FONDI Segnalo che nel campo link figurano anche riferimenti a fonti delle notizie in formato cartaceo (verificati). Una colonna in più per questi che non link automaticamente il testo (il quale ovviamente essendo una espressione tipo Corriere delle Alpi, 25/08/2016, pag. 2 porta a pagina inesistente)?

**Comment by gufogio** [comment]
@epoeta Con l'ordine alfabetico rischiamo che le raccolte "istituzionali" si perdano, potremmo categorizzare le raccolte (regioni, province, media, associazioni nazionali, associazioni locali) e ordinarle per rilevanza :)

**Comment by ValeriaV** [comment]
Andrea Borusso @aborruso ha scritto su Telegram:
#facebook: su idea ottima di @dontyna ho creato un feed RSS per tutto ciò che avviene nel gruppo fb. Può essere utile a tutti quelli che si stanno prendendo cura per tutto ciò che avviene al suo interno. Vi potete iscrivere con il client che preferite e attivare tutte le automazioni del caso.
Questo l'URL 
http://feeds.feedburner.com/GruppoFacebookTerremotocentroitalia

Ad uso interno per monitorare la pagina Facebook

**Comment by favoeva** [comment]
@mfortini segnalo che in DONAZIONI la colonna link non arriva al csv :(

**Comment by iltempe** [comment]
Con la #242 il foglio google attualmente rimane attivo per PRESS e VITTIME e basta.
