### ISSUE TITLE
Creare Feed RSS delle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#281]
Creare Feed RSS delle segnalazioni 
https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues

**Comment by marco-acorte** [comment]
allora... qualcosa gia' esiste in formato ATOM 
https://github.com/terremotocentroita.atom
e corrisponde a quello visibile qui
https://github.com/terremotocentroita?tab=activity

**Comment by iltempe** [comment]
OK,  ma io mi riferivo al repo delle segnalazioni che stiamo alimentando che ho linkato sopra.

Potrebbe essere utile avere un FEED RSS per ogni categoria di label.... @aborruso che dici?

**Comment by iltempe** [comment]
chiudo perchè se ne parla in #287
