### ISSUE TITLE
Correggere Informativa su WebForm

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#282]
Per quel che riguarda l’informativa, non abbiamo bisogno di chiedere il consenso (dobbiamo solo un’informativa) e quindi non è necessario, ed è da togliere, il flag di accettazione. 
Quel flag è da sostituire con questa frase “LEGGI L’INFORMATIVA TRATTAMENTO DATI PERSONALI” e con  un link mettere l’informativa alla pagina  /legal_segnalazioni

**Comment by Pinzauti** [comment]
Fatto
