### ISSUE TITLE
Usare lista issue per pagine fabbisogni, notizie utili, ...

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#284]
Dopo il #276 issues.md contiene esempi su come filtrare le segnalazioni in funzione delle label.

Usare questi dati nelle pagine fabbisogni, notizie utili, alloggi, raccolte fondi

**Comment by iltempe** [comment]
@mfortini intendi dire si fa query sulle label degli issue esitenti per generare pagine come l'esempio tuo?

**Comment by iltempe** [comment]
ok mi pare un'ottima soluzione. Non appena si è migrato tutto da Google sheet switchamo su questa.

**Comment by iltempe** [comment]
ho fatto questa prova. http://terremotocentroitalia.info/risorse-disponibili/ dimmi che ne pensi

**Comment by iltempe** [comment]
a livello di contenuti la cosa è OK. c'è da lavorare sul design ho aperto #290 e #289 . chiudo.
