### ISSUE TITLE
Nuovo Layout Homepage HP / uno sketch

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#285]
ho fatto un minimo di prova che incollo qui.
c'è qualche volontaria/o che se ne occupa? :-)

![tcihp](https://cloud.githubusercontent.com/assets/1769578/18547101/ea6553ee-7b41-11e6-86b8-fe304991a647.png)

**Comment by iltempe** [comment]
io avevo trovato un tema jekyll su cui si potrebbe lavorare un po' per renderlo con i PULSANTONI come si diceva ieri. Ovviamente colori e stili da modificare come vogliamo.

https://jeromelachaud.github.io/freelancer-theme/  che dite?

**Comment by nelsonmau** [comment]
ottima soluzione secondo me!

**Comment by nelsonmau** [comment]
@iltempe nell'attesa ho fatto un branch con la nuova hp, 

https://github.com/emergenzeHack/terremotocentro/tree/newHomePage

incollo qui uno screenshot
anche il filtro sembra funzionare...

che ne dici? @aborruso? @dontyna? 

![tci_hpokkey](https://cloud.githubusercontent.com/assets/1769578/18569184/606c41ce-7ba1-11e6-892f-14336c4f1a4d.png)

**Comment by c83n** [comment]
A me piace un casino quello che state facendo :)
una domanda; è possibile secondo voi impostare il bollettino trasponendo i campi riga / colonna e dando all'utente la possibilità di ordinare e filtrare?

**Comment by nelsonmau** [comment]
@c83n non è semplice, sono singole schede... si può fare in modo che siano più 'belle' ed efficaci.
Il filtro l'ho messo: quando mettiamo online la nuova HP, vedrai che funziona
@mfortini ci dai un'occhiata anche tu? ma anche @favoeva e @Manfro 
se siete d'accordo la mettiamo in produzione (va fatto semplicemente il merge di questo branch su `master`)
grazie regaz!

**Comment by iltempe** [comment]
@nelsonmau per me va bene, una cosa "segnalazioni aperte e chiuse" dove linka?

**Comment by nelsonmau** [comment]
@iltempe è il filtro di prima, ora fatto con `<button>`

**Comment by c83n** [comment]
@nelsonmau yo :+1:

**Comment by nelsonmau** [comment]
va bene, deploio

**Comment by nelsonmau** [comment]
è on line http://terremotocentroitalia.info/

**Comment by c83n** [comment]
yo yo yo yo yo yo !!!!

**Comment by mfortini** [comment]
ho cambiato in homepage prendendo la lista bollettino da github e non da gsheet. Ho tolto i tasti aperta/chiusa perché attualmente da github estraiamo solo le issue aperte

**Comment by asiadag** [comment]
ciao ragazzi, 
mi inserisco nella conversazione. Sono la communication officer di ActionAid. Prima di tutto vi faccio davvero i complimenti da parte mia/nostra, perché state facendo un lavorone e si percepisce anche a distanza tutta la passione e la professionalità che ci mettete. 
Ci faceva piacere darvi un nostro feedback, per cui oggi ho guardato la nuova homepage con i colleghi, tra cui la webmaster del nostro sito istituzionale, per potervi dare delle indicazioni anche da parte nostra.
Prima domanda: in homepage non c'è una foto per scelta o per impossibilità? A nostro avviso una foto di contesto nella parte alta dell'homepage ci vorrebbe. 
In ottica di rendere l'homepage più "attraente" ci immaginavamo una struttura di questo tipo:
- foto
- titolo "terremoto centro italia"
- breve descrizione di 3-4 righe (questo perché temiamo che chi entra per la prima volta sul sito non capisca esattamente di cosa si tratta)
- eviteremmo di usare la parola "progetto" all'interno di questa breve descrizione: risulta troppo "burocratica"
- sotto i bottoni come avete messo adesso. Al posto di "ultimora" forse meglio "news" come era prima, e al posto di "fabbisogni" qualcosa tipo "richieste". 
  Infine rimetteremmo in fondo un paio di storie come erano messe nella prima versione dell'homepage e sposteremmo tutto il bollettino dall'homepage, perché così ci sembra venga molto pesante. Meglio in una pagina dedicata.
  Fatemi sapere cosa ne pensate e cosa permette il sito a livello di struttura.
  Spero i nostri suggerimenti possano esservi utili. Ancora complimenti per la passione e dedizione che mettete in questo progetto.
  ciao
  Asia

**Comment by ghost** [comment]
@asiadag questa issue è stata chiusa. Copio e incollo la tua richiesta su una nuova issue, così da continuare su un nuovo thread #298 .
