### ISSUE TITLE
Nuova Gestione Bollettino

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#287]
A seguito della messa a punto del #242 segnalo che il bollettino può essere gestito da ora in poi come issue github con una label apposita. Tutti gli issue possono diventare cioè anche parte del bollettino basta apporre la label sull'issue stessa aggiungendola a quelle già presenti.

Ad esempio 
https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/414

Questo lo dico soprattutto per gli affezionatissimi del tema che sono @dontyna e @aborruso ;-) che dite?

**Comment by cristigalas** [comment]
Anche a me il bollettino piace tanto, quindi ottima iniziativa!

**Comment by aborruso** [comment]
@iltempe molto comodo e con le API di githib è tutto facile.

Con curl si prende tutto e si estrae solo ciò che è `Accettato` e marcato come `Bollettino`:

``` bash
curl -s "https://api.github.com/repos/emergenzeHack/terremotocentro_segnalazioni/issues" |  \
jq '. |= map(select(.labels[].name == "Accettato"))   | .  |= map(select(.labels[].name == "Bollettino"))  | [.[] | {title:.title,created_at:.created_at,body:.body,url:.html_url}]' |  \
sed 's/<pre><yamldata>//g' | sed 's/<\/yamldata><\/pre>//g' | \
in2csv -f json > "$output/gitubissuestmp_segnalazioni.csv"
```

E si tira fuori (è solo un esempio) un CSV https://gist.github.com/aborruso/2423c867d9287d9c7c585cb0af1c9ba6

Ottimo

**Comment by iltempe** [comment]
ok. mi pare molto semplice. potremmo fare quindi uno script a cui passare come parametro una label e da quello tirare fuori csv solo di quelle segnalazioni o anche un feed rss. che dici?

**Comment by marco-acorte** [comment]
potremmo usare Trello integrato con github
https://github.com/integrations/trello

**Comment by aborruso** [comment]
@iltempe possiamo fare mille cose, ma non capisco cosa serve più.

Assegnami un task circoscrivendo una o più cose da fare e mi attivo.

Grazie

**Comment by iltempe** [comment]
@aborruso secondo me dobbiamo predisporre i canali Twitter e Telegram affinchè il Bollettino continui a funzionare automaticamenteanche con il sistema issue github (facendo riferimento a issue Accettati e che abbiano una label Bollettino). ti assegno questo issue. se usi degli script dimmelo che cerchiamo il modo metterli condivisi su heroku.

**Comment by aborruso** [comment]
Ecco il nuovo feed RSS direttamente dalle ISSUE del repo delle segnalazioni http://feeds.feedburner.com/BollettinoDelProgettoTerremotocentroitalia

Come href ho inserito il link alla issue, perché non sempre è presente un link dentro la segnalazione.

@iltempe prima di attivare gli automatismi, farei un test. Io mi sono messo già in ascolto

**Comment by iltempe** [comment]
ottimo @aborruso. attendo qualche giorno prima di chiudere e vediamo come procede. grazie

**Comment by aborruso** [comment]
@iltempe ho modificato l'href, adesso punta correttamente alla pagina del sito e non alla segnalazione sul repo http://feeds.feedburner.com/BollettinoDelProgettoTerremotocentroitalia

**Comment by iltempe** [comment]
chiudo.
