### ISSUE TITLE
Rivedere design di issue.html

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#289]
il layouts issue.html ha bisogno di essere rivisto come design. Non sarebbe male incasellare tutto in una "scheda" e inserire tutti i pulsanti di share sui social. che dite?

**Comment by mfortini** [comment]
In funzione del contenuto dell'array page.issue.labels si potrebbe cambiare
leggermente il layout.
I dati si trovano come membri dell'oggetto page.issue.data

Il gio 15 set 2016, 22:13 Iltempe notifications@github.com ha scritto:
