### ISSUE TITLE
Selezionare tool per ottimizzare la gestione delle issue su github

### ISSUE THREAD

**Issue by mcicolella** [emergenzeHack/terremotocentro#295]
Per chi ha esperienza di kanban posso segnalare waffle.io che permette di ottimizzare la gestione delle issue su github in modo da avere in una board lo stato delle varie attività e migliorare i vari flussi di lavoro. Per chi volesse avere un'idea di base c'è un interessante articolo https://www.ideato.it/technical-articles/waffle-io-la-kanban-board-ama-github
Inoltre waffle è free.

**Comment by aborruso** [comment]
Aggiungo allora l'ottimo **zenhub** https://www.zenhub.com/

**Comment by mcicolella** [comment]
Visto che ci sono diversi prodotti sul mercato forse conviene modificare il titolo della issue in qualcosa di più generico

**Comment by aborruso** [comment]
@mcicolella ottima idea!

**Comment by iltempe** [comment]
Ciao @mcicolella e @aborruso proprio ieri ho letto che github ha introdotto la gestione dei progetti che dovrebbero essere un modo anche per gestire gli issue e assegnare azioni. ecco qua https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features ci sarebbe da sperimentarlo un po'...

**Comment by mcicolella** [comment]
Molto interessante! Non sapevo di questa novità di Github. Proverò a testarlo con un mio progetto open source. A prima vista ricalca molto i tool sopracitati e come questi (almeno waffle) non supporta le swimline.

**Comment by mcicolella** [comment]
Allora ho provato un po' "Projects" di Github. E' carino ma richiede di creare le diverse colonne, di aggiungere manualmente le varie issue che poi si possono spostare. Non ci sono ulteriori strumenti.
Ecco un esempio https://github.com/freedomotic/freedomotic/projects/1
Ho fatto invece un test con waffle ed ecco il risultato https://waffle.io/emergenzeHack/terremotocentro
L'inserimento avviene in maniera automatica almeno per Backlog e Done.
Naturalmente, registrandosi, si accede ad altre funzioni e si può interagire con Github da cui legge il flusso per modificare/aggiungere issue. 
I grafici possono fornire un'idea del lavoro fatto
https://waffle.io/emergenzeHack/terremotocentro/metrics/throughput utilizzando i vari filtri

**Comment by iltempe** [comment]
attualmente è stato attivato project da @favoeva . per ora chiudo.
