### ISSUE TITLE
Homepage jumbotron con foto e cambio label

### ISSUE THREAD

**Issue by ghost** [emergenzeHack/terremotocentro#298]
## Riporto per intero i buoni consigli di @asiadag rif #285 

ciao ragazzi, 
mi inserisco nella conversazione. Sono la communication officer di ActionAid. Prima di tutto vi faccio davvero i complimenti da parte mia/nostra, perché state facendo un lavorone e si percepisce anche a distanza tutta la passione e la professionalità che ci mettete. 
Ci faceva piacere darvi un nostro feedback, per cui oggi ho guardato la nuova homepage con i colleghi, tra cui la webmaster del nostro sito istituzionale, per potervi dare delle indicazioni anche da parte nostra.
Prima domanda: in homepage non c'è una foto per scelta o per impossibilità? A nostro avviso una foto di contesto nella parte alta dell'homepage ci vorrebbe. 
In ottica di rendere l'homepage più "attraente" ci immaginavamo una struttura di questo tipo:

foto
titolo "terremoto centro italia"
breve descrizione di 3-4 righe (questo perché temiamo che chi entra per la prima volta sul sito non capisca esattamente di cosa si tratta)
eviteremmo di usare la parola "progetto" all'interno di questa breve descrizione: risulta troppo "burocratica"
sotto i bottoni come avete messo adesso. Al posto di "ultimora" forse meglio "news" come era prima, e al posto di "fabbisogni" qualcosa tipo "richieste". Infine rimetteremmo in fondo un paio di storie come erano messe nella prima versione dell'homepage e sposteremmo tutto il bollettino dall'homepage, perché così ci sembra venga molto pesante. Meglio in una pagina dedicata. Fatemi sapere cosa ne pensate e cosa permette il sito a livello di struttura. Spero i nostri suggerimenti possano esservi utili. Ancora complimenti per la passione e dedizione che mettete in questo progetto. ciao Asia

**Comment by nelsonmau** [comment]
grazie @tailot 
@asiadag: riesci a fare un wireframe o mockup di ciò che intendi?
inoltre: riesci a scrivere una descrizione alternativa?

grazie! :)

**Comment by ghost** [comment]
Una cosa che possiamo fare senza troppa fatica è inserire l'immagine allargata e aggiungere l'effetto parallax con il testo:
![parallax](https://cloud.githubusercontent.com/assets/330838/18603348/efabd8a2-7c70-11e6-8f23-4b343adceec4.png)

Prima di fare la modifica ci serve l'immagine e il testo da associare.

Cosa ne pensate ?

**Comment by mfortini** [comment]
Per me perfetto: attenzione che il template prevede già un'opzione bigimage che si può aggiungere alla pagina e configura appunto un jumbotron, se utile partiamo da lì.

**Comment by nelsonmau** [comment]
non è male per niente. @lorenzoperone ci consigli tu una immagine da utilizzare?
dobbiamo poi inoltre definire per bene i testi

**Comment by iltempe** [comment]
@lorenzoperone a me piace. Forse per l'immagine converrebbe andare su foto scattata da noi o di pubblico dominio

**Comment by ghost** [comment]
Se serve vi segnalo questo fantastico servizio https://pixabay.com pieno  di immagini ad alta risoluzione di pubblico dominio.
@mfortini si l'effetto finale sarà simile a quello visto nel sito ufficiale dell'autore del tema: http://deanattali.com/

**Comment by nelsonmau** [comment]
grazie @tailot, il lo uso partendo da questo motore di ricerca http://search.creativecommons.org/?lang=it

@iltempe esatto, il meglio è mettere una foto tra quelle 'nostre' dai luoghi del sisma. Aspettiamo un attimo @lorenzoperone che sta guarendo da una febbrina dai

**Comment by asiadag** [comment]
ciao ragazzi, 
posso farvi avere un wireframe domani nel pomeriggio. per la foto pensavo che sì, potreste usarne una delle vostre, per quello ve la proponevo. renderebbe il sito sicuramente più appetibile. la descrizione poi secondo me è la parte più importante: chi entra e non ne sa nulla deve subito capire cosa offre il sito. 
a domani,
ciao
Asia

**Comment by nelsonmau** [comment]
grazie @asiadag! benissimo per il wireframe e per il vostro contributo nel fare una proposta di descrizione! 
le foto di progetto sono su flickr a questo indirizzo https://www.flickr.com/groups/3003557@N20/
provate a indicarne voi alcune?

**Comment by asiadag** [comment]
ciao @nelsonmau ,
ne prenderei una con le macerie, più che una dei campi. qualcosa tipo questa: https://www.flickr.com/photos/144881851@N07/29033912610/ non so se ha una risoluzione sufficiente per il sito però...valutate questo aspetto e nel caso sceglietene pure un'altra sullo stesso stile.

**Comment by ghost** [comment]
@asiadag la foto ha una risoluzione un po bassa. L'ideale sarebbe prendere una foto con un width più grande. L'altezza è trascurabile, conviene comunque "cropparla" per non appesantire la pagina.

**Comment by asiadag** [comment]
@tailot non so il sito che risoluzione vi richiede, immaginavo quella fosse piccola... ne vedi di utilizzabili tra quelle con le macerie? (wireframe in arrivo a breve)

**Comment by asiadag** [comment]
![hp terremoto centroitalia](https://cloud.githubusercontent.com/assets/21690871/18714409/e9c29856-8015-11e6-8421-0505acc4b029.jpg)

Cari,
ecco il wireframe che ci avevate chiesto. La scritta "terremoto centro Italia" vorremmo che (a differenza di questo schema fatto rapidamente) fosse sulla foto, come nell'esempio di @tailot poco sopra per intendersi. 

I riquadri sotto (dove ci sono due segnalazioni al momento) sono messi per far capire la grandezza, ma lì dentro ci immaginiamo le ultime due news come leggete nella nota. Il bollettino infatti secondo noi va rimosso dall'HP.

Per la foto in base alla disponibilità potete immaginarla così oppure a tutto schermo (sarebbe meglio).

Speriamo di esservi stati utile, continuiamo a seguire la conversazione. 
ciao

**Comment by iltempe** [comment]
scusate la foto si è trovata?

**Comment by lorenzoperone** [comment]
ciao, ora mi metto alla ricerca, non so se tra quelle che abbiamo ce ne sia una adatta, vi faccio delle proposte qui

**Comment by lorenzoperone** [comment]
@iltempe @nelsonmau @asiadag @tailot 
tra le foto caricare su Flickr nel nostro profilo non ne abbiamo nessuna con risoluzione sufficente, piuttosto che cercare in rete foto con licenza compatibile io farei un piccolo contest attraverso la nostra pagina Facebook, io mi offro di gestire la cosa, che ne pensate? Vi faccio una proposta dettagliata?

**Comment by nelsonmau** [comment]
@lorenzoperone sì, per me ottima idea e sarebbe figo anche farsi dare da tutti foto in CCby anche per arricchire l'album di TCI
vai!

**Comment by lorenzoperone** [comment]
@nelsonmau quelle del gruppo le possiamo utilizzare

**Comment by iltempe** [comment]
@lorenzoperone non perderei molto tempo a dettagliare la tua idea che è ottima secondo me. Facciamo un post da condividere per call to action! grazie!

**Comment by lorenzoperone** [comment]
scritto post per il lancio del contest, appena @iltempe mi abilita in scrittura sul repo lo uppo.

**Comment by lorenzoperone** [comment]
La bozza è qui https://github.com/lorenzoperone/lorenzoperone.github.io/blob/master/post/2016-9-23-Lancio-contest-fotografico.md

**Comment by iltempe** [comment]
in ogni caso a questo proposito vorrei fare su un fork uno switch di tema. ad esempio muovermi su una cosa cosi http://jekyllthemes.org/themes/ion/ @tailot proviamo?
