### ISSUE TITLE
Pulsante "CONDIVIDI I TUOI DATI"

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/terremotocentro#299]
Proposta: Visto che ci sono delle raccolte dati organizzate da gruppi chiusi (es. coordinamento volontariato marche censisce cosa fanno operatori; gruppo X censisce attività economiche; gruppo Y ha la mappa dei campi) = sarebbe possibile inserire un pulsante "condividi i tuoi dati/la tua mappatura"? Con vicino una mini spiegazione del perché è importante integrare i dati, del perché è importante che siano open e di cosa deve fare il data owner per agganciarsi a TCI e ai nostri dati già open? Che ne pensate?

**Comment by aborruso** [comment]
@chiccap apri un tema utile e importante. Sicuramente dobbiamo preparare una pagina da cui si chiaro quali sono i dati TCI, quali licenza open viene adottata, e lo schema dei dati.

Io nei prossimi giorni inizio a lavorarci

**Comment by iltempe** [comment]
io la trovo una cosa molto utile che spinge anche verso il far capire quanto sia appunto importante rendere disponibili le informazioni in queste situazioni. @aborruso se ti serve mano per la parte di descrizione degli schemi sto qua. per le licenza dei contenuti credo che qualcosa sia già nelle note legali del sito ma non so dire se si riferisce proprio ai "dati grezzi"

**Comment by alesarrett** [comment]
Per i dati geografici sarebbe bello riuscire a creare (per i dati significativi) un flusso anche verso Openstreetmap, in modo da far sì che OSM sia velocemente aggiornata.
Per quanto riguarda la licenza, in particolar modo per i dati, credo che la CC-BY 4.0 sia più adatta della 3.0 che ho visto nelle note legali. Ma @aborruso ha sicuramente più esperienza in questi contesti.

**Comment by iltempe** [comment]
@alesarrett quando parli di flusso verso OSM avevi in mente qualche idea?

**Comment by alesarrett** [comment]
Dipende molto dai dati di cui stiamo parlando, ma se ad es. ci sono dati geolocalizzati su nuovi campi, o quando arriveranno le casette, oppure l'apertura di nuove attività economiche o luoghi di incontro ecc., si potrebbe creare un flusso verso Openstreetmap, ad es. tramite la creazione (non ho idea se si possa automatizzare o se sia la scelta migliore) di note (http://wiki.openstreetmap.org/wiki/Notes) che poi i mappatori OSM potrebbero integrare nella mappa.

**Comment by c83n** [comment]
in generale aspettiamoci dati sporchi e non georef dove ci sara' al limite
indirizzo
andranno puliti e spiegato al provider come inviarne di migliori
my2cents

Il mercoledì 21 settembre 2016, Alessandro Sarretta <
notifications@github.com> ha scritto:

**Comment by iltempe** [comment]
per quanto riguarda i dati di TCI per il momento è stata creata questa pagina http://terremotocentroitalia.info/opendata/

**Comment by c83n** [comment]
grazie mat mi pare ottima!

Il domenica 2 ottobre 2016, Iltempe notifications@github.com ha scritto:

**Comment by chiccap** [comment]
@iltempe bella!

**Comment by alesarrett** [comment]
Riprendo il mio commento sulla licenza: c'è qualche motivo per mantenere la CC-BY 3.0? Visto tra l'altro che si parla di dataset, la 4.0 è sicuramente più indicata perché gestisce i "Sui generis database rights" che la 3.0 invece mi pare escludesse.

**Comment by iltempe** [comment]
@alesarrett  non c'è un motivo particolare se non che sulle note legali è stata per il momento messa quella. si può cambiarla.
