### ISSUE TITLE
Link twitter sbagliato nella pagina /aiuto/

### ISSUE THREAD

**Issue by ebergam** [emergenzeHack/terremotocentro#3]
Ciao ragazzi,
il link twitter [qui](https://emergenzehack.github.io/terremotocentro/aiuto/), reindirizza a https://emergenzehack.github.io/terremotocentro/aiuto/twitter.com/terremotocentro. Credo basti aggiungere https:// perché il motore lo rigiri bene, se no lo considera interno.

**Comment by iltempe** [comment]
ok. fatto grazie.
