### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by cattivik74** [emergenzeHack/terremotocentro#300]
Sviluppo java, anche android. Simpatizzante informatici senza frontiere. Sono a vostra disposizione

**Comment by iltempe** [comment]
ciao! hai fatto un giro tra gli issue?

**Comment by cattivik74** [comment]
Ciao, 
si ho controllato, ma a parte il discorso soap per gli sms non vedo nulla di attinente 
alla mia figura.
Pensavo che potrei realizzare un’app android che comunica ad un server le posizioni gps 
di coloro che l’hanno installata, in modo da avere immediatamente, nel malaugurato
caso di una tragedia del genere, una mappa approssimativa dei posti da controllare in 
prima battuta.
L’app ovviamente invierebbe solo le coordinate gps al server, nessun altro dato delle persone
che hanno deciso di installarla, e girerebbe sempre sul telefonino come servizio, mandando il dato 
anche una volta ogni ora o mezz’ora.
Appena si uniscono al gruppo uno sviluppatore ios e uno windows mobile potremmo convertirla 
nelle altre piattaforme.
Lo spazio su playstore posso metterlo a disposizione io, per il server potremmo chiedere alla protezione
civile o all’ingv.
Che ne pensate?

**Comment by nelsonmau** [comment]
@cattivik74 non sembra per nulla una brutta idea. Hai guardato tutta la parte relativa alle segnalazioni con bot telegram? le due cose si intrecciano, si potrebbe studiare un modo per ottenere un servizio migliore o più ampio rispetto a quello attivo

**Comment by francescolovecchio** [comment]
Ciao, io potrei dare una mano per iOS. (Da martedì)

**Comment by iltempe** [comment]
@francescolovecchio @cattivik74  c'era già qualcuno che stava lavorando ad una app mobile ma non so dove sia arrivato. conviene chiedere nel gruppo telegram per capire se la cosa è ferma o si può collaborare. grazie

**Comment by francescolovecchio** [comment]
@iltempe va bene, grazie
