### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by francescolovecchio** [emergenzeHack/terremotocentro#302]
Disponibile dal 20/09

**Comment by iltempe** [comment]
ciao hai fatto un giro sugli issue?

**Comment by francescolovecchio** [comment]
Ciao, ho solo esplorato rapidamente per capire come siete organizzati. Sono un programmatore e voglio darvi una mano da martedì

**Comment by iltempe** [comment]
Ok! Ti aspettiamo!

**Comment by nelsonmau** [comment]
bene, risolto allora :)
