### ISSUE TITLE
Pagina Fabbisogni: aggiungere descrizione con info + filtro ricerca

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#303]
qui l'url http://terremotocentroitalia.info/fabbisogni/

chi scrive una descrizione? @dontyna ?

io metto il filtro di ricerca a breve

**Comment by psykola** [comment]
se la ricerca non ha prodotto risultati, forse dovrebbe apparire una scritta "non è stato trovato alcun annuncio con la parola xxx" o semplicemente "la tua ricerca non ha prodotto risultati
