### ISSUE TITLE
Uniformare ricerca Indirizzo nel form delle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#306]
Esattamente come fatto da @mfortini per 
https://terremotocentroitalia.herokuapp.com/segnalazioni/alloggi.html
inserire la gestione della ricerca indirizzo anche per 
https://terremotocentroitalia.herokuapp.com/segnalazioni/fabbisogni.html
https://terremotocentroitalia.herokuapp.com/segnalazioni/donazioni.html
https://terremotocentroitalia.herokuapp.com/segnalazioni/contatti.html

**Comment by drizzt** [comment]
Dovrebbe essere a posto ora
