### ISSUE TITLE
Flussi informativi: mappatura e riorganizzazione

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#309]
Ciao a tutti, 

Vorrei provare a fare il punto sui flussi informativi presenti, crearne uno schema (tipo sitemap), vedere se ci sono ridondanze e avviare una riorganizzazione (se necessario, se possibile).

@dontyna e @favoeva: mi date una mano? È possibile fare un elenco complessivo dei flussi informativi?

Al momento a me risultano

**Flussi informativi in entrata**: accessibili da [Segnala](http://terremotocentroitalia.info/aiuto/).

**Flussi informativi in uscita**
- pagina [**News**](http://terremotocentroitalia.info/news/): c'è un feed con varie fonti all'interno creato da @aborruso (seconda parte della pagina) + un flusso iniziale (non ne conosco la fonte)
- pagina [**Alloggi**](http://terremotocentroitalia.info/alloggi/): c'è un flusso con le offerte di ospitalità
- Flusso [**HomePage**](http://terremotocentroitalia.info): c'è un flusso che pare diverso dai precedenti due

È una ricostruzione completa? Manca qualcosa?
È possibile dettagliare queste info (fonti? chi se ne occupa?) e provare a capire se possibile semplificare? / cc @iltempe @mfortini @aborruso @Pinzauti @tailot ? altri da taggare e coinvolgere?

**Comment by dontyna** [comment]
Come **flussi in uscita** ci sono anche:
- pagina [blog](http://terremotocentroitalia.info/post/)
- pagina [storie](http://terremotocentroitalia.info/storie/) 

Potrebbero essere riuniti in una pagina unica ("blog", mentre "storie" può essere un tag).

Nella **pagina** [**news**](http://terremotocentroitalia.info/news/) per chiarezza dell'utente andrebbe esplicitato che di tipo di news si tratta e qual è la fonte.

Altri **canali di flussi in uscita** sono:
- il canale [Telegram](https://telegram.me/terremotocentroitalia)
- l'account [Twitter](https://twitter.com/terremotocentro)
- il gruppo [Facebook](https://www.facebook.com/groups/1758670357733881/) (funziona da fonte e anche da megafono)
- un account [Medium](https://medium.com/terremotocentroitalia) (si potrebbe riversare in "blog"?)

**Comment by nelsonmau** [comment]
@dontyna se mi segnali un tool con cui disegnare uno schema, disegno uno schema :)
se non ne conosci, faccio a mano...

**Comment by favoeva** [comment]
@nelsonmau può essere utile? https://bubbl.us/

**Comment by nelsonmau** [comment]
yes @favoeva. Rispetto alle cose descritte su da me e @dontyna ti risulta che ci sia altro? io faccio un po' fatica ad orientarmi...

**Comment by favoeva** [comment]
La fonte del flusso iniziale di news sono le issue con label bollettino

**Comment by favoeva** [comment]
domani sera hangout gestione segnalazioni h 21.30 : cercheremo di definire al meglio utilizzo label per issue e (quindi) anche automatismi pubblicazione . Che ne dite @nelsonmau @dontyna se affrontiamo la site map come step successivo?

**Comment by favoeva** [comment]
Non stasera ;) domani

**Comment by dontyna** [comment]
Si, uno schema è utile anche all'utente finale.

**Comment by favoeva** [comment]
@annaluciont aveva aperto questa issue per creazione nuove label e loro utilizzo per flussi in uscita automatici e pubblicazioni manuali da parte del media team 
 https://github.com/emergenzeHack/terremotocentro/issues/314

**Comment by favoeva** [comment]
@aborruso ha fatto questo feed rss per tutte le issue con label bollettino, contiene href che punta al permalink (molto utile per tenere d'occhio la situazione di ciò che è arrivato nelle news sul sito e verificare nella issue git se è ancora da rilanciare sui nostri canali social. Se rilanciamo ricordiamoci di togliere la label 'da pubblicare su fb' 'da pubblicare su twitter')  http://feeds.feedburner.com/BollettinoDelProgettoTerremotocentroitalia

**Comment by mfortini** [comment]
Mi inserisco al volo. Vedo che per esempio per una segnalazione si parla di aggiungere label come "da pubblicare su fb", per poi toglierla quando pubblicata: volendo fare i precisini il modo corretto per gestire questa cosa è, come vedo ad esempio che @favoeva fa già, creare una nuova issue che faccia riferimento alla issue precedente, e poi chiudere quella. Il motivo è che la issue originale vive di vita propria (es è un bisogno), e la sua pubblicazione diventa un issue correlata, che si chiude quando la pubblicazione è avvenuta, mantenendo tracciata la cosa. Se mettiamo una label e la togliamo, la storia della pubblicazione rimane sepolta nella issue, mentre nell'altro caso è possibile vedere quante issue "pubblica su..." sono state create, quante sono aperte, quante chiuse.

**Comment by epoeta** [comment]
Sarebbe opportuno che nel repo affluissero non solo segnalazioni via webform, ma anche tutto il feed da gruppo Fb cosicché sia possibile processare in maniera coordinata le info condivise su di esso (tranne quelle, ovviamente, che saranno pubblicate da terremotocentroitalia e che creerebbero un loop). Stesso discorso per le menzioni o gli hashtag #terremotocentroitalia su Twitter. 
Vantaggi: 
1. sostituire il Gsheet di coordinamento con il quale il Media Team si autocoordinava nelle prese in carico di quanto appariva sul gruppo Fb per poi inserirlo nelle varie sezioni di terremotocentroitalia.info;
2. evitare a chi lavora sulla repo che alimenta il sito e i vari canali di tenere troppe finestre aperte, rendendo possibile/agevole la gestione con una qualsiasi app per GitHub (es. OcroDroid ecc.) anche a chi non sta a un desktop;
3. poter verificare con la search di GitHub attraverso le label (o l'assenza di esse) quali elementi informativi restano da trattare prima di metterli in circolazione sui vari canali.

**Comment by mfortini** [comment]
Sono d'accordo, si creano issue "grezze" dai feed e le si tagga in modo che
qualcuno le moderi o le chiuda. Resta il fatto che però per formattare bene
una issue è meglio usare il webform. Forse è possibile fare una webform che
semplicemente impagini il testo da copiare e incollare nella issue in modo
da rendere facile aggiornare la issue da fb perché sia nel formato corretto?

Il dom 18 set 2016, 11:38 plurale notifications@github.com ha scritto:

**Comment by iltempe** [comment]
@epoeta @mfortini 
vedo due criticità:
- rimettere a mano gli issue può causare problemi di formattazione
- se automatizziamo secondo me gli issue esplodono in termini di numero e diventerà più complesso gestirli.

**Comment by epoeta** [comment]
@mfortini @iltempe a ben vedere abbiamo due grossi canali di input davanti: uno preformattato (si spera, perché le entry qualcuno potrebbe metterle in maniera molto personalizzata, si tratta di segnalazioni infatti), un altro grezzo (Facebook, Twitter eccetera). Il secondo potrebbe far esplodere GitHub creando disordine. Per questo secondo serve dunque una piattaforma unitaria di "compensazione" a interfaccia semplificata (sviluppare una app costa troppo tempo e fatica, ma una webapp o un adaptative si potrebbe pensare), attraverso la quale il MediaTeam giri i contenuti selezionati e riformattati alla repo principale.
Come organizzare però questa piattaforma che coaguli tutti i contributi grezzi?
La struttura dei post Facebook e Twitter ha sotto uno schema opengraph comune, lo si potrebbe sfruttare per dare formalizzazione e consentire un rovesciamento editato?

**Comment by favoeva** [comment]
bisogna tener presente anche questa issue Sezione "VUOI DONARE" - riorganizzazione https://github.com/emergenzeHack/terremotocentro/issues/310

**Comment by iltempe** [comment]
torno intanto sul topic dell'issue. @nelsonmau lavoro ad uno schema e poi lo condivido.

**Comment by iltempe** [comment]
ho iniziato a disegnare una mappa
https://bubbl.us/?s=7177445#MzYwNDQ5Mi83MTc3NDQ1LzhjNTk2Y2UwYTMxOTUwNWIzOGQ3MmQ1OWI5NGI2YzNj?X

è tutto in progress ma se avete da segnalarmi qualcosa dite pure qui sotto.

**Comment by favoeva** [comment]
@iltempe ottimo, mi torna tutto. solo pensavo: può essere utile creare sezione UTILITA' (nome brutto ma per capirci) con dentro: 
- mappe 
- dati (tra cui anche VITTIME) 
- link a archivio doc TCI su archive
- il flusso dal gruppo flickr (se diventa archivio immagini)

vi sembra possa aver senso?

**Comment by favoeva** [comment]
Aggiornamento: grazie ad @aborruso , label bollettino manda di nuovo tweet automatico (la label 'da pubblicare tw' va quindi eliminata ) #314

**Comment by nelsonmau** [comment]
@asiadag ti segnalo anche questa discussione sui flussi informativi. L'ottimo @iltempe ha fatto questa ricostruzione qui https://bubbl.us/?s=7177445#MzYwNDQ5Mi83MTc3NDQ1LzhjNTk2Y2UwYTMxOTUwNWIzOGQ3MmQ1OWI5NGI2YzNj?X

ci date un'occhiata e un feedback?

Anche con @dontyna e @favoeva si pensava che forse sarebbe meglio semplificare e aggregare in modo da evitare il rischio di disperdere notizie ed energie.
grazie!

**Comment by iltempe** [comment]
@nelsonmau @asiadag la mappa è in progress... conto di finirla in nottata ;-)

**Comment by asiadag** [comment]
ok ottimo x la mappa. ci sembra ok. immagino che nelle donazioni inseriate sia possibilità di cash che di oggetti. domanda? perché c'è sia "news" che "blog" ? forse sono accorpabili.

**Comment by iltempe** [comment]
mappa aggiornata allo stato attuale delle cose. dite la vostra. https://bubbl.us/?s=7177445#MzYwNDQ5Mi83MTc3NDQ1LzhjNTk2Y2UwYTMxOTUwNWIzOGQ3MmQ1OWI5NGI2YzNj?X

**Comment by psykola** [comment]
![mappatci](https://cloud.githubusercontent.com/assets/22292017/18678677/18d7dbb0-7f5d-11e6-9d4a-12e77b65fff3.jpeg)  
Per me dal punto di vista dell'utente dovrebbe essere così il sito

**Comment by iltempe** [comment]
@favoeva condivido. possiamo fare una sezione utilità con codeste voci certamente ma forse dovremmo discutere allora tutta la struttura dei menu dato che c'è anche la proposta di @psykola da valutare.

**Comment by iltempe** [comment]
flussi documentati nella mappa.
