### ISSUE TITLE
Sezione "VUOI DONARE" - riorganizzazione

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#310]
Idee per rendere più utile la sezione "**Vuoi donare**":
- **[Risorse disponibili](http://terremotocentroitalia.info/risorse-disponibili/)** è in realtà una pagina che andrebbe sotto "Hai bisogno": indica i beni che enti e persone hanno messo a disposizione dei luoghi colpiti e può essere utile a enti e persone che cercano oggetti e servizi. L'elenco dovrebbe essere organizzato per "luoghi", e per tipologia di "materiali". Il titolo delle segnalazioni dovrebbe essere il più accurato possibile, es "scarpe", "cibo", ... 
- **[Raccolte fondi](http://terremotocentroitalia.info/fondi/)** sarebbe utile organizzarlo in categorie (enti pubblici, ong, privati, ecc)
  -**[Fabbisogni](http://terremotocentroitalia.info/fabbisogni/)** anche qui un'organizzazione per luoghi può facilitare la consultazione.

**Comment by cristigalas** [comment]
Condivido la tua proposta @dontyna ma mi chiedevo se possa avere un senso prevedere in "Vuoi donare", oltre al la voce "raccolta fondi", anche quella "raccolta beni' per chi voglia o possa offrire qualcosa. Forse ora che gli sfollati lasciano i campi, dove non poteva entrare nulla, questa voce potrebbe essere utile. Ho visto ad es. associazioni che raccolgono beni "mirati" come scarpe e indumenti invernali... Ma forse è superflua, ragioniamoci insieme...

**Comment by iltempe** [comment]
@dontyna riorganizzare per luoghi può essere sempre fatto se ovviamente i dati sono geotaggati. In quel modo riusciamo a raggrupparli per zone. Non credo tutti adesso lo siano ancora ma si può iniziare a riorganizzare in questo senso.

**Comment by iltempe** [comment]
visto che abbiamo riorganizzato un po' tutto, chiudo.
