### ISSUE TITLE
Twitter: fermare automatismi

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#311]
Il social media team si gestisce in maniera automa (altrimenti il rischio è avere tweet di questo tipo: https://twitter.com/terremotocentro/status/777076480987856896)

**Comment by epoeta** [comment]
Concordo su tutta la linea. Lascerei automatici solo i tweet su scosse e su mobilità (Waze).

**Comment by aborruso** [comment]
@dontyna questo è avvenuto perché per l'automatismo di pubbliazione dall'account twitter del Comune_Amatrice, che non avevo un controllo sull'inserimento dell'URL al tweet.

L'ho corretto.

Se voi "socialcosi" mi confermate lo spengo.

Io terrei attivo anche il bollettino

**Comment by epoeta** [comment]
Converrebbe far confluire tutti questi automatismi nel repo. Insomma una sorta di segnalazione automatica. Poi si decide se accettare, aggiustare e/o ridiffondere (anche via Twitter).

**Comment by aborruso** [comment]
@epoeta si sta andando in questa direzione. Il bollettino a breve uscirà nella nuova versione, e pescherà dal repo a partire da tutte le issue marcate come "Bollettino" e "Accettato"

**Comment by iltempe** [comment]
@dontyna  io vorrei tenere attiva la label bollettino in automatico (solo quella) per twitter e telegram. In ogni caso la label sarebbe posta in modo manuale quindi abbiamo un controllo sull'invio automatico di informazioni.

**Comment by cristigalas** [comment]
Sono d'accordo @dontyna ma dovremo fare attenzione al testo cioè al numero dei caratteri perché altrimenti torniamo al problema dei tweet tronchi... Tuttavia, se il sistema prende solo i titoli dovrebbe essere sufficiente, credo.

**Comment by aborruso** [comment]
Ok, domani attivo pubblicazione automatica di tutto ciò che è marcato come "Bollettino" e "Approvato" su twitter e su canale Telegram.

**Comment by epoeta** [comment]
@aborruso se hanno etichetta per twitter o facebook ;-) quanto ai titoli twittabili, per esperienza dico che funzionano se fino a 75 caratteri e il resto per hashtag e shortlink

**Comment by aborruso** [comment]
@epoeta trovo come label "Pubblicare su TW" 

La label "Facebook" immagino non sia uguale a "Pubblicare su Facebook".

Chiedo a @dontyna, te, @iltempe e @cristigalas 

Domanda:
-  sul canale Telegram si pubblica in automatico tutto ciò che è marcato come "Bollettino" e "Accettato"?
-  sul twitter si pubblica in automatico tutto ciò che è marcato come "Bollettino", "Accettato" e "Pubblicare su TW"?

A me, sembrerebbe avere più senso pubblicare su Telegram e twitter tutto ciò che è marcato come "Bollettino" e "Accettato", perché se ha senso su Telegram, ha senso anche su twitter. 

In ogni caso mi fermo e domani non faccio nulla. Aspetto una proposta di chiusura :)

**Comment by cristigalas** [comment]
Anch'io credo che se marcato con BOLLETTINO e ACCETTATO possa andare diretto su Twitter e Telegram.  Teniamo la label "da pubblicare su Twitter" nel caso ci siano altri tipi di segnalazione che non vanno su bollettino ma può essere utile tuittare ad es. tagga no account specifici.

**Comment by iltempe** [comment]
@aborruso sono d'accordo con te. direi di pubblicare in automatico su twitter e telegram solo quello che è marcato con accettato e bollettino. Se ha anche altre label non prendiamole in considerazione per gli automatismi.

**Comment by annaluciont** [comment]
Domanda: come evitiamo di postare la stessa cosa se non ce lo diciamo?

**Comment by aborruso** [comment]
@annaluciont nessuno posta più nulla  su twitter e sul canale telegram, in merito al bollettino: avverrà in automatico.

Poi ciascuno potrà ripostare le notizie del bollettino dove riterrà opportuno.

**Comment by annaluciont** [comment]
Wow, mi taccio.

**Comment by aborruso** [comment]
Ok, chiudo
