### ISSUE TITLE
In alcune segnalazioni non è visibile il testo del campo descrizione

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#312]
Sul sito alcune segnalazioni non hanno il testo nel campo 'descrizione', eppure il campo su Github è compilato e pare inserito con la giusta sintassi. In particolare vedi segnalazioni: #231 #380 #414 #428 #571 (ma può darsi che ce ne siano altri).

**Comment by cristigalas** [comment]
Dopo attenta analisi 😜 credo di aver capito cosa non va in queste segnalazioni: ad ogni apostrofo va aggiunta una virgoletta singola [']! Probabilmente qualcuno aveva tolto le virgolette, credendo di 'ripulire il testo', e invece il testo originario le aveva e togliendole il campo descrizione è andato in tilt! Ora le sto reinserendo tutte e mi pare funzioni. Suggerisco di aggiungere nel Wiki che se incollando il testo nel campo 'descrizione' si porta dietro una vitprgoletta dopo un apostrofo bisogna lasciarla (tanto lato sito non si vedono). Che ne dite @iltempe e @mfortini?

**Comment by cristigalas** [comment]
Ultima cosa: se siete d'accordo chiuderei issue...

**Comment by drizzt** [comment]
certo, ho aggiustato appositamente il codice del bot telegram e del webform
per generare yaml valido, per cui mette gli apici dove serve e non li mette
dove non serve.
il tuo caso specifico, apice singolo, viene convertito in apice doppio (
http://yaml.org/spec/current.html#id2534365)

Il sab 17 set 2016, 23:04 Cristina G. notifications@github.com ha scritto:

**Comment by cristigalas** [comment]
Ok, dunque chiudo issue e inseriamo una nota nel Wiki?

**Comment by dontyna** [comment]
Si @cristigalas , lascia traccia di queste info utili!

**Comment by iltempe** [comment]
ottimo @cristigalas
