### ISSUE TITLE
Inserire campi CHI, CONTATTI, LINK e INDIRIZZO nelle segnalazioni da Telegram

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#313]
Per facilitare il lavoro di verifica e accettazione delle segnalazioni che vengono dal bot Telegram e per renderle anche più fruibili sul sito, suggerirei di inserire i campi CHI e anche CONTATTI, LINK (per eventuali approfondimenti) e INDIRIZZO. Quest'ultimo è secondo me necessario anche se ci sono le coordinate lat/long perché l'indicazione testuale del luogo faciliterebbe chi legge la segnalazione sul sito.

**Comment by iltempe** [comment]
tecnicamente è fattibile. praticamente quello strumento era stato pensato per essere "di uso rapido" per chi è in campo per cui CHI, LINK eviterei sicuramente di metterli, potremmo chiedere con una voce specifica un contatto mail o telefonico ma non vorrei appesantire troppo l'inserimento dati.

**Comment by cristigalas** [comment]
Vero, però considera che quelle segnalazioni vanno poi sul sito e sono quindi a disposizione di tutti e il bot col tempo potrebbe essere usato anche da chi non conosciamo... Ieri, infatti, volevo accettare due segnalazioni ma erano poco chiare e poi, grazie al gruppo su Telegram, ho scoperto chi le aveva fatte e quindi gli ho chiesto ulteriori info, le ho aggiunte e quindi ho accettato ma non sempre potremo fare così... Comunque, a mio avviso, il rischio (col tempo) è avere delle segnalazioni da Telegram che poi nessuno le considera perché troppo 'scarne'.

**Comment by c83n** [comment]
secondo me in questa fase occorre mantenere strumento snello

alcune proposte per attendibita' delle fonti
- pensare ad una versione "pro" solo per afficionados
- lavorare sulla comunicazione per chiedere di settare nome user
- impostare modalita' di "reputazione" dei segnalatori
- istruzioni su aggiunta info in chat tipo che il bot potrebbe chiedere
  qualcosa tipo "lascia un contatto" opzionale
- eventualmente qualche procedura di triangolazione dell'informazione

pero' magari sn cazzate.. :)

Il domenica 18 settembre 2016, Cristina G. notifications@github.com ha
scritto:

**Comment by cristigalas** [comment]
@c83n per me le tue proposte vanno bene, non sono un'esperta e dunque lascio decidere a voi smanettoni ;) ma credo che occorra qualcosa per garantire un minimo di attendibilità delle segnalazioni che arrivano da bot e per renderle più fruibili sul sito.
Già che ci sono vi segnalo che in questa segnalazione arrivata via bot non si visualizza la descrizione, eppure c'è e sembra corretta [(http://www.terremotocentroitalia.info/issues/604/index.html)]

**Comment by iltempe** [comment]
@c83n per favore se ritieni necessario apriamo un issue per ogni proposta sopra. grazie.
