### ISSUE TITLE
inserimento nuove Labels

### ISSUE THREAD

**Issue by annaluciont** [emergenzeHack/terremotocentro#314]
Potremmo inserire nuove voci Labels a seconda della tipologia di bene (es. sociosanitario; b.materiale; legale; se per vigili del fuoco,  etc) e per comune (se anche per frazione, sarebbe il top!). Ci permetterebbe di essere più veloci nello smistare le segnalazioni.
@cristigalas 
@dontyna 
@Manfro 
aggiungete vostre indicazioni da gruppo telegram ;)

**Comment by cristigalas** [comment]
Come suggeriva @favoeva potremmo anche inserire due label per identificare le fonti social delle segnalazioni, ovvero Twitter e Facebook, visto che Telegram (bot) già c'è. Inoltre potremmo aggiungere altre due label, ovvero 'da pubblicare su Fb' e 'da pubblicare su Twitter' e poi, se passiamo anche alla gestione manuale del canale Telegram, 'da pubblicare su Tg' ma quest'ultima forse può aspettare...

**Comment by Manfro** [comment]
Allora per le label di "pubblicazione" (su TW o FB) ho già provveduto. Però non vorrei creare troppe label, farei solo quelle strettamente necessarie, quindi dovremmo discuterne e sceglierle al meglio

**Comment by annaluciont** [comment]
Elenco miei e suggerimenti di cris poi valutiamo quali:
- socio-sanitario
-  legale
- bene materiale
- da FB (se arriva da FB)
- per FB (se da postare su FB)
- da Twitter
- per Twitter
-  sigla comune esigenza aiuto

**Comment by favoeva** [comment]
Sono d'accordo con @Manfro io farei solo label
 -categorie presenti nel menù sito (così da predisporre flussi contenuti per le pagine )
- fonti di provenienza 
- comune 
- provincia

tutto il resto lo metterei nei commenti alle issue

**Comment by favoeva** [comment]
Rifaccio  ... sono su mobile e mi formatta male ;)
- categorie presenti nel menù sito (così da predisporre flussi contenuti per le pagine )
- fonti di provenienza
- comune (in questo caso avremmo lista di 17 label)
- provincia

In alternativa a label comune si potrebbe decidere di editare sempre testo titolo issue inserendo  ' nome comune:'

**Comment by annaluciont** [comment]
Ok. E' che parallelamente c'è chi smista e telefona direttamente al contatto più vicino alla segnala2ione quindi sarebbe utile avere immediate indica2ioni. 
Forse può sembrare inutile in questa fase ma mi aspetto un flusso in crescita..e prevenire è meglio! Sempre in attesa di una migliore gestione delle segnala2ioni.
Delucidatemi se esiste già!!!
