### ISSUE TITLE
Formato data dd/mm/yyyy per Press

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#315]
Convertire il formato data nel template della pagina Press da yyyy/mm/dd del csv a dd/mm/yyyy.

**Comment by mfortini** [comment]
Allo stesso modo, tradurre cose come "Posted on" in "Pubblicato il"

**Comment by mfortini** [comment]
Abbiamo più strade IMHO:
- mettere le date dd/mm/yyyy
- usare un sistema come http://alanwsmith.com/jekyll-liquid-date-formatting-examples e mettere le date "24 Settembre 2016"
- localizzare il sito (che però è tutto in Italiano http://polyglot.untra.io/)

**Comment by francescolovecchio** [comment]
Come faccio per partecipare? È già stato creato un branch? @mfortini

**Comment by drizzt** [comment]
dovresti forkarti il repository, aggiustare le cose e fare una pull request

**Comment by aborruso** [comment]
@epoeta @mfortini l'output della pagina http://terremotocentroitalia.info/press/ l'ho creato usando [datatables.net](https://datatables.net/).

Ho impostato la data in quel modo per due ragioni, perché abbastanza leggibile e perché consentiva un sorting nativo con datatables che legge per bene YYYY/MM/DD.

Si può modificare datatables o buttare :)

**Comment by drizzt** [comment]
Forse si può usare https://datatables.net/blog/2014-12-18

**Comment by aborruso** [comment]
@drizzt con datatables si può gestire, è un pacchetto ottimo. 
Io adesso non me ne posso occupare :(

**Comment by francescolovecchio** [comment]
@drizzt https://datatables.net/plug-ins/sorting/date-dd-MMM-yyyy anche questa non è male

**Comment by drizzt** [comment]
@francescolovecchio Please note that this plug-in is *_deprecated_. The datetime plug-in provides enhanced functionality and flexibility.

**Comment by iltempe** [comment]
@drizzt @francescolovecchio questo issue non si può chiudere?

**Comment by drizzt** [comment]
Fatto usando il plugin di sort date-eu di datatables e l'operatore | date: di Liquid
