### ISSUE TITLE
Integrazione webform nel sito : proposta da discutere

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#316]
Il buon @Pinzauti ha integrato il modulo segnala nel sito così dopo la mia richiesta #258 

Che dite? La sostituiamo alla pagina segnala? Le indicazioni sugli altri canali dove le mettiamo? http://terremotocentroitalia.info/segnala/

**Comment by cristigalas** [comment]
Sì la sostituirei e il resto lo inserirei in 'altri canali' sotto "Il progetto". Ma come mai sul sito non promuoviamo anche il gruppo Telegram, oltre che bot e canale? Ieri quando ho fatto il tweet per promuovere i nostri spazi Telegram, così come aveva chiesti @Manfro, ho promosso tutti e tre gli strumenti: canale, bot e gruppo. Quest'ultimo è utile segnalarlo, secondo me, perché può essere utile per chi voglia partecipare attivamente e/o interagire con noi.

**Comment by iltempe** [comment]
@Pinzauti agirei facendo queste modifiche:
- Alla voce Hai Bisogno?-Segnala linkare questa pagina nuova che hai fatto
- In home page linkare questa pagina nuova al pulsante "Segnala"
- Spostare il contenuto di questa pagina http://terremotocentroitalia.info/aiuto/ all'interno di 
  questa pagina http://terremotocentroitalia.info/canali/ facendo attenzione agli elementi che sono già su entrambe.

**Comment by Pinzauti** [comment]
Ci sarebbe da:
- Eliminare la pagina "Aiuto"
- Aggiustare le descrizioni: http://terremotocentroitalia.info/canali/

**Comment by iltempe** [comment]
ottimo. ci penso io. chiudo.
