### ISSUE TITLE
Proposta di procedura gestione post-segnalazione

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/terremotocentro#317]
Possibile procedura di gestione delle segnalazioni FB:
1) il primo che vede chiede amicizia al segnalatore 
2) informa gruppo TCI media team per capire chi ha piu' tempo 
3) chi ha tempo desk apre issue
4) si informa chi è sul campo della cosa
5) appena ricevuti contatti si chiama il soggetto per spiegare progetto
6) chiediamo disponibilità per incontro dal vivo
7) concordiamo con chi è sul campo incontro dal vivo
8) aggiorniamo mappa contatti/sensori 
9) aggiorniamo issue con quanto fatto

**Comment by iltempe** [comment]
@chiccap integriamo queste indicazioni nei Wiki?

**Comment by chiccap** [comment]
@iltempe direi di sì!

**Comment by iltempe** [comment]
Avevo iniziato a scrivere qualcosa qui. Mi dici come aggiorneresti?

https://github.com/emergenzeHack/terremotocentro/wiki/Creare-e-Gestire-segnalazioni

**Comment by chiccap** [comment]
Io su "gestione segnalazioni" farei una specifica per le "segnalazioni Facebook" che, per loro natura, necessitano di una gestione diversa da bot e webform (vedi possibile contatto diretto con segnalatore che poi potrebbe autonomamente in futuro usare bot o webform).

**Comment by chiccap** [comment]
@c83n che ne pensi?

**Comment by iltempe** [comment]
ok. @chiccap sai editare le pagine WIKI?

**Comment by chiccap** [comment]
Mai fatto ma ci provo!!!!!!!

**Comment by chiccap** [comment]
@iltempe @c83n fatto ditemi che ne pensate: https://github.com/emergenzeHack/terremotocentro/wiki/Creare-e-Gestire-segnalazioni

**Comment by c83n** [comment]
@chiccap 6 mito!

facciamo un file drive con elenco aggiornato di staff sul campo e lo
linkiamo nel wiki dove dici "Si informa chi è sul campo della
segnalazione;" ?

#yo

Il domenica 2 ottobre 2016, Chiara notifications@github.com ha scritto:

**Comment by iltempe** [comment]
@chiccap ottimo! @c83n nel file https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=2097001070 trovate un foglio chiamato SensoriInCampo. Elencate pure li dentro e linkate pure

**Comment by c83n** [comment]
mi sa che @chiccap non ha abuto tempo di linkare :)

Il lunedì 3 ottobre 2016, Iltempe notifications@github.com ha scritto:

**Comment by chiccap** [comment]
@iltempe grazie :)

**Comment by chiccap** [comment]
Link al wiki inserito!
