### ISSUE TITLE
Mappa dei comuni colpiti

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#318]
Occorre una mappa semplicissima che indichi i comuni colpiti dal terremoto con il nome dei comuni cliccabile come POI.

**Comment by favoeva** [comment]
qui la lista (ancora in progress) dei comuni 
https://github.com/emergenzeHack/terremotocentro/issues/335

**Comment by psykola** [comment]
no la issue #335 è su quegli ESCLUSI.

I comuni inclusi sono:
MARCHE
1. Acquasanta Terme (AP)
2. Arquata del Tronto (AP)
3. Montefortino (FM)
4. Montegallo (AP)
5. S. Montemonaco (AP)

ABRUZZO
1. Montereale (AQ)
2. Capitignano (AQ)
3. Campotosto (AQ)
4. Valle Castellana (TE)
5. Rocca Santa Maria (TE)

LAZIO
1. Accumoli (RI)
2. Amatrice (RI)
3. Cittareale (RI)

UMBRIA
1. Cascia (PG)
2. Monteleone di Spoleto (PG)
3. Norcia (PG)
4. Preci (PG)

**Comment by favoeva** [comment]
@psykola sì certo: sono esclusi dal decreto MEF (tra l'altro nel lazio la presidenza consiglio dei ministri pare ne abbia aggiunto un altro, ma nell'hangout si diceva che la mappa la vogliamo fare anche con quelli esclusi. Dovranno essere taggati con categorie differenti è ovvio ;)

**Comment by nelsonmau** [comment]
Se c'è qualcuna /o che vuole imparare a fare la mappa, mi offro volontario per spiegare come si fa. @psykola? @favoeva?

**Comment by psykola** [comment]
Rispondo da mail cellulare non so se funziona
Io sono disponibile, dopo le 9, e possiamo provare, anche se premetto che
non ho capacità di coding

**Comment by nelsonmau** [comment]
@psykola va bene e non c'è fretta!
Prima cosa: vai su drive.google.com e crea un nuovo spreadsheet. All'interno inserisci i comuni, ciascuno in una riga della colonna A.
Quando hai fatto fammi un fischio qui! A dopo :-)

**Comment by psykola** [comment]
fatto

**Comment by psykola** [comment]
Allora, io ho iniziato intanto a lavorare su un foglio gsheet che sta qui: https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=0
Sul quale sto raccogliendo anche dati di diversa natura sui comuni del cratere.
Sul lungo termine, sarebbe figo riuscire a mappare anche tutte le frazioni, che sono tantissime!!!
Metto in questa issue pure @marco-acorte che già condivide il foglio google.
Per editarlo insieme a me mandatemi una mail: psykola13@gmail.com

Spero di star facendo un lavoro utile

**Comment by nelsonmau** [comment]
@psykola eccomi, scusa il blackout :) 
- ho agggiunto il foglio "Meta", lì sarebbe utile descrivere brevemente cosa c'è nello spreadsheet, sennò @aborruso ci rimprovera :)
- ho visto che hai già inserito delle coordinate. Da dove le hai prese? Se da google, non sono open. Se da openstreetmap, invece sono Open quindi ok. Per trovare coordinate con openstreetmap può usare tanti strumenti, ti metto qui intanto il link al [geocoder di dataninja](http://school.dataninja.it/tools/geocoder-trova-le-coordinate/)

**Comment by psykola** [comment]
Ho usato questo: https://nominatim.openstreetmap.org/
spero di non aver fatto un casino. ho consultato @mfortini per avere conferma sullo strumento

**Comment by nelsonmau** [comment]
Va benissimo!

Ora occorre splittare le coordinate

1) crea due colonne vuote a fianco di quella con le coordinate
2) nella prima cella a fianco della prima coordinata inserisci la formula =SPLIT(nomecellacoordinata, ",")
3) questo farà in modo di avere una conna con tuttable latitudini e una altra colonna ckn tutte le longitudini

Ok?

**Comment by nelsonmau** [comment]
Inoltre nel foglio Meta inserisci una voce tipo "Coordinate ricavate con OpenStreetMap Nominatim"

**Comment by psykola** [comment]
Fatto tutto, finora. I comuni sono tutti geolocalizzati.
Ho anche iniziato a fare una lista delle frazioni per ogni comune, dove riesco sto geolocalizzando. Anche se è un lavoro infinito (molte volte devo confrontare con google maps, perché i nomi sono leggermente diversi, ecc)
Penso possa essere utile per fare una mappa ad aree (ma questo lo sapete voi capoccioni, io colleziono solo i dati)

**Comment by nelsonmau** [comment]
in `Meta` ho aggiunto anche la voce "Fonte dei dati", dove puoi mettere l'url della pagina (o pagine) da cui hai preso l'elenco

**Comment by nelsonmau** [comment]
nel caso delle frazioni è un lavoro da fare a mano. Magari poi i dati corretti da te li possiamo mettere su Openstreetmap e su questo chiedo aiuto per esempio al mitico @sabas: Stefano, quando hai un attimo dai un'occhiata a questa conversazione e ci dai un feedback pls? grazie! :)

**Comment by sabas** [comment]
Le frazioni su OSM dovrebbero esserci tutte (con tutto il lavoro che hanno fatto con i task)...

**Comment by psykola** [comment]
IMPORTANTE: il lavoro c'era già
https://docs.google.com/spreadsheets/d/1ERSFsWsqV_X_qPLekXo6NakcWjz3DWpTZEwTgAq1EKM/edit#gid=0
Va verificato eventualmente come migliorarlo

**Comment by nelsonmau** [comment]
@psykola ok, ho visto quest'ultimo foglio che hai linkato (`provageo`) e non capisco esattamente cosa sia (vedi, com'è importante avere un foglio 'meta' che descriva i dati? :P )

direi cmq che se vuoi puoi provare a fare una mappa.
Due ipotesi con tool online:
- umap https://umap.openstreetmap.fr/it/
- carto https://carto.com/

In esntrambi i casi la proceduta è semplice:
- crea un account
- scarica i dati da google sheet in formato CSV 
- caricali all'interno del servizio che hai scelto
- indica all'interno del servizio (se necessario) quali sono le colonne di latitudine e longitudine

forse l'ho detta troppo sinteticamente?
fammi sapere!

**Comment by psykola** [comment]
Scritto come lo scrivi, sembra facile, spero di riuscirci (se lo farò io)! 
Siccome oggi pomeriggio sarò off, chiedo - se per caso qualcun altro ci mette mano - di commentarlo qui. Grazie!

**Comment by sabas** [comment]
@nelsonmau Se non volete dipendere da un servizio online (ma magari metterlo sul sito), con il csv puoi:
- Aprirlo con qgis (anche qui nel form puoi dire quali sono le colonne long / lat
- Inserire uno sfondo OSM (plugin quickmapservices)
- Con il plugin qgis2web generare una mappa openlayers / leaflet

**Comment by psykola** [comment]
@sabas io non sono uno sviluppatore, posso catalogare i dati o fare qualche piccola cosa su indicazioni precise (ecco perché @nelsonmau mi parlava come si spiegherebbe a un bambino), le cose che mi scrivi te non le so fare -_-

**Comment by nelsonmau** [comment]
@psykola e @sabas facciamo un passo alla volta :)
@psycola: in realtà le cose che dice sabas non sono difficili, se hai voglia e tempo di aiuto :)

**Comment by psykola** [comment]
Allora carissimi tutti, finalmente ho potuto dare un'occhiata al lavoro fatto in emergenza subito dopo il sisma, effettivamente riguarda solo l'area di Amatrice, Acquasanta e Arquata. Ora che il cratere è definito può essere utile mappare anche gli altri comuni interessati.
Fatemi capire se è meglio arricchire e sistemare il file provageo (alcune voci non capisco la differenza) , oppure quello fatto da me "TCI - comuni del cratere". 
Io eseguo volentieri la raccolta dati, se c'è qualcuno che al posto mio "fa la mappa", tanto meglio. Se però non c'è proverò tutorata da qualcuno.
Stasera (21/09/2016) penso posso mettermici dopo le 21 più o meno

**Comment by nelsonmau** [comment]
@psykola provi intanto a fare la mappina con i dati raccolti da te?

**Comment by psykola** [comment]
mi vuoi male :°
Come faccio a farla qui su github? 
1) Aprirlo con qgis>>>  NON SO che è qgis (dove si prende, dove si apre, da che lato si guarda e cose cosi)
2) Inserire uno sfondo OSM (plugin quickmapservices)>>> totale non comprensione
3) Con il plugin qgis2web generare una mappa openlayers / leaflet >>> vabbè ci pensiamo dopo

**Comment by sabas** [comment]
Altra soluzione più semplice:
- download file dal foglio google (salva come -> csv separato da virgola)
- apri http://geojson.io/
- trascina o apri il file scaricato sul sito
- riconosce in automatico le colonne lat e long, l'ho salvato come Gist su Github https://gist.github.com/anonymous/53465dd3ea666de673dd6755c67ea847

**Comment by psykola** [comment]
Ho fatto tutto da sola giuro!
https://gist.github.com/anonymous/4b7ee55ebb62ce1213dd70535f9b259c

**Comment by iltempe** [comment]
@psykola mito!!!!!

**Comment by nelsonmau** [comment]
@psykola! Bene! Prova con Umap adesso
L'importante è che i dati siano formattati bene, poi vanno bene per tutti i tool

**Comment by psykola** [comment]
@nelsonmau  perché devo provare con Umap? non andava bene quell'altro modo?
Io le faccio pure le cose che mi dite (come un automa), così imparo, però ogni tanto ho pure bisogno di capire se devo fare una cosa solo per imparare (e diventare una risorsa) oppure perché ha una reale utilità.
PS. stanotte ho sognato di GEOREFERENZIARE (avete creato un mostro)

**Comment by nelsonmau** [comment]
@psykola beh se non vuoi farla non farla :)
Anyway, [Umap](https://umap.openstreetmap.fr/it/) è uno strumento di self publishing di mappe, molto più personalizzabile rispetto al gist che hai fatto. Stesso discorso per [Carto](cartodb.com). Facendo la stessa mappa con strumenti differenti, ti renderesti conto delle sostanziali similitudini e delle cose in cui gli strumenti differiscono.

Inoltre la mappa che hai fatto in gist non è inseribile così com'è sul sito (su mobile per esempio non viene renderizzata: cioè i singoli punti geografici su mobile vengono visualizzati come dati e non rappresentati su mappa)

Altro cosa: il meraviglioso mondo delle mappe ha un suo strumento per eccellenza che è [QGIS](http://www.qgis.org/it/site/), che è quello da capire e iniziare a usare se si vuole veramente ragionare di mappe.

Ti reincollo qui quello che ha scritto @sabas 

```
Se non volete dipendere da un servizio online (ma magari metterlo sul sito), con il csv puoi:

* Aprirlo con qgis (anche qui nel form puoi dire quali sono le colonne long / lat
* Inserire uno sfondo OSM (plugin quickmapservices)
* Con il plugin qgis2web generare una mappa openlayers / leaflet
```

non so se la spiegazione è chiara e sufficiente :)

**Comment by marco-acorte** [comment]
@psykola guarda questa guida per installare qgis su ubuntu 12.04
http://www.acor3.it/2015/04/16/howto-installare-qgis-2-8-ubuntu-12-04/

**Comment by marco-acorte** [comment]
intanto importati dati qui https://umap.openstreetmap.fr/it/map/tci-comuni-del-cratere_103799

**Comment by psykola** [comment]
Siete preziosi. Ma avrei bisogno di giornate di almeno 30 ore, anziché 24. 
E grazie @nelsonmau !!!!!

**Comment by psykola** [comment]
Sto sistemando i dati del mio foglio, rispetto alle frazioni che lo script non riesce a identificare dentro Nominatim.
Ho notato che in alcuni casi le frazioni non sono proprio riportate su Open Street Map. Sto confrontando OpenStreetMap con GoogleMap per trovare i luoghi. In alcuni casi è facile individuarli (es. Casale Nibbi di Amatrice - luogo che conosco di persona), altri  casi invece non sono riportati nemmeno da Google, se non perché citati come indirizzo di qualche azienda (es. Casale Bucci di Amatrice).

Quello che sto facendo l'ho scritto nel foglio Meta: https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=636719506

**Comment by lorenzoperone** [comment]
Ciao Giorgia,
credo che sia necessario utilizzare i toponimi delle CTR regionali.
Io ora purtroppo non riesco a guardarci.
Ciao.
l.

Lorenzo Perone
twitter: @lorenzo_perone https://twitter.com/lorenzo_perone
photoblog: http://immagini.me

Il giorno 23 settembre 2016 15:31, Giorgia Brugnerotto <
notifications@github.com> ha scritto:

**Comment by favoeva** [comment]
nella mappa per ogni poi comune si potrebbe aggiungere link a sito o pagina fb . Quello che segue è elenco fatto per comuni decreto MEF 

MARCHE
Acquasanta Terme
 https://www.facebook.com/paginaufficialedelcomunediacquasantaterme/?fref=ts
http://www.comune.acquasantaterme.ap.it/hh/index.php 

Arquata del Tronto (AP)
fb onlus Omnibus Omnes  https://www.facebook.com/omnibusomnes/ 
hp sito comune http://www.halleyegov.it/c044006/hh/index.php 

Montefortino (FM)
 non ufficiale https://www.facebook.com/ComunediMontefortino/ 
http://halleyweb.com/c044037/hh/index.php 

 Montegallo (AP)
http://www.halleyegov.it/c044038/hh/index.php 
pagina fb non ufficiale ma riporta notizie sito comune https://www.facebook.com/Ricostruiamo-Montegallo-323346368005569/?fref=ts 

S. Montemonaco (AP)
pagina fb proloco riporta notizie raccolta materiali https://www.facebook.com/prolocodi.montemonaco/?fref=ts 
sito comune http://www.tecuting.it/c044044/hh/index.php 

ABRUZZO

Montereale (AQ) 
sito http://www.comune.montereale.it/c066056/hh/index.php 
pagina fb non ufficiale Comune di Montereale – AQ https://www.facebook.com/montereale1/ 

Capitignano (AQ)
http://www.comune.capitignano.aq.it/ 
unica pagina fb relativa alla città quella della squadra di calcio https://www.facebook.com/groups/118719748290900/?fref=ts 

Campotosto (AQ)
pagina fb progetto campotosto https://www.facebook.com/groups/268115903268934/?fref=ts 
sito http://www.comune.campotosto.aq.it/ con anche avvisi incontri pubblici 

Valle Castellana (TE)
http://www.comune.vallecastellana.te.it/ 
pagina fb Valle Castellana Info-News https://www.facebook.com/vallecastellana.infonews/?fref=ts 

Rocca Santa Maria (TE)
http://www.roccasm.it/ 
uniche pagine fb relative al comune sono pro loco e squadra calcio (non riportano notizie terremoto)

LAZIO

Accumoli (RI) 
http://www.comune.accumoli.ri.it/ 
pagina fb Villanova Accumoli per Ricominciare Onlus (aperta dal 7 settembre) https://www.facebook.com/VillanovaAccumoliOnlus/?fref=ts 

Amatrice (RI) 
http://www.comune.amatrice.rieti.it/ 
pagina fb ufficiale comune https://www.facebook.com/ComunediAmatrice/?fref=ts 
gruppo pubblico https://www.facebook.com/groups/amatricelink/?fref=ts 
comunità FB https://www.facebook.com/pat771/?fref=ts (chiuderà il 24 settembre )
gruppo chiuso www.facebook.com/groups/sosamatriceterremoto/?fref=ts  

Cittareale (RI) 
http://www.cittareale.it/ 
pagina fb centro smistamento cittareale https://www.facebook.com/centrosmistamentocittareale/?fref=ts 

UMBRIA

Cascia (PG)
http://www.comune.cascia.pg.it/ 
pagina fb ufficiale https://www.facebook.com/ComuneCascia/?fref=ts

Monteleone di Spoleto (PG)
http://www.comune.monteleonedispoleto.pg.it/ 

Norcia (PG)
http://www.comune.norcia.pg.it/ 
pagina ufficiale comune fb https://www.facebook.com/ComuneNorcia/ 
altra pagina post sisma “Segnalazioni Norcia” https://www.facebook.com/groups/993292824038901/?fref=ts 

Preci (PG) 
http://www.comune.preci.pg.it/ 
pagina fb non ufficiale https://www.facebook.com/Preci.PG/

**Comment by epoeta** [comment]
Altri gruppi e siti qua: #244

**Comment by nelsonmau** [comment]
@psykola ti do una notizia choc, [questo foglio](https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=903810664) è concettualmente sbagliato e da rifare. Va fatto così, a due colonne.
Se non riesci a lavorarci, faccio io dopo :)

| nome comune | provincia  |
| comune 1        | provincia1|
| comune 2        | provincia2|

**Comment by nelsonmau** [comment]
@favoeva ho fatto un foglio nuove per mettere i link web e facebook dei comuni come dici tu. Ci lavoro dopo, qui l'indirizzo https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=1314692407

se vuoi cominciare tu fai cosa gradita: io da siculo vado cenare, mentre voi lumbard è risaputo che cenate alle 19:30 :)))

**Comment by nelsonmau** [comment]
ecco, qui gli url inseriti da @favoeva https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=1314692407

**Comment by psykola** [comment]
@nelsonmau dove ti chatto? mi tutorizzi? impostiamo il file insieme così poi vado spedita?

**Comment by nelsonmau** [comment]
@psykola eccomi, l'ho impostato qui https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=975453356

**Comment by nelsonmau** [comment]
(occorre riempire **solo** le prime due colonne)

**Comment by psykola** [comment]
Non l'ho capito il foglio. Mi sembrano mischiati comuni e frazioni, non capisco la catalogazione

**Comment by psykola** [comment]
Intanto che giocavo con Umap, ho fatto la mappa dei 17 comuni. Con le coordinate delle frazioni, tramite mappa ho potuto verificare che c'erano dei punti a cavolo, per cui occhio allo script. 
Ho fatto questa, dei 17 comuni: https://umap.openstreetmap.fr/it/map/terremotocentroitalia-comuni-del-cratere_103875

**Comment by nelsonmau** [comment]
@psykola è più chiaro [il foglio in questo modo](https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=975453356)?

Ho messo tre colonne: | località | comune | provincia |
che sono le uniche da compilare

**Comment by iltempe** [comment]
la mappa è online sul sito qui. http://terremotocentroitalia.info/2016-08-24-mappa-comuni-cratere/. Ogni modifica alla mappa UMAP viene automaticamente pubblicata sul sito quindi aggiornate pure se necessario.

**Comment by aborruso** [comment]
Specie per @psykola : ho fatto il geocoding dei toponimi che ho trovato elencati nel foglio denominato "query ( prova)".

Ho utilizzato [OpenCage](https://geocoder.opencagedata.com/api), un motore basato su dati OpenStreetMap (e altro).  Trovi tutto [qui](https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit#gid=861107286) (risultati nelle colonne in giallo).

Tra i risultati, trovo utili le colonne:
-  confidence ("The precision of a match returned in the confidence field. This contains a value between 0 and 10 , where 0 reflects inability to determine a confidence (due to there being no bounding box) 1 reflects low precision and 10 reflects high precision.");
- type, che indica il tipo di oggetto trovato.

Quando sono presenti più di un risultato, ho preso (oggi) solo il primo. Di poco più di 5 toponimi non si hanno risultati.

@ebergam, @iltempe, @lorenzoperone, @sabas, @nelsonmau   buttateci un occhio anche voi. 

Notte

**Comment by ebergam** [comment]
@aborruso #mito grazie mille!! Domanda: avevo provato con OpenCage e Nominatim sul foglio query ma non funzionavano/erano lentissimi, come se le richieste fossere bloccate, ma non ne avevo fatte un'esagerazione e mi ero autenticato in entrambi i casi. Tu le hai fatte da un foglio tuo?

**Comment by aborruso** [comment]
Caro @ebergam ho usato Open Refine

**Comment by psykola** [comment]
Non so come hai fatto ma è fantastico. Grazie @aborruso ! 
Ora è da capire (cioè confrontarci), come usiamo questi dati?
Mappa di tutte le frazioni insieme (ma prenderà il perimetro oppure i pallini?)? Mappa di frazioni per comune? Io intanto faccio qualche prova di mappa, mi piacerebbe che qualcuno mi desse la sua visione, tipo @mfortini

**Comment by aborruso** [comment]
@psykola due cose:
- appena posso descrivo il processo;
- sono coppie di coordinate, quindi al momento sono pallini.

**Comment by psykola** [comment]
Ho già evidenziato quelli sbagliati (importando il csv su Umap). Sul foglio fatto da te @aborruso li evidenzio in rosso: https://docs.google.com/spreadsheets/d/14onftpJmPN586rWzHk9Y7Np3KtV7GE7tyBug81yzfwI/edit?userstoinvite=lorenzo.perone@gmail.com&ts=57ea1ac8&actionButton=1#gid=861107286
Che faccio correggo?

**Comment by aborruso** [comment]
@psykola sì, correggi pure. Ho aggiunto nel foglio una colonna "Correto" in cui inserirei una `x` nei record corretti "a mano".

**Comment by psykola** [comment]
Pensavo di fare questo: faccio un foglio per ogni comune e le sue relative frazioni geolocalizzate con OpenCage Query, lo esporto e lo carico come LIVELLO su Umap. In questo modo vedo immediatamente gli errori di geolocalizzazione, che correggo sempre sul foglio OpenCage Query.
Quando ho corretto le coordinate di un comune, esporto di nuovo e carico sempre sulla stessa mappa: https://umap.openstreetmap.fr/it/map/terremotocentroitalia-comuni-del-cratere_103875
