### ISSUE TITLE
Errore avviando il sito in locale

### ISSUE THREAD

**Issue by lorthirk** [emergenzeHack/terremotocentro#32]
Ho seguito le istruzioni su GitHub Pages per installare Jekyll in locale presenti [qui](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-2-install-jekyll-using-bundler) ma al momento di avviare il server con `bundle exec jekyll serve` ottengo il seguente errore:

```
bundle exec jekyll serve
Configuration file: C:/Users/cmezzasalma/Desktop/terremotocentro/_config.yml
            Source: C:/Users/cmezzasalma/Desktop/terremotocentro
       Destination: C:/Users/cmezzasalma/Desktop/terremotocentro/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository. in sitemap.xml
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.
```

Forse è il caso di scrivere una procedura nel README per l'avvio del progetto in locale?

**Comment by iltempe** [comment]
Non so se usi MAC o OS, ma io che ho MAC lavoro in locale con editor di testo e committo direttamente su github. Ha volte ho provato a farlo in locale ma per questo progetto non ho avuto modo di configurare l'ambiente ancora.

**Comment by gufogio** [comment]
Dal messaggio di errore sembra che tu non abbia fatto il clone con `git` ma l'abbia scaricato in un altra maniera. Qui ci sono le istruzioni base per installare `git`: https://help.github.com/articles/set-up-git/

Sto provando a vedere come fare, per aggiungere alla wiki le istruzioni :)

**Comment by lorthirk** [comment]
Il problema era la mia installazione di Jekyll (che, ammetto, non avevo mai utilizzato) su Windows.

Dopo un po' di tribolazioni ho seguito [queste istruzioni](https://getpocket.com/a/read/1394277339) oltre a quelle sulla homepage di Jekyll per l'installazione su Windows, e ora sembra andare tutto.

Grazie, chiudo!
