### ISSUE TITLE
UX: necessità di modifica form, homepage e menù del sito 

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/terremotocentro#326]
Quelle che seguono sono proposte emerse  dall'hangout gestione segnalazioni del 19 settembre 2016 a cui hanno partecipato persone che sono attive sulla gestione segnalazioni e  altre che sono 'sul campo' e che, stando lì, hanno raccolto richieste e esperienze di navigazione sul sito TCI . 
Questa issue sviluppa riflessioni già avviate qui https://github.com/emergenzeHack/terremotocentro/issues/309

**Comment by iltempe** [comment]
riporto una prima riflessione di @favoeva in #309 

Può essere utile creare sezione UTILITA' (nome brutto ma per capirci) con dentro:

- mappe
- dati (tra cui anche VITTIME)
- link a archivio doc TCI su archive
- il flusso dal gruppo flickr (se diventa archivio immagini)

**Comment by favoeva** [comment]
con @marco-acorte @annaluciont @cristigalas @dontyna e altr\* abbiamo concordato sul fatto che in HP dovrebbe esserci una mappa con due livelli di lettura iniziali: 
- mappa comuni colpiti dal sisma (lista MEF + integrazione dei 13 che mancano e che ci fornirà @annaluciont) https://github.com/emergenzeHack/terremotocentro/issues/335,  
- mappa dei campi ufficiali e autogestiti  _storicizzata_  a ultima rilevazione disponibile; (su questo ieri @marco-acorte ha iniziato a verificare possibilità di importazione mappa Massimo Tufano che abbiamo già pubblicato qui https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/453

inoltre, sempre in HP, i bottoni che ora sono SEGNALA - ULTIMORA - ALLOGGI - FABBISOGNI 
dovrebbero, se possibile, diventare così

1) SEGNALA andrebbe spacchettato in: ‘hai bisogno’ e ‘vuoi essere utile’ entrambi che mandano a form dove si trovano due opzioni 
- servizi
- beni  

2) ULTIMORA ora manda a pagina con titolo “News” . Bisognerebbe chiamare anche il tasto in HP “News” (nota per gestione issue: nell’editing delle issue inseriremo manualmente la data della notizia non dell’inserimento)

3) ALLOGGI

4) FABBISOGNI potrebbe diventare 'cosa serve' 

Queste invece le necessità evidenziate durante l'hangout per le sezioni del sito accessibili dalle voci di  menù in alto a destra 
- da 'aggiornamenti' va eliminata la sottosezione ‘blog’ (che non è altro che la pagina archivio documenti) 
- va creata una nuova sezione 'UTILITA' (o dati e mappe) con dentro due sottosezioni:
1. mappe (all'interno cambiare il titolo 'Mappa delle immagini inviate dal bot Telegram' con 'mappa delle immagini dai luoghi colpiti')
2. dati (spostare qui elenco vittime). Questa sarà la sottosezione dove inseriremo _appena possibile_ la mappa chiesta per l'HP e tutti gli altri dati che man mano saremo in grado di aggregare (lista necessità dati aggregati potrebbe iniziare a compilarla @dontyna in base a riflessioni 2° hangout ?) 
3. link a archivio doc TCI su archive.org 
4. il flusso dal gruppo flickr (se diventa archivio immagini)
- nella sezione progetto: 
  la sottosezione wiki diventa qualcosa tipo ‘join us’ ‘contribuisci’ ‘come puoi partecipare’ ‘unisciti a noi’
  nel testo del wiki vanno messi alcuni cross link alla fine tra cui il link alla chat di gruppo TCI su telegram e al gruppo terremotocentroitalia su FB

**Comment by favoeva** [comment]
ALTRO PER IL FORM

da qui http://terremotocentroitalia.info/link_utili/ 

togliere i 'contatti' e metterli con una voce di menu separata, che pesca in entrata da una nuova voce del form  “segnala servizi / enti / associazioni sul territorio” 
in uscita va messo in nuova sottosezione UTILITA' 
(in ogni caso ci siamo accort\* che va ripulita lista attuale, inizia a lavorarci @cristigalas )

**Comment by cristigalas** [comment]
La sezione contatti l'ho ripulita oggi.

**Comment by psykola** [comment]
Per semplificare il lavoro di sviluppo e migliorare l'usabilita del sito pensavo che si potrebbe semplicemente:
riportare il form "segnala", così com'è, sotto la pagina "Vuoi donare?", solo togliendo il tasto "chiedi un aiuto".

**Comment by cristigalas** [comment]
Io rimarrei alla proposta discussa ieri sera nell'hangout, che credo meglio risponda alla richiesta di chiarezza e di una migliore usabilità che veniva da più parti...

**Comment by favoeva** [comment]
Durante l'hangout è emersa anche l'opportunità di creare un feed RSS per le sottosezioni modulistica nella sezione TRASPARENZA dei siti dei comuni colpiti dal sisma, ma purtroppo da un controllo sommario pochi ce l'hanno :(
i moduli post sisma sono normalmente pubblicati in hp 
per il momento si potrebbe quindi pubblicare la lista url hp siti comuni nella nuova sezione del sito TCI denominata UTILITA'

per quanto infine riguarda albopop, durante l'hangout ci si chiedeva se fosse possibile attivarlo per i siti dei comuni colpiti con filtro su alcune parole chiave tipo SOMMA o URGENZA o ORDINANZA, sarebbe utile per monitorare bandi / gare post sisma e ordinanze appunto
Su albopop si sta lavorando nella issue https://github.com/emergenzeHack/terremotocentro/issues/84

**Comment by Pinzauti** [comment]
Per quanto riguarda la nuova voce del form “segnala servizi / enti / associazioni sul territorio” , non potremmo utilizzare la voce "Segnala Contatto", magari cambiandole nome?

**Comment by psykola** [comment]
Riflettevo che:
- i contatti sono delle persone sul territorio a cui rivolgersi, o potrebbero essere associazioni e comitati LOCALI
- i servizi (offerti da singoli o associazioni varie), di fatto si configurano come delle "Risorse Disponibili", il cui database è alimentato dal form di segnalazione "Fai una donazione".
  Forse basterebbe cambiare il nome di "Fai una donazione" in "Dona beni o servizi"....

**Comment by cristigalas** [comment]
Sì @psykola concordo, potrebbe essere una soluzione... Questa voce "dona beni o servizi" andrebbe quindi nella sezione "Vuoi essere utile" (ora "Vuoi donare"), di cui scriveva @favoeva riportando la discussione in hangout. Che dite?

**Comment by iltempe** [comment]
se @franziner inizia a fare le icone anche per i pulsanti che ci sono in home page posso nel frattempo creare una cosa stile http://terremotocentroitalia.info/mappe/

**Comment by psykola** [comment]
Non ho avuto modo di commentarlo altrove ma le icone di
http://terremotocentroitalia.info/mappe/ sono una fihata

Il 12/ott/2016 09:11, "Iltempe" notifications@github.com ha scritto:

**Comment by franziner** [comment]
ahaha grazie @psykola 
@iltempe ho già aperto illustrator!

**Comment by iltempe** [comment]
@psykola appena hai fatto fai un fischio qui!

**Comment by psykola** [comment]
Ho fatto. Sono qui. Fiiii (era un fischio)

Il 12/ott/2016 20:59, "Iltempe" notifications@github.com ha scritto:

**Comment by franziner** [comment]
habemus icone per l'home page! 

![tci-alloggi](https://cloud.githubusercontent.com/assets/15049880/19418082/0d431b1a-93bd-11e6-94c1-ee1ab4815656.png)
![tci-alloggi2](https://cloud.githubusercontent.com/assets/15049880/19418080/0d3f5142-93bd-11e6-8cd2-5d98c0c0c33b.png)
![tci-fabbisogni](https://cloud.githubusercontent.com/assets/15049880/19418085/0d456884-93bd-11e6-9889-c1caa05a8f9d.png)
![tci-fabbisogni2](https://cloud.githubusercontent.com/assets/15049880/19418084/0d4515a0-93bd-11e6-9a49-bdbba722419c.png)
![tci-news](https://cloud.githubusercontent.com/assets/15049880/19418081/0d42a310-93bd-11e6-872f-d7707837cd23.png)
![tci-news2](https://cloud.githubusercontent.com/assets/15049880/19418083/0d433b2c-93bd-11e6-94ce-1bcf5a9039a3.png)
![tci-segnala](https://cloud.githubusercontent.com/assets/15049880/19418086/0d549e94-93bd-11e6-8d9d-29ca71dd5f88.png)
![tci-segnala2](https://cloud.githubusercontent.com/assets/15049880/19418087/0d5765a2-93bd-11e6-9b31-81798f5d0fa3.png)

**Comment by c83n** [comment]
booooooom :)

Il domenica 16 ottobre 2016, Francesca Maio notifications@github.com ha
scritto:

**Comment by iltempe** [comment]
nuovo aggiornamento della home. http://www.terremotocentroitalia.info/ grande @franziner !!!

**Comment by iltempe** [comment]
ho cercato di sistemare alcune delle richieste dell'issue all'inizio di @favoeva chiudo questo e ne apro un'altro come suggerimenti per home page.
