### ISSUE TITLE
Aggiungere pulsanti condivisione

### ISSUE THREAD

**Issue by annaluciont** [emergenzeHack/terremotocentro#327]
Questa proposta nasce dalla mia esigenza di condividere i contenuti della piattaforma con le chat Telegram e Whatsapp dei vari gruppi solidali in cui sono inserita e che per diverse e varie questioni sono ancora avvezzi a monitorare le segnalazioni autonomamente. 
Si possono inserire i due pulsanti condivisione Telegram e Whatsapp?

**Comment by iltempe** [comment]
@annaluciont se vedi nelle pagine dei singoli avvisi sul sito esistono già due pulsanti per facebook e twitter. dicci se ti servono altre  funzionalità particolari.
Guarda questo per esempio:
http://terremotocentroitalia.info/issues/610/

**Comment by annaluciont** [comment]
@iltempe  Scusami, ho riformulato correttamente l'issue, erroneamente avrò cancellato una parte e non era chiaro ciò che volevo dire ;)
(Ne approfitto per ri-segnalare che per questa tipologia di issue non ho abilitazione ad inserire label)

**Comment by annaluciont** [comment]
Scusate, manca la parte in cui spiegavo di telegram e whatsapp, non capisco come mai non compare più. Sorry

**Comment by iltempe** [comment]
allora per condividere su whatsapp e telegram non credo esista uno specifico pulsante di condivisione, la cosa che puoi fare è fare copia link e incollarlo in whatsapp e telegram o vedere se quando stai sulla pagina che vuoi condividere il tuo smartphone ti consente di condividere il link (di suo) con altre app. Il mio iphone ad esempio lo consente. per i permessi ora dovresti averli

**Comment by marco-acorte** [comment]
per whatsapp
whatsapp://send?text=xxxxxxxxxxxxxxxxxxxxxxx

**Comment by iltempe** [comment]
ottimo. non l'ho mai fatto, ma possiamo aggiungerlo.

**Comment by marco-acorte** [comment]
si whatsapp testato e funziona bene...

**Comment by marco-acorte** [comment]
ed ecco x telegram >> http://telegram.wiki/tips:websharing

https://telegram.me/share/url?url=https://telegram.wiki

**Comment by iltempe** [comment]
ok. chiudo qui e vedo di farlo fare.
