### ISSUE TITLE
creare una app mobile

### ISSUE THREAD

**Issue by marco-acorte** [emergenzeHack/terremotocentro#328]
topic per valutare se sviluppare e in che modo app mobile per android, ios, windowsphone

**Comment by Pinzauti** [comment]
Intanto sembra essere uscita questa:
https://play.google.com/store/apps/details?id=eh.terremotocentroitalia

**Comment by iltempe** [comment]
per android è fatta.

**Comment by Pinzauti** [comment]
@iltempe io la incentrerei maggiormente sul lato segnalazioni, magari nativamente invece che in webview. Con notifiche e tutto. E' un lavoro un po' lungo ma potrebbe essere interessante.

**Comment by mfortini** [comment]
Come al solito il principio è che facciamo quello che ci sembra necessario
e che riusciamo a fare. L'idea dell'app nativa è buona, se la facciamo però
dobbiamo assicurarci che sia manutenuta: con la webview abbiamo
aggiornamenti automatici

Il mer 21 set 2016, 20:02 Francesco Pinzauti notifications@github.com ha
scritto:

**Comment by Pinzauti** [comment]
L'idea era di creare un ulteriore canale per le segnalazioni oltre al bot telegram e al form, dove poter comunicare magari anche direttamente con l'utente, dove può lui stesso chiudere la segnalazione, aggiungere informazioni eccetra.
Ma è giusto un'idea, mi rendo conto che necessiti di uno sviluppo costante.
