### ISSUE TITLE
l'uso di caratteri accentati nel CSV mostra un warning Liquid (syntax error)

### ISSUE THREAD

**Issue by olistik** [emergenzeHack/terremotocentro#33]
```
⎋ jekyll serve
Configuration file: /Users/olistik/projects/terremoto-centro-italia/terremotocentro/_config.yml
            Source: /Users/olistik/projects/terremoto-centro-italia/terremotocentro
       Destination: /Users/olistik/projects/terremoto-centro-italia/terremotocentro/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
    Liquid Warning: Liquid syntax error (line 110): Expected id but found open_square in "{{member.['Breve descrizione delle necessità']}}" in donazioni.md
    Liquid Warning: Liquid syntax error (line 115): Expected id but found open_square in "{{member.['Elenco completo dei fabbisogni']}}" in donazioni.md
    Liquid Warning: Liquid syntax error (line 123): Unexpected character à in "member.Località" in donazioni.md
    Liquid Warning: Liquid syntax error (line 125): Unexpected character à in "{{member.Località}}" in donazioni.md
                    done in 0.599 seconds.
 Auto-regeneration: enabled for '/Users/olistik/projects/terremoto-centro-italia/terremotocentro'
Configuration file: /Users/olistik/projects/terremoto-centro-italia/terremotocentro/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

Analogamente a [questo post](http://stackoverflow.com/a/37047318) su StackOverflow, relativo all'inclusione di partial, penso che Liquid non digerisca bene le lettere accentate.

A meno di altre soluzioni, potremmo modificare la presenza delle accentate anche solo nei nomi delle colonne CSV (anche solo dopo averle scaricate con [scripts/csvupdate.sh](https://github.com/emergenzeHack/terremotocentro/blob/master/scripts/csvupdate.sh)).

**Comment by mfortini** [comment]
Ok mi sa che la cosa più veloce sia cambiare le intestazioni nel gsheet condiviso e poi aggiornare il template di conseguenza. Quando torno operativo se nessuno è riuscito faccio io

**Comment by drizzt** [comment]
c'è anche il problema che non digerisce campi delle colonne contenente spazi.
`Liquid Warning: Liquid syntax error (line 115): Expected id but found open_square in "{{member.['Elenco completo dei fabbisogni']}}" in donazioni.md`
In questo caso si sta lamentando non per le accentate (che non ci sono), ma perché utilizza member.[]. Una cosa veloce da fare potrebbe essere sostituire spazi con _ e le accentate con lettere senza accentate nello script che parsa il cvs.
Qualcosa tipo
`echo "blabla" | sed 's/ /_/g' | iconv -t ascii//TRANSLIT`

**Comment by iltempe** [comment]
chiudo?

**Comment by massimog** [comment]
Forse può servire, forse no. In questa discussione https://github.com/jekyll/jekyll/issues/3369 si parla anche della differenza tra {{ e {% , ho notato che nel codice quotato da @drizzt c'è scritto {{
