### ISSUE TITLE
Armonizzare tutti i pulsanti di condivisione social

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#333]
I pulsanti di share sui social vanno armonizzati e fatti tutti uguali.  

Suggerirei di replicare ovunque quelli in Home page 
http://terremotocentroitalia.info/

(se vedete ad esempio qui sono diversi http://terremotocentroitalia.info/issues/626/index.html)

E di metterli oltre che nei singoli post anche nelle sezioni 
http://terremotocentroitalia.info/alloggi/
http://terremotocentroitalia.info/news/
http://terremotocentroitalia.info/fondi/
http://terremotocentroitalia.info/fabbisogni/

Aggiungerei a quelli esistenti anche il pulsante di condivisione su WhatsApp e Telegram.

**Comment by Pinzauti** [comment]
Ma quale è l'md che genera i vari post?

**Comment by iltempe** [comment]
@Pinzauti se ti riferisci alle segnalazioni eccolo qua
https://github.com/emergenzeHack/terremotocentro/blob/master/_layouts/issue.html
