### ISSUE TITLE
migliorare UX dei form di ricerca

### ISSUE THREAD

**Issue by marco-acorte** [emergenzeHack/terremotocentro#334]
migliorare UX dei form di ricerca come da immagine

![image](https://cloud.githubusercontent.com/assets/6375935/18718938/8a2f6f9e-8025-11e6-894e-a5f1aaa4b07b.png)

usare questo HTML code + bootstrap

`<div class="form-group">    
      <div class="input-group">
            <div class="input-group-addon">Cerca:</div>
            <input type="text" class="form-control">
    </div>
</div>`

**Comment by marco-acorte** [comment]
applicare in 
http://terremotocentroitalia.info/
http://terremotocentroitalia.info/news/
http://terremotocentroitalia.info/vittime/

**Comment by marco-acorte** [comment]
fatto una cagata ... devo inserire questo codice qui:

`$(document).ready(function() {
  $("div.sieve").sieve({ itemSelector: ".panel-info", 
    searchTemplate: "<div class='form-group'><div class='input-group'><div class='input-group-addon'>Cerca:</div><input type='text' class='form-control' placeholder='scrivi il testo da cercare...'></div></div>" });
});`

**Comment by iltempe** [comment]
chiudo.
