### ISSUE TITLE
OFF TOPIC: elenco comuni ESCLUSI dal cratere

### ISSUE THREAD

**Issue by annaluciont** [emergenzeHack/terremotocentro#335]
Provincia: MACERATA
- Acquacanina
  sindaco Giancarlo Ricottini  
  Indirizzo: Via Giacomo Leopardi 29, 62035 Acquacanina MC  
  Telefono: 0737 52143
- Bolognola
  sindaco Cristina Gentili  
  Indirizzo:Via L. Maurizi, 20 - 62035  
  Tel: +39 0737 520 225
- Camerino
  sindaco Gianluca Pasqui  
  Indirizzo: Corso Vittorio Emanuele II, 62032 Camerino MC  
  Telefono: 0737 634711
- Castelsantangelo sul Nera 
  sindaco Mauro Falcucci  
  sindaco@castelsantangelo.sinp.net  
  Indirizzo: Via Roma, Castel Sant'angelo Sul Nera MC 
  Telefono:0737 970039
- Fiastra
  sindaco Claudio Castelletti  
  Indirizzo: Via Roma, 1, 62035 Fiastra MC  
  Telefono: 0737 52112
- Fiordimonte
  sindaco Massimo Citracca  
  Indirizzo: Via Roma, Valle E Castello MC  
  Telefono: 0737 644115
- Montecavallo
  sindaco Pietro Cecoli  
  Indirizzo: Via Roma, 19, Monte cavallo MC  
  Telefono: 0737 519728
- Muccia
  sindaco Mario Baroni  
  Indirizzo: Via Roma, 5 - 62034
  Tel: +39 0737 646 135
- Pieve Torina  
  sindaco Alessandro Gentilucci  
  Indirizzo: Via Roma, 126 - 62036    ù
  Tel: +39 0737 518 022
- Pievebovigliana
  sindaco Sandro Luciani  
  Indirizzo: Piazza Vittorio Veneto - 62035  
  Tel: +39 0737 44126
- Serravalle di Chienti 
  sindaco Gabriele Santamarianova  
  Indirizzo: Corso Giacomo Leopardi, 77 - 62038  
  Tel: +39 0737 53121
- Ussita
  sindaco Marco Rinaldi  
  Indirizzo: Piazza XI Febbraio, 5, 62039 Ussita MC  
  Telefono: 0737 971211
- Visso
  sindaco Giuliano Pazzaglini  
  Indirizzo: Largo G.B. Gaola Antinori, 1, 62039 Visso MC
  Telefono: 0737 95120

**Comment by favoeva** [comment]
http://www.ilgiornale.it/news/politica/terremoto-corsa-agli-aiuti-i-comuni-esclusi-lista-1302920.html 

Il Giornale 5 settembre 2016 

_"Sono 16 i paesi indicati nel primo decreto della presidenza del Consiglio: cinque nelle Marche, cinque in Abruzzo, due nel Lazio e quattro in Umbria. Uno (laziale) in più, 17, quelli interessati invece dal decreto di sospensione dei tributi firmato da Pier Carlo Padoan.
Ma star dentro ai «confini» del disastro può voler dire molto, perché il nesso tra sisma e danni subiti non è messo in discussione. Il neo commissario alla ricostruzione, Vasco Errani, ha invitato a stare tranquilli, assicurando che «ci sarà riconoscimento del danno anche fuori dal cratere, laddove sia dimostrabile un legame diretto tra terremoto e danno puntuale». Ma sindaci e politici locali non stanno poi così tranquilli, visto che, al momento, già tanti lamentano di essere rimasti fuori dal decreto del Mef che congela le bollette. Così per esempio nelle Marche il governatore Luca Ceriscioli mette le mani avanti, e snocciola i nomi di ben 60 comuni che quando la terra ha tremato avrebbero riportato danni e lesioni. E anche in Abruzzo il presidente della Regione Luciano D'Alfonso «allunga» la lista, indicando in 29 il numero dei centri abitati che lamentano problemi in seguito al sisma. Insomma, la partita per la definizione dei «confini» del cosiddetto cratere sismico è cominciata."_

che ne dite: per la mappa def. bisogna recuperare le liste di Ceriscioli e D'Alfonso e incrociarle con lista MEF + @annaluciont ?

**Comment by psykola** [comment]
@annaluciont trovo davvero poca rassegna stampa sulla faccenda...

**Comment by annaluciont** [comment]
Prova anche tu a cercare l'ordinanza della Prit. Civile, intorno al 28/29 agosto, dovrebbero essere riportati i comuni nel cratere.

**Comment by iltempe** [comment]
@psykola @annaluciont su questo issue abbiamo altro da dirci? posso chiudere?
