### ISSUE TITLE
Proposta layout a cascata

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#337]
Che ne dite? http://masonry.desandro.com/

secondo voi si potrebbe usare per rendere il sito più "accattivante"? o crea dei problemi funzionali?

**Comment by marco-acorte** [comment]
in realta giocando html e bootstrap ci riusciamo gia...
http://webjeda.com/cards/

**Comment by iltempe** [comment]
l'idea non mi pareva malvagia....anzi.

**Comment by marco-acorte** [comment]
non so se aggiungere un ulteriore layer javascript (masonry) possa appesantire ancora di più' il peso di tutto il sito che ora viene fruito da mobile embeddato nelle app (x ora android) ...
cmq dicevo che avendo gia' bootstrap usato come framework UI possiamo lavoraci sopra per ottenere un effetto CARD tipo quello ottenuto con masonry... un esempio di come potrebbe venire lo si puo vedere qui: http://webjeda.com/cards/

appena faccio pace con git e i proxy web provo in un fork a fare una prova....

**Comment by iltempe** [comment]
chiudo.
