### ISSUE TITLE
Dashboard degli offerenti di servizi

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#339]
Ciao, faccio una proposta
OBIETTIVO: incrementare l'efficacia dell'incrocio domanda (segnalazioni) / offerta (persone che offrono servizi). Noi tracciamo le prime e le seconde al momento nello stesso modo. Ma quando riceviamo una segnalazione avremmo bisogno secondo me di poter ricercare velocemente fra le disponibilità di offerta in modo da vedere in un colpo solo se c'è qualcuno adatto e chiudere il cerchio velocemente. Si potrebbe ragionare su una ulteriore specificazione delle label come suggerito da @lorenzoperone https://goo.gl/P1C2xf e forse si potrebbe pescare dalla repo e organizzare gli offerenti in un dashboard facilmente ricercabile.
che ne dite?
grazie
c

**Comment by iltempe** [comment]
ne dico che mi sembra una ottima "naturale evoluzione di TCI" adesso che abbiamo un sistema per registrare i dati: relazionare richieste con offerte. Si può fare sia con delle mappe cercando di evidenziare nei luoghi chi offre e chi ha bisogno e si può fare anche etichettando per argomento. Su quest'ultimo punto ci sono già delle label per tipologia di richiesta ma possiamo ovviamente modificarle o aggiungerne altre che riteniamo utili.

**Comment by c83n** [comment]
yo !

**Comment by annaluciont** [comment]
@iltempe forse si riferisce a  issue chiusa #314
Ma @c83n si è spiegato, ovviamente, molto meglio.
@favoeva @Manfro @cristigalas

**Comment by iltempe** [comment]
@c83n si spiega sempre benissimo ... sono io quello contorto ;-) intanto nella sezione mappe ho iniziato a mettere le mappe delle singole categorie di informazioni ne possiamo fare anche con più livelli. http://terremotocentroitalia.info/mappe/
