### ISSUE TITLE
Struttura label -> funzionalità di TCI

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#340]
Ciao,
grazie allo spunto di @lorenzoperone (https://goo.gl/P1C2xf) faccio una proposta che probabilmente merita un approfondimento di medio periodo

Sintesi: l'architettura delle label determina la funzione della piattaforma.
- Pertanto a diverse "strutture di labeling" corrispondono diverse funzionalità e vice versa

Faccio dei semplici esempi ma il focus del post non sono gli esempi in sé ma la necessità di organizzare questo processo di architettura del labeling che a mio avviso dovrebbe coinvolgere esperti e persone sul campo per ogni funzionalità a seconda delle esigenze.
1. EMERGENZA: incrocio fra segnalazioni dal territorio e offerta di beni e servizi di base 
   (Struttura dei label del tipo: "cibo", "tende", etc....)
2. MONITORAGGIO RICOSTRUZIONE: incrocio fra “sensori” locali che monitorano cantiere e desk che hanno competenze di monitoraggio 
   (Struttura dei label del tipo: "segnalazione azienda", "potenziale irregolarità", "stato di avanzamento" etc...)
3. SUPPORTO DEL WELFARE LOCALE:  mettere a disposizione tale tecnologia dei comuni colpiti in modo da utilizzarla anche per la ricostruzione di una rete di servizi funzionali alle esigenze del territorio da estendere anche all’ordinaria amministrazione.
   (Struttura dei label del tipo: "servizio 1", "tipo di bisogno" etc.... ovviamente da concordare con e istituzioni locali)

Che ne dite?
grazie
c

**Comment by iltempe** [comment]
Ok. mi pare che in parte abbia a che fare anche con #339 . Ma se tu sei d'accordo potremmo buttare giù soprattutto partendo dal campo dei nuovi "modelli" di labelling da integrare con quelli esistenti in modo da diversificare tutto nei tre modi che proponi. che dici?

**Comment by c83n** [comment]
appena ho un attimo sono a bordo di sta cosa con tutti i neuroni (vivi) che
mi restano :)
domani pome abbiamo riunione e vorrei affrontare questa cosa con i miei
con la dovuta calma vi aggiorno appena posso
daje
c

Il giovedì 22 settembre 2016, Iltempe notifications@github.com ha scritto:

**Comment by marco-acorte** [comment]
allora io una mezza idea di come riorganizzare le label ce l'avrei...

@iltempe @c83n
la butto li.... 

https://docs.google.com/spreadsheets/d/1MWu8sJVvZ33VXgfDhXNSpFdh_SfQeiXbQpzO5fFURng/edit#gid=0

**Comment by marco-acorte** [comment]
esempio di flusso approvativo issue con esito (positivo/negativo)
![new-mind-map](https://cloud.githubusercontent.com/assets/6375935/18883141/627e8450-84e2-11e6-846e-28e6c5088397.png)

**Comment by c83n** [comment]
yo yo yo yo

Il martedì 27 settembre 2016, MARCO ACORTE notifications@github.com ha
scritto:

**Comment by iltempe** [comment]
@marco-acorte non leggo il documento. @favoeva coordiniamoci con @marco-acorte sulle label. grazie

**Comment by marco-acorte** [comment]
ecco il link.... @iltempe @favoeva 
https://docs.google.com/spreadsheets/d/1MWu8sJVvZ33VXgfDhXNSpFdh_SfQeiXbQpzO5fFURng/edit?usp=sharing

**Comment by iltempe** [comment]
@favoeva @marco-acorte la politica di gestione delle label si può mettere nel WIKI?

**Comment by marco-acorte** [comment]
@favoeva @iltempe per chiarire... mi sembrava che il flusso 

![new-mind-map](https://cloud.githubusercontent.com/assets/6375935/18883141/627e8450-84e2-11e6-846e-28e6c5088397.png)

non fosse in uso... ad esempio il KO non lo vedo tra le label disponibili

**Comment by iltempe** [comment]
@favoeva tu avevi una linea guida aggiornata per le label?

**Comment by iltempe** [comment]
chiudo.
