### ISSUE TITLE
Aggiungere Mappa Campi

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#342]
@marco-acorte ha fatto questa mappa dei campi.
https://umap.openstreetmap.fr/it/map/campi-e-tende-comuni-colpiti-dal-sisma_103694#12/42.6544/13.2598

chi può la inserisce in un post tra le mappe del sito?

grazie

**Comment by c83n** [comment]
@marco-acorte uomo del secolo 
ps: scuse rinnovate per la Giorgia :)

**Comment by annaluciont** [comment]
@marco-acorte dovrebbero esistere delle immagini  se vuoi inserirle (prova a cercarle fra le immagini inviate dal bot telegram) ;)

**Comment by iltempe** [comment]
@marco-acorte questa mappa è aggiornata? i dati da dove vengono?

**Comment by iltempe** [comment]
@marco-acorte riusciamo a risalire alla fonte dei dati secondo te?

**Comment by marco-acorte** [comment]
la fonte dei dati e' la mappa fatta su google maps 
https://www.google.com/maps/d/viewer?mid=1-wdTR-Z51PvWTFMYVL7kHSbL9Wk
fatta da tale Massimo Tufano... (https://www.facebook.com/massimo.tufano.39) non mi ricordo chi l'aveva segnalata... di fatto io l'ho esportata i POI in KML e reimportata in OSM

**Comment by iltempe** [comment]
chiudo.
