### ISSUE TITLE
DOMANDA sulla TRASPARENZA

### ISSUE THREAD

**Issue by annaluciont** [emergenzeHack/terremotocentro#345]
Premetto che la seguente è solo una considerazione del tutto neutrale, nessuna polemica.
Per cui riporto, solo come esempio, la raccolta fondi Slow Food:
http://www.slowfood.it/un-futuro-amatrice-locali-aderenti/

Oltre alla donazione di 2 euro promuovono anche quest'altra formula:
"Ma non è tutto! Nelle casse dei negozi sarà inoltre possibile effettuare una donazione a favore delle vittime del terremoto del Centro italia."

 Ad ogni modo, per la qualsiasi formula che ciascuno decide di adottare,  sono curiosa di sapere se:

1) è possibile monitorare il flusso in entrata e in seguito quello in uscita dei locali aderenti? 
(spesso accade che per varie questioni il gestore non emette ricevuta, ergo le 2 euro dell'entrata sfuggono e potrebbero restare nelle casse private del gestore)

2) idem 1 ma per quanto riguarda il flusso sia in entrata che in uscita delle donazioni spontanee raccolte nei vari punti di ristoro. 

Per flusso di entrata mi riferisco al passaggio monetario tra cliente e ristoratore.
Per flusso in uscita mi riferisco al passaggio monetario tra ristoratore e conto Iban messo a disposizione da Slow Food.

3) se si può poi monitorare sia le entrate che le uscite del conto Iban.

4) se è corretto, da un punta di vista legale, raccogliere fondi senza avere un progetto specifico
(es. raccolta fondi causale "per la ricostruzione" è troppo generico, può significare qualsiasi cosa o niente)

**Comment by cristigalas** [comment]
Mah, ciò che proponi @annaluciont mi pare molto complesso. Secondo me il nostro impegno a diffondere info utili e verificate significa che verifichiamo l'attendibilità dell'informazione, ovvero l'attendibilità della fonte. Non mi spingerei, almeno al momento, più in là. Per come la vedo io, siamo un servizio che diffonde un'informazione di pubblica utilità e facilita l'incontro tra offerte (verificate) e bisogni (verificati), insomma uno strumento per 'avvicinare' solidarietà e necessità. Mi pare già molto ;-)

**Comment by annaluciont** [comment]
Certo @cristigalas !! 
Occorre pensare anche al medio periodo, quando le segnalazioni di "bisogno materiale" non saranno più necessarie e i bisogni sono di altra natura (come il mio, è che già fremo da adesso!) :)

**Comment by annaluciont** [comment]
Abbiamo cominciato a parlarne anche nell'hangout della sera scorsa..

**Comment by annaluciont** [comment]
Chiudo perchè deve essere meglio argomentata. La riaprirò quando troverò le parole.
