### ISSUE TITLE
Bot che notifichi commenti Disqus su gruppo Media Team TCI

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#346]
Sarebbe utile un bot che giri le notifiche lasciate con Disqus ai post sul terremotocentroitalia.info. Il bot potrebbe essere inserito come membro di un gruppo per la presa in carico di segnalazioni o commenti da moderare (es. Media Team TCI).

**Comment by aborruso** [comment]
E' semplice, c'è il feed RSS http://terremotocentroitalia.disqus.com/latest.rss

Quindi basta scegliere in canale di "revisione" contenuti fare postare il bot

**Comment by annaluciont** [comment]
me serve un tutorial!

**Comment by epoeta** [comment]
@aborruso mi sembra che Media Team possa essere un 'luogo' adeguato :-)

**Comment by aborruso** [comment]
Tutto fatto, arriverà avviso sul gruppo Telegram media team.
