### ISSUE TITLE
Inserire data di scadenza nelle segnalazioni raccolta fondi, fabbisogni, notizie utili

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#354]
Secondo me occorre prevedere nelle segnalazioni che inseriamo una "data di scadenza", in particolare per raccolte fondi, fabbisogni e notizie utili ma forse è meglio prevederle per tutte e poi le inseriamo solo dove è indicato o serve. Dunque un campo data di scadenza non obbligatorio che poi in automatico allo scadere chiuda la issue. Aiuterebbe molto a tenere pulito e aggiornato il database delle segnalazioni. Che ne dite @iltempe @favoeva @epoeta @Manfro @annaluciont @psykola?

**Comment by iltempe** [comment]
esiste un campo a destra sotto le labels negli issue chiamato Milestone. Normalmente è usato per definire entro quando va fatto qualcosa. Si possono definire varie Milestone come scadenze (1 giorno, 1 settimana, 1 mese 1 anno) può andare?

**Comment by cristigalas** [comment]
Potrebbe essere una soluzione credo, ma si possono inserire solo scadenze ad 1 giorno, 1 mese, ecc. o anche a 2 o 3 giorni, 2 o 3 settimane, ecc.? Insomma modulare il tempo di scadenza? Comunque bisognerebbe provare e vedere...

**Comment by iltempe** [comment]
puoi fare delle prove. in ogni caso puoi mettere anche intervalli di giorni precisi.

**Comment by cristigalas** [comment]
Ok, farò delle prove e vediamo...

**Comment by cristigalas** [comment]
Scusa Matteo, ho cercato di impostare la scadenza con milestone a questa issue https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/678 ma non capisco come fare... Help!
