### ISSUE TITLE
Rendere visibili campi IBAN, causale, intestazione nelle raccolte fondi

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#355]
Nelle segnalazioni di raccolte fondi non si visualizzano i campi Iban, intestazione, causale, ecc. nonostante su Github siano inserite. Vedi ad esempio qui http://terremotocentroitalia.info/issues/687/index.html

**Comment by iltempe** [comment]
dovrebbe essere ok.
