### ISSUE TITLE
Bot telegram supporto cittadini

### ISSUE THREAD

**Issue by Joker8991** [emergenzeHack/terremotocentro#356]
Buongiorno, sto realizzando un bot telegram che fornisca alcune indicazioni utili ai cittadini.
Il bot dovrebbe fornire la posizione di punti di interesse per emergenze o altro.
Sto usando openstreetmap come base di dati, come consigliato da Matteo Fortini. Purtroppo i dati disponibili per i punti di interesse per le emergenze quali: estintori, idranti, defibrillattori, punti di raccolta(ammassamento), sono quasi nulli. Ci sarebbe qualcuno disposto a taggare tali luoghi su openstreetmap o magari a fornirmi la loro posizione in modo che io possa provvedere a taggarli?
Grazie mille

**Comment by iltempe** [comment]
@mfortini cosa avevi in mente?

**Comment by iltempe** [comment]
@Joker8991 come ti ho detto in chat, nel contempo valutiamo questa cosa
http://www.salvatorecordiano.it/creare-un-bot-facebook-guida-passo-passo/

**Comment by iltempe** [comment]
chiudo perchè abbiamo aperto questo #376
