### ISSUE TITLE
Creare Feed News Terremoto da Protezione Civile

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#357]
La protezione civile italiana ha una pagina di comunicati stampa solo sul terremoto.

http://www.protezionecivile.gov.it/jcms/it/comunicati_stampa.wp?selectedNode=terremoto_centro_italia_2016

Può essere utile per alimentare in modo automatico gli issue di github con la label Notizie Utili e Bollettino creare un FEED RSS di queste notizie.

**Comment by lorenzoperone** [comment]
Forse si potrebbe filtrare questo 
http://www.protezionecivile.gov.it/jcms/do/jprss/Rss/Feed/show.action?id=23577&lang=it

**Comment by ebergam** [comment]
@lorenzoperone ho fatto un import veloce ed è tutto abbastanza pulito. Devo solo capire come "tradurre" la data in maniera furba. https://docs.google.com/spreadsheets/d/1sl8LWssjH2eGedsH5NJ0XnP_FAJNPMbx7C3kYLoIkF8/edit#gid=581332022

**Comment by aborruso** [comment]
@ebergam ho modificato un po' il foglio ed ho ottenuto questo http://feeds.feedburner.com/Tci-FeedProtezioneCivile

**Comment by ebergam** [comment]
@aborruso Su validator vedo sempre lo stesso problema, fa lo stesso se non valida e teniamo la data così?

**Comment by aborruso** [comment]
@ebergam qualcuno ha modificato il foglio. Lo rendi per favore accessibile in scrittura solo a me, te, Lorenzo e Matteo?

Chi vuole accesso, fa un fischio e si da.

Torno a metterlo a posto

**Comment by aborruso** [comment]
@ebergam dovrei avere risolto http://feeds.feedburner.com/Tci-FeedProtezioneCivile

**Comment by ebergam** [comment]
@aborruso poi aprirò un'issue per farti una statua d'oro massiccio

**Comment by c83n** [comment]
basta adulare borruso plis
e' GIA' leggenda :)

Il martedì 27 settembre 2016, Enrico Bergamini notifications@github.com
ha scritto:

**Comment by nelsonmau** [comment]
@aborruso @ebergam perché passare da gdoc se il feed è funzionante? Per filtrare solo TCI?

**Comment by iltempe** [comment]
quindi questo feed è fatto?

**Comment by ebergam** [comment]
@nelsonmau l'URL usato è quello della ricerca a tag terremoto, quindi già specifico, gli altri hanno altro dentro e vanno filtrati. 
@iltempe yes, il definitivo è: http://feeds.feedburner.com/Tci-FeedProtezioneCivile

**Comment by iltempe** [comment]
Ok, @aborruso lo possiamo usare come gli altri feed rss? Attualmente vanno direttamente nel canale telegram e non su twitter. che dici? https://bubbl.us/#MzYwNDQ5Mi83MTc3NDQ1LzhjNTk2Y2UwYTMxOTUwNWIzOGQ3MmQ1OWI5NGI2YzNj?X

**Comment by iltempe** [comment]
chiudo. il feed lo abbiamo creato.
