### ISSUE TITLE
Rilasciare tutti i dati di TCI in formato open

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#360]
Vorrei cominciare a discutere del fatto di inserire sul nostro sito una sezione in cui ci sono i link dinamici ai nostri dati in formato open con relativa licenza di uso.

Vorrei aprire tutti i dati in nostro possesso ovvero almeno:
- segnalazioni
- vittime
- press
- eventuali dati georiferiti elaborati da noi (verificando le licenze se provengono da altre fonti)

Attualmente le legal del sito indicano come licenza di uso dei contenuti la CC BY v3.0.
http://terremotocentroitalia.info/legal/

licenza che io propongo è quindi la CC BY v3.0.

Vorrei inoltre associare una licenza di riuso del sito.

Si accettano proposte/suggerimenti/critiche.

**Comment by iltempe** [comment]
Intanto ho creato questa pagina.
http://terremotocentroitalia.info/opendata/
Si alimenta da un opendata.csv nella cartella data del repository.
Fatemi sapere che ne pensate

**Comment by c83n** [comment]
a me pare una fi - ha - ta :)
solo 1 pregunta scema: ma la colonna label si puo' spacchettare? non saprei
come se non creando un'infinita' di colonne tanti quanti sono i label per
poi metterci flag x ma di sicuro ci sono modi piu' intelligenti per farlo
credo che faciliterebbe l'attivita' di filtro per utente desk che usa solo
xls o simili
ma magari e' una boiata
intanto #daje
c

Il giovedì 29 settembre 2016, Iltempe notifications@github.com ha scritto:
