### ISSUE TITLE
#URGENTE - BOT TELEGRAM NON FUNZIA

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#361]
ciao il bot dà ancora problemi
dopo l'invio della foto non dice "segnalazione registrata"

**Comment by c83n** [comment]
faccio finta di essere edo e scrivo: "porco giuda hai ragione"

**Comment by drizzt** [comment]
Ciao, scusa il ritardo ma ci ho messo un po' per debuggare il problema.
Ho già pushato un fix sul nostro repository e fatto pull request sul repository del bot telegram (WPGov/telegram-bot#2).

Puoi verificare?

Grazie

**Comment by c83n** [comment]
mito!!!!!
già che ci sono ti chiedo ma il problema dell'overload dovuto al fatto che
la versione gratis aveva capacity limitata è stato risolto?
grazie
c

2016-09-28 12:54 GMT+02:00 Timothy Redaelli notifications@github.com:

**Comment by drizzt** [comment]
ho cambiato il numero di "connessioni" contemporanee a 8, per cui il problema dovrebbe essere risolto
