### ISSUE TITLE
#MONITORAGGIO Ricostruzione - richiesta di DATI APERTI a D.P.C :)

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#362]
Ciao, 
scrivo in merito alla questione monitoraggio per iniziare a ragionare sui DATI aperti da richiedere alle istituzioni. Propongo di avviare un brainstorming per individuare più precisamente possibile i dati di cui richiediamo il rilascio.

Se lo ritenete possiamo usare questo google sheet per inserire proposte: https://goo.gl/Jtmeyr

Segue un breve riassunto delle puntate precedenti:
-  19 settembre: richiesta incontro a Commissario e DPC in merito a monitoraggio
- 23 settembre: Commissario e Premier annunciano prossima costruzione di piattaforma open data
- 28 settembre: segreteria Commissario comunica ok incontro dopo il 7 ottobre
- 04 ottobre: call di coordinamento (h 11:30/13:00) - tutti invitati (add me on skype "chrisinaction")

Progetto su preparazione incontro made by @favoeva: https://goo.gl/G3WFb9 

Ciao e grazie
c

**Comment by psykola** [comment]
@c83n ho cambiato il titolo, i titoli delle issue devono essere pensati come quelli dei giornali. devi capire subito di che si tratta
(non tutti vagliamo ogni giorno le centinaia di issue aperte) XP
Spero tu non ti offenda

**Comment by c83n** [comment]
@psykola io sono risaputamente uno che si offende :)
brava anzi mi ero reso conto che il titolo era criptico sorry 
#menitencs

**Comment by c83n** [comment]
Riporto post di Antonella Milanini (@milanini) fatto in 1 altra repo (terremotocentro_segnalazioni)
https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/740

Dopo un mese di frequentazione e osservazione dell'esperienza di TCI, sono convinta che abbiano preso il via anche a livello istituzionale delle azioni di informazione mimetiche, ed è un bene!
Forse ora occorre tracciare una mappatura più ampia e tessere una trama più fitta e mi spiego.
Il Comune di Amatrice dopo un mese dal terremoto ha individuato l'elenco delle opere pubbliche 
necessarie per una ricostruzione e con lo slogan Adotta un'opera, https://docs.google.com/spreadsheets/d/12HK_aH5m7As8FBG30aPPvQ1uiYhP7zrGBsgI4XO1T6s/edit?usp=sharing

ha avviato una raccolta fondi contrassegnata da un proprio obbligo di informazione e trasparenza nei confronti di ogni singolo donatore.
L'adozione di ogni singola opera in realtà potrebbe avere molteplici aspetti di cura:
dal punto di vista di chi sta raccogliendo documentazione ai fini della trasparenza, diventa più semplice, ricostruirne una storia in atti amministrativi relativamente recenti (ultimi 5 anni se ci sono), ma anche provare a dare suggerimenti ai residenti rimasti sul posto di azioni di monitoraggio permanente sul presente, e sul futuro possibile coinvolgendosi in processi partecipati veri e non da sondaggio o da fruizione passiva.
Inoltre ogni opera potrebbe già apparire indicata su una mappa georeferenziata a cui agganciare tutta una serie di informazioni, non solo amministrative, ma storiche, antropologiche, culturali, quelle informazioni che si tramandano anche nell'oralità dei residenti (penso a ipotesi come Mappi-na) in termini di recupero di memoria dei luoghi, che potrebbe vedere protagonisti i vari Comitati locali e Associazioni mobilitate. sul posto, con un lavoro di riscoperta o svelamento di microstorie, capaci di consentire una sorta di "walkabout" a 360° su ogni opera da ricostruire, ma anche di solidificare le radici di chi rimane.
Quindi potremmo auspicarci e spingere affinché anche gli altri Comuni colpiti dal sisma, definiscano quanto prima un elenco delle opere da ricostruire, affinché attorno a queste si ricostruisca una comunità di saperi e di buona amministrazione. Cosa ne pensate?

**Comment by c83n** [comment]
@iltempe @chiccap dovremmo iniziare a porci il problema dell'archiviazione di dataset come quello di Antonella Milanini (ps: potete aggiungerla a questa repo come @milanini?) poiché ad esempio il file di amatrice ha senso solo se gli diamo una versione e una data di pubblicazione, altrimenti diventa obsoleto nel giro di poco. @iltempe secondo me sarebbe opportuno aprire un issue in cui impostiamo un modo di classificazione e archiviazione dei dataset che via via raccogliamo dal web, che dite? il tutto si integra con la #299

**Comment by c83n** [comment]
UPDATE RIUNIONE 04 OTTOBRE 2016:

Partecipanti: Beatrice Costa (AA), Matteo Tempestini (TCI), Antonella Milanini (TCI), Isabella Mori (Cittadinanza attiva), Andrea Nelson Mauro (OnData), Eugenio Orsi (Riparte il Futuro), Chiara Putaturo (Transparency Italia), Boris Vitiello (AA), Annalucia Cardillo (AA), Christian Quintili (AA), Lorenzo Perrone (Ninux)

Prossimi passi concordati
- AA recall Commissario e conferma appuntamento
- TUTTI quando abbiamo DATA / ORARIO / LUOGO decidiamo delegazione e ODG della riunione
- prepariamo prima di riunione nota alla stampa / CS da circolare a seguito dell’incontro
- TUTTI danno input aggiuntivi su DATI da richiedere
- Christian e @chiccap predispongono collegamento di comunicazione tra questo gruppo e TCI.

---

Note della call

ACTIONAID - update su lavoro preparatorio:
- Issue github con stato dell'arte: https://goo.gl/L6hHVv
- Rappresentazione grafica di quello che vogliamo fare: https://goo.gl/iGiLhk
- Draft lista dataset da richiedere (in progress): https://goo.gl/Jtmeyr
-  in caso di incontro ottenuto predisponiamo CS / nota alla stampa su contenuti – esiti incontro

TRANSPARENCY
- utile questa impostazione proposta di AA; abbiamo progetto aperto in Italia con AA su Patti di Integrità (monitoraggio gare d’appalto su alcune opere) à proposta di applicare IPACT a un’opera della ricostruzione
- Registro dei titolari effettivi (beneficial ownership) delle società sarà una sezione specifica del registro imprese - alla revisione sta lavorando Isabella Fonata del MEF. La scadenza a livello europeo (la direttiva europea che prevede il registro è la Quarta Direttiva Antiriciclaggio) per l'introduzione è giugno 2017, ma probabilmente in Italia lo introdurranno prima.

CITTADINANZATTIVA
- darà input su documenti (non visti online)
- occhio ad appalti sotto soglia
- proposta di protocollo se c’è disponibilità da parte della struttura

ONDATA
- importante invece che piattaforma dati aperti perché tanta complessità difficilmente comprimibile in unico strumento
- chiedere una figura nella struttura commissariale a cui far riferimento
- fare link sempre con community TCI
- mettere insieme TCI con gruppo

RIPARTEILFUTURO  
- darà input su documenti (non visti online)

TCI [Antonella Milanini]: 
- ogni strumento deve essere semplice e usato dai cittadini che stanno sul posto.

**Comment by c83n** [comment]
UPDATE 18 OTTOBRE 2016 - DATA INCONTRO CON ERRANI

Abbiamo una data per incontrare il commissario Errani:  
martedì prossimo 25 ottobre ore 12.30
La delegazione può essere formata al massimo da 3 persone e dobbiamo comunicarla entro venerdì.
Vi propongo quindi di sentirci via skype venerdì alle 10 per
- decidere la delegazione
- confermare i messaggi / le richieste con cui vogliamo presentarci – preparare eventuale materiale.
- condividere i contenuti del CS / nota alla stampa che vorremmo fare uscire in seguito

Fateci sapere chi ci sarà venerdì.
grazie

**Comment by lorenzoperone** [comment]
Ciao,
io venerdì ci sarò.
Ciao.
l.

Il 18/10/2016 10:09, christian quintili ha scritto:

**Comment by favoeva** [comment]
alle 10 orario impossibile per me mi spiace :(

**Comment by cristigalas** [comment]
Anche per me le 10 è impossibile...

**Comment by claucole** [comment]
Purtroppo venerdi' a quell'ora non posso
Claudio

**Comment by psykola** [comment]
io per la call ci sono. 
Ma non è possibile farla di sera, visto che venerdì mattina le persone più interessate/coinvolte non ci sono?

**Comment by milanini** [comment]
se confermate, alle 10 ci sono

**Comment by c83n** [comment]
ciao a tutte e tutti
domani vi so dire se riunione e' confermata
giorgia hai perfettamente ragione e mi impegno a suggerire orari un po'
piu' comodi per tutti a partire dalla prossima riunione.
grazie mille e vi aggiorno qui
un abbraccio e daje
c

Il mercoledì 19 ottobre 2016, milanini notifications@github.com ha
scritto:

**Comment by chiccap** [comment]
Ciao! La riunione di domani è confermata h14.
A domani!!

**Comment by claucole** [comment]
Ciao, grazie, a quell'ora domani ci sono e mi farebbe piacere partecipare. Un saluto, Claudio

**Comment by chiccap** [comment]
Ciao a tutti e scusateci per il collo di bottiglia nelle comunicazioni. Vi chiediamo di mandare una email con vostro utente skype a me e a christian (chiara.parapini@actionaid.org e christian.quintili@actionaid.org). Vi chiediamo contatto e vi aggiungiamo alla call che è confermata per domani alle 14.  
Per il futuro ci impegnamo a organizzare call in orario più comodo. Grazie

**Comment by milanini** [comment]
Ciao a tot, confermo per domani (skyoe: antonella.milanini) e vi segnalo, se nn lo ha avete già letto nel Decreto terremoto: **Art. 36 Disposizioni in materia di trasparenza e di pubblicita' degli atti**
1. Tutti gli atti del Commissario straordinario relativi a nomine e designazioni di collaboratori e consulenti, alla predisposizione dell'elenco speciale di cui all'articolo 34, comma 1, nonche' alle relative iscrizioni ed esclusioni, alla programmazione di lavori, opere, servizi e forniture, nonche' alle procedure per l'affidamento di appalti pubblici di servizi, forniture, lavori e opere ed alle erogazioni e concessioni di provvidenze pubbliche per la ricostruzione privata, ove non considerati riservati ai sensi dell'articolo 112 ovvero secretati ai sensi dell'articolo 162 del decreto legislativo 18 aprile 2016, n. 50, sono pubblicati e aggiornati sul sito istituzionale del commissariato straordinario, nella sezione «Amministrazione trasparente» e sono soggetti alla disciplina di cui al decreto legislativo 14 marzo 2013, n. 33 e successive modificazioni. Nella medesima sezione, e sempre ai sensi e per gli effetti del predetto decreto legislativo n. 33 del 2013, sono altresi' pubblicati gli ulteriori atti indicati all'articolo 29, comma 1, del decreto legislativo n. 50 del 2016.

**Comment by chiccap** [comment]
Buongiorno a tutti, torno da voi chiedendovi di nuovo immensamente scusa in quanto la riunione è questa mattina h10. C'è stato un errore. Mi dispiace moltissimo per i mille cambi e per il poco preavviso, ho i vostri contatti e provvederó ad aggiungervi alla Skype call. a dopo

**Comment by iltempe** [comment]
Posso chiudere?

**Comment by lorenzoperone** [comment]
Il 21/10/2016 08:46, Chiara ha scritto:

> Buongiorno a tutti, torno da voi chiedendovi di nuovo immensamente 
> scusa in quanto la riunione è questa mattina h10. C'è stato un errore. 
> Mi dispiace moltissimo per i mille cambi e per il poco preavviso, ho i 
> vostri contatti e provvederó ad aggiungervi alla Skype call. a dopo
> 
> Ciao Chiara,
> purtroppo ho un appuntamento alle 9:30 per le 10:00 non credo di aver 
> finito.
> Mi connetterò appena mi è possibile.
> Vi rinnovo comunque la disponibilità di OnData a partecipare 
> all'incontro con Errani per supportare la definizione dei formati dei 
> dati da richiedere e per un supporto tecnologico al processo.
> Ciao.
> Lorenzo

**Comment by c83n** [comment]
secondo me puo' essere utile anche x aggiornamenti su next steps ma magari
troviamo modo ancora migliore, chesso' googlegroup? valutate voi comunque
cia' :)

Il venerdì 21 ottobre 2016, Iltempe notifications@github.com ha scritto:

**Comment by lorenzoperone** [comment]
Ciao Matteo,
direi di si.
l.

**Comment by c83n** [comment]
antonella grazie!

Ciao a tot, confermo per domani (skyoe: antonella.milanini) e vi segnalo,
