### ISSUE TITLE
Integrazione - whatzupp

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#364]
Ciao
mi segnalano che sarebbe fico integrare whatzupp come canale in ingresso
possibile?
c

**Comment by drizzt** [comment]
whatsapp non ha api per creare bot e non li vuole.
creare un bot violerebbe i loro termini d'uso

**Comment by c83n** [comment]
ma è possibile dire chessò scrivi a questo contatto che inserisce diretto in github?

**Comment by marco-acorte** [comment]
@c83n no purtroppo whatsapp non permette di sviluppare nessun codice per poter fare quello che chiedi... 
come dice @drizzt il codice si potrebbe pure scrivere ma violerebbe i loro termini d'uso della piattaforma e qualora se ne accorgessero (e se ne accorgono) poi bannano l'utente e ti mandano la SWAT  a casa :)

**Comment by c83n** [comment]
blame on them :)
grazie!
c

2016-09-28 17:28 GMT+02:00 MARCO ACORTE notifications@github.com:

**Comment by iltempe** [comment]
Potremmo valutare notifiche automatiche su Facebook Messenger che invece ha le API.

**Comment by c83n** [comment]
mica no? ...

Il mercoledì 28 settembre 2016, Iltempe notifications@github.com ha
scritto:

**Comment by tizianoblasi** [comment]
Effettivamente agganciare anche messenger potrebbe essere ottimo per allargare la base.

**Comment by iltempe** [comment]
chiudo perchè è inserito qui #356 e qui #376
