### ISSUE TITLE
RSS Protezione civile in tweet automatici

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#366]
Sì potrebbero "sparare" anche su Twitter gli RSS della Protezione civile? E anche quelli di Ingv, suggerisce @epoeta.

**Comment by iltempe** [comment]
@aborruso ha già fatto il feed di entrambi (vedere #357)

**Comment by cristigalas** [comment]
Ah ok, quindi significa che ora andranno in automatico su Twitter, oltre che su Telegram?

**Comment by iltempe** [comment]
attualmente come automatismi FEED io ho sulla mappa i feed di WAZE e INGV che vanno diretti su telegram. Su twitter non mi risulta niente Non so se @aborruso ha messo in piedi altro in questi giorni. https://bubbl.us/#MzYwNDQ5Mi83MTc3NDQ1LzhjNTk2Y2UwYTMxOTUwNWIzOGQ3MmQ1OWI5NGI2YzNj?X

**Comment by aborruso** [comment]
Ho appena attivato pubblicazione automatica su twitter di http://feeds.feedburner.com/Tci-FeedProtezioneCivile

**Comment by iltempe** [comment]
ok. La situazione aggiornata flussi è qui
https://bubbl.us/?s=7177445#MzYwNDQ5Mi83MTc3NDQ1LzhjNTk2Y2UwYTMxOTUwNWIzOGQ3MmQ1OWI5NGI2YzNj?X
