### ISSUE TITLE
Rivedere Pagina Mappe

### ISSUE THREAD

**Issue by tizianoblasi** [emergenzeHack/terremotocentro#368]
Ciao, [qui](http://terremotocentroitalia.info/mappe/) ci sono tantissime informazioni ma la forma di elenco non da giusto risalto a quelle più rilevanti. 

Si potrebbero mettere in evidenza le più rilevanti (bisogni, contatti, contatti e segnalazioni) magari con delle icone standard e lasciare gli altri link in coda per chi cerca risorse più specifiche.

**Comment by iltempe** [comment]
@tizianoblasi ottimo, fai un fork e ci proponi qualcosa?

**Comment by tizianoblasi** [comment]
@iltempe ciao, lo farei volentieri ma non sono uno sviluppatore. L'ho comunque segnalata perché mi sembra una pagina importante da mettere in rilievo, appena ci sono le energie per farlo.

**Comment by franziner** [comment]
ciao, per quanto riguarda le icone potrei pensarci io graficamente. Per integrarle nella pagina non saprei perchè non ho mai usato github (ma posso provarci se il backend della gestione delle pagine è simile a wordpress). 
Provo a fare un restyling grafico della pagina e poi capiamo con chi smanetta github se si può procedere? Aspetto conferma

**Comment by iltempe** [comment]
Potremmo fare una cosa del genere. http://iltempe.github.io/opendatagentediprato/

**Comment by franziner** [comment]
Sì, così è molto più immediato
Inizio a realizzare le icone e il restyling della pagina . Mi dò come scadenza la settimana prossima

**Comment by franziner** [comment]
Voilà, che ne pensate?
[iconemappe-tci.zip](https://github.com/emergenzeHack/terremotocentro/files/522842/iconemappe-tci.zip)
![layout-mappe-01](https://cloud.githubusercontent.com/assets/15049880/19286505/4ae0e7c6-8ffe-11e6-8d7a-98b7311fca85.jpg)

**Comment by c83n** [comment]
per me e' bellissima :)

Il martedì 11 ottobre 2016, Francesca Maio notifications@github.com ha
scritto:

**Comment by iltempe** [comment]
splendida. ho messo tutte le icone qui https://github.com/emergenzeHack/terremotocentro/tree/master/img/icone lavoro al layout

**Comment by franziner** [comment]
grazie :)

**Comment by iltempe** [comment]
@franziner fatto. http://terremotocentroitalia.info/mappe/ bella bella bella!

**Comment by tizianoblasi** [comment]
Complimenti davvero, mi pare fatta benissimo.
