### ISSUE TITLE
Aggiungere un indirizzo email del team di progetto nella pagina About

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#37]
se qualcuno  (non iscritto a twitter o fb) vuol mandare una mail non sa dove farlo
(a meno che non mi sia sfuggito)

**Comment by iltempe** [comment]
Hai ragione Andrea. l'indirizzo mail del progetto è terremotocentroita@gmail.com. per chi procede con questo issue lo inserisca.
