### ISSUE TITLE
[Monitoraggio] Open Data Consip

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#372]
Ciao,
farò adeguato link con #362 ma secondo me merita punto a parte per discussione autonoma.

E' online il porale http://dati.consip.it che ha molta rilevanza per il lavoro di monitoraggio
- Per info su Consip segnalo: http://www.consip.it/chi_siamo/ 
- Per discussione sul progetto open data consip segnalo [discussione su community spaghetti open data](https://goo.gl/MAKqN0) in cui sono intervenute varie persone attive in questo progetto fra cui @piersoft:  

A mio avviso è utilissimo pensare a come legare questi dati a quelli che (si spera) raccoglieremo ed (eventualmente) a quelli di [soldipubblici.gov.it](https://goo.gl/LSsQ4V) 

cià :)

**Comment by iltempe** [comment]
chiudo. sposterei sui gruppi di monitoraggio questo tipo di discussioni.
