### ISSUE TITLE
Problema ripetizione messaggi sul Canale Telegram TCI 

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/terremotocentro#373]
![image](https://cloud.githubusercontent.com/assets/9965333/19141623/3e3737f2-8b97-11e6-9fed-ec64c1380134.jpg)
 sul canale telegram si ripetono ogni giorno questi due messaggi dal feed rss di protezione civile

**Comment by aborruso** [comment]
@favoeva sei sicura che siano ripetizioni? Te lo chiedo perché è come se la protezione civile aggiornasse ogni giorno le stesse due pagine.

Se vedi l'ultimo è aggiornato a ieri. C'è da capire se cambiano la data, mentre il testo rimane uguale ogni giorno

![image](https://cloud.githubusercontent.com/assets/30607/19144304/fff5ba88-8ba8-11e6-8ebd-12058aa39521.png)

**Comment by favoeva** [comment]
verificato ;)  grazie @aborruso è come dici tu ! chiudo issue
