### ISSUE TITLE
Raccolta dati CENSIMENTO attuali residenti abitanti 

### ISSUE THREAD

**Issue by annaluciont** [emergenzeHack/terremotocentro#375]
Ecco il Drive per inserire la numerazione per il censimento. 
https://docs.google.com/spreadsheets/d/1ScamlxUFTBfG84a5Ulo5kjkLm_ckXN42Oz9PtNsVI5o/edit?usp=sharing

Per quanto riguarda la raccolta chi conosce una procedura?

**Comment by aborruso** [comment]
Questi report giornalieri potrebbero essere utili http://www.protezionecivile.gov.it/jcms/it/view_com.wp?contentId=COM60102

**Comment by annaluciont** [comment]
Grazie @aborruso ma i dati ufficiali finora forniti sono troppo generici.
Il censimento di questa issue riguarda gli attuali abitanti, quelli che stanno continuando a vivere nei luoghi colpiti. Così eventualmente da poterli poi raggiungere con il form segnalazioni.

**Comment by c83n** [comment]
@annaluciont il link al file drive che hai messo non funzia, puoi correggerlo?

suggerimento (ma non ho tempo di seguirlo quindi valutate voi) 
- semplice giro di telefonate fra persone locali che conosciamo
- ognuna ci segnala altri numeri 
- vediamo se raggiungiamo persone rimaste
- aggiorniamo un file xls (interno con dati sensibili) 
- agiorniamo un file xls esterno con localizzazione e segnalazione bisogni

non so se può funzionare, parlane magari con roberto di città reale (a proposito hai suo account git)?
baci
c

**Comment by annaluciont** [comment]
@robertoviola91 hai qualche idea?

**Comment by robertoviola91** [comment]
Secondo me la procedura migliore per fare il censimento è quella proposta da @c83n, magari oltre ai contatti telefonici potremmo sfruttare i gruppi relativi ad amatrice, social in generale e cosi via

**Comment by c83n** [comment]
Ciao,
ho preso file creato da @annaluciont e l'ho messo in cartella
- [MONITORAGGIO]_TERREMOTOCENTROITALIA https://goo.gl/jrwrQN (da aggiungere a vs drive)
- Subcartella [MONITORAGGIO]_POPOLAZIONE
- File  "000_Censimento per Comuni" (https://goo.gl/UXlx4m) 

In merito ai contatti coperti da privacy chiedo a @annaluciont di sentirsi con @chiccap per usare in parte (e integrare) quelli della cartella [DIFFUSIONE]_TERREMOTO_CENTROITALIA (che però è ad accesso riservato) coinvolgendo in questa azione anche @robertoviola91 che ormai fa parte della #squadrafortissimi :) Che ne dite?

#daje!
c

**Comment by Saraveg** [comment]
ciao,
prima o forse contestualmente al giro di telefonate proposto da @c83n bisogna provare i dati ufficiali che ci fanno capire dove sono le persone.
In particolare il dato più significativo sono le richieste di cas. i moduli sono stati raccolti dai coc ma chissà se hanno avuto ancora modo di processarli. Con @veronicaboggini abbiamo provato a sentire quello di arquata finora senza successo. Da lì sapremo quante persone non stanno usufruendo dell'accoglienza in tendopoli e in alberghi convenzionati e, ma questo è un dato che possiamo richiedere solo aggregato x località, immagino, dove sono (devono indicare un domicilio contestualmente alla domanda).

**Comment by c83n** [comment]
#great! :)

Il domenica 9 ottobre 2016, Saraveg notifications@github.com ha scritto:

**Comment by iltempe** [comment]
chiudo, per favore se avete degli update aprire issue specifico.
