### ISSUE TITLE
Mettere il canale Facebook in Deploy

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#376]
Il buon @joker8991 ha rilasciato questo bot che funge da canale Facebook inviando aggiornamenti . https://github.com/emergenzeHack/TCI_fbMessenger_bot

è ancora da far approvare a facebook ma intanto vorrei metterlo in deploy cosi da provarlo.

**Comment by drizzt** [comment]
Perché non l'ha committato direttamente sotto https://github.com/emergenzeHack/terremotocentroitalia-heroku-php?

**Comment by iltempe** [comment]
Non sapevamo se era integrabile, ma possiamo integrarlo. Comunque il file webhook.php è quello che riceve i messaggi Mentre startSendMessages.php deve essere eseguito ogni ora se lo si vuole eseguire più o meno frequentemente va cambiato il numero di secondi impostati. a me basta che comunque il repo dove si sviluppa questa app sia uno solo. per cui se si integra eliminiamo il repo in emergenzehack

**Comment by Joker8991** [comment]
Ciao @drizzt ho appena fatto una commit inserendo il token della pagina terremotocentroitalia.
Se mi dai l'indirizzo del webhook appena fatto il deploy lo inserisco. In questo modo gli amministratori della pagina potranno iniziare a testare il bot.

**Comment by c83n** [comment]
ciao, dopo varie chiacchiere con potenziali utenti riporto alcune impressioni
- whatzupp ce l'hanno tutti e fanno una fatica boia a mollarlo per telegram
- idem per messenger
- se si potesse integrare messenger e telegram avremmo vinto tutto

se dico fesserie o cose non fattibili ignoratemi :)

**Comment by iltempe** [comment]
@Joker8991 sta testando messenger. @Joker8991  come sta andando?

**Comment by Joker8991** [comment]
Ciao, sì sto testando e sembra funzionare.
@iltempe se vuoi provare invia un messaggio alla pagina Terremotocentroitalia con scritto START, dovrebbe andare anche se sei amministratore.
Se qualcuno altro volesse essere aggiunto come tester mi invii il suo username o id facebook.

**Comment by drizzt** [comment]
Quando lo integriamo su terremotocentroitalia-heroku-php facciamo un bot nuovo? (visto che ormai i token ce li siamo bruciati)

**Comment by c83n** [comment]
volentierissimo: https://www.facebook.com/christian.quintili
grazie
c

Il giorno 14 ottobre 2016 09:41, PietroC notifications@github.com ha
scritto:

**Comment by Joker8991** [comment]
@c83n Aggiunto. Per iniziare invia un messaggio alla pagina terremotocentroitalia

**Comment by Joker8991** [comment]
@drizzt Ho fatto deploy del bot sul mio account heroku, in quanto per inviarlo per l'approvazione il bot doveva essere funzionate. Comunque mi sto perdendo qualcosa. A cosa ti riferisci con token bruciati?

**Comment by Joker8991** [comment]
Ciao a tutti, il bot per fb messenger ha superato la certificazione. Ora è pubblico e dovrebbe essere raggiungibile in questi modi:
- cercando in fb messenger "terremotocentroita"
- seguendo il link https://m.me/terremotocentroita
- scannerizzando il codice con fb messanger.
  [messenger_logo.zip](https://github.com/emergenzeHack/terremotocentro/files/538389/messenger_logo.zip)

**Comment by aborruso** [comment]
Grazie @Joker8991

**Comment by iltempe** [comment]
Grande @Joker8991 ! Ma quindi funziona? Quali feed al momento invia?
