### ISSUE TITLE
Monitoraggio MACERIE

### ISSUE THREAD

**Issue by psykola** [emergenzeHack/terremotocentro#377]
Questa Issue ci serve più che altro da promemoria e da flusso di informazioni per il lavoro di reperimento dati collegato a issue #362 e #372  (vedi anche lista dei dataset: https://goo.gl/Jtmeyr)

I dati da monitorare riguardano lo smaltimento delle macerie, e in particolare:
- Appalti ditte di smaltimento
- Smaltimento vero e proprio: flussi di rifiuti (ton prelevate e ton scaricate)
- geolocalizzazione dei siti di smaltimento (due ex cave, una tra Posta e Borbona, l'altra vicino ad Accumoli)

**Comment by psykola** [comment]
Documenti utili
Ordinanza smaltimento 11/09/2016: https://archive.org/details/circolare_macerie_ocdpc_2016

**Comment by milanini** [comment]
Ho trovato la prima ordinanza di Amatrice che ti allego, la quale però manca dell'allegato con le ditte, anche se parla del seguente allegato, ergo andrebbe fatta richiesta di Accesso Civico (è accaduto che nel documento da scaricare come allegato c'è di nuovo l'ordinanza, vogliamo provare?   https://archive.org/details/7482016

**Comment by Saraveg** [comment]
ciao! 1 domanda 1 link utile
dalla lettura dell'ordinanza sulle macerie mi sembra si parli solo di aziende integrate del ciclo dei rifiuti o di amministrazioni direttamente (quindi non appalti esterni a meno che nel periodo di somma urgenza - vedasi ordinanza del comune di amatrice). Non capisco  inoltre se attuano la differenziazione tra macerie pubbliche e private.

Poi...sicuramente sarà girato anche altrove ma credo sia utile mettere qua il link al lavoro fatto a l'aquila che utile anche a vedere dataset (è open) necessari.
http://www.maceriesisma2009.it/index.php?lang=it&section=home

**Comment by milanini** [comment]
Ottimo ho caricato i link nei dataset da richiedere come promemoria e carico in archive il documento trovato nel sito: tracciabilità macerie http://www.maceriesisma2009.it/usrc_634_usra_1737_03022015.pdf

**Comment by c83n** [comment]
#mitiviventi :)

Il domenica 9 ottobre 2016, milanini notifications@github.com ha scritto:

**Comment by iltempe** [comment]
chiudo.
