### ISSUE TITLE
[Monitoraggio] - Archivio docs ufficiali

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#378]
Ciao,
Antonella e @chiccap stanno archiviando i documenti ufficiali in https://archive.org/details/@terremotocentroita  e hanno anche fatto una sezione apposita del wiki su [come archiviare documentazione](https://goo.gl/08tF3o))

Mi chiedo e chiedo alle autrici + a  @favoeva @tempe @dontyna e @psykola se non sia il caso di creare un mini db su google sheet che permetta di fare un registro della documentazione archiviata in modo che possa essere utile come riferimento per altri issue tipo #377 #362 e #372 

Ne ho abbozzato uno in 
- [MONITORAGGIO]_TERREMOTOCENTROITALIA https://goo.gl/jrwrQN (da aggiungere a vs drive)
- Subcartella [MONITORAGGIO]_ARCHIVIO_DOCS

My2cents
c

**Comment by iltempe** [comment]
con il buon @mfortini oggi riflettevamo su come unire il mondo "archive" con il mondo issue "github". Una proposta potrebbe essere per ogni documento caricato su archive si apre in automatico un issue in un repository "documenti" in cui viene trattato e discusso esattamente come una segnalazione e poi anche messo sul sito. che dici?

**Comment by c83n** [comment]
secondo me e' un ottima idea
in questo modo se non sbaglio basta fare estrazione da github et voila c'e'
db dei docs ricercabile e linkato a github, giusto?
comunque #daje

Il domenica 9 ottobre 2016, Iltempe notifications@github.com ha scritto:

**Comment by iltempe** [comment]
Si in più portando il link del documento tra i dati nel sito si può EMBEDDARE il documento stesso cosi:
http://iltempe.github.io/blog/2016/08/11/l-archivio-un-unica-grande-bibloteca-per-tutti.html

**Comment by milanini** [comment]
che ne dite di rendere virale, chiedendoglielo, questa cosa carina di Giuseppe Ragusa, Open data Sicilia, https://medium.com/dirittiallefonti/san-giuseppe-jato-diamo-unocchiata-in-comune-84ab4e645812#.a5sntn8u9
allo stesso tempo terremotocentroitalia utilizzandola lancia una richiesta: cercasi attivisti monitori di albi pretori, così da averli su tutti i Comuni del sisma, facciamo un elenco di un referente per Comune, magari poi avrebbero  gli avvisi specifici di albopop con telegram, allo stesso tempo potrebbero inoltrare le loro domande di accesso civico, io sarei disponibile a seguirli ... :)

**Comment by aborruso** [comment]
Gli albiPOP di tutti i comuni sono pronti, in un altro thread ve ne scriveremo

**Comment by c83n** [comment]
yo yo yo
io appena ho un minuto mi rileggo tutti gli updates
c

2016-10-10 12:38 GMT+02:00 Andrea Borruso notifications@github.com:

**Comment by marco-acorte** [comment]
non so se ho gia' scritto da altre parti ... @aborruso interessa per albo pop un feed rss del comune di rieti?

**Comment by aborruso** [comment]
@marco-acorte grazie, ma non lo so, ma ogni rilancio può essere utile. Noi al momento abbiamo lavorato su questi:
- Amatrice (RI) 
- Accumoli (RI) 
- Arquata del Tronto (AP)  
- Montereale (AQ)  
- Cascia (PG)  
- Monteleone di Spoleto (PG)  
- Norcia (PG)  
- Preci (PG)  
- Acquasanta Terme (AP) 
- Montefortino (FM) 
- Montegallo (AP)  
- Montemonaco (AP)  
- Capitignano (AQ)  
- Campotosto (AQ)  
- Valle Castellana (TE) 
- Rocca Santa Maria (TE)  
- Cittareale (RI)

**Comment by marco-acorte** [comment]
@aborruso cmq per albopop puo' essere un contributo a prescindere. no?

**Comment by aborruso** [comment]
@marco-acorte certo, scusami non avevo allora capita la tua proposta, sorry

**Comment by marco-acorte** [comment]
@aborruso http://feeds.feedburner.com/AlboPretorioComuneRietiV3 dimmi sa va bene o se posso/devo migliorare qlcosa

**Comment by aborruso** [comment]
@marco-acorte eccolo [http://albopop.it/comune/rieti/](http://albopop.it/comune/rieti/)

**Comment by iltempe** [comment]
@aborruso secondo te è possibile fare in modo che ogni aggiornamento di alboPOP si tramuti in un issue github? vorrei cercare un modo di mettere queste informazioni + quello che c'è in archive + altro relativo alla trasparenza nel sito terremotocentroitalia.info, per non tenerle separate. Come la vedi?

**Comment by milanini** [comment]
@aborruso      @iltempe    visto il decreto di ieri albopop va ampliato a 62 comuni  più le quattro province e gli stessi Comuni delle Province, l'elenco che ho abbozzato, dove incasellare anche un elenco di attivisti monitori
https://docs.google.com/spreadsheets/d/1ke84ywHjiZ32GgpbEe5tV9prAKlB9zc0e3N0tU4CvI4/edit#gid=1829752802

**Comment by c83n** [comment]
@milanini sulla lista dei monitori puoi coordinarti con @chiccap e/o con @annaluciont che seguono lista sensori per diffusione? grazie :)

**Comment by iltempe** [comment]
@c83n chiudo questo issue: nella pagina opendata adesso esiste l'elenco dei dati relativi ai nomi dei documenti caricati su archive. Dai nomi si possono ricavare link e quindi tutte le altre informazioni che si vogliono, c'è da fare magari uno script ma si fa. http://www.terremotocentroitalia.info/opendata/
