### ISSUE TITLE
Segnalazione by CAMPER AA: CesaVentre

### ISSUE THREAD

**Issue by Saraveg** [emergenzeHack/terremotocentro#379]
cari,
sottopongo a tutti la questione, difficile:
Il camper è stato contattato più volte dalla frazione di CesaVentre (Accumoli) 
Nella frazione vivono 23 persone, ovvero 5 nuclei familiari, mentre una coppia di anziani si sono trasferite a L'Aquila. Ci sono minori (bambini e adolescenti) e anziani con problemi di salute.
Non si registrano crolli maggiori, ma numerose case sono parzialmente inagibili e l'intera popolazione vive in roulotte da oltre 1 mese, tranne una famiglia che è riuscita a ottenere una casa su ruote tramite una donazione privata. 2 bagni chimici sono arrivati solo la scorsa settimana insieme all'allaccio di 6kw di corrente (prima andavano con un generatore).
E' un caso in cui si potrebbe ottenere il rientro nelle case vere dopo le ristrutturazioni in tempi brevi e in cui non dovrebbero essere necessario la costruzione di sae/map.
La signora che ci ha contattate molte volte ha avanzato la richiesta di avere informazioni e supporto per l'ottenimento di 5 case su ruote
Abbiamo contattato il Comune dell'Aquila in modo da ottenere un incontro con il dirigente dell'ANAS L'Aquila, proprietari di 28 casette su ruote utilizzate per il sisma del 2009 e rese disponibili dall'Amministrazione al fine di comprendere meglio le condizioni di messa a disposizione di queste soluzioni abitative . L'incontro è avvenuto e il coordinatore ci ha confermato la disponibilità ma che si possono muovere solo su indicazione di un ente pubblico.
 Allo stesso tempo, abbiamo sondato con i residenti la disponibilità dell'Amministrazione Comunale di Accumoli alla posa delle stesse: a differenza di Amatrice, qui il Sindaco non è totalmente contrario (non ha infatti impedito la posa dell’unica casa su ruote arrivata a Cesaventre).
Abbiamo inoltre contattato il comitato di Accumoli "Radici Accumolensi" per sottoporre la questione. Il presidente ha detto che si sarebbero informati ma ad oggi non abbiamo feedback.

La signora oggi mi richiama dicendo che apprezza il nostro sforzo ma non riesce a vedere una soluzione in vista. Ci chiede se possiamo portare giornalisti/avvocati (io ho la disponibilità di avvocati volontari aquilani).

Sondaggio....che si fa?

**Comment by iltempe** [comment]
Contattami decidiamo come muoverci

**Comment by psykola** [comment]
Per @Saraveg - domani (mercoledi 12), prima dell'incontro con la protezione civile,  ne parlo con Pablo, che è un ingegnere (Sara sa di chi parlo), e mi confronto con lui su cosa si può fare tecnicamente.
Perché se si potesse mettere mano alle case e renderle agibili, non so tecnicamente con quale deroga, si potrebbe fare un crowdfounding per alzare i soldi dei lavori, soldi che poi - una volta sbloccati i finanziamenti statali - i proprietari potrebbero restituire (senza interessi). Io su questo potrei anche avere l'appoggio di Banca Etica.
