### ISSUE TITLE
INVITO: 15/16 ottobre ! 

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#381]
Ciao 
questo post è rivolto al team (per diffusione esterna usate questo evento fb: https://goo.gl/n0UZbi).

Il 16 ottobre alle ore 15 ad Arquata c'è questa cosa qua sotto (vedi volantino) organizzata da Sara Vegni e @chiccap in collaborazione con ask the dust! 

Avremmo piacere che ci foste tutti voi che avete creato TCI. Ci stiamo organizzando per hangout quindi di sicuro @iltempe ci sarà e tutti siete invitati (connessione permettendo) 

Se volete esserci anche dal vivo posso passarvi a prendere. Partirò in auto da Terni il 15 ottobre farò queste tappe: https://goo.gl/ZbljFZ prima di raggiungere Arquata il 16. Posso deviare (sempre il 15) per roma / rieti e raccogliere chiunque (al max 4 persone) poi occorre organizzare logistica per la notte.

Chiunque voglia aggregarsi (il 15 e/o 16) faccia un fischio e poi ci organizziamo
# daje :)

![pac](https://cloud.githubusercontent.com/assets/1081488/19309218/df62e7c0-9083-11e6-9080-2aa80c820c18.jpg)

**Comment by favoeva** [comment]
Ci sarò 👍

**Comment by c83n** [comment]
daje sentiamoci domani! :)

Il mercoledì 12 ottobre 2016, Marieva Favoino notifications@github.com ha
scritto:

**Comment by c83n** [comment]
update: parto il 16 presto e non + il 15 :)
