### ISSUE TITLE
Velocità di caricamento

### ISSUE THREAD

**Issue by Pinzauti** [emergenzeHack/terremotocentro#384]
Segnalo alcuni problemi di performance: 
Link: https://gtmetrix.com/reports/terremotocentroitalia.info/8QzeLwBc 

[Versione PDF](https://github.com/emergenzeHack/terremotocentro/files/531947/GTmetrix-report-terremotocentroitalia.info-20161016T093254-8QzeLwBc-full.pdf)

**Comment by iltempe** [comment]
Abbiamo aggiunto le icone che comunque non dovrebbero pesare molto. I dati in home page sono molti. che dici?

**Comment by iltempe** [comment]
@Pinzauti che dici?

**Comment by Pinzauti** [comment]
@iltempe Le icone andrebbero un po' ridotte:
![capture](https://cloud.githubusercontent.com/assets/16691846/19419865/969b75a6-93e0-11e6-8bdf-c2bd3a8352af.PNG)

Ma il problema non è solo quello, si va dalla compressione, alla cache, a javascript, al dom, agli headers ecc. ecc.
Sicuramente anche i dati sono troppi, forse andrebbero mostrati (in home page) solo le principali segnalazioni.

**Comment by iltempe** [comment]
ok. @Pinzauti riesci a farmi una verifica anche su questa pagina dove ci sono icone simili? http://www.terremotocentroitalia.info/mappe/

**Comment by iltempe** [comment]
@franziner riusciamo a fare una versione leggermente più compressa delle icone?

**Comment by franziner** [comment]
certo @iltempe , riduco e invio

**Comment by Pinzauti** [comment]
@iltempe sulla pagina mappe intanto segnalo un problema di visualizzazione per quanto riguarda il mobile.
![Immagine](https://cloud.githubusercontent.com/assets/16691846/19436694/00142e4c-9472-11e6-94ac-c36a04db6bfd.png)

Per quanto riguarda la velocità:
Link: https://gtmetrix.com/reports/www.terremotocentroitalia.info/WtNY1Jta

[PDF](https://github.com/emergenzeHack/terremotocentro/files/533366/GTmetrix-report-www.terremotocentroitalia.info-20161017T140129-WtNY1Jta-full.pdf)

**Comment by franziner** [comment]
@iltempe ho visto che hai cambiato la visualizzazione delle icone nell'homepage. Bella! 
Ecco le icone per l'home page ridotte..in arrivo anche quelle della pagina Mappe
[icone-hp-tci.zip](https://github.com/emergenzeHack/terremotocentro/files/534401/icone-hp-tci.zip)

**Comment by franziner** [comment]
ecco quelle di mappe, @iltempe spiegami pure quando puoi come si fa ad inserirle che ci penso io :)
[icone-mappe-tci.zip](https://github.com/emergenzeHack/terremotocentro/files/534427/icone-mappe-tci.zip)

**Comment by iltempe** [comment]
@franziner non c'è stato bisogno di nulla. stesse immagini stesso nome le ho semplicemente aggiunte io. in ogni caso, per il futuro, la configurazione delle icone sta in questo file https://github.com/emergenzeHack/terremotocentro/blob/master/_data/logos.yml è piuttosto leggibile. Ogni elemento definisce il testo sotto l'icona, l'immagine, se è una mappa e il link. Cambiando il file o aggiungendo delle voci si aggiungono icone.

**Comment by iltempe** [comment]
@Pinzauti da cosa dipende il disallineamento?

**Comment by Pinzauti** [comment]
Dal CSS però non saprei come fixare @iltempe
