### ISSUE TITLE
Materiale Assemblea 17/10 Arquata

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/terremotocentro#385]
Ciao!
Che ne pensate di pubblicare sul sito il resoconto di quello che ci siamo detti oggi all'assemblea con la cittadinanza?
Per quanto riguarda i video, @antomil suggeriva addirittura di trasformarli in mp4 e caricarli su archive.org.

Qui il programma dell'assemblea: https://goo.gl/v8q3cQ
Qui le slide che abbiamo utilizzato: https://goo.gl/OK0RBX
Qui le dirette video: https://goo.gl/jRnuPX

**Comment by favoeva** [comment]
ottimo @chiccap qui c'è anche il comunicato stampa  che annunciava l'incontro https://docs.google.com/document/d/1g9gBMKxUdAe7MFKOSzrEeViTxyrWH_XKkdferMuuRFY/edit

io caricherei tutto su archive anche i volantini  
![14680778_10154702705957728_7035830156940051570_n](https://cloud.githubusercontent.com/assets/9965333/19421153/284576c8-93fa-11e6-8a21-23040d14aafc.jpg)
![14753476_10154705130052728_5672019808634405480_o](https://cloud.githubusercontent.com/assets/9965333/19421154/2f907f4a-93fa-11e6-809f-f9fe58781b3b.jpg)

**Comment by iltempe** [comment]
sono d'accordo. mettiamo su archive.

**Comment by chiccap** [comment]
Secondo voi non sarebbe il caso anche di scrivere un pezzo sul blog?

**Comment by marco-acorte** [comment]
sto scaricando i video da facebook per renderli disponibili offline appena finito li condivido

**Comment by iltempe** [comment]
Posso chiudere?

**Comment by chiccap** [comment]
@iltempe chiudi!
