### ISSUE TITLE
Miglioramenti da fare su Home Page

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#386]
Attualmente la home ha 4 pulsanti/icone e sotto tutte le segnalazioni aperte con etichetta Bollettino.

Ci viene richiesto per motivi di performance di caricamento della pagina di ridurre anche i dati presenti. Idee? proposte?

Se la nostra home page ha bisogno di altri miglioramenti secondo voi, elencateli qui sotto.

**Comment by Joker8991** [comment]
Secondo me si potrebbero paginare le segnalazioni, come ad es nei risultati di ricerca google, mostrandone 10-20 per pagina.
In questo modo si eviterebbe anche lo scrolling lunghissimo.

**Comment by iltempe** [comment]
@Joker8991 cioè dici paginarne 10 per volta? ma la home è una sola....

**Comment by Joker8991** [comment]
Sì, anche di più. La home resta com'è mantenendo le icone etc, presentando però solo i le prime 20 segnalazioni ed a fondo pagina i numeri < 1 2 3 ... > che linkano la pagina successiva o la pagina n.
Non so se sia fattibile come cosa.

**Comment by cristigalas** [comment]
Secondo me in home andrebbero aggiunti altri due pulsanti: risorse disponibili e raccolte fondi. Quest'ultime, in particolare, sono insieme alle news le segnalazioni che continuano ad arrivare, anche via web form, con più regolarità e quindi, a mio avviso, andrebbero valorizzate di più... Graficamente i bottoni potrebbero essere quindi su due righe, tre per ogni riga (1^ riga: segnala, news, fabbisogni - 2^ riga: raccolte fondi, alloggi, risorse disponibili)

**Comment by iltempe** [comment]
@Joker8991 @cristigalas vedrei bene pulsanti e ricerca in HOME e basta. il resto consultabile nelle varie sezioni.

**Comment by cristigalas** [comment]
Intendi niente più notizie da bollettino in home? E aggiungeresti altri bottoni o lasceresti solo quelli che già ci sono? Secondo me, ribadisco, è riduttivo mettere solo quei bottoni...

**Comment by iltempe** [comment]
@cristigalas io la home la vedrei bene con i bottoni e una barra per fare un cerca (tipo google). i dati in home page sono troppi diventa lentissimo a caricare adesso. il resto delle sezioni tutte visitabili come sono adesso.

**Comment by iltempe** [comment]
ho fatto un primo prototipo di nuova home page qui. commenti ben accetti.
http://www.terremotocentroitalia.info/index2

**Comment by ghost** [comment]
@iltempe carino centrerei soltanto l'input.

**Comment by iltempe** [comment]
Si, e poi mi sa che c’è da rivalidare tutto il responsive….che dici?

**Comment by ghost** [comment]
@iltempe si

**Comment by Joker8991** [comment]
@iltempe @tailot Anche a me piace. Forse modificherei la label "cosa stai cercando?" in quanto non essendoci più la lista delle segnalazioni diventa un po' vaga. Metterei ad esempio "Cerca tra le segnalazioni" o qualcosa di simile.
