### ISSUE TITLE
Aggiungere gruppo Telegram e Archive nella sezione "canali di comunicazione" sul sito

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#389]
Nella sezione "canali di comunicazione" sul sito [http://terremotocentroitalia.info/canali/](http://terremotocentroitalia.info/canali/) bisognerebbe aggiungere il canale Telegram (ci sono solo canale e bot) e anche la nostra raccolta su Archive.org. Quest'ultima, in particolare non viene mai menzionata sul sito se non con una iconcina nella barra delle iconcine social che compare in calce ad alcune pagine.

**Comment by Pinzauti** [comment]
In questi giorni non ce la faccio perché sono fuori, ci do un occhio nel fine settimana prossimo

**Comment by cristigalas** [comment]
Ok, grazie!
