### ISSUE TITLE
Label "sisma agosto" a tutte le segnalazioni fino alla 841

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#393]
Visto che adesso la label "sisma ottobre", si potrebbe aggiungere di default una label "sisma agosto" a tutte le segnalazioni giunte fino a ieri alle 19, ovvero fino alla issue 841? Che ne dite?

**Comment by iltempe** [comment]
@mfortini esiste un modo per fare questo?
