### ISSUE TITLE
Dati GeoJson

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#395]
A partire dal file delle segnalazioni CSV https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issues.csv
o anche quello delle segnalazioni JSON
https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issuesjson.json

andrebbe elaborato e continuamente aggiornato ad ogni aggiornamento del CSV lo stesso file in formato GeoJson ed archiviato nella folder _data ogni volta che viene aggiornato. Ovviamente il file deve contenere solo le segnalazioni georiferite.

**Comment by mfortini** [comment]
Mettendo come terzo argomento un nome di file, vi scrive un GEOJSON.

**Comment by iltempe** [comment]
grande @mfortini ! @drizzt riesci a riconfigurare i parametri dello script per produrre i tre file in _data?
- primo argomento: CSV
- secondo argomento (opzionale): JSON
- terzo argomento (opzionale): GEOJSON

**Comment by mfortini** [comment]
@drizzt il file GEOJSON lo chiamiamo _data/issues.geojson
