### ISSUE TITLE
Aggiornamento mappa comuni sisma

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#396]
a valle del terremoto del 26 ottobre andrebbe aggiornata la mappa di @psykola con i nuovi comuni. va cercata una lista ufficiale dei comuni colpiti e vanno aggiunti. che ne dite?  http://www.terremotocentroitalia.info/2016-08-24-mappa-comuni-cratere/

**Comment by psykola** [comment]
Ne va fatta secondo te una'nuova, per differenziare i due eventi? Che dici?
Puoi assegnare a me

Il 29/ott/2016 18:41, "Iltempe" notifications@github.com ha scritto:

**Comment by iltempe** [comment]
@psykola potremmo fare un livello diverso. cioè metti i comuni in una nuova lista e li mappi come livello "26 ottobre" che dici?

**Comment by favoeva** [comment]
viste le notizie di ieri e di oggi dovremmo aggiornare la mappa. cerco altri elenchi.

**Comment by iltempe** [comment]
nel gdrive ho inserito una colonna FONTE

**Comment by favoeva** [comment]
con @chiccap abbiamo raccolto altri comuni dalle segnalazioni che ci arrivano e dai siti ufficiali 
Bolognola (MC)
Sellano (PG) 
Cerreto Di Spoleto (PG)
Poggiodomo (PG) 
Vallo Di Nera (PG) 
Acquacanina (MC) 
Montefortino (FM) 
Fiordimonte (MC) 
Monteleone Di Spoleto (PG)
Sant’Anatolia Di Narco (PG)

Luca Zanelli su fb parla di 108 comuni solo nella provincia di macerata (gli ho chiesto fonte e lista se ce l'ha)

**Comment by favoeva** [comment]
Fonte di Luca Zanelli: Protezione Civile Marche, intervistata a TG Marche di oggi (non ha lista ma sta cercando di farla  da segnalazioni che trova su fb e che rilancia su gruppo TCI)

**Comment by iltempe** [comment]
ok. io per ogni comune ho specificato la fonte nel foglio gdrive. se lo aggiornate citate la fonte sempre grazie

**Comment by favoeva** [comment]
vanno aggiunti:
visso 
ussita

**Comment by favoeva** [comment]
la tabella che stiamo aggiornando è questa  https://docs.google.com/spreadsheets/d/1cDw6doPl-WTn9KgNNyxwm92gKLnemMyrE1iCjCE5Cds/edit?ts=5814fb4b#gid=1542119982

**Comment by favoeva** [comment]
Da Regione Marche abbiamo i numeri ma non i nomi http://www.regione.marche.it/News-ed-Eventi/Post/16481/OLTRE-25MILA-LE-PERSONE-FUORI-CASA-NELLE-MARCHE 

"Sono in totale oltre 25 mila le persone attualmente fuori casa nelle Marche. In particolare 20766 a Macerata, 1898 a Fermo, 2247 ad Ascoli Piceno e 526 ad Ancona. Nelle strutture comunali e nei centri di prima assistenza sono stati allestiti 7 mila posti letto di cui 5 mila brandine. Un centinaio tra alberghi e strutture ricettive stanno accogliendo inoltre coloro che si sono spostati sulla costa dove continuano i trasferimenti.
**Le zone rosse, ossia le aree interdette ai cittadini perche' a rischio crolli, sono in tutto 216: 162 a Macerata, 17 a Fermo, 33 a Ascoli Piceno e 4 ad Ancona.
Sono invece _108_ i Comuni marchigiani con edifici che hanno subito crolli e danni gravissimi: 50 a Macerata, 26 a Fermo, 24 ad Ascoli Piceno, 8 ad Ancona."**

**Comment by favoeva** [comment]
ci segnalano sfollati anche a Civitanovamarche

**Comment by chiccap** [comment]
Mi ha appena risposto il sindaco di Gualdo Cattaneo (PG) a cui avevo chiesto se avesse dati ufficiali su quali e quanti fossero i comuni umbri coinvolti dal sisma dopo il terremoto del 30. Mi ha dato il numero del coordinatore comunale della protezione civile dicendomi di chiamarlo perchè ad oggi forse la protezione civile è l'unica ad avere queste informazioni. domattina provo

**Comment by iltempe** [comment]
@psykola @favoeva @chiccap secondo voi si riesce a mettere tutti i comuni su una mappa sola? magari anche su più livelli (24 agosto e successivi)? cosi la sostituiamo a quella presente sul sito....

**Comment by milanini** [comment]
qst sono  gli elenchi grezzi e grossolani dei link dei Comuni che hanno fatto atti in occasione del sisma del 26 e 30 agosto, dovrebbero poi esserne monitorati gli AlbiPretori, (info che già ho messo nella issue di Albopop #84,  gli elenchi sono suddivisi per regione: 
vedi Marche (ma devo ancora verificare la provincia di Pesaro Urbino): https://docs.google.com/document/d/1SBvsXAwJuKr3R819EnX6EjXwbL_AF6iPAch_rZCS_aY/edit
Umbria: 
https://docs.google.com/document/d/1GIBPIz5oTGuZCsl9gTj27o8G_i2hXGk0fMOGkg96kJg/edit
Lazio (ma occorre verificare ancora Roma e Viterbo):
https://docs.google.com/document/d/1L-4vxQ3K4nqkiv7pURrTrglCnjc4yAaBXHnuPF6ri40/edit
Abruzzo: 
https://docs.google.com/document/d/1jCmK6cYbfHZ-mIMXqXHHqSwygKOFNZXoxFBqRzsEFw0/edit

**Comment by chiccap** [comment]
@milanini che lavorone! grazie!

**Comment by cristigalas** [comment]
Non so se può essere utile http://www.viveremarche.it/index.php?page=articolo&articolo_id=614114&utm_source=dlvr.it&utm_medium=twitter

**Comment by favoeva** [comment]
link a mappa COC Umbria su google maps https://www.google.com/maps/d/viewer?mid=1yv9i2qh-nVkfOBl_rwVpgP1T8-o&ll=42.92610703820189%2C12.748961096093808&z=9
fonte: http://www.regione.umbria.it/centri-operativi

**Comment by cristigalas** [comment]
Ecco l'elenco dei comuni marchigiani aggiunti al cratere dopo le scosse di ottobre: http://www.ilrestodelcarlino.it/ascoli/cronaca/terremoto-cratere-macerata-ascoli-fermo-1.2677887

**Comment by milanini** [comment]
il Disegno di legge A.S. n. 2594 "Conversione in legge del decreto-legge 11 novembre 2016, n. 205, recante nuovi interventi urgenti in favore delle popolazioni e dei territori interessati dagli eventi sismici del 2016" a pag.28 l'elenco (più o meno provvisorio) degli ulteriori Comuni interessati dal sisma del 30 ottobre                                                                                  http://www.senato.it/service/PDF/PDFServer/BGT/00993988.pdf     
qui l'elenco che ho aggiornato: in rosso i Comuni di ottobre
https://docs.google.com/spreadsheets/d/1ke84ywHjiZ32GgpbEe5tV9prAKlB9zc0e3N0tU4CvI4/edit#gid=1829752802

**Comment by iltempe** [comment]
chiudo, è stato creato il nuovo dataset dei comuni.
