### ISSUE TITLE
Aggungere Lista Comuni a Opendata

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#397]
aggiungendo a questo file i riferimenti del file della lista comuni della mappa dei comuni colpiti facciamo opendata della lista. https://github.com/emergenzeHack/terremotocentro/blob/master/_data/opendata.csv

**Comment by psykola** [comment]
So che è chiusa, ma il file va modificato.
A lista comuni cratere 24 agosto va aggiunto
Lista ufficiale dei Comuni colpiti dal sisma 24 agosto (decreto ministeriale 20/10/2016): https://docs.google.com/spreadsheets/d/116NBajcH4lkMH3rbwzvZU5baoCWiu9gqlJk2otSQmac/edit?usp=sharing
