### ISSUE TITLE
Abbellire e migliorare sito (CSS)

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#40]
CSS, font, organizzazione più fruibile dei contenuti generati dai template.

**Comment by frankadimcosta** [comment]
Conosco bene Drupal. Posso dare una mano ?

**Comment by lambia** [comment]
Su cosa gira il sito? Versione CMS, nome template, eventuali plugin e modifiche hardcoded. Grazie.

**Comment by mfortini** [comment]
Gira su github pages, il motore è jekyll, il template è 
beautiful-jekyll, più info sul wiki di progetto

Il 29/08/2016 12:26, lambia ha scritto:

**Comment by iltempe** [comment]
ho chiesto espressamente di aprire issues specifici sul web design. chiudo e rimando ad altri punti.

**Comment by iltempe** [comment]
ho chiesto espressamente di aprire issues specifici su web design. chiudo e rimando ad altri punti.
