### ISSUE TITLE
Aggiornamento mappa viabilità

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#400]
dovremmo aggiornare mappa viabilità sul sito 
- prendendo dati di waze su zona nuovi epicentri
- aggiungendo posto dove segnalare blocchi da cui Waze al massimo peschi ma non sia la fonte

**Comment by ebergam** [comment]
@mfortini @iltempe @lorenzoperone @aborruso 
https://github.com/emergenzeHack/terremotocentro/blob/master/_posts/2016-8-25-mappa-traffico.md

Cambiamo l'iframe qui con le nuove coordinate?

**Comment by ebergam** [comment]
Sulla mappa waze confermato il tratta di chiusura su SS4 ([Corriere della Sera](http://www.corriere.it/cronache/16_ottobre_30/terremoto-metro-chiusa-roma-salaria-bloccata-massi-strada-8bde358e-9e78-11e6-a6dc-5f117ed55cf3.shtml))

**Comment by ebergam** [comment]
Mappa waze confermata chiusura SS685 (che sarebbe la Tre Valli) tra Norcia e Arquata da [Spoletonline](http://www.spoletonline.com/?page=articolo&id=155019)

**Comment by ebergam** [comment]
TG la 7 dice chiusa strada per crolli tra Visso e Preci (SP476) e SP477. Confermata da altre fonti. NON SEGNALATA SU WAZE @mfortini

**Comment by ebergam** [comment]
Feed CCISS Marche: http://mobile.cciss.it/viabilita/CCISSMobileTraffico/gotoRegion.do?strRegion=Marche

Feed CCISS Umbria: http://mobile.cciss.it/viabilita/CCISSMobileTraffico/gotoRegion.do?strRegion=Umbria

Feed generale CCISS: http://www.cciss.it/portale/rss;jsessionid=ZF3GYVWPqPCFnnfvJ8s4lS2hSp3lkvjbwBLlvKN8GVmX2ZgfXmnD!1350987649!1839745147?rsstype=traffic

**Comment by iltempe** [comment]
attualmente waze sta aggregando le nostre segnalazioni. su gruppo facebook c'è waze italia che osserva e rilancia.
