### ISSUE TITLE
Aggiornare About

### ISSUE THREAD

**Issue by epoeta** [emergenzeHack/terremotocentro#401]
La pagina About fa riferimento ai territori colpiti di Rieti, Ascoli Piceno e Perugia, omettendo - visti i più recenti sviluppi - quelli di Macerata (inoltre non ci sono anche comuni abbruzzesi colpiti?)

**Comment by iltempe** [comment]
aggiornata descrizione restando un po' più generico. tempo qualche minuto e si aggiorna anche il sito. grazie @epoeta
