### ISSUE TITLE
#VIABILITA' - feed rss CSSI 

### ISSUE THREAD

**Issue by c83n** [emergenzeHack/terremotocentro#402]
Mi pare utile ma un po' generico
http://www.cciss.it/portale/rss;jsessionid=1bnJYW4LVCf347QnNBv18j71KdzDn74cX1vvpvs1hGzVnLnh0nBz!-2095519972!1535755452?rsstype=traffic

si può focalizzare su zone specifiche e/o fargli un po'di stalking?
c

**Comment by mfortini** [comment]
Molto bello ma quasi nessuna info che sia leggibile da una macchina.

Il lun 31 ott 2016, 08:56 christian quintili notifications@github.com ha
scritto:

**Comment by iltempe** [comment]
chiudo è incluso in #400
