### ISSUE TITLE
URGENTE - Problema con aggiornamento issue sul sito 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#403]
Questa segnalazione https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/990 ha qualcosa che non va: non si vede sul sito e il link inviato in automatico via Twitter risulta corrotto. E comunque credo che tutto il sito sia bloccato, ci sono anche altre segnalazioni che non compaiono...

**Comment by iltempe** [comment]
ci sto lavorando. ho contattato anche un po' di gente tra cui @drizzt ...vediamo di risolvere.

**Comment by iltempe** [comment]
pare si sia ripreso. stanno aggiornando Gitlab, la nostra piattaforma di deploy.  "We'll be deploying GitLab 8.13.2 shortly. No downtime is expected but you may see intermittent errors during this time." attendiamo un po' e vediamo come va.

**Comment by cristigalas** [comment]
Ora mi pare funzionare tutto!

**Comment by iltempe** [comment]
per ora è risolto.
