### ISSUE TITLE
Cambiare descrizione sito che compare quando si condivide link

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#404]
Quando si condivide il link del sito compare una breve descrizione che fa riferimento solo al sisma del 24 agosto. Andrebbe modificata usando la dicitura che abbiamo già inserito sulla home e i canali social: _Un progetto per informare sugli eventi sismici che hanno colpito il Centro Italia nel 2016_

**Comment by Pinzauti** [comment]
Il codice mi sembra che vada bene, puoi fare un'altra prova e caso mai linkare la pagina specifica che causa problemi?

È possibile che a Facebook sia rimasta in cache la vecchia descrizione.
Segnalo [questo](https://developers.facebook.com/tools/debug/) tool per aggiornare e controllare i tag Open Graph.

**Comment by cristigalas** [comment]
Grazie! Adesso mi pare sia ok.
