### ISSUE TITLE
URGENTE- Messaggi Telegram pubblicati monchi

### ISSUE THREAD

**Issue by gloriaschiavi** [emergenzeHack/terremotocentro#405]
Ci sono due messaggi telegram che sembrano parziali

quello delle 1346
"Ordinanza n. 400: le misure per potenziare la risposta all"

e quello delle 1021
"Ocdpc n. 400 del 31 ottobre 2016: ulteriori interventi urgenti di protezione civile conseguenti all"

Magari succederà anche ad altri..? Forse l'apostrofo?

**Comment by iltempe** [comment]
questo accade su telegram in corrispondenza del carattere ' . non saprei perchè. @aborruso @mfortini mai successo a voi nulla del genere?

**Comment by gloriaschiavi** [comment]
Ne ho trovato un altro. 1 novembre ore 21:56
Terremoto centro Italia: l
forse un altro apostrofo...

**Comment by aborruso** [comment]
Grazie @gloriaschiavi 

Mi assegno il task

**Comment by iltempe** [comment]
mi pare vada meglio. chiudo.
