### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by andp97** [emergenzeHack/terremotocentro#406]
Vorrei contribuire al progetto come sviluppatore

**Comment by iltempe** [comment]
@andp97 ciao. ci dici un po' di te? che competenze hai?

**Comment by andp97** [comment]
Andrea 19 anni
Diplomato in informatica 
Ottime conoscenze di HTML Js CSS sto iniziando da poco ad utilizzare dei framework Js...
Realizzo siti web con WordPress principalmente ma anche con Joomla. Conosco C# e Vb.Net C++. Ovviamente anche PHP e SQL...se avete altre domande più specifiche fare pure :)

**Comment by iltempe** [comment]
ok. @andp97 parti dalla lista di questi issue, e discutine con gli altri. per lavorarci il modo più sicuro è fare FORK e poi PULL request secondo le procedure di Github. Se hai bisogno nel wiki nostro trovi una guida semplice per usare github. chiudo qui.
