### ISSUE TITLE
Errore nella pagina open data (elenco nuovi comuni)

### ISSUE THREAD

**Issue by ebergam** [emergenzeHack/terremotocentro#407]
Qui http://terremotocentroitalia.info/opendata/ se scarico il csv dei comuni coinvolti ad ottobre, trovo il csv con i metadati, non il foglio giusto .

**Comment by ebergam** [comment]
Fatta pull request, scusate ma non ho le permission per modificare: https://github.com/emergenzeHack/terremotocentro/pull/408

**Comment by iltempe** [comment]
grazie.
