### ISSUE TITLE
Ricerca delle Segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#409]
Io e @mfortini abbiamo fatto questa prova per creare una funzione di ricerca tra tutte le segnalazioni di TCI.

Siamo partiti da qui:
http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/

e siamo arrivati a questo http://terremotocentroitalia.info/searchissues/

La box cerca una o più parole in tutte le segnalazioni contenute nei nostri dati in CSV e pare "funzionicchiare"

Secondo noi c'è ancora da fare questo:
- sistemare il campo descrizione in modo che venga visualizzato meglio
- gestire il "escape" all'interno del file search.js (attualmente vuole stringhe da tokenizzare).
- aggiungere un'icona-gif di attesa mentre il sistema cerca (ci può volere qualche secondo)
- rendere la box di ricerca più grande e centrale nella pagina

Assegno ad un po' di persone che secondo me possono dare una mano.
Per favore facciamo pull request e commentiamo qui in modo da valutare e testare cosa facciamo prima di mettere online questa funzione.

Grazie

**Comment by mfortini** [comment]
Ho committato l'ultima versione _non_ funzionante: in pratica non sono ancora riuscito a convincere liquid a comportarsi bene per fare l'escape dei caratteri che non piacciono a JS. Per qualche oscura ragione, alcuni double quote non vengono corretti da uri_escape

**Comment by iltempe** [comment]
Con le ultime modifiche fatte pare funzionare bene. Anche la descrizione si vede bene.

A questo punto resta da : 
- aggiungere un'icona di attesa mentre il sistema cerca (ci può volere qualche secondo)
- rendere la box di ricerca più grande e centrale nella pagina

**Comment by olistik** [comment]
è legato a #414 ?

**Comment by iltempe** [comment]
chiudo e sposto nella #414
