### ISSUE TITLE
URL per puntare ai dati del foglio in formato CSV

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/terremotocentro#41]
Ho creato una pagina dove raccogliere gli URL per accedere in formato `CSV` ai dati che stiamo raccogliendo nel [foglio di lavoro condiviso](https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg).

Per il momento trovate solo l'URL per il foglio "Bollettino": [https://github.com/emergenzeHack/terremotocentro/wiki/Entropia](https://github.com/emergenzeHack/terremotocentro/wiki/Entropia)

**Comment by mfortini** [comment]
Gli altri li puoi recuperare dallo script csvupdate.sh

Il sab 27 ago 2016, 10:40 Andrea Borruso notifications@github.com ha
scritto:

**Comment by aborruso** [comment]
fatto, grazie @mfortini
