### ISSUE TITLE
modifica hashtag bollettino da #terremotoinfo a #terremoto

### ISSUE THREAD

**Issue by favoeva** [emergenzeHack/terremotocentro#412]
le issue segnalazioni con label bollettino vengono pubblicate in automatico su canli twitter e telegram TCI; l'hashtag automatico che viene loro attribuito è ora #terremotoinfo. Dovrebbe diventare #terremoto

**Comment by iltempe** [comment]
@favoeva #terremotoinfo c'era solo per i tweet ed ora è #terremoto. su telegram compare solo #bollettino, preferite avere anche #terremoto ?

**Comment by favoeva** [comment]
No ok telegram lasciamolo così . Errore mio.  Grazie 😊

**Comment by iltempe** [comment]
perfetto chiuso.
