### ISSUE TITLE
Terremoto in Cifre: raccolta dati da addetti ai lavori in Google Spreadsheet

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#413]
sarebbe carino raccogliere i dati disseminati online dagli addetti ai lavori (come [questo dei Vigili del Fuoco segnalato da @favoeva](https://mobile.twitter.com/i/web/status/793709491971907585)) e netterli in un google spreadsheet.
Ne parlammo all'epoca con @dontyna 

è possibile mapparle intanto in questa issue le fonti?
Incollo qui esempio di come potrebbe essere l'output... (dati inventati a caso da me...)

![tci_numerihp](https://cloud.githubusercontent.com/assets/1769578/19941296/dc08df32-a12f-11e6-9888-39b3dd89ce2a.png)

**Comment by nelsonmau** [comment]
Leggo qui da internazionale http://intern.az/1vv3

**Comment by nelsonmau** [comment]
Comunicati ufficiali protezione civile http://www.protezionecivile.gov.it/jcms/it/view_com.wp?contentId=COM60798

**Comment by nelsonmau** [comment]
@favoeva: [ecco qui i dati in tabella](https://docs.google.com/spreadsheets/d/1UJDpaxLS9_eRpvW2-326HQFLnrxUsoW591eE5eM9R2E/edit#gid=72588218)
Sono formattati per essere comprensibili dai noi esseri umani e non dai computer :)

Ad ogni modo ti chiedo: è questo il modo in cui i dati vengono diffusi di solito oppure ci sono altri esempio di protezione civile o di altri soggetti? Hai altri link?

grazie!

**Comment by cristigalas** [comment]
Su Fb ci segnalano questo, non so se può essere utile http://www.lavoripubblici.it/news/2016/11/CRONACA/Catalogazione-degli-edifici-danneggiati-dal-terremoto_17642.html

**Comment by cristigalas** [comment]
Articolo con dati dettagliati su Comuni colpiti nelle Marche http://www.viveremarche.it/index.php?page=articolo&articolo_id=614114&utm_source=dlvr.it&utm_medium=twitter

**Comment by iltempe** [comment]
@cristigalas @favoeva chiudo? o abbiamo degli update?

**Comment by cristigalas** [comment]
@iltempe a [quel file](https://docs.google.com/spreadsheets/d/1UJDpaxLS9_eRpvW2-326HQFLnrxUsoW591eE5eM9R2E/edit#gid=72588218) con i dati della Pc, di cui scriveva a suo tempo @nelsonmau, ci sto lavorando proprio in questi giorni per Ricostruzione Trasparente. Ma qui direi che puoi chiudere.

**Comment by iltempe** [comment]
ottimo.
