### ISSUE TITLE
Ritoccare ricerca e inserire loading sul sito

### ISSUE THREAD

**Issue by ghost** [emergenzeHack/terremotocentro#414]
- Creare un meccanismo di loading

- Sistemare la ricerca e stilizzare con bootstrap

**Comment by iltempe** [comment]
@tailot possiamo verificare per favore? mi pare che alla prima ricerca il loader non compaia e compare invece solo dopo un refresh della pagina searchissues. grazie

**Comment by ghost** [comment]
Si, attualmente quel search è bloccante per cui sostanzialmente si paralizza tutto, bisognerebbe renderla più efficiente

**Comment by olistik** [comment]
@tailot Ottima soluzione :-)
in https://github.com/emergenzeHack/terremotocentro/commit/394fbfda4aed459b78451ad97e3be2353bcdbab3 avevo provato un approccio diverso ma lo spinner restava bloccato dal processo della request e e di rendering.

Il fatto di iniettare il codice JS direttamente in page tende a creare qualche problemino in fase di sviluppo: il watch del server è lento a rigenerare la pagina di search..

Se per voi ha senso posso provare a riscrivere la pagina in modo che si appoggi ad un json generato staticamente ad ogni build del progetto (e quindi esterno alla pagina), in modo che la l'html della search resti sempre snello.

**Comment by ghost** [comment]
@olistik era una cosa che mi martellava nella testa. Si sembra una buona idea staticizzare il json.

**Comment by iltempe** [comment]
il json se intendete quello delle segnalazioni c'è già. https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issuesjson.json @olistik @tailot

**Comment by iltempe** [comment]
@tailot una volta che il search è di vostro gradimento e lo avete abbellito io lo piazzerei in prima pagina  
togliendo tutto tranne i pulsantoni. Togliendo anche la lista delle segnalazioni. Stile Google. Che dite?
![untitled](https://cloud.githubusercontent.com/assets/6368214/19963994/605615c2-a1bf-11e6-86ce-ec6b9377e7b2.png)

**Comment by iltempe** [comment]
Ho tirato giù un mockup di una possibile home page. che dite? si può lavorare in questa direzione? ovviamente va messo a posto CSS, validata etc... http://terremotocentroitalia.info/index2/ fatemi sapere
