### ISSUE TITLE
DashBoard Metriche delle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#421]
Andrebbe creata una dashboard ad uso interno che tramite il file CSV delle segnalazioni https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issues.csv
mostra un po' di statistiche/metriche di progetto. 
Idee?

**Comment by nelsonmau** [comment]
Su quali dati? Analytics del sito da google?

**Comment by iltempe** [comment]
no su quelli del file che ti ho linkato, sono i nostri dati

**Comment by iltempe** [comment]
@mfortini e guntcher hanno creato questa. c'è ancora qualche problemino di JS. http://terremotocentroitalia.info/dashboard/ qualcuno ci da una mano? thanks!

**Comment by olistik** [comment]
@iltempe riesci ad isolare i problemi presenti?

**Comment by iltempe** [comment]
si allora attualmente ci sono dei problemi a tirare dentro i dati dal JSON relativo alle segnalazioni. vedi un po' tutto dalla console JS di chrome. https://github.com/emergenzeHack/terremotocentro/blob/master/_data/issuesjson.json giusto @mfortini ?

**Comment by iltempe** [comment]
...il campo body e description di alcune issue contiene dei doppi apici non escaped
quindi o si vede aggiungere un controllo in profondità oppure va usata una rappresentazione literal tipo JSON.stringify() che dici?

**Comment by olistik** [comment]
@iltempe 

> ...il campo body e description di alcune issue contiene dei doppi apici non escaped
> quindi o si vede aggiungere un controllo in profondità oppure va usata una rappresentazione literal tipo JSON.stringify() che dici?

mi ricorda qualcosa.. 🤣 
Se non ricordo male avevo suggerito di aggiornare lo script Python. Sai se poi si è proseguito in quel senso?

**Comment by Ibernato93** [comment]
Il file JSON ha una virgola che non deve esserci nell'ultima riga. Togliete la virgola e provo tramite console e rifare il parse. Ho fatto la fork del repository però non mi fa fare il parse tramite il link di github del file nella fork. Mi dice accesso negato.

**Comment by iltempe** [comment]
finita. http://terremotocentroitalia.info/dashboard/
