### ISSUE TITLE
Home Page Rensponsive Fix

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#423]
si può rimettere http://www.terremotocentroitalia.info/ responsive? le icone al rimpicciolire dello schermo non si allineano. c'è un errore nel CSS?

**Comment by ghost** [comment]
Ci guardo subito!

**Comment by ghost** [comment]
Il problema viene provocato da quello stile usato per le "icone grandi" applicato inline direttamente nella pagina. È sempre buona norma non posizionare il css inline e usare il più possibile img-responsive. Riadatto la pagina.

**Comment by ghost** [comment]
@iltempe devo togliere quel force del conteiner. Per fare ciò mi serve rendere le icone un pelo più piccole

**Comment by ghost** [comment]
In alternativa una delle icone finisce a capo.
