### ISSUE TITLE
Distribuzione #ROULOTTE e #CAMPER

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/terremotocentro#431]
Mercoledì 2/10 mi contatta Doriana Tobaldo conosciuta tramite questa sua segnalazione su FB: http://terremotocentroitalia.info/issues/1036/ --> voleva sapere dove servissero roulotte da consegnare

Doriana fa parte di questo gruppo di attivisti TeamRibelle: https://www.facebook.com/groups/401875066516775/?ref=notif&notif_t=group_added_to_group&notif_id=1478261374438661 --> che oggi ha consegnato la ventinovesima roulotte avendo seguito le segnalazioni sul nostro sito e in settimana ne portano altre due (da Emilia - contatto Francesca Corcione) con trasporto a cura TeamRibelle

Doriana mi dice che: Venerdì 11 pomeriggio/sera vuole scendere nelle zone del cratere con un camper a portare abiti, scarponi ecc... Ho visto tra i bisogni sul sito, ma ci sono punti raccolta al massimo fino al sei. Lei vorrebbe portare materiale oltre ai vestiti suddetti in base alle segnalazioni NOSTRE direttamente a chi ha bisogno senza passare da enti o associazioni. 
Inoltre vuole documentare tutto con video e foto --> userà solo nostra piattaforma + per la strada da percorrere fino a destinazione ha detto che si fida solo di noi/waze

Che ne pensate?

**Comment by cristigalas** [comment]
Intanto mi sembra che questa storia della consegne di roulotte è molto interessante e sarebbe bello sapere quali delle nostre segnalazioni ha seguito e soddisfatto. Puoi saperlo? E poi rispetto a portare beni direttamente lì, difficile muoversi senza contatto in loco diretto. Però visto che c'è questa storia di Montemonaco aperta e in pieno sviluppo direi che può contattare direttamente la cittadina che ci aveva fatto la segnalazione e che è in stretto contatto con sindaco e vicesindaco e chiedere a loro di cosa hanno bisogno, qui la sua email martellinipaola@gmail.com che legge abbastanza frequentemente oppure la si puà contattare su Fb e Tw. Si chiama Paola Martellini. Dì a questa Doriana di scriverle subito. Qui la segnalazione da cui era partito tutto [](http://terremotocentroitalia.info/issues/1074/)

**Comment by chiccap** [comment]
segnalazione Montemonaco: http://terremotocentroitalia.info/issues/1074/

**Comment by favoeva** [comment]
Per la gestione incroci offerte roulotte e camper che stanno arrivando su TCI (alcune con mail) io e @cristigalas ragionavamo sul fatto che sarebbe meglio far decidere agli offerenti, chiedendo loro di tenerci aggiornat\* su sviluppi in modo da poter chiudere issue se la cosa ha funzionato.

**Comment by favoeva** [comment]
Avremmo deciso di inviare agli offerenti link sito TCI a questa  ricerca http://terremotocentroitalia.info/searchissues/?query=Camper+roulotte

**Comment by chiccap** [comment]
È la soluzione piú giusta. Brave ragazze. Procediamo così con tutti gli offerenti allora chiedendogli di farci sapere chi decidono di contattare.

**Comment by cristigalas** [comment]
Ok! Allora preparo il testo della email. Ho visto che solo un donatore non ha email. A lui manderemo sms, ok?

**Comment by cristigalas** [comment]
@favoeva @chiccap Qui il testo email o sms che avrei pensato:

Salve, nel ringraziarla per aver offerto una roulotte/camper a chi vive nelle zone colpite dal terremoto, le segnaliamo che a questo link può trovare le richieste che ci sono giunte fino ad oggi: http://terremotocentroitalia.info/searchissues/?query=Roulotte+camper
Visto che le richieste sono più delle offerte, stiamo chiedendo a chi offre roulotte o camper di consultare la lista delle richieste e quindi mettersi in contatto con chi ne ha bisogno. 
Se la donazione andasse a buon fine, le saremo grati se potesse avvisarci così da poter chiudere entrambe le segnalazioni di offerta e richiesta. 
Grazie ancora per la disponibilità e la collaborazione.
Cordiali saluti

**Comment by favoeva** [comment]
Ottimo @cristigalas 👍

**Comment by cristigalas** [comment]
Ok allora oggi spedisco! Tu @chiccap quello che aveva solo cellulare (Daniele Cartechini, Macerata) lo avevi già sentito vero? Nel caso gli mandi tu per sms il testo che ho scritto oppure vuoi che faccia io?

**Comment by chiccap** [comment]
@cristigalas sì sì l'avevo sentito io e posso risentirlo io senza problemi! Per ogni email/messaggio inviato aggiorniamo direttamente issue no?

**Comment by cristigalas** [comment]
Inviate email a Leonardo Sandon, Elvira, Arnaldo&Elvira. A questo punto @chiccap puoi inviare anche sms a Daniele Cartechini. 
Scorrendo le offerte, ho visto che c'è anche questa http://terremotocentroitalia.info/issues/471/ che dite, telefoniamo per sapere se è ancora disponibile?

**Comment by chiccap** [comment]
sì io inserirei. messaggio inviato! @cristigalas

**Comment by cristigalas** [comment]
Ho telefonato a questo Luigi che offriva 2 ruolotte a settembre (http://terremotocentroitalia.info/issues/471/) ma non risponde, riproverò.. purtroppo c'è solo cellulare e non email.

**Comment by iltempe** [comment]
questo issue lo sposterei negli issue del repo segnalazioni.

**Comment by iltempe** [comment]
da spostare in segnalazioni se è necessario proseguire.
