### ISSUE TITLE
Aggiungere "Segnala una Bufala"

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#433]
Si discuteva oggi dell'esigenza di segnalare le bufale.  

Aggiungerei una sezione qui http://terremotocentroitalia.info/segnala/ fatta come "Segnala Notizie".

Aggiungerei anche una label corrispondente "Bufale" nel repo degli issue.

Che dite?

**Comment by cristigalas** [comment]
A me pare un'ottima idea! Non ho idea di quale possa essere la risposta dei nostri utenti... chissà! Però io dire: proviamo!

**Comment by Pinzauti** [comment]
Mi sembra un'ottima idea, se mi date il via l'aggiungo

**Comment by iltempe** [comment]
@Pinzauti vai. crea tu la label facciamolo esattamente come per le notizie.

**Comment by Pinzauti** [comment]
Fatto
