### ISSUE TITLE
Aggiungere sul sito possibilità di richiedere rimozione

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#44]
E' necessario indicare un contatto per rimozione di dati impropri o inesatti da parte di chi legge. Basta un link ad una mail. quella del progetto sarà terremotocentroita@gmail.com

**Comment by StefanoF** [comment]
Posso mettere il contatto con descrizione in help.md che punta all'alias: terremotocentroita+rimozione@gmail.com 
In questo modo possono essere filtrate facilmente dalla mail principale terremotocentroita@gmail.com
1b1c515118ca6f1f6db82dfe3db95b45009a51f2

**Comment by StefanoF** [comment]
#66

**Comment by iltempe** [comment]
fatto.
