### ISSUE TITLE
Icona bufale in homepage

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#442]

**Comment by iltempe** [comment]
@franziner che dici?

**Comment by franziner** [comment]
assolutamente, ghe pensi mi (come si dice qui, a Milano) :)

**Comment by franziner** [comment]
ho preparato 3 icone, le inserirei ma temo di compromettere la visualizzazione su mobile. ci sono stili da modificare nel caso?
[bufala-tci.zip](https://github.com/emergenzeHack/terremotocentro/files/600986/bufala-tci.zip)

**Comment by iltempe** [comment]
un mito. fatto.
