### ISSUE TITLE
Gestire l'emergenza: smettere di subire l'emergenza, cominciare a progettare il modo per gestirla

### ISSUE THREAD

**Issue by TheBestMovieIsYourImagination** [emergenzeHack/terremotocentro#445]
Il lavoro che sta facendo terremotocentroitalia.org è fondamentale, però a mio parere è giunto il momento di strutturare meglio la cosa, e passare anche a una fase di progettazione, da affiancare al "lavoro sporco".
Il rischio è quello di continuare a subire l'emergenza, rincorrendo la nuova emergenza quotidiana, e dimenticando invece quelle passate, senza tener conto di priorità e visione globale della situazione.
Per questo l'emergenza va gestita. meglio farlo prima che si presenti, ma si può fare anche mentre ci siamo, ormai è tardi per farlo prima.
Gestire vuol dire coordinarsi, ragionare per priorità, focalizzarsi, organizzarsi.
Sappiamo bene che gli enti pubblici non possono fare tutto da soli, non sono capaci di farlo, e non sarebbe nemmeno giusto delegare tutto allo Stato.
Compito dell'associazionismo e dei cittadini auto-organizzati è vigilare, agire dove lo Stato non arriva, sperimentare forme innovative, supportare l'azione pubblica, ecc
Il primo passo è organizzare il lavoro e decidere le priorità.

**Comment by iltempe** [comment]
@TheBestMovieIsYourImagination questo luogo serve appunto per avere una traccia delle cose da fare. sulla gestione di subire o gestire non mi esprimo, io non ho tutte codeste certezze a riguardo, sicuramente chi lavora a questo progetto si adopera moltissimo per far si che le informazioni siano divulgate. non lo definirei affatto "lavoro sporco". Per quanto riguarda le pubbliche amministrazioni nessuno qui si contrappone in nessun modo allo stato, ma tutti proviamo a fare qualcosa. tu riesci a lavorare su qualcuno dei punti della lista degli issue aperti?

**Comment by TheBestMovieIsYourImagination** [comment]
@iltempe non credo tu abbia letto bene o compreso quello che ho scritto, visto che hai travisato praticamente ogni mia parola (certezze, lavoro sporco, contrappone, subire o gestire,... praticamente non hai colto nulla di quello che ho detto). 
parlo di progettazione, non tutto si fa con un'issue su GitHub. evidentemente la cosa non ti interessa, a qualcun altro interessa?
ci sono delle priorità sulle quali bisogna ragionare e lavorare, contattare altri soggetti, coordinarsi, non può bastare un'issue su GitHub. vorrei capire se qui c'è qualcuno disposto a lavorare su come gestire questa situazione, perchè sembra che in tutta Italia non ci sia nessuno disposto a farlo, e il rischio che vedo è che tutto si risolva come al solito.
continuano a passare settimane e mesi e tutto sembra fermo, nessuno si è mosso sulla gestione di questa situazione: tutto viene delegato agli enti pubblici e alle logiche di interesse privato, e nulla si muove per gestire questa situazione in modo diverso da quella delle logiche burocratiche o degli interessi privati. nessuno in Italia è interessato a gestire il post-terremoto secondo una logica di bene comune?

**Comment by iltempe** [comment]
@TheBestMovieIsYourImagination, mi spiace che tu mi risponda che no ho colto, perchè a me pare invece di non mi pare di aver travisato nulla. ho semplicemente letto. ho letto che hai parlato di "strutturare meglio la cosa, e passare anche a una fase di progettazione, da affiancare al "lavoro sporco". Di quale "lavoro sporco" parli? Il lavoro di questa comunità lo trovo nobile. Inoltre: dove ho mai detto che tutto si possa fare con un issue Github? Github è solo uno strumento che abbiamo scelto per comunicare in questo progetto. Potevamo sceglierne un altro. Abbiamo scelto questo. Riguardo al fatto che "nessuno sia disposto a gestire" ti rispondo nuovamente: qui si cerca "in piccolo" di fare delle cose per informare le persone. Tu parli invece di "gestione di una situazione" evidentemente ti senti di poter fare molto di più, che è cosa ammirevole, per la quale se hai delle proposte concrete da portare a questa comunità ti invito ad aprire un issue di discussione. grazie

**Comment by TheBestMovieIsYourImagination** [comment]
Ma guarda che le proposte concrete sono molto semplici:
basterebbe organizzarsi, contattare i proprietari di strutture o case vuote, metterli in contatto con le persone che ne hanno bisogno, e mettere su un sistema di traporto efficiente dai comuni limitrofi alle zone del sisma per chi ci lavora. basterebbe una paio di settimane. di container ne servirebbero pochissimi. le persone vivrebbero in modo decente fino a quando saranno pronte le casette di legno. ma nessuno si muove, tutto avviene come al solito arrangiandosi, distribuendo soldi a pioggia, arricchendo i privati a danno del bene pubblico.
Tanto per iniziare.
Per continuare c'è da pensare alla ricostruzione, per la quale già si muovono forti interessi, e poi tanto altro. se non ci muoviamo gli interessi privati a danno di quelli pubblici e la corruzione troveranno il solito (ampio) spazio.
L'ho detto all'inizio, il lavoro fatto qui è fondamentale, ma non basta. non è che se non basta è sbagliato, semplicemente non basta.

p.s. il "lavoro sporco" è quello tecnico e di gestione quotidiana, ovvio che è nobile anche quello, era per capirsi, se non ti piace il termine "sporco" usane un altro, non c'è problema.

**Comment by TheBestMovieIsYourImagination** [comment]
visto che [le finalità di questo progetto non sono queste](https://github.com/emergenzeHack/terremotocentro/issues/447#issuecomment-260154235), direi di chiudere anche questa issue, cercherò altrove, chi vuole saperne di più invece mi contatti in privato.
