### ISSUE TITLE
Aggiungere link ai Centri Operativi Comunali umbri alla Mappa contatti

### ISSUE THREAD

**Issue by TheBestMovieIsYourImagination** [emergenzeHack/terremotocentro#446]
L'elenco e la mappa dei Centi Operativi Comunali è stata inserita solo come [notizia](http://terremotocentroitalia.info/issues/1214/index.html), ma direi che è un'informazione importante e quindi deve stare in modo stabile sul sito, nella [Mappa contatti](http://terremotocentroitalia.info/2016-09-22-mappa-contatti/).

Quindi aggiungerei alla pagina Mappa contatti il link della [pagina](http://www.regione.umbria.it/centri-operativi) della Regione Umbria, e anche il link alla [mappa](https://www.google.com/maps/d/viewer?mid=1yv9i2qh-nVkfOBl_rwVpgP1T8-o). In questo modo non dobbiamo preoccuparci di mantenerli aggiornati.
Ho cercato anche quelli di Marche e Lazio ma non ho trovato qualcosa di simile.

**Comment by iltempe** [comment]
@TheBestMovieIsYourImagination ok, per fare questo devi verificare la fonte di questi dati https://www.google.com/maps/d/viewer?mid=1yv9i2qh-nVkfOBl_rwVpgP1T8-o&ll=42.92610703820189%2C12.748961096093808&z=10 verificare che abbiano licenza aperta che ti conceda di riusarli dopodiché aggiungere un layer sulla mappa dei contatti. Sai come procedere?

**Comment by TheBestMovieIsYourImagination** [comment]
a mio parere non serve aggiungere un layer alla mappa, basta mettere un link. cmq non so come si aggiunge un layer alla mappa.

**Comment by TheBestMovieIsYourImagination** [comment]
la mappa dei centri operativi comunali è stata aggiunta alla pagina [link e contatti utili](http://terremotocentroitalia.info/link_utili/)
