### ISSUE TITLE
Gestire l'emegenza 2: utilizzare le case vuote invece dei container fin dove possibile

### ISSUE THREAD

**Issue by TheBestMovieIsYourImagination** [emergenzeHack/terremotocentro#447]
Sembra che l'unica soluzione siano i container. non è vero.
Basterebbe organizzarsi, contattare i proprietari di strutture o case vuote, metterli in contatto con le persone che ne hanno bisogno, e mettere su un sistema di traporto efficiente dai comuni limitrofi alle zone del sisma per chi ci lavora. basterebbe una paio di settimane. di container ne servirebbero pochissimi. le persone vivrebbero in modo decente fino a quando saranno pronte le casette di legno. 
Ora invece tutto avviene come al solito arrangiandosi, distribuendo soldi a pioggia, arricchendo i privati a danno del bene pubblico.
Io sto parlando con le persone che vivono nelle zone colpite dal sisma e la situazione non è degna di un paese civile, ed è destinata a peggiorare con il freddo e la neve.
Loro vogliono restare vicine ai paesi di origine distrutti, ma non vogliono nemmeno vivere nei container, con bagni e docce comuni. La prospettiva di affittare un appartamento in qualche città vicina con i soldi della regione non la trovano dignitosa, ed è anche scomoda senza un sistema di traporto efficiente, perchè quelle strade, già colpite dal sisma, non sono in grado di reggere questo traffico.

**Comment by iltempe** [comment]
@TheBestMovieIsYourImagination ti invito a leggere ciò che abbiamo scritto essere lo scopo di questo progetto. lo trovi nel sito ma anche nel wiki github. il progetto si pone lo scopo di informare correttamente sul tema del sisma non di gestire l'emergenza nè tantomeno le segnalazioni direttamente, noi facciamo da facilitatori e da aggregatori di notizie ma non ci occupiamo di "gestire" direttamente le segnalazioni per risolverle.

**Comment by iltempe** [comment]
chiudo perchè off topic.

**Comment by TheBestMovieIsYourImagination** [comment]
su telegram si parla continuamente di come risolvere le segnalazioni e aiutare le popolazioni. 
forse allora dovresti chiarire meglio lo scopo del sito, che a quanto pare è solo informativo.
quindi direi che invece chi vuole aiutare le popolazioni deve creare un altro sito. basta saperlo, grazie.
