### ISSUE TITLE
Preparare la lista dei CREDITI

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#45]
a partire dalla pagina About del sito va compilata una lista di ringraziamenti a tutti coloro hanno dato un contributo al progetto.

Serve indicare Nomi Cognomi, Associazioni, Gruppi Informali, Aziende e il motivo del ringraziamento.

**Comment by rirri93** [comment]
Posso farlo io, se mi date le indicazioni necessarie mi metto a lavoro

**Comment by favoeva** [comment]
Timothy Mario Redaelli (il perchè lo sapete voi meglio di me) 
Fabio Manfrin : una delle colonne portanti del gruppo monitoraggio FB, nonché ideatore dello sticker set TCI ;)
