### ISSUE TITLE
Notifica automatica di pubblicazione segnalazione e richiesta utente di aggiornamento/modifica della segnalazione

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#452]
Per migliorare la gestione delle segnalazioni stavo pensando se era possibile inviare una notifica automatica quando una segnalazione viene pubblicata all'indirizzo email indicato nella segnalazione, ovviamente nel caso in cui ci sia. 
Inoltre, oltre alla notifica di "segnalazione pubblicata", sarebbe secondo me utile anche qualcosa che dica: 'se vuoi aggiornare o chiudere la segnalazione perché risolta clicca qui' e se uno clicca si apre la segnalazione su Github che si può aggiornare o chiudere. O meglio bisognerebbe che a noi ci venisse notificato che la segnalazione è stata aggiornata/modificata o è stato richiesto di chiuderla e sta a noi accettare e quindi pubblicare le modifiche o chiudere la segnalazione. 
Insomma bisognerebbe prevedere qualcosa che coinvolga anche gli utenti nella gestione delle segnalazioni. Ciò secondo me ci aiuterebbe a gestirle meglio e a tenerle aggiornate. Che ne dite?

**Comment by TheBestMovieIsYourImagination** [comment]
Su ogni segnalazione c'è in fondo il link alla issue su GitHub, quindi in realtà c'è già il modo per chiederne la chiusura o l'aggiornamento.
Sarebbe utile anche una pagina che però spiegasse come funziona questo sistema, perchè a parte i programmatori non credo che nessuno lo conosca, e non credo nemmeno sia tanto intuitivo il fatto che per aggiornare/chiudere bisogna usare l'issue su GitHub.

**Comment by iltempe** [comment]
@TheBestMovieIsYourImagination esiste questo wiki dove abbiamo cercato di spiegare tutto il progetto. E' piuttosto corposo ma se vuoi approfondire è un'ottima base di partenza. C'è ancora molto da migliorarla ma puoi contribuire a tenerlo aggiornato o a fixarlo tu stesso se trovi degli errori. https://github.com/emergenzeHack/terremotocentro/wiki

**Comment by TheBestMovieIsYourImagination** [comment]
@iltempe se vuoi che il sito sia più usabile non puoi usare soltato la wiki su GitHub per spiegare come funziona il sito, l'utente deve trovare un link, o una finestra in sovra-impressione o pop-up, nella stessa pagina nella quale l'utente ne ha bisogno.
non puoi sperare che l'utente vada a leggere la wiki su GitHub, tranne che in casi particolari, nella maggior parte dei casi l'utente rinuncerà..

**Comment by iltempe** [comment]
attualmente ho buoni feedback da chi ha provato a leggere il wiki. certo non è un libro di carta da sfogliare o non come se qualcuno te lo spiegasse a voce ma è un buon punto di partenza (da migliorare).
