### ISSUE TITLE
Rinominare pagina "Link" in "Link e contatti utili" e spostarla nella sezione "Utilità"

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#454]
Stavo cercando sul sito i contatti e non li trovavo fino a che li ho trovati nella pagina link che a sua volta sta nella sezione 'offerte'. Secondo me così non va bene, o meglio potrebbero stare anche nella pagina link ma rinominando la pagina in "Link e contatti utili" e poi la pagina forse starebbe meglio nella sezione Utilità. Che ne dite?

**Comment by mfortini** [comment]
Fatto
