### ISSUE TITLE
Pubblicare nuovo elenco Link utili e rinominare sezione Fonti Importanti

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#458]
Ho rivisto e ampliato i link pubblicati sul sito nella pagina Link e contatti utili (sezione Fonti Importanti). In questo file su GoogleDrive il nuovo elenco, pronto per essere pubblicato: https://docs.google.com/document/d/186oApJnEF4I979UGaquoJtyHUT9yeO0OvPOaF61wDTg

Bisognerebbe, secondo me, anche rinominare la sezione link che adesso si chiama Fonti Importanti in Link Utili, così come del resto è riportato anche nella voce di menù. Che ne dite?

**Comment by iltempe** [comment]
fatto.
