### ISSUE TITLE
Natale Doni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#459]
Suggerisco di provare ad iniziare a conttare grandi aziende di giocattoli per registrare donazioni di regali per i bambini terremotati. Occorre secondo me una task force dei "social media cosi" su questo punto. Io posso supportare al massimo. Che dite?

**Comment by iltempe** [comment]
Ho creato una label per gli issue "Bambini"

**Comment by cristigalas** [comment]
Ma ci muoviamo senza richieste precise? Credo sia più difficile intercettare disponibilità delle aziende senza richieste... Per sondare le eventuali richieste, possiamo semmai chiedere nel gruppo Facebook se ci sono associazioni o Comuni o gruppi di cittadini interessati a stabilire contatti con aziende di giocattoli? Che dite?

**Comment by iltempe** [comment]
Mi aggancerei a realtà locali. Associazioni o laboratori o scuole. MA difficilmente qualche bambino o genitore chiederà espressamente un dono. Sondiamo il terreno.

**Comment by cristigalas** [comment]
Guardando tra i contatti sul sito e le richieste ricevute potremmo fare una lista di associazioni, comitati civici, scuole (soprattutto quelle nelle tensostrutture) e quindi inviare loro una mail chiedendo se sono interessati... che ne dici @chiccap?

**Comment by cristigalas** [comment]
Un'ultima cosa: a proposito della label "bambini" ma la usiamo solo per richieste e donazioni giocattoli o anche per altri beni rivolti ai bambini? Penso ad esempio ad abiti e scarpe...

**Comment by iltempe** [comment]
la userei per tutto ciò che riguarda i “bambini”

**Comment by chiccap** [comment]
@cristigalas domani pomeriggio mi ci metto e la
Faccio!

**Comment by cristigalas** [comment]
Ok! Intanto io inserisco label "bambini" a tutte le segnalazioni che riguardano i bambini.

**Comment by cristigalas** [comment]
Inserita label bambini a tutte le segnalazioni. Sono 20 per ora.

**Comment by iltempe** [comment]
fatta anche la pagina chiudo.
