### ISSUE TITLE
Invio email a enti, associazioni, comitati del cratere per avviare o stabilizzare collaborazione

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#465]
Raccogliendo anche quanto emerso nel gruppo Telegram (vedi #464), con @chiccap abbiamo pensato di inviare una email a tutti gli enti, associazioni e comitati civici che in questi mesi si sono impegnati sul territorio del cratere per sollecitarli ad avviare con noi una collaborazione più stabile e concreta e per invitarli ad usare, come meglio credono, il nostro progetto. 

L'elenco dei contatti è qui https://docs.google.com/spreadsheets/d/1B3eqSrYShfeFUeTSLFJyH2rG_e9ZFK90fhOhDS_pUGE/edit?usp=sharing 
Il file è stato ricavato dalla pagina "contatti e link utili" che è sul sito: http://terremotocentroitalia.info/link_utili/ Manca ancora qualche associazione ma il grosseo c'è.

Questo il testo della email che vorremmo inviare:

_Salve, 
sono una volontaria del progetto non profit TerremotoCentroItalia. Come forse già sapete, siamo un gruppo di volontari e attivisti che dal 24 agosto offre un servizio di monitoraggio, raccolta e diffusione di segnalazioni verificate riguardanti le aree terremotate. In particolare attraverso il nostro sito http://terremotocentroitalia.info/ e i nostri canali social cerchiamo di facilitare l'incontro tra le richieste di aiuto e l'offerta di beni e servizi. Ad oggi abbiamo raccolto oltre 1500 segnalazioni._ 

_In questi giorni stiamo cercando di raggiungere gli enti, le associazioni e i comitati che in questi mesi si sono attivati nelle aree colpite dai terremoti del 24 agosto e 30 ottobre perché vorremmo creare collaborazioni più stabili con chi, come voi, ogni giorno opera sul territorio per far fronte ai bisogni delle popolazioni._ 

_Il nostro servizio e i nostri volontari sono a vostra completa disposizione per diffondere richieste e bisogni, offerte e donazioni, raccolte fondi e notizie utili. Potete inviarci le segnalazioni attraverso i nostri canali di comunicazione (vedi qui http://terremotocentroitalia.info/canali/) oppure attraverso la nostra webform "Segnala" http://terremotocentroitalia.info/segnala/ o la nostra app gratuita (Android) https://play.google.com/store/apps/details?id=eh.terremotocentroitalia_

_La webform può essere facilmente inserita sul vostro sito (vedi indicazioni in calce alla webform) 
così da facilitarne l'uso anche da parte dei vostri utenti._

_Ci rendiamo conto che dopo la fase di cosiddetta emergenza, si è aperta una fase post-terremoto, se possibile, ancora più complessa e delicata. Saremo felici di poter dare una mano concreta a voi e agli abitanti delle aree terremotate, nel modo che riterrete più utile e opportuno._

_Rimaniamo a disposizione per ogni ulteriore informazione o richiesta. Intanto vi ringraziamo della vostra attenzione e soprattutto del vostro impegno!_

_Un caro saluto
Cristina Galasso
Team TerremotoCentroItalia_

**Comment by TheBestMovieIsYourImagination** [comment]
> Il nostro servizio e i nostri volontari sono a vostra completa disposizione per diffondere richieste e bisogni, offerte e donazioni, raccolte fondi e notizie utili. Potete inviarci le segnalazioni attraverso i nostri canali di comunicazione (vedi qui http://terremotocentroitalia.info/canali/) oppure attraverso la nostra webform "Segnala" http://terremotocentroitalia.info/segnala/ o la nostra app gratuita (Android) https://play.google.com/store/apps/details?id=eh.terremotocentroitalia

Io aggiungerei qualcosa in più oltre a chiedere di usare il webform.
Proporrei TCI come un futuro canale di comunicazone tra le popolazioni che vivono nelle zone colpite e i soggetti destinatari delle loro richieste.
**Quello che manca a quelle popolazioni non è un'altra webform**, di quelle ne esistono fin troppo ;-), ma gli serve un canale di comunicazione efficace. 
Forse TCI non è ancora così efficace, ma possiamo proporci di lavorarci su. 
Quello che può fare TCI rispetto ai canali istituzionali è proprio lavorare sulla capacità di comunicazione: quella istituzionale è fissa, noi possiamo migliorare.

**Comment by TheBestMovieIsYourImagination** [comment]
sarebbe anche utile spiegare meglio l'utilità del sito e delle segnalazioni attraverso il sito. noi lo sappiamo come funzionano, ma loro forse no ;)

**Comment by cristigalas** [comment]
@favoeva e @chiccap stanno preparando una email da inviare solo ai Comuni che propone loro di usare TCI così come ha fatto recentemente la Provincia di Teramo. A questo punto il testo qui copiato potrebbe essere un po' modificato e aggiornato sulla base di quanto accaduto con il terremoto del 18/1  e quindi inviato solo a associazioni e comitati civici.

**Comment by favoeva** [comment]
mail ai Comuni inviata, ecco il testo:

Gentilissimi Sindaci, 
vi contatto perché vorremmo farvi conoscere il Progetto TerremotoCentroItalia, una comunità di attivisti che dal 24 agosto 2016 si è messa al lavoro per raccogliere, verificare e condividere informazioni utili, richieste, offerte e tutto quello che può essere di aiuto alle popolazioni colpite dal sisma. Qui trovate quello che i media, sia locali che nazionali, raccontano di noi http://terremotocentroitalia.info/press/ . 
Sappiamo che vi state adoperando al meglio come amministratori pubblici per mettere a punto tutte le azioni, amministrative e non, che possano far rientrare al più presto nella normalità la vita dei vostri concittadini e dunque vorremmo invitarvi a usarci per: 
diffondere richieste specifiche in caso di emergenza 
sostenere una rapida circolazione di informazioni su quello che sta accadendo nei vostri Comuni 
o qualsiasi altra cosa di cui abbiate bisogno.
Una prima pubblica amministrazione lo ha già fatto: la Provincia di Teramo per far fronte all'emergenza neve in Abruzzo ha deciso di adottare il sistema di gestione delle segnalazioni del progetto Terremotocentroitalia, rendendo disponibile una persona che assieme a noi sta monitorando segnalazioni provenienti dalla Provincia. Questi gli strumenti che sta utilizzando:
il modulo creato per raccogliere le segnalazioni https://enketo.ona.io/x/#YBjh;
mappa per raccogliere le segnalazioni http://umap.openstreetmap.fr/it/map/emergenza-teramo-segnalazioni-emergenza-neve_122333.
Il sistema che abbiamo messo a punto è basato su software open source, aperto alla implementazione e miglioramento costante e consente:
- ricerca per parole chiave tra le diverse tipologie di segnalazioni, 
- elaborazione dei dati per mappature e future analisi, 
- attribuzione certa di compiti di gestione ai vostri operatori,
collaborazione e sostegno da parte della nostra rete di circa 70 attivisti per ”‘incrocio” tra fabbisogni e disponibilità. 
Gli strumenti che abbiamo messo a punto possono essere adattati in base alle vostre specifiche esigenze, lo abbiamo fatto con la Provincia di Teramo e possiamo farlo anche per voi.

Alcuni numeri sul progetto

Segnalazioni suddivise per tipologia gestite ad oggi dalla nostra rete:
- 365 fabbisogni
- 260 raccolte fondi
- 575 notizie utili
- 83 offerte di alloggio e di stalli per animali
- 265 donazioni di beni e servizi
- 51 richieste di acquisto solidale
- 97 contatti utili
- 24 ‘bufale’ (notizie false e loro di smentita)

La community
- 7004 iscritti al gruppo Facebook
- 3117 follower su Twitter
- 553 iscritti al canale Telegram
- 244 iscritti al gruppo Telegram (attivisti di terremotocentroitalia.info: comunicatori, social media manager, sviluppatori, cittadini e cittadine)
- 443 follower su Instagram
- 433 documenti su Archive.org (sezione del sito dedicata alla raccolta dei documenti pubblici per la gestione del post terremoto)
- 10 mappe 
- 68 citazioni sui media

Il sito web

- 88.517 visitatori
- 116.000 sessioni
- 298.272 visualizzazioni
Fabbisogni, News e Acquisti Solidali le pagine più visitate
Italia, Usa, Gran Bretagna, Germania e Svizzera i paesi di provenienza dei visitatori

Se avete bisogno di ulteriori chiarimenti, siamo a vostra disposizione.
Grazie e buon lavoro!

Matteo Tempestini 
Coordinamento Progetto TerremotoCentroItalia

I nostri contatti:
indirizzo email terremotocentro@gmail.com  ;
gruppo Facebook https://www.facebook.com/groups/1758670357733881/ ;
Twitter @terremocentro https://twitter.com/terremotocentro  ;
gruppo Telegram https://telegram.me/joinchat/BgW6eEBsI3rLKsJk9L7FJg 

Qui invece il wiki del progetto https://github.com/emergenzeHack/terremotocentro/wiki
