### ISSUE TITLE
Proposta di nuova tipologia segnalazione "cerco/offro lavoro"

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#468]
Sul gruppo Facebook è stata postata questa proposta da Alessandra Merizzi:

_Ciao, sono una volontaria parte del coordinamento psico-sociale Marche, area 4 del fermano. Vorrei sapere se possibile aggiungere la voce "cerco-offerta lavoro" nel sito terremotocentroitalia.info
Ci sono molte persone che hanno perso la loro attività lavorativa e hanno esigenza di ricominciare a lavorare sia per una questione economica che psicologica. Sarebbe veramente utile creare una piattaforma per lo scambio di domande & offerte di lavoro in questo momento, anche lavori stagionali. Crediamo che il vostro sito sia ideale in quanto c'è possibilità di cercare/offrire alloggi e ci sono molte altre informazioni utili. Che ne dite? Grazie._

**Comment by iltempe** [comment]
Io la trovo un'idea interessante, purchè la si possa limitare ad offerte e richieste delle zone in emergenza, un filtro che potremmo fare noi in redazione. Le segnalazioni potrebbero essere inviate con un modulo esattamente come quello che c'è ora sul sito. potremmo fare due pulsanti cerco lavoro offro lavoro. che ne dite?

**Comment by cristigalas** [comment]
Sì, per la form non credo ci siano problemi (per Cerco lavoro si può usare Chiedi aiuto e per Offro lavoro quella Donazioni) e ok anche per i due pulsanti. Riguardo, invece, all'area: @iltempe pensavi di limitare offerte e richieste ai comuni del cratere o alle regioni convolte dal sisma? Io credo potrebbe essere utile distinguere, allargando alle regioni interessate dal sisma (Lazio, Abruzzo, Marche e Umbria) per chi offre lavoro, così da ampliare un po' il raggio di offerta ma non troppo, ma limitando ai soli Comuni del cratere per chi cerca lavoro. È fattibile?

**Comment by iltempe** [comment]
Proposta:
-aggiungere nel form una sezione Lavoro (cerco/offro) dove si può specificare domanda e offerta di lavoro e a quale luogo si riferisce
- la segnalazione arriva in redazione come issue con label "cerco lavoro" o "offro lavoro"
- la redazione valuta di volta in volta se la domanda o l'offerta sono "pubblicabili" e se si riferiscono alle aree interessate.
- si fa una pagina di offerte lavoro e una di richieste lavoro sul sito.

**Comment by cristigalas** [comment]
Ok ma poi qualche criterio dovremmo darcelo per accettare le segnalazione, ad esempio per "area interessata" cosa intendiamo? Comune o Regione? E almeno un criterio lo renderei pubblico e lo scriverei anche sulla form, ovvero che chi cerca lavoro debba risiedere nei comuni del cratere, anche se ho l'impressione che potremmo fare ben poco per verificare l'autenticità della segnalazione.

**Comment by favoeva** [comment]
anch'io come @cristigalas vedo difficile verifica ...  

ho dato una rapida occhiata alle offerte di lavoro che in questo momento risultano aperte da [centri per impiego regione marche qui ](http://www.regione.marche.it/Regione-Utile/Lavoro-e-Formazione-Professionale/Servizi-per-limpiego-pubblici-e-privati#Offerte-di-lavoro)
e ne hanno parecchie!

Pensavo che per le offerte lavoro potremmo chiedere a centri impiego delle regioni colpite in che modo potremmo collaborare con loro come aggregatore e canale di diffusione non solo delle offerte di lavoro, ma anche di notizie utili per chi cerca lavoro nei comuni colpiti (nuovi strumenti di sostegno ai lavoratori o aggiornamenti su strumenti già disponibili). 

ho cominciato a raccogliere i contatti CPI Marche , ditemi se ha un senso e se andare avanti con altre regioni

**Comment by iltempe** [comment]
@cristigalas potremmo accettare solo le ricerche di lavoro dei comuni colpito e le offerte chiaramente utili per quelle persone. @favoeva va benissimo procedere raccogliendo quei contatti secondo me. @Pinzauti qui ci sarebbe da aggiornare il nostro webform con questa nuova idea, che dici?

**Comment by cristigalas** [comment]
@favoeva secondo me ha molto senso contattare i centri per l'impiego! Ottima idea!

**Comment by chiccap** [comment]
se decidiamo di far inserire le segnalazioni di ricerca del lavoro possiamo pensare di far caricare il cv dall'interessato...così potrebbe essere leggermente più verificabile, no @cristigalas? inoltre, starei attenta a limitare ai soli residenti la possibilità della ricerca lavoro: se una persona lavorava in un'azienda del cratere ma non risiede nel cratere?

**Comment by cristigalas** [comment]
Questa del curriculum è un'ottima idea, brava @chiccap! Riguardo all'altra questione che sollevi, hai ragione... possiamo quindi limitare la ricerca lavoro a chi risiede o è domiciliato nell'area del cratere...

**Comment by Pinzauti** [comment]
Ciao a tutti,
Nel fine settimana aggiorno la webform.
Inserisco anche una descrizione di chi può inserire gli annunci? Se sì quale?
Cerco e Offro li metto in due sezioni separate o li inserisco in un unica sezione magari facendo scegliere l'utente da una dropdown list il tipo di annuncio?

**Comment by cristigalas** [comment]
@Pinzauti grazie Francesco. 
Per me va bene fare un'unica sezione con dropdown list a patto che:
1. nella tipologia "cerco lavoro" compaia questo testo:  "Gli annunci per la ricerca di lavoro sono limitati a coloro che risiedono o sono domiciliati nei Comuni del cratere. Qui l'elenco: http://terremotocentroitalia.info/2016-08-24-mappa-comuni-cratere/"
2. In calce alla segnalazione ci sia la possibilità di allegare file, in particolare curriculum vitae. Opzione che renderei obbligatoria, così da rendere un po' più verificabile la segnalazione. Anche in questo caso aggiungerei un testo come questo: "E' obbligatorio allegare il proprio curriculum vitae".

Che ne dite?

**Comment by chiccap** [comment]
Sottoscrivo tutto @cristigalas!
Grazie mille @pinzauti

**Comment by iltempe** [comment]
Ottimo @Pinzauti . Facciamo per favore che sia distinte con due label OFFERTE da RICHIESTE. grazie!!!

**Comment by Pinzauti** [comment]
I curriculum dove li carichiamo?
Intanto ecco un'anteprima = https://terremotocentroitalia.herokuapp.com/segnalazioni/lavoro.html

**Comment by iltempe** [comment]
@Pinzauti io non farei caricare i CV. metterei piuttosto un link ad un CV online (linkedin, sito aziendale, personale o altro). Grazie

**Comment by cristigalas** [comment]
@iltempe però avere i cv ci aiuterebbe nella verifica e a rendere più 'attendibile e seria' la richiesta. Non si può creare una repository su Github dedicata?

**Comment by cristigalas** [comment]
@Pinzauti vista l'anteprima... secondo me andrebbe tolto il campo 'cosa' che non mi pare aver senso visto che già c'è cerco/offro, mentre andrebbe inserito il campo (obbligatorio) nome&cognome.

**Comment by iltempe** [comment]
@cristigalas si può fare ma va creata una folder dove poi dobbiamo creare un modo per fare upload in rete e far dichiarare a tutti che tutti i contenuti del CV son liberi da privacy. Tanto vale far linkare un profilo o un sito già online. Se anche mettono un profilo social (uno qualunque) possiamo usarlo per verificare ed eventualmente contattare.

**Comment by cristigalas** [comment]
@iltempe ho capito, va bene. Però almeno al campo link aggiungiamo un testo tipo: per completare la richiesta si consiglia di inserire un link  a curriculum online, profilo social o pagina web di presentazione. Inoltre, a questo punto, il campo file si può togliere, no?

**Comment by iltempe** [comment]
@cristigalas @Pinzauti si io farei cosi: toglierei il campo file e dove c'è il link scriverei una cosa tipo "inserisci un link ad un curriculum online, profilo social o pagina web di presentazione per facilitare l'approvazione interna della tua segnalazione"...

**Comment by cristigalas** [comment]
Ok! E in fondo invece che "inserisci donazione" mettiamo ovviamente qualcosa come "inserisci annuncio" (espressione che può andare bene sia per domanda che offerta).

**Comment by iltempe** [comment]
perfetto. per le label github ne facciamo una per "cerco lavoro" e una per "offro lavoro"? che dite?

**Comment by cristigalas** [comment]
Sì sì! Due label!

**Comment by iltempe** [comment]
ok allora @Pinzauti riassumendo: 
- toglierei il campo file 
- dove c'è il link scriverei una cosa tipo "inserisci un link ad un curriculum online, profilo social o pagina web di presentazione per facilitare l'approvazione interna della tua segnalazione"
- in fondo invece che "inserisci donazione" mettiamo qualcosa come "inserisci annuncio" (espressione che può andare bene sia per domanda che offerta)
- oltre a "webform" predisponiamo due label GITHUB una per "cerco lavoro" e una per "offro lavoro"
grazie!

**Comment by Pinzauti** [comment]
Fatto!

**Comment by chiccap** [comment]
A me piace molto! Mi sembra molto intuitivo, grazie!

**Comment by cristigalas** [comment]
Grazie @Pinzauti ottimo lavoro!

**Comment by cristigalas** [comment]
Scusa @Pinzauti ma è possibile che con Chrome su IPad non riesca a vedere il nuovo bottone cerco/offro lavoro? Con Safari lo vedo ma con Chrome no!

**Comment by Pinzauti** [comment]
Prova a cancellare la cache e a ricaricare, è possibile che la pagina sia rimasta in memoria.

**Comment by cristigalas** [comment]
Avevi ragione :( grazie!

**Comment by chiccap** [comment]
@Pinzanuti riesci a rendere obbligatorio il campo 'luogo' per favore?

**Comment by favoeva** [comment]
scusate non seguivo più questa issue e ora ho visto commento su gruppo telegram @_@ 
ok allora proseguo con raccolta contatti Centri per l'Impiego poi decidiamo cosa farne.

**Comment by Pinzauti** [comment]
Fatto  @chiccap

**Comment by chiccap** [comment]
Grazie mille @Pinzanuti!
