### ISSUE TITLE
Risultati ricerca in ordine temporale

### ISSUE THREAD

**Issue by chiccap** [emergenzeHack/terremotocentro#469]
Ciao!
Mi sono resa conto che quando si utilizza l'opzione 'cerca' sul sito poi i risultati vengono fuori in ordine temporale sparso. Sarebbe utile, se fosse possibile, far uscire i risultati con le issue più recenti in cima.
Che ne pensate?
Grazie!

**Comment by cristigalas** [comment]
Hai ragione, brava @chiccap!

**Comment by cristigalas** [comment]
Che ne dite @mfortini @iltempe, si possono ordinare? Effettivamente la ricerca ora è un po' faticosa...

**Comment by cristigalas** [comment]
@mfortini @iltempe @chiccap mi sono persa... ma a che punto siamo con questa issue?

**Comment by chiccap** [comment]
Non so, forse è ferma... (?)

**Comment by cristigalas** [comment]
@mfortini ha provveduto! Ora i risultati delle ricerche sono in ordine cronologico. Chiudo.
