### ISSUE TITLE
[richiesta iscrizione]

### ISSUE THREAD

**Issue by ghost** [emergenzeHack/terremotocentro#470]
Salve a tutti,

Mi chiamo Francesco e vorrei essere considerato per contribuire al vostro progetto.

Ho un'esperienza di qualche anno nel giornalismo (anche nell'area editing e fact-checking) e nella ricerca (il campo era quello del terrorismo). Ho inoltre una conoscenza piuttosto approfondita di Excel, una base di statistica e un'infarinatura di R Studio e Open Refine.

La gestione delle emergenze è un settore che mi interesserebbe moltissimo, in particolare l'aspetto della raccolta dei dati e delle mappature.

Credo quindi che sarebbe molto interessante poter contribuire anche in maniera minima.

Trovate qui il mio profilo LinkedIn: [https://www.linkedin.com/in/francesco-finucci-7973868a/]

A presto,
Francesco Finucci

**Comment by iltempe** [comment]
ciao @FrancescoFinucci ! qui la lista degli issue su cui lavoriamo ti consiglio anche la sezione WIKI per capire come funziona il progetto e dove sono i dati utili per te. Per comunicazioni veloci abbiamo un gruppo telegram.

**Comment by ghost** [comment]
Ciao! Ho visto la wiki e mi sono connesso al gruppo Telegram. Serve fare qualche altra cosa per ora?

**Comment by iltempe** [comment]
Se trovi persone che hanno foto del terremoto puoi fargli seguire questo http://www.terremotocentroitalia.info/2016-08-30-Condividere-immagini-e-video-dell-evento/ grazie!
