### ISSUE TITLE
Proposta di nuova tipologia segnalazione "eventi" 

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#471]
Oggi Sara Vegni di AA ha fatto presente l'esigenza di avere un form di segnalazione per Eventi provenienti dai territori terremotati. Pare sia possa essere molto utile.

@Pinzauti ti è possibile creare una nuova pagina di segnalazione ?

Come campi propongo:
- Nome
- Indirizzo (con mappa)
- Descrizione 
- Data
- Ora
- Link

Assocerei a queste segnalazioni una label Github "Eventi".
Che ne pensate?

**Comment by Pinzauti** [comment]
D'accordo, aggiorno nel fine settimana!

**Comment by cristigalas** [comment]
Riguardo ai campi, invece che "nome" proporrei "titolo evento" e poi aggiungerei un campo "ente promotore" dove inserire il nome dell'ente che organizza/promuove l'evento.

**Comment by iltempe** [comment]
perfetto allora facciamo:

- Titolo Evento
- Indirizzo (con mappa)
- Descrizione
- Data
- Ora
- Promotore
- Link

**Comment by Pinzauti** [comment]
Fatto!

**Comment by iltempe** [comment]
ottimo, grazie @Pinzauti e auguri di buon compleanno (in ritardo!!!)

**Comment by Pinzauti** [comment]
Grazie! =D

**Comment by iltempe** [comment]
puoi correggere la label Github e mettere Eventi anzichè Donazioni? grazie @Pinzauti

**Comment by Pinzauti** [comment]
Corretto

**Comment by iltempe** [comment]
@Pinzauti scusami se ti disturbo ancora. 
'titolo evento': 
'data evento': 
'ora evento':

andrebbero cambiate in titolo_evento data_evento ora_evento in modo da non dover mettere gli apici nel corpo dell issue github relativo. grazie

**Comment by cristigalas** [comment]
Anche campo Promotore...

**Comment by iltempe** [comment]
@Pinzauti scusami ancora! vedo che nonostante tu abbia messo il formato della data evento come gg/mm/aaaa dentro l'issue https://github.com/emergenzeHack/terremotocentro_segnalazioni/issues/2453 la data è arrivata in formato aaaa/mm/gg puoi verificare? se possibile sarebbe meglio gestire tutto con formato gg/mm/aaaa. grazie

**Comment by Pinzauti** [comment]
Mmm vedo, guardo come risolvere nel weekend

**Comment by Pinzauti** [comment]
Fatto!

**Comment by iltempe** [comment]
ottimo thanks!
