### ISSUE TITLE
Problema segnalato da Github

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#474]
Github ci ha inviato una email segnalando un errore, questo il testo:

The page build failed with the following error:
Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.
For information on troubleshooting Jekyll see:
https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by iltempe** [comment]
dovrebbe essere a posto.
