### ISSUE TITLE
Verificare tutte le issue "alloggi"

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#494]
Estrarre tutte le email dalle issue di tipo "alloggi" e aggiornare le segnalazioni indicando cosa ne sia successo.

**Comment by cristigalas** [comment]
Inviata email a circa 400 indirizzi ([vedi qui](https://docs.google.com/spreadsheets/d/16ADTJ9Swr39Jlam9CesZn8B2iaWZRyN9slCGyJBkzCg/edit)) in cui chiediamo di indicare se l'offerta di alloggio è stata accolta da qualcuno e se è ancora disponibile.

**Comment by cristigalas** [comment]
Issue #Alloggi aggiornate grazie a @chiccap e inviata email di ringraziamento a tutti coloro che ci hanno risposto. Chiudo issue.
