### ISSUE TITLE
Problema nell'invio automatico comunicati Protezione Civile e due proposte

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#496]
Da qualche tempo c'è un problema nell'invio automatico dei comunicati della Protezione civile nel canale Telegram. Vengono mozzati... Per capirci sono quelli pubblicati nella sezione "Comunicati" del sito della Provic, ovvero [qui](http://www.protezionecivile.gov.it/jcms/it/comunicati_stampa.wp?frame5_item=1). Si potrebbe risolvere il problema?

Già che ci sono propongo due cose:
1. Ad oggi su Telegram e Messanger vengono pubblicati automaticamente tutti i comunicati della Prociv anche quelli che nulla hanno a che fare con il tema 'terremoto' e, visto che l'emergenza terremoto è passata, ciò significa che pubblichiamo automaticamente tanti comunicati che riguardano altro (incendi boschivi, maltempo, ecc.). Si potrebbe pubblicare solo quelli che contengono la parola "terremoto" che apre sempre i comunicati riguardanti gli eventi sismici durante e post emergenza? Forse in questo potrebbe esserci di aiuto @aborruso?
2. Oltre che su Telegram e Messanger, si potrebbe pubblicare automaticamente i comunicati ProCiv anche su Twitter? Fino ad oggi, infatti, tuittiamo a mano questi comunicati che però rischiano di sfuggirci sia quando sono tanti (in caso di emergenza in corso, vedi Ischia), sia quando sono molto pochi (vedi terremoto Centro Italia). Secondo me, quindi, sarebbe meglio che anche su Twitter venissero pubblicati automaticamente.

@iltempe @mfortini @favoeva @chiccap che ne dite?

**Comment by chiccap** [comment]
Ciao!
Grazie @cristigalas per la solita attenzione ai particolari. Fanno la differenza. 
Per quanto riguarda il punto 2 sono molto d'accordo: in primo luogo è importante per la neonata collaborazione con il giornale della ProtCiv e, inoltre, ci scarica di un lavoro meccanico e che, appunto, talvolta può risultare impreciso.

**Comment by aborruso** [comment]
Lo assegno a me.

Grazie @cristigalas

**Comment by cristigalas** [comment]
@chiccap grazie! Sapevo che avresti capito il mio essere un po' pallosa ;)
E grazie a te @aborruso per il pronto intervento!

**Comment by iltempe** [comment]
ma è risolto'?

**Comment by aborruso** [comment]
@iltempe ho risolto il problema. Le due proposte potrebbero essere due nuove issue

**Comment by iltempe** [comment]
per le proposte fare nuovi issue. chiudo. grazie
