### ISSUE TITLE
inserire nel maxi feed gli aggiornamenti Google sheet

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#50]
Aggiungere ai feed del maxi feed tutti gli aggiornamenti degli sheet con alloggi, raccolte fondi etc...

**Comment by aborruso** [comment]
@mfortini hai già fatto feed per  alloggi, raccolte fondi, ecc.?

**Comment by iltempe** [comment]
scusate ma questo maxi feed è ancora gestito oppure ogni feed è gestito per conto suo? posso chiudere l'issue se non lo gestiamo?
