### ISSUE TITLE
Sul sito la Mappa generale e la Mappa delle segnalazioni sono sparite

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/terremotocentro#504]
Segnalo che sul sito la [pagina](https://terremotocentroitalia.info/mappa/) che un tempo conteneva la 'Mappa Generale' è adesso vuota e così anche la [pagina ](https://terremotocentroitalia.info/2016-09-01-mappa-segnalazioni/) con la Mappa delle segnalazioni inviate... @mfortini @iltempe sapete come mai?

**Comment by iltempe** [comment]
scusate questo è ancora aperto?

**Comment by cristigalas** [comment]
@iltempe sì, le mappe non si vedono...

**Comment by cristigalas** [comment]
Mappa generale ora funziona mentre quella delle segnalazioni no. @mfortini dice che ci deve lavorare Piersoft.

**Comment by iltempe** [comment]
ho rimosso la mappa delle segnalazioni per il momento. chiudo.
