### ISSUE TITLE
Linkare il canale telegram nel sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#51]
Nelle pagina di link ai social inserire link a canale telegram.

**Comment by StefanoF** [comment]
Già risolto: http://terremotocentroitalia.info/aiuto/

**Comment by iltempe** [comment]
a me non funziona il link.

Direi di inserire link al canale telegram
https://telegram.me/terremotocentroitalia

 e al gruppo telegram
https://telegram.me/joinchat/BgW6eEBsI3rLKsJk9L7FJg https://telegram.me/joinchat/BgW6eEBsI3rLKsJk9L7FJg
