### ISSUE TITLE
Linkare il maxi feed a Twitter

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#52]
Usare ifttt per Linkare il maxi feed a Twitter

**Comment by dontyna** [comment]
Non so se è la issue giusta dove segnalare ma l'account twitter @terremotocentro twitta nomi utenti senza @ e quindi senza menzionare. forse è problema di ricetta ifttt?

**Comment by aborruso** [comment]
@dontyna è una policy di IFTTT, per evitare di usare ricette per fare brutti scherzi

**Comment by iltempe** [comment]
@aborruso se ci sono i feed rss dei fogli google li butterei tutti su Twitter e sul canale Telegram almeno rilanciamo le informazioni, che dici?

**Comment by aborruso** [comment]
@iltempe di quali fogli pensi sia utile creare i feed?
Per bollettino già c'è

**Comment by dontyna** [comment]
Il mio dubbio è questo: a cosa serve l'account twitter di @terremotocentro? Abbiamo detto a informare. Secondo me anche a raccogliere le segnalazioni. Buttare dentro l'account tweet di questo tipo https://twitter.com/terremotocentro/status/769901137193500673 non ha senso, crea rumore e disturba anche flusso di tweet con hashtag #terremoto. In questo caso secondo me l'automazione (automatizzazione?) non aiuta ma peggiora. Rimaniamo sull'obiettivo, meno messaggi ma coordinati e utili a chi vuole capirne qualcosa in più. Credo che con persone come @rosy2015 e @cristigalas possiamo fare turni per gestirlo.

**Comment by aborruso** [comment]
Anche io sono per non mettere nulla di automatico su twitter. Vi propongo solo due eccezioni:
- i post del sito;
- gli elementi pubblicati nel bollettino.

Ma va bene anche nulla. Mi affido al know how di dominio di @dontyna

**Comment by rosy2015** [comment]
Grazie Donata, concordo ed è quello che in parte ho cercato di ovviare con
il mio account e quello di Cittadini Reattivi.
Confermo la mia disponibilità per aiutare la gestione e la comunicazione
(creare liste ecc.ecc). La comunicazione e l'engagement non possono
risolversi con automatismi.
A presto
Rosy

Rosy Battaglia
Giornalista Freelance - Social Media Specialist
cell. + 3492861293 - skype rosy.battaglia
e-mail: info@rosybattaglia.it
Blog: http://bat-blog.org
Web: http://www.rosybattaglia.it
Social Network : http://about.me/rosybattaglia

Il 28/Ago/2016 16:31, "Donata Columbro" notifications@github.com ha
scritto:

**Comment by favoeva** [comment]
Sono d'accordo :) Unico automatismo che vedrei bene in questo momento è con nostri post su gruppo FB

**Comment by dontyna** [comment]
@aborruso se i post del sito e i bollettini vengono fuori "puliti" per me si può lasciare.

**Comment by dontyna** [comment]
@favoeva quelli del gruppo fb eviterei perché non sono tutti verificati e link che rimanda da twitter a facebook è sempre da evitare, per esperienza. #talebanadellapuliziadeifeed :)

**Comment by iltempe** [comment]
Per me va bene lasciare i post e i bollettini.

**Comment by cristigalas** [comment]
Grazie @dontyna per aver sollevato la questione Twitter! Quando vedevo i tweet automatici dell'account stavo male ;-) mi occuperei molto volentieri della gestione insieme a @rosy2015 ma, se siete d'accordo, abolirei ogni automatismo... credo che proprio per il tipo di progetto a cui stiamo lavorando e per trasmetterne davvero lo spirito siano necessari tweet ben scritti (a mano) e coinvolgimento... E quindi concordo che bisognerebbe diffondere le richieste che arrivano anche già Twitter, almeno quelle più significative.

**Comment by cristigalas** [comment]
Ps. Post e bollettini possiamo tuittarli in automatico ma come scrivi anche tu @dontyna se vengono fuori per bene...

**Comment by aborruso** [comment]
@iltempe per favore spegni tu allora tutte le automazioni su twitter, non vorrei spegnere roba di troppo, e  tienile attive soltanto per http://terremotocentroitalia.info/feed.xml

Il bollettino contiene ancora un po' di sporcizia

**Comment by cristigalas** [comment]
se siete d'accordo quando @iltempe avrà tolto gli automatismi può passare a me e @rosy2015  le chiavi di accesso all'account così iniziamo a gestirlo... Poi io e te @rosy2015 possiamo sentirci e concordare come lavorare.

**Comment by rosy2015** [comment]
Sì per me va bene Cristina :-)

Rosy Battaglia
Giornalista Freelance - Social Media Specialist
cell. + 3492861293 - skype rosy.battaglia
e-mail: info@rosybattaglia.it
Blog: http://bat-blog.org
Web: http://www.rosybattaglia.it
Social Network : http://about.me/rosybattaglia

Il 28/Ago/2016 17:42, "Cristina G." notifications@github.com ha scritto:

**Comment by dontyna** [comment]
ci sono anch'io ragazze @rosy2015 @cristigalas così in tre meno lavoro :). facciamo gruppetto telegram?

**Comment by rosy2015** [comment]
Oh yeah ;-)

Rosy Battaglia
Giornalista Freelance - Social Media Specialist
cell. + 3492861293 - skype rosy.battaglia
e-mail: info@rosybattaglia.it
Blog: http://bat-blog.org
Web: http://www.rosybattaglia.it
Social Network : http://about.me/rosybattaglia

Il 28/Ago/2016 18:20, "Donata Columbro" notifications@github.com ha
scritto:

**Comment by cristigalas** [comment]
Ok! Lo fai tu?

**Comment by iltempe** [comment]
Automatizzato su Twitter e Telegram solo il bollettino e i Feed del post del sito. grazie.

**Comment by dontyna** [comment]
@iltempe @aborruso l'account twitter continua ripostare cose di questo tipo, qual è il feed da spegnere? https://twitter.com/terremotocentro/status/770188064429838336 sorry ma secondo me è urgente.
