### ISSUE TITLE
Aggiungere nominativi vittime

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#53]
Sui siti delle prefetture locali iniziano ad essere publicati nomi delle vittime. Li Aggiungerei al sito quindi:
Fare foglio nel Google doc
Importarli come per gli altri dati in una pagina del sito

**Comment by albertocottica** [comment]
Il Google Doc a cui fa riferimento @iltempe è [questo](https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=746874049).

**Comment by albertocottica** [comment]
Sto provando a tirare giù le vittime della prefettura di Rieti (189). C'è un file PDF, che deve essere convertito. Ora ci provo con OCR. Sembra quasi... una scansione :-) :-(

**Comment by albertocottica** [comment]
Fatti quelli della prefettura di Rieti. Segno la procedura: 
1. il dato di partenza è uno squallido PDF raster (http://www.prefettura.it/rieti/allegati/3274078.htm).
2. @aborruso l'ha convertito via document cloud
3. script Python per inserire le virgole al posto degi spazi (Google Refine ha una funzione di separazione di colonne, ma non mi pare funzioni con gli spazi!)
4. Poi Refine per separare le colonne e pulire tutte le schifezze
5. Poi esportazione in formato .ods
6. A questo punto copia-incolla sul Google.

**Comment by iltempe** [comment]
Aggiungo io una pagina ad hoc nel sito.

**Comment by dontyna** [comment]
Aggiunte anche le vittime della prefettura di Ascoli, elenco aggiornato al 26/08/2016.

**Comment by aborruso** [comment]
Ho creato un piccolo script che ogni giorno, a partire da [questo foglio](https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=746874049), genera un file Markdown predisposto per Jekyll.

Il file MD lo trovate qui:
http://blog.spaziogis.it/static/projs/terremotocentroitalia/vittime.md

@mfortini se aggiungi questo file .md, al tuo script in cui fai download CSV, commit and push, abbiamo anche la pagina vittime che si autoaggiorna.

**Comment by iltempe** [comment]
Ottimo, ma serve inserirlo nello script di @mfortini?
Non basta linkare l MD file come per le altre pagine dato che lo script lo hai già fatto tu?

Matteo

**Comment by iltempe** [comment]
ok. ho ho fatto delle prove. @mfortini serve fare come dice @aborruso per avere la pagina che si aggiorna. grazie

**Comment by aborruso** [comment]
@mfortini ho modificato lo [script](https://github.com/emergenzeHack/terremotocentro/blob/master/scripts/csvupdate.sh) e adesso dovrebbe aggiornare pure il md delle vittime. Appena puoi fai un check?

Grazie

**Comment by iltempe** [comment]
chiudiamo?

**Comment by dontyna** [comment]
@iltempe purtroppo non è ancora finito il riconoscimento e la ricerca dei dispersi.

**Comment by aborruso** [comment]
La chiudiamo questa?
