### ISSUE TITLE
creare backup continuo del Gdrive sheet

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#54]
Archiviare periodicamente in una copia di backup i dati del gsheet. Più è frequente il backup e meglio è ma Direi non più di un'ora come tempi per schedulare il backup

**Comment by grutig** [comment]
se mi dite dove trovo un elenco dei dati organizzo il backup.

**Comment by mfortini** [comment]
https://drive.google.com/folderview?id=0B6F5bbIgNBMFU0wyQUJvYV9SMGM quello
che è qui dentro sicuramente

Il sab 27 ago 2016, 15:11 grutig notifications@github.com ha scritto:

**Comment by grutig** [comment]
ok provvedo

**Comment by grutig** [comment]
Da quanto vedo pare che Google impedisca l'enumerazione dei file presenti su di un'area condivisa, a differenza di quelli del proprio account, e sembrerebbe una 'feature by design'. Quindi il backup della cartella sembrerebbe possibile solo per il proprietario.

**Comment by grutig** [comment]
Per il momento ho attivato il backup ogni 10 minuti delle tavole ALLOGGI, DONAZIONI, RACCOLTE, NOTIZIE, BOLLETTINO, FABBISOGNI in CVS su terremoto.i8zse.eu, sono scaricate e storicizzate ogni 10 minuti. Se bisogna conservare altro fatemelo sapere. 
Nel caso, fatemi sapere anche se serve proteggere l'accesso con una password

**Comment by iltempe** [comment]
ottimo.

se ci sono altri link da backuppare li segnaliamo qui.

**Comment by aborruso** [comment]
Io questa la chiuderei
