### ISSUE TITLE
Pagina troppo larga su mobile pagine alloggi donazioni etc

### ISSUE THREAD

**Issue by mfortini** [emergenzeHack/terremotocentro#58]
Verificare il layout perché il menù collassato finisce tutto a destra e bisogna fare scroll nelle pagine dinamiche.

**Comment by gufogio** [comment]
Se mandi uno screen provo a dare un occhio :)

**Comment by ghost** [comment]
![photo_2016-08-27_20-20-49](https://cloud.githubusercontent.com/assets/330838/18029285/0dc94dde-6c94-11e6-9587-af3091b424a0.jpg)

Problema sembra verificarsi per il link che finiscono fuori dai box
