### ISSUE TITLE
proposta: strumento per raccogliere foto/info/dati sul campo

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/terremotocentro#59]
Sfruttando la comodità e la potenza di XLSForm e OpenDataKit, potremmo mettere a disposizione un form per raccogliere foto, informazioni e dati sul campo, da rimettere poi a disposizione di tutti.

Trovate una demo qui, che funziona anche da mobile e non richiede l'installazione di nulla, è una pagina web: [https://enketo.ona.io/x/#Y9N1](https://enketo.ona.io/x/#Y9N1)

Per costruirla basta usare un foglio elettronico come quello in allegato, da costruire secondo queste specifiche [http://xlsform.org/](http://xlsform.org/)

Che ne pensate?

**Comment by iltempe** [comment]
A me piace. potrebbe valer la pena diffonderlo ed aggregare su foglio i dati. mi pare semplice, ci vuole solo un post di guida. si può fare.

**Comment by aborruso** [comment]
@iltempe c'è da ragionare un po' insieme su cosa serve. Chiedendo anche a chi è sul campo.

E poi avere un riscontro sui campi. Ne ho inseriti alcuni d'esempio e sulla categorizzazione li ho proprio buttati.

Vale la pena discuterne un po'

**Comment by iltempe** [comment]
ok andrea. possiamo avere anche più strumenti per rilevare e direi di convergere su mappe uniche di segnalazioni. magari divise per livelli.

**Comment by sebcossu** [comment]
Ciao ragazzi,
io un anno fa feci un esame di Interazione Uomo-Macchina (HCI) in cui abbiamo progettato un'applicazione dal punto di vista dell'interfaccia grafica e del funzionamento (quindi anche elementi di ingegneria del software, ma senza i vari documenti, però utilizzando un approccio agile) per raccogliere/visualizzare/caricare foto relative ai terremoti. Le foto venivano geolocalizzate dall'utente che vi poteva aggiungere anche delle tag. Sotto alle foto, le persone potevano lasciare dei commenti dove scambiarsi informazioni e notizie relativamente a quella foto (ritrovamento di sopravvissuti, richiesta di informazioni relative alle condizioni del soggetto della foto, ecc).
Potrei ritirare fuori questo progetto e adattarlo a questa idea che ha proposto @aborruso .
Che ne pensate?

**Comment by iltempe** [comment]
Direi intanto di convergere sulla proposta di @aborruso  con eventuali miglioramenti da apportare nel caso il campo lo richiedesse.

**Comment by sebcossu** [comment]
@iltempe perché, quello che ho scritto non ci convergeva? o.o

**Comment by iltempe** [comment]
chiudo. c'è un thread su BOT.

**Comment by iltempe** [comment]
Abbiamo deciso per il momento di andare verso
- telegram bot #23 
- web form #240 
  e gestire tutto come issue github #242
