### ISSUE TITLE
Mappa unica delle segnalazioni

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#62]
Anche se abbiamo vari flussi di informazioni provenienti da vari canali, conviene avere una unica mappa (divisa per livelli) di segnalazioni sul campo dove convergere tutto. Umap mi pare attualmente lo strumento più veloce ma va benissimo anche altro.

**Comment by ebergam** [comment]
Bella idea. Primo elenco da fare sono i layer che abbiamo e quelli che servirebbero. 
Se ho ben capito ora c'è il layer con le segnalazioni provenienti dal bot. Guardando lo sheet farei un layer con "alloggi"

**Comment by mfortini** [comment]
Un umap modificabile da tutti con già un layer di esempio qui Matteo
Fortini:
http://umap.openstreetmap.fr/it/map/segnalazioni-terremotocentroitalia-bot-telegram_100019#11/42.5111/13.1087

Il sab 27 ago 2016, 22:33 Enrico Bergamini notifications@github.com ha
scritto:

**Comment by iltempe** [comment]
direi di usare questo UMAP come base.

**Comment by ebergam** [comment]
Per il layer con le foto di chris aspetto che mi chiami e di vedere i dati, immagino abbiano caricato le foto da qualche parte e fatto una tabellina con lat lng. Per il resto dobbiamo capire quali dati aggiungere al layer. Io pensavo ad "alloggi" e "fabbisogni". Che dite?

**Comment by ebergam** [comment]
Geolocalizzando "Fabbisogni": i primi fabbisogni sono ad Amatrice, io per ora metto tutto in punto sovrapposto generico "amatrice", poi facciamo a cluster?

**Comment by ebergam** [comment]
Domanda veloce magari ad @aborruso o @mfortini . Sono sui dati di chris, ho creato due nuovi fogli in cui usa una query per ordinare i dati. Ci sono 5 fogli totali nello spreadsheet. Sto costruendo l'url per tirare fuori il csv da [guardian datastore explorer](http://ouseful.open.ac.uk/datastore/gspreadsheetdb4.php). Non capisco quale sia però il modo per identificare i diversi fogli. Se non imposto nulla a parte la key mi esce il primo foglio (che non mi interessa) se lo imposto (inserendo il numerino nel campo sheet number) mi nega l'accesso. Cosa mi conviene fare?

**Comment by ebergam** [comment]
Niente, risolto :)

**Comment by ebergam** [comment]
Ok ho aggiunto il layer Fabbisogni ( @mfortini ho messo le mani in terremotocentroitaliaRSS) e nei fogli di Chris ho separato in due layer campi e danni, che ovviamente erano i gruppi più numerosi. Ho visto tardi che erano gli stessi dati che avevi mappato tu Matte (+ quei 4 o 5 che non erano nè danni nè campi). Ora è ancora tutto duplicato. Aspetto te e Chris (era lui stamattina a dirmi di separe le cose) per dirmi qual è il modo migliore.
Mi sembra che tra i dati che abbiamo l'unica altra roba mappabile dei dati che abbiamo siano gli alloggi. C'è da fare il geoloc sui nomi delle vie con OSM o gmaps però

**Comment by ValeriaV** [comment]
https://docs.google.com/spreadsheets/d/1G4uDDVwNFXXQHmVf6bIrDOGTYF65TZrnsJ7ciudb5Jg/edit?usp=sharing

Si può usare questo per mappare le immagini che abbiamo. Questo è stato iniziato dalla Standby Task Force (SBTF), una noprofit americana che opera nel campo del crisis mapping. Possono supportarci nel data cleaning e per visualizzarli su mappa una volta geolocalizzato tutto.

**Comment by ebergam** [comment]
@ValeriaV posso già aggiungere questi alla mappa di cui sopra! Se mi dai il via faccio una query da quel foglio lì e inserisco un nuovo layer :)

**Comment by iltempe** [comment]
il file di valeria è ottimo secondo me. usiamolo.

**Comment by ValeriaV** [comment]
Avviso i miei della cosa, stavano discutendo se fare un ESRI Photo Map Tour o qualcosa di più rapido. Bisogna fixare però la parte di verifica: al momento sono segnate in verde con geolocalizzazione a cui è stato fatto un double check - aggiungiamo colonna Verified e mettiamo solo quelle verificate online?

**Comment by ebergam** [comment]
@ValeriaV ottimo, ho preparato la query adesso che tra poco faccio una pausa. Più tardi ci riguardo e la cambio per tenere solo quelle verified. Intanto grazie e bel lavoro :)

**Comment by mfortini** [comment]
@ValeriaV ho esportato la mappa con i nomi abbreviati su umap se si clicca vengono fuori le info. ESRI sicuramente più efficiente, vedete voi come fare. http://umap.openstreetmap.fr/it/map/segnalazioni-terremotocentroitalia_100019#11/42.5111/13.1087

**Comment by aborruso** [comment]
@ValeriaV @mfortini io ieri avevo preparato [questa bozza](http://umap.openstreetmap.fr/it/map/italy-earthquake-photo-map-tour_100111) ma poi mi sono fermato (c'è da fare click su play)

![image](https://cloud.githubusercontent.com/assets/30607/18048799/a220658e-6de4-11e6-99ca-a165f113c01e.png)

**Comment by ValeriaV** [comment]
A me piace. @iltempe cosa ne dice?

**Comment by iltempe** [comment]
@aborruso @ValeriaV per me è ottima. riusciamo ad usare umap con flickr secondo voi?

**Comment by piersoft** [comment]
possiamo chiuderla? la mappa unica c'è già su www.piersoft.it/terremotocentro/ quella umap non la stiamo più implementando.

**Comment by iltempe** [comment]
Per me si, ma il codice della mappa e i csv che attualmente usi li trovo in qualche repo github?

**Comment by piersoft** [comment]
si su https://github.com/piersoft/terremotocentroitalia

Il giorno 5 settembre 2016 14:30, Iltempe notifications@github.com ha
scritto:

**Comment by iltempe** [comment]
ok. chiudo.
