### ISSUE TITLE
creare feed rss twitter

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#7]
é necessario un feed rss da Twitter da rilanciare con HT #terremoto #nomecomune #categoria secondo queste regole http://terremotocentroitalia.info/2016-08-25-come-postare-sui-social/

**Comment by aborruso** [comment]
@iltempe quali tweet vorresti raccogliere, in altre parole puoi scrivere la query da lanciare su twitter cui vorresti generare il feed.

Grazie

**Comment by aborruso** [comment]
Sto raccogliendo [qui](https://docs.google.com/spreadsheets/d/14tzIRMOWrppiYAnTovEHzm-6Yv3ZATmvRBN134LbnqQ/edit?usp=sharing) tutti i tweet geotaggati attorno alle coordinate 42.695435, 13.294964 in un raggio di 7 miglia

**Comment by iltempe** [comment]
Ottimo. Aggiungerei nel Wiki e poi lo mettiamo come task il link ai tweet come flusso da controllare per popolare il Google sheet. Esattamente come per Facebook.
