### ISSUE TITLE
Ordine Informazioni Bollettino

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#72]
Le informazioni nel bollettino (sul sito) devono essere ordinate dalla più recente alla più vecchia secondo il campo data.

**Comment by ghost** [comment]
@lucaferri il filtro sembra non funzionare correttamente. Se provi a inserire nel cvs un bollettino fake con data 01/09/2016 questo viene messo sotto a tutti gli altri elementi.

**Comment by gufogio** [comment]
Magari, ordiniamole direttamente dallo spreadsheet e limitiamoci a fare un `reversed` per facilitare le cose

**Comment by lucaferri** [comment]
Scoperto l'arcano: le date vengono trattate come stringhe a meno che venga usato il formato 'yyyy-mm-dd'.
Quindi direi che si può optare per la soluzione proposta da @gufogio oppure eventualmente convertire tutte le date del bollettino in quel formato e proseguire con il sort.

**Comment by aborruso** [comment]
Ciao a tutti, ho aggiunto [qui](https://docs.google.com/spreadsheets/d/1-OIq4Cmb-eURusfbAVmaJONSSAqJGh7NB0dTxduwwcg/edit#gid=220064593) una colonna che autogenera un ID numerico a partire da data e ora.

Lo spreadsheet da cui viene generato il CSV è questo https://docs.google.com/spreadsheets/d/1WL5BuoKQRM560VNctYOeDeineLeBwP7vtFlwltasASM

Ho creato in questo (per il momento) una copia del foglio Bollettino esistente (si chiama "Copy of Bollettino") e se fate una chiamata di questo tipo per ottenere il CSV, lo ottenete ordinato per data DESC.:

[http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CF%2CG%2CH%2CI%2CJ%20order%20by%20J%20desc&key=1WL5BuoKQRM560VNctYOeDeineLeBwP7vtFlwltasASM&gid=459981054](http://spreadsheets.google.com/tq?tqx=out:csv&tq=select%20A%2CB%2CC%2CD%2CE%2CF%2CG%2CH%2CI%2CJ%20order%20by%20J%20desc&key=1WL5BuoKQRM560VNctYOeDeineLeBwP7vtFlwltasASM&gid=459981054)

Che senza encoding contiene la query

``` SQL
select A,B,C,D,E,F,G,H,I,J order by J desc
```

Che ne dite?
