### ISSUE TITLE
Mapping HotSpot Wifi

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#73]
Potrebbe essere utile elencare coordinate georiferite degli hotspot wifi funzionanti per mappa.

**Comment by mfortini** [comment]
Guardate qui forse conviene appoggiarsi e usare le loro app https://wigle.net/

**Comment by ValeriaV** [comment]
Concordo con Matteo Fortini. Evitare duplicazioni ove possibile è fondamentale in questi casi

**Comment by mfortini** [comment]
Ok quindi questa issue diventa mettiamo la loro mappa sul sito:
- Embeddando se si può definire un bbox
- Scaricandola e mettendola noi

**Comment by iltempe** [comment]
@mfortini mi pare non si possa embeddare e non mi pare che si possa nemmeno fare download.

**Comment by mfortini** [comment]
https://github.com/brannondorsey/ProbeKit/wiki/Batch-Downloading-Wigle.net-Data

Hanno una API
https://wigle.net/wiki/index.cgi?API

Possono filtrare per coordinate

Il dom 28 ago 2016, 15:21 Iltempe notifications@github.com ha scritto:

**Comment by iltempe** [comment]
ok. inserito nelle app da usare per il campo.

**Comment by favoeva** [comment]
segnalazione wi-fi arrivata su gruppo FB  a twmc ;)  https://www.facebook.com/groups/1758670357733881/permalink/1761754494092134/

**Comment by c83n** [comment]
Update 1) stiamo ragionando con @lorenzoperone @annaluciont  e sara vegni che è sul campo ma senza github :)  per portare connettività a questi splendidi ragazzi di ask the dust che paiono essere interessati. https://goo.gl/gXIVT0

Update 2) Credo che in prospettiva sarebbe utile avere dati su mappa delle zone dove 
- c'è (breve p) / tornerà (medio p.) popolazione a cui serve wifi
- non c'è attualmente wifi

se non si può mappare tramite app (perché magari non tutti hanno app) occorre inventarci qualcosa di più semplice. che ne dite?

**Comment by iltempe** [comment]
chiudo.
