### ISSUE TITLE
Titoli sezioni poco chiari.

### ISSUE THREAD

**Issue by sebcossu** [emergenzeHack/terremotocentro#75]
Salve ragazzi,
ho notato che la sezione dei link utili sul sito si chiama "fonti" e trovo sia fuorviante, in quanto non si capisce subito che è una pagina che contiene link utili alla causa. Una persona potrebbe metterci qualche secondo prezioso in più a trovare i contatti di cui ha bisogno o addirittura pensare che non esistano. Io propongo di rinominare la sezione come "Link" o "Link utili".
Che ne pensate?

**Comment by gufogio** [comment]
Ottimo! Proporrei anche "Siti utili"

Anche "Bollettino" mi sembra poco chiaro

**Comment by dariodip** [comment]
A mio modesto parere "Link utili" è più chiaro.
Potrei occuparmi io di cambiarlo

**Comment by gufogio** [comment]
Va benissimo :) E se mettiamo "Aggiornamenti" invece che "Bollettino"? Si confonde con "Blog"?

**Comment by dariodip** [comment]
Non saprei...
Nel frattempo cambio da "Fonti" a "Link utili"

**Comment by sebcossu** [comment]
Sì, anche io penso che "bollettino" sia un po' fuori dal tempo, come titolo. "Aggiornamenti" può starci, ma forse anche un semplice "News" o "Annunci". Se avete qualche titolo migliore, proponete. Cambio il titolo dell'issue per rispecchiare anche questa cosa in un generico "Titoli delle sezioni fuorvianti".
@darioskal va bene se lo fai tu. Non so come si aggiungono assignees per questa issue... mo vedo di capirlo.

**Comment by gufogio** [comment]
Io forse assocerei _Aggiornamenti_ più alla situazione terremoto, mentre ho paura che _News_ si confonda con _Blog_, e su _Annunci_ penserei qualcosa tipo cerco - dono. Dico io :)

_Blog_ quasi quasi lo metterei in fondo con _About_, per mettere insieme quello che parla di noi e del sito

**Comment by mfortini** [comment]
su _config.yml c'è la possibilità di fare sottomenu. Per esempio notizie utili e bollettino potrebbero essere messi in un sottomenu

**Comment by sebcossu** [comment]
Ma infatti "blog" non ha per niente le caratteristiche di un blog... bisognerebbe capirne il criterio e dargli un titolo appropriato. Non riesco a trovare il collante di quegli articoli che stanno in blog.

**Comment by aborruso** [comment]
@killerklown non so se è la risposta che cerchi, ma blog è generato a partire da questo file https://github.com/emergenzeHack/terremotocentro/blob/master/post.md

**Comment by sebcossu** [comment]
@aborruso quindi in pratica qualunque cosa che viene caricata sul sito, viene messa lì? Allora è tipo una timeline? Un changelog? Ma ha davvero un'utilità? Mi sembra sia un po' confusionario, no?

**Comment by iltempe** [comment]
@killerklown il blog è costruito con tutti i post caricati direttamente come file md nella cartella _post.

**Comment by sebcossu** [comment]
@iltempe sì, ma mi sembra di aver visto che molti di questi sono duplicati in altre sezioni del sito.

**Comment by iltempe** [comment]
@killerklown i post vanno per categorie. é possibile mettere un post in più pagine , la categoria è un metadato nell'intestazione del post.

**Comment by iltempe** [comment]
Una proposta per il BLOG potrebbe essere nella home page inserire tutti i post con categoria BLOG e tutte le news di bollettino. e la pagina BLOG rinominarla "Aggiornamenti LIVE" e contenere lo stesso contenuto.che dite?

**Comment by sebcossu** [comment]
@iltempe era proprio quello che stavamo discutendo io e @gufogio

**Comment by iltempe** [comment]
@killerklown provi a fare un fork e vediamo come viene?

**Comment by gufogio** [comment]
Dopo la #100 abbiamo sia "Aggiornamenti" che "Bollettino"
Come possiamo unirli?

**Comment by gufogio** [comment]
@killerklown Ora "Link utili" non è più solo link, come possiamo chiamarla?

**Comment by Pinzauti** [comment]
@gufogio Con la #100 ho modificato il titolo da "Blog" in "Aggiornamenti" solo perché ho visto che nel menù la sezione era linkata come "Aggiornamenti" e mi sembrava non avesse senso che poi l'utente finisse su "Blog", se non va bene possiamo rimettere come prima o eventualmente unire con la sezione "Bollettino".

**Comment by gufogio** [comment]
Woops, errore mio, @Pinzauti, pensavo avessi cambiato pure il menu! Nessun problema in ogni caso, anzi, scusa l'incomprensione :)

Qui si diceva di unire Blog e Bollettino, ma visto che sono due sorgenti diverse (.md nel repository vs Google Sheet) ho paura sia eccessivamente difficoltoso.

Io farei un subitem, About > Blog, [come diceva @mfortini](#issuecomment-242965005), per quelli che ora sono "Aggiornamenti".

Ormai abbiamo optato per _Bollettino_ sui feed, bot, etc quindi per il momento ce lo teniamo così. Casomai apriamo un altro issue.

**Comment by iltempe** [comment]
@Pinzauti puoi indagare tu come mai il tuo update pare non funzionare? grazie!

**Comment by Pinzauti** [comment]
@iltempe sembra che il problema non sia del mio update ma di alcuni  \n \r contenuti nel csv che non permettono a jeckill di aggiornarsi. 
Il problema si dovrebbe risolvere con la #132

**Comment by Pinzauti** [comment]
@iltempe Problema risolto.

**Comment by iltempe** [comment]
ok, chiudo se ci fossero altre proposte sui titoli riaprire issue specifico.
