### ISSUE TITLE
Ricerca informazioni nelle pagine

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#8]
Occorre prevedere un sistema di ricerca in ogni pagina web per argomeno per facilitare l'utente che visita il sito.

**Comment by massimog** [comment]
Si potrebbe usare la Google Custom Search https://cse.google.it/cse/ se non c'è niente in contrario

**Comment by aborruso** [comment]
@massimog io direi proprio di sì, e poi si fa l'embedding del form di search.

Te ne puoi occupare?

Grazie

**Comment by massimog** [comment]
Ok prendo in carico questa issue.

Spero tanto di avere tempo libero a sufficienza 😅

**Comment by massimog** [comment]
Ho fatto due pull request (sorry, sto ancora imparando GiuHub)

**Comment by iltempe** [comment]
@massimog pare non funzionare.

**Comment by iltempe** [comment]
@massimog hai aggiornamenti?

**Comment by massimog** [comment]
Sto preparando una pagina di ricerca su un mio fork. Funziona ma è decisamente brutta, forse per questione di fogli di stile. Cercare di aggiustare quei css mi porta via tantissimo tempo.

Mi servirebbe un howto su come installare jekyll in locale, andrei molto più spedito

**Comment by iltempe** [comment]
guarda i wiki ci sono delle indicazioni.

**Comment by massimog** [comment]
Ho aggiunto pull request #262
