### ISSUE TITLE
Albopop sui comuni del sisma

### ISSUE THREAD

**Issue by nelsonmau** [emergenzeHack/terremotocentro#84]
Fare rss per monitorare bandi finanziamenti e incarichi (poi completo la issue)

**Comment by aborruso** [comment]
Il feed per Amatrice è già pronto http://feeds.feedburner.com/AlbopopAmatrice

**Comment by nelsonmau** [comment]
Grazie :-)

Da mettere 
- elenco comuni
- feed che aggrega tutti gli albi del sisma
- pagina che visualizza i feed

Ci lavoro...

**Comment by nelsonmau** [comment]
Ci vuole anche l'elenco delle altre pa che danno incarichi, tipo protezione civile

**Comment by ebergam** [comment]
Ci sono anch'io per questa ragazzi. Domani comincio a guardare il comune di Accumoli

**Comment by iltempe** [comment]
Suggerisco sul tema di fare un post per il blog con tutti i riferimenti del progetto albopop utili a questa iniziativa.

Matteo

**Comment by nelsonmau** [comment]
Anche questo è da tebere d'occhio http://www.protezionecivile.gov.it/jcms/it/atti_documenti.wp

**Comment by ebergam** [comment]
@aborruso vedo che Albo Accumoli e Amatrice sono uguali. (http://www.comune.accumoli.ri.it/albo-pretorio/). Con importxml non funziona perché generato in JS. L'hai fatto via scripting? Se si, mi illumini? :)

**Comment by aborruso** [comment]
caro @ebergam no una cosa semplice con gdrive e lo script di Matteo. Qui il foglio di cui puoi fare copia https://docs.google.com/spreadsheets/d/1Ywh38OU49rdBSZ_RgShaztgpvsPNbzzBXlj3EKqesCA/edit?usp=sharing

Apri la pagina (quella che trovi nell'iframe), poi la console e cerca la chiamata con i dati. Sarà una cosa come quella di sotto

![image](https://cloud.githubusercontent.com/assets/30607/18046326/a8e4c890-6dd7-11e6-89ad-5a771d875b04.png)

**Comment by ebergam** [comment]
Albopop Accumoli http://feeds.feedburner.com/AlbopopAccumoli

**Comment by aborruso** [comment]
grande @ebergam !!

**Comment by ebergam** [comment]
Albopop Arquata del Tronto: http://feeds.feedburner.com/AlbopopArquataDelTronto

**Comment by ebergam** [comment]
Albopop Montereale: https://feeds.feedburner.com/AlbopopMontereale

**Comment by aborruso** [comment]
Una piccola cosa interessante è notare che (ovviamente) nei comuni più in difficoltà l'albo è fermo a prima dell'evento sismico.

**Comment by ebergam** [comment]
Vero!
Ho fatto uno sheet in cui tenere l'elenco e la traccia di quello che c'è da fare, eccolo qui: https://docs.google.com/spreadsheets/d/1UJJk1Kz-klJBvyu0EdPGJ036UAqqn4Ntc0INy-nMuE0/edit?usp=sharing

**Comment by aborruso** [comment]
Aggiunti @ebergam : 
- http://albopop.it/comune/accumoli/
- http://albopop.it/comune/arquata_del_tronto/
- http://albopop.it/comune/montereale/

**Comment by iltempe** [comment]
C’è qualcuno dei collaboratori di Albopop che fa un post con tutti i riferimenti da condividere?

Grazie!
Matteo

**Comment by nelsonmau** [comment]
Al momento gli albipop disponibili sono quindi
- http://albopop.it/comune/amatrice/
- http://albopop.it/comune/accumoli/
- http://albopop.it/comune/arquata_del_tronto/
- http://albopop.it/comune/montereale/

non ci sono altri comuni colpiti dal sisma? @ebergam se ne occupi lei pls!

**Comment by ebergam** [comment]
@nelsonmau https://docs.google.com/spreadsheets/d/1UJJk1Kz-klJBvyu0EdPGJ036UAqqn4Ntc0INy-nMuE0/edit#gid=0 sto lavorando qui. 
Da domani avrò più tempo e finirò tutto. Poi avrò bisogno di aiuto per costruire il maxifeed.

**Comment by nelsonmau** [comment]
ottimo lavoro @ebergam si merita una mapping distro che le recapiterò a breve come promesso :)

**Comment by jenkin** [comment]
Se possibile vi chiedo almeno per questi nuovi feed di gestire meglio il tag `<category>` del feed in uscita, come spiego qui: https://github.com/ondata/albopop-enhanced/issues/7.

**Comment by nelsonmau** [comment]
una prima versione funzionante è pronta. Non è possibile ancora metterla pubblica per questioni tech (migrazione server) ma rende l'idea. Ci hanno lavorato fin qui @jenkin @aborruso ed @ebergam (io ho fatto lo screenshot che allego). Il repo è qui » https://github.com/ondata/albopop-enhanced/

![albopoptci](https://cloud.githubusercontent.com/assets/1769578/19082927/724cfd0c-8a60-11e6-84e4-9d9019cbde1f.png)

**Comment by c83n** [comment]
vabbeh ovazione per tutti :)
davvero fico!
#eddaje!

Il martedì 4 ottobre 2016, Andrea Nelson Mauro notifications@github.com
ha scritto:

**Comment by c83n** [comment]
Ciao secondo voi questa cosa si integra in qualche modo con la #378 ?

**Comment by jenkin** [comment]
@c83n In via di principio sì (non per lo storico, ma solo da qui in avanti), almeno per i documenti che finiscono negli albi pretori... nel senso che se quei documenti sono pubblicati nei rispettivi albi pretori e gli scraper di albopop li raccolgono correttamente come da [specifiche](http://albopop.it/specs/), i metadati (titolo, descrizione, ..., link al pdf originale, ...) sono archiviati, indicizzati e ricercabili... a questo punto si può scrivere un processo automatico che data una ricerca raccolga materialmente anche i pdf (scaricandoli dall'url indicato) e li carichi su archive.org. Finora tutto quel lavoro è stato fatto a mano, vero?

**Comment by ebergam** [comment]
@c83n @jenkin sto leggendo al volo ma non so: ale, spesso l'URL con il link al dettaglio delle delibere che i nostri scraper prendono non è un .pdf ma una pagina di dettaglio in cui poi sono contenuti gli allegati sotto forma di link ad un altro .pdf. Poi da lì bisognerebbe raccogliere il link interno .pdf e scaricarlo. Un esempio a caso: http://halleyweb.com/c054035/mc/mc_gridev_dettaglio.php?x=&interno=1&id_pubbl=4832

**Comment by nelsonmau** [comment]
indubbiamente ci dovrebbe essere in parte un lavoro manuale (clicchi sul link albopop » vai alla pagina di dettaglio » scarichi e archivi il documento pdf)

peraltro nel caso specifico il link da cui si scarica il pdf non estraibile semplicemente in la posizione del pdf non è esplicita, ma il download è associato all'evento onclik.

eccolo

```
<a href="#" onclick="window.open('mc_attachment.php?x=&amp;mc=10600&amp;');">DETERMINA_n_314.PDF</a>
```

**Comment by aborruso** [comment]
@nelsonmau , @ebergam si può automatizzare in molti casi, ma ovviamente la cattura può variare da albo a albo.

In [questo foglio](https://docs.google.com/spreadsheets/d/1-0V4vIZVCWZVLJq3rwilFXlVDn_tFDvUjzbAw4XaZjY/edit#gid=581332022) nell'ultima colonna (allegati_raw) ricostruisco l'URL del pdf e quindi si potrebbe pensare al download in batch. E si recupera associato all'evento onclick.

Lo estraggo con query XPATH (che è da migliorare, vale per ora solo come esempio):

```
//a[1]/@onclick
```

Ottengo 

```
window.open('mc_attachment.php?x=&mc=10604&');
```

E poi faccio un trova e sostituisci con `REGREPLACE` di `^(.*?mc=)([0-9]{3,10})(&'.*?;)$` con `$2`. Quest'ultimo mi da l'ID del download del PDF.

Ripeto è solo dimostrativo, si può fare e si può fare molto meglio fuori da uno sheet.

**Comment by aborruso** [comment]
Sempre sull'esempio citato [qui](https://github.com/emergenzeHack/terremotocentro/issues/84#issuecomment-252269787), ho modificato un po' l'XPATH in `//a[../img[@alt='File']][1]/@onclick`: ovvero la proprietà `onclick` del primo tag `<a>`, fratello di un tag `<img>` e che ha la proprietà `alt` uguale a `File`.

**Comment by jenkin** [comment]
@ebergam le specifiche prevedono un tag enclosure, direttamente linkato al pdf... Come prendere quell'url è un problema dello scraper, che adotterà una soluzione ad hoc... La struttura dei dati è data (sic), poi le regole si devono adattare di volta in volta, per questo albopop è un progetto partecipato... :)

**Comment by ebergam** [comment]
Aggiunti campi alla prima colonna, cosa che tutti noi avremmo sperato di non fare: https://docs.google.com/spreadsheets/d/1UJJk1Kz-klJBvyu0EdPGJ036UAqqn4Ntc0INy-nMuE0/edit#gid=0

**Comment by milanini** [comment]
ciao, io ho fatto una ricognizione veloce di link istituzionali, che ci danno info su sisma con Ordinanze già fatte o presumibili nei prox gg, gli elenchi sono suddivisi per regione: 
vedi Marche (ma devo ancora verificare  la provincia di Pesaro Urbino): https://docs.google.com/document/d/1SBvsXAwJuKr3R819EnX6EjXwbL_AF6iPAch_rZCS_aY/edit
Umbria: 
https://docs.google.com/document/d/1GIBPIz5oTGuZCsl9gTj27o8G_i2hXGk0fMOGkg96kJg/edit
Lazio (ma occorre verificare ancora Roma e Viterbo):
https://docs.google.com/document/d/1L-4vxQ3K4nqkiv7pURrTrglCnjc4yAaBXHnuPF6ri40/edit
Abruzzo: 
https://docs.google.com/document/d/1jCmK6cYbfHZ-mIMXqXHHqSwygKOFNZXoxFBqRzsEFw0/edit

**Comment by milanini** [comment]
@nelsonmau @aborruso @ebergam @iltempe @jenkin 
vi chiedo  se c'è un modo di memorizzare automaticamente i "googlesheets" dei Comuni albopop del Sisma settimanalmente, in maniera tale che non si perda memoria della documentazione ricercabile, anzi divengano indice della documentazione a prescindere da archive? richiesta che vi faccio in relazione al fatto che tra ieri e oggi sono "spariti" una ventina di documenti che avrei dovuto caricare dall'albopop del Comune di Amatrice in Archive, anche se poi ho trovato il modo, in maniera intuitiva per risalirvi;  ma ormai abbiamo oltre 130 Comuni da monitorare, e il "googlesheets"  storico ci consentirebbe di non perdere tracce di atti che si potrebbero rivelare importanti

**Comment by ebergam** [comment]
cara @milanini, assolutamente, ciò che scrivi è fondamentale. Stiamo lavorando sul discorso archiviazione ad un sistema più complesso di quello attuale dei google sheets, che ci aiuterà a fare anche analisi oltre ad archiviare. Ci vorrà un po' di tempo ancora, stay tuned :)

**Comment by iltempe** [comment]
@aborruso possiamo chiudere ed "esportarlo" al progetto RT? che dici?

**Comment by aborruso** [comment]
@iltempe I agree
