### ISSUE TITLE
gestire la pagina contatti del gsheet nel sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#91]
Tutte le info del gsheet in Contatti devono essere riversate con la stessa filosofia delle altre informazioni nel sito. Vanno messe nella pagina dei Link. Gli attuali link della pagina del sito possono essere rimossi una volta verificato che stiano su gsheet.

**Comment by mfortini** [comment]
Ok fatto, mi raccomando adesso è live, tenere i contatti ordinati.
