### ISSUE TITLE
scrivere linea guida per compilare il gsheet

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#93]
Va scritta una linea guida per compilare il gsheet da metter nel Wiki. Deve contenere le  informazioni attualmente sul gsheet utili a compilare ogni foglio e indicazioni utili a moderare le informazioni presenti nel gruppo Facebook.

**Comment by gufogio** [comment]
Ho cominciato a buttare giù qualcosa. https://github.com/emergenzeHack/terremotocentro/wiki/Linea-guida-per-compilare-il-google-sheet-(bozza)

Scrivete pure qui se c'è qualcosa da aggiungere, quello che vi viene in mente, e alla forma ci penso io :)

**Comment by epoeta** [comment]
Nelle raccolte fondi è superfluo inserire nella cella IBAN e BIC, provvede il template. Inoltre sotto il piano formale anche il campo  Intestazione va completato con il nome dell'intestatario e causale. Qualora il testo inizi con causale non mettere in maiuscola: sul sito viene subito dopo due punti.

**Comment by gufogio** [comment]
La causale la mettiamo in Intestazione, @epoeta? Ho visto che in molti casi era in IBAN. Ci vorrebbe un campo apposito.

**Comment by epoeta** [comment]
In teoria andrebbe in un campo apposito. Sto togliendole dagli IBAN.

**Comment by epoeta** [comment]
Togliere i testi in tutte MAIUSCOLE.

**Comment by iltempe** [comment]
Per me è ottimo. chiudo?

**Comment by gufogio** [comment]
Perfetto, casomai riapriamo se c'è qualcosa da sistemare :+1:
