### ISSUE TITLE
Stop rilancio tweet automatici su nostro canale

### ISSUE THREAD

**Issue by dontyna** [emergenzeHack/terremotocentro#97]
L'account twitter @terremotocentro continua rilanciare tweet di questo tipo, qual è il feed da spegnere? https://twitter.com/terremotocentro/status/770188064429838336 Sorry ma secondo me è urgente.

**Comment by aborruso** [comment]
@iltempe mi sono permesso di stoppare questo

![image](https://cloud.githubusercontent.com/assets/30607/18049339/007fef52-6de8-11e6-8084-819654d34a23.png)

**Comment by aborruso** [comment]
@dontyna @iltempe io spegnerei anche i due a seguire

Che dite?

![image](https://cloud.githubusercontent.com/assets/30607/18049359/19a6237a-6de8-11e6-8c57-4dd8e35351fb.png)

![image](https://cloud.githubusercontent.com/assets/30607/18049363/20c66160-6de8-11e6-8189-f51da24f6cbb.png)

**Comment by dontyna** [comment]
sì, sono d'accordo @aborruso.

**Comment by iltempe** [comment]
ok. va benissimo.
