### ISSUE TITLE
Invio e Ricezione via SMS

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/terremotocentro#98]
ActionAid sta predisponendo un sistema di invio SMS da web, valutare se si può integrare e come. Siamo in attesa delle API per usare il servizio. Qui sotto aggiungerò dettagli.

**Comment by iltempe** [comment]
Qui la mail ricevuta dai tecnici.

Documentazione API:
http://developer.contactlab.com/soap-api/

Client:
http://developer.contactlab.com/code/

Metodi da prendere in considerazione:
1. ```
    getSubscriber:
   ```
   
   http://developer.contactlab.com/soap-api/getSubscriber
   metodo per recuperare un singolo utente in base all'id interno di contactlab
2. ```
    addSubscriber:
   ```
   
   http://developer.contactlab.com/soap-api/addSubscriber
   metodo per aggiungere un singolo utente
3. ```
    addSubscribers:
   ```
   
   http://developer.contactlab.com/soap-api/addSubscribers
   metodo per aggiungere più utenti (ti suggeriamo di non superare i 2000 utenti alla volta)
4. ```
    updateSubscriber:
   ```
   
   http://developer.contactlab.com/soap-api/updateSubscriber
   Modifica di determinati campi di un utente (da tenere presente che il campo di iscrizione si chiamerà __cls1)
5. ```
    modifySubscriberSubscriptionStatus
   ```
   
   http://developer.contactlab.com/soap-api/modifySubscriberSubscriptionStatus
   Modifica dello stato di iscrizione
6. ```
    findSubscribers
   ```
   
   http://developer.contactlab.com/soap-api/findSubscribers
   Ricerca di utenti in base al valore di un campo

WSDL:
https://soap.contactlab.it/soap/services?wsdl

NOTE:
per poter utilizzare le api dovremo fornirvi le credenziali per l'utilizzo (per ottenere il token tramite metodo borrowToken). Oltre a questo dovremo richiedervi gli IP degli ambienti da cui verranno effettuate le chiamate.

Metodi per gestire una campagna.

createSMSMessageModel
createSMSTriggeredCampaign

Pensate si possa fare? Gli sviluppatori del sistema sono a disposizione

**Comment by erolm-a** [comment]
Quando dici "invio SMS da web" intendi fare un servizio di feed di notizie, e quindi gli abbonati al servizio ricevono SMS sullo stato dei terremotati?

Comunque, posso offrirmi. Ho una VPS che posso usare per questi scopi, e con l'occasione studio pure il protocollo SOAP.

**Comment by iltempe** [comment]
Intendo dire che tramite nostro feed di aggiornamento notizie si possa inviare via SMS passando appunto da questa piattaforma, che ne dici?

**Comment by iltempe** [comment]
Gli step sono :
1. ```
     Tramite il form le persone lascio il numero di telefono che tramite API inserirete su un db (che aprono in centrale) in piattaforma contactlab
   ```
2. ```
     Tramite chiamate API dovrete creare una campagna sms con il testo che inserirete e con la lista di destinatari presa dal db suddetto
   ```

Riporto nuovamente sotto per comodità le chiamate da considerare

createSMSMessageModel

createSMSTriggeredCampaign

Appena abbiamo lo script facciamo creare il db in centrale.

**Comment by erolm-a** [comment]
Allora avevo capito bene.

Sì, si può fare. Come ho detto, lo faccio a doppio fine didattico e umanitario, quindi mi sta molto bene.
Quindi mi serve il token per Oauth e l'ip per l'ambiente di testing.
L'ip è 31.14.133.71 (corrisponde al dominio [trasporti360.net](http://www.trasporti360.net))

**Comment by aurasphere** [comment]
Ciao, anche io vorrei aiutare su questo issue! Ho già esperienza con SOAP (con Java). @erolm-a possiamo sentirci in privato in modo da coordinarci un secondo? Grazie!

**Comment by iltempe** [comment]
ciao @Aurasphere ! sentiti con le persone che lavorano a questo. ci occorrerà anche poter ricevere sms non solo inviare.

**Comment by iltempe** [comment]
Aggiornamento sul tema. il servizio dovrà consentire di 
- inviare SMS broadcast
- registrare un numero di telefono all'interno di una campagna. tramite un SMS.
- scaricare dal DB tutte le segnalazioni ricevute via SMS

**Comment by aurasphere** [comment]
Ciao, mi sto mettendo subito al lavoro. Unica cosa, avrei bisogno delle seguenti risorse:
- il wsdl, ho visto il link ma se ci clicco mi dice che il mio ip non è abilitato. Potete girarmelo? O richiedere l'abilitazione del mio ip?
- l'endpoint dell'api soap per le chiamate
- un token mokkato per testare

Potete farmele avere il prima possibile? In questo momento sono abbastanza bloccato altrimenti.

Grazie mille!

**Comment by iltempe** [comment]
chiudo, non mi pare la cosa sia andata avanti e forse adesso non serve più.

**Comment by aurasphere** [comment]
Se il discorso si dovesse riaprire o ci fossero usure simili resto a disposizione.
