### ISSUE TITLE
Segnalazione automatica di nuove issue nel gruppo Telegram

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/terremotocentro#99]
Per ogni nuova issue qui su github, verrà inviato un messaggio di avviso anche nel gruppo Telegram.

Sarà più semplice "stare sul pezzo" e rimanere aggiornati

Questo dovrebbe essere proprio il primo avviso automatico ad arrivare

**Comment by iltempe** [comment]
bellissimo. @aborruso mi segnalano (un ragazzo della PC) che per il canale però è un po' fuori dagli "schemi" delle informazioni per chi non sta su github. possiamo lasciare sul canale solo le nostre news e usarlo all'interno del gruppo? fammi sapere

**Comment by aborruso** [comment]
rimosso dal canale

**Comment by iltempe** [comment]
chiudo.
